import {Link} from '@/i18n/navigation';

type Locale='en'|'zh-CN'|'ja'|'zh-TW'|'vi'|'th';
export type LegalKind='about'|'contact'|'privacy'|'terms'|'refunds';
type Section={title:string;body:string[]};
type Doc={title:string;updated:string;intro:string;sections:Section[];back:string};
type LocalizedDoc={title:string;updated?:string;intro:string;back:string;sectionTitles:string[];sectionBodies?:string[][]};

const EN:Record<LegalKind,Doc>={
 about:{title:'About Korea Concierge',updated:'Updated September 9, 2026',intro:'Korea Concierge is a travel-and-culture website for international visitors who want practical, personalized help before and during a Korea trip.',sections:[{title:'What we build',body:['Free tools include browser-local Personal Color guidance, rule-based Hanbok matching, Gyeongbokgung route planning, sourced food/cafe discovery, Saju cultural exploration, Korean naming, and Quick Help.','Premium features are not treated as live until ownership, delivery, recovery and payment controls pass launch QA.']},{title:'Product principles',body:['Prefer deterministic/local processing when it is good enough. Keep AI calls optional and cost-controlled. Do not infer nationality, ethnicity, religion, health, emotion or other sensitive traits from a selfie or voice.','For changing travel and business information, show the source and verification date and ask visitors to re-check before traveling.']}],back:'Back to home'},
 contact:{title:'Contact & support',updated:'Updated September 12, 2026',intro:'Korea Concierge is still in pre-launch payment mode.',sections:[{title:'Before checkout opens',body:['We will not invent a merchant identity or support address. The legal merchant name, customer-support email, response channel and refund contact will be published here before real payment is enabled.','Until then, no page should represent live paid checkout as available.']},{title:'For travel information',body:['Opening hours, closures, inventory and restaurant details can change. Use the linked official source on the relevant page for same-day confirmation.']}],back:'Back to home'},
 privacy:{title:'Privacy',updated:'Updated September 12, 2026',intro:'The current pre-launch build minimizes data collection and keeps several personalization steps on the device.',sections:[{title:'Personal Color',body:['The free Personal Color preview processes the selected JPEG, PNG or WebP in your browser. Its current analysis path does not upload the selfie to an AI model or Korea Concierge server.','The result is a visible-color tendency, not an inference of race, ethnicity, nationality, health or identity.']},{title:'Saju & Naming',body:['The current Saju and Naming experiences use deterministic local/server application logic and do not require an LLM call. Birth time is not guessed when unknown.','Results are not persisted to an account in the current pre-launch build unless a future saved-result feature is explicitly enabled.']},{title:'Payments and accounts',body:['Real checkout is currently disabled. Before it opens, a dedicated Korea Concierge account/database environment, row-level ownership controls, durable payment-event handling and private paid-result delivery must be deployed and tested.','Payment-provider and account privacy details will be updated here before live checkout is enabled.']},{title:'Third-party links',body:['Official tourism, palace, image-source and other external links are operated by third parties and follow their own privacy policies.']}],back:'Back to home'},
 terms:{title:'Terms of use',updated:'Updated September 12, 2026',intro:'These pre-launch terms describe the current free website experience. Live paid checkout is not yet enabled.',sections:[{title:'Travel information',body:['Routes, hours, closures, restaurant information and rental availability can change. Korea Concierge provides planning assistance, not a guarantee of admission, inventory, price or operating hours. Re-check the linked official source before relying on time-sensitive information.']},{title:'Cultural tools',body:['Saju, zodiac and naming content is provided for cultural and entertainment purposes. It is not medical, legal, financial or other professional advice and should not be treated as a certain prediction.']},{title:'Personalization',body:['Personal Color and Hanbok outputs are style suggestions based on the inputs you provide and deterministic rules. They are not professional color diagnosis or an assessment of protected/sensitive personal traits.']},{title:'Paid products',body:['No real-money checkout should be available while the site is in pre-launch payment mode. Before payment opens, price, deliverables, merchant/support details, refund/cancellation handling and delivery terms will be shown clearly before purchase.']},{title:'External content',body:['Some visual references and travel facts link to licensed or official third-party sources. Their names, trademarks and external services remain subject to their respective owners and terms.']}],back:'Back to home'},
 refunds:{title:'Refunds & cancellations',updated:'Updated September 12, 2026',intro:'Real-money checkout is currently disabled, so there is no live paid order to cancel or refund on Korea Concierge today.',sections:[{title:'Current pre-launch status',body:['No page should accept a real payment while the dedicated Korea Concierge ownership, fulfillment and refund controls remain unavailable. A test or placeholder checkout state does not create a paid entitlement.','The legal merchant name, customer-support email, refund contact and binding sale terms will be published before real checkout is enabled.']},{title:'Planned My Korea Look handling',body:['The launch contract is intended to include one successful revision within 30 days and result access for 90 days. If a confirmed payment does not produce the first result within 15 minutes, the service is designed to request a full refund automatically. These paid-product promises do not become active until checkout is actually enabled.','A failed revision must not consume the included revision. Re-opening a result, changing display language or downloading the same result again is not a revision.']},{title:'Legal rights and final sale terms',body:['Applicable statutory consumer rights take priority over the operating promises described here. Digital-content consent, cancellation exceptions, taxes and provider-specific refund handling must be finalized for the actual merchant and sale regions before launch.','Until those seller-controlled details are published, Korea Concierge must remain fail-closed for real-money checkout.']}],back:'Back to home'}
};

const LOCALIZED:Partial<Record<Locale,Partial<Record<LegalKind,LocalizedDoc>>>>={
 'zh-CN':{
  about:{title:'关于 Korea Concierge',intro:'Korea Concierge 面向国际游客，提供韩国旅行与文化的实用个性化工具。',back:'返回首页',sectionTitles:['我们提供什么','产品原则']},
  contact:{title:'联系与支持',updated:'更新于 2026 年 9 月 12 日',intro:'Korea Concierge 目前仍处于真实付款上线前阶段。',back:'返回首页',sectionTitles:['开放结账之前','旅行信息'],sectionBodies:[['在真实付款启用前，我们不会虚构商户身份或客服地址。法定商户名称、客户支持邮箱、回复渠道和退款联系方式将在这里正式公布。','在这些信息和相关控制完成之前，任何页面都不应把真实付费结账描述为已经可用。'],['营业时间、临时闭馆、库存和餐厅信息都可能变化。请使用相关页面提供的官方来源，在当天出行前再次确认。']]},
  privacy:{title:'隐私',updated:'更新于 2026 年 9 月 12 日',intro:'当前上线前版本尽量减少数据收集，并把多项个性化处理保留在设备本地。',back:'返回首页',sectionTitles:['个人色彩','四柱与韩国命名','付款与账户','第三方链接'],sectionBodies:[['免费的个人色彩预览会在你的浏览器中处理所选 JPEG、PNG 或 WebP 图片。当前分析流程不会把自拍上传到 AI 模型或 Korea Concierge 服务器。','结果只是对照片中可见颜色倾向的提示，不用于推断种族、族裔、国籍、健康状况或身份。'],['当前四柱与韩国命名体验使用确定性的本地或服务器应用逻辑，不需要调用大语言模型。出生时间未知时不会擅自猜测。','当前上线前版本不会把结果保存到账号中，除非未来明确启用保存结果的功能。'],['真实结账目前关闭。开放前，必须部署并测试 Korea Concierge 专用的账号/数据库环境、行级所有权控制、持久化支付事件处理和私有付费结果交付。','真实付款启用前，本页会补充支付服务商和账号相关的最终隐私说明。'],['官方旅游、宫殿、图片来源和其他外部链接由第三方运营，并适用各自的隐私政策。']]},
  terms:{title:'使用条款',updated:'更新于 2026 年 9 月 12 日',intro:'这些上线前条款适用于当前免费网站体验。真实付款尚未开放。',back:'返回首页',sectionTitles:['旅行信息','文化工具','个性化','付费产品','外部内容'],sectionBodies:[['路线、营业时间、闭馆安排、餐厅信息和韩服租赁可用情况都可能变化。Korea Concierge 提供旅行规划帮助，不保证入场、库存、价格或营业状态。依赖时效信息前请重新确认所链接的官方来源。'],['四柱、生肖和命名内容仅用于文化与娱乐体验，不构成医疗、法律、金融或其他专业建议，也不应被视为确定的未来预测。'],['个人色彩和韩服结果是根据你提供的输入和确定性规则生成的风格建议，并非专业色彩诊断，也不是对受保护或敏感个人特征的评估。'],['网站处于付款上线前阶段时不得开放真实付款。开放前会在购买前清楚显示价格、交付内容、商户/客服信息、退款与取消处理方式以及交付条款。'],['部分视觉参考和旅行事实链接到经许可或官方第三方来源。其名称、商标和外部服务仍受各自权利人和条款约束。']]},
  refunds:{title:'退款与取消',updated:'更新于 2026 年 9 月 12 日',intro:'目前尚未开放真实付款，因此现在没有可在 Korea Concierge 取消或退款的真实付费订单。',back:'返回首页',sectionTitles:['当前上线前状态','My Korea Look 计划处理方式','法定权利与最终销售条款'],sectionBodies:[['在 Korea Concierge 专用的所有权、交付和退款控制尚未就绪时，任何页面都不应收取真实款项。测试或占位结账状态不会产生付费权益。','在开放真实付款前，我们会公布法定商户名称、客户支持邮箱、退款联系方式和具有约束力的销售条款。'],['计划的上线合同包括：首次结果完成后 30 天内一次成功修改，以及 90 天的结果访问期。若已确认付款但 15 分钟内仍未产生首次结果，系统设计为自动请求全额退款。这些付费承诺只有在真实结账开放后才生效。','失败的修改不会消耗所包含的一次修改。重新查看结果、切换显示语言或再次下载同一结果不算修改。'],['适用的法定消费者权利优先于此处描述的运营承诺。数字内容同意、取消例外、税费和支付服务商退款流程必须在上线前按照实际商户和销售地区最终确定。','在这些由卖家确认的细节正式公布前，Korea Concierge 的真实付款必须保持关闭状态。']]}
 },
 ja:{
  about:{title:'Korea Concierge について',intro:'Korea Concierge は、海外からの旅行者向けに韓国旅行と文化の実用的なパーソナライズ支援を提供するウェブサイトです。',back:'ホームへ戻る',sectionTitles:['提供するもの','プロダクト原則']},
  contact:{title:'お問い合わせ・サポート',updated:'2026年9月12日更新',intro:'Korea Concierge は現在、実決済開始前の段階です。',back:'ホームへ戻る',sectionTitles:['決済開始前','旅行情報について'],sectionBodies:[['実決済を開始する前に、架空の販売者情報やサポート先を表示することはありません。法的な販売者名、カスタマーサポートのメール、回答窓口、返金連絡先は実決済開始前にこのページで公開します。','それまでは、どのページも実際の有料決済が利用可能であるかのように表示してはいけません。'],['営業時間、休業、在庫、飲食店情報は変わる可能性があります。該当ページの公式情報源を使い、当日にもう一度確認してください。']]},
  privacy:{title:'プライバシー',updated:'2026年9月12日更新',intro:'現在のプレローンチ版ではデータ収集を最小限にし、複数のパーソナライズ処理を端末内に保ちます。',back:'ホームへ戻る',sectionTitles:['パーソナルカラー','四柱・韓国名','決済・アカウント','外部リンク'],sectionBodies:[['無料のパーソナルカラープレビューは、選択した JPEG、PNG、WebP をブラウザ内で処理します。現在の分析経路では、自撮り写真を AI モデルや Korea Concierge のサーバーへアップロードしません。','結果は写真に見える色の傾向を示すもので、人種、民族、国籍、健康状態、本人性を推定するものではありません。'],['現在の四柱と韓国名の体験は、決定論的なローカルまたはサーバーのアプリケーションロジックを使用し、LLM 呼び出しを必要としません。出生時刻が不明な場合は推測しません。','現在のプレローンチ版では、将来の保存機能が明示的に有効にならない限り、結果をアカウントへ保存しません。'],['実決済は現在無効です。開始前に、Korea Concierge 専用のアカウント/データベース環境、行レベルの所有権制御、永続的な決済イベント処理、非公開の有料結果配信を導入してテストする必要があります。','実決済を開始する前に、決済事業者とアカウントに関する最終的なプライバシー情報をこのページへ追記します。'],['公式観光情報、宮殿、画像出典などの外部リンクは第三者が運営し、それぞれのプライバシーポリシーが適用されます。']]},
  terms:{title:'利用規約',updated:'2026年9月12日更新',intro:'このプレローンチ規約は現在の無料サイト体験に適用されます。実決済はまだ有効ではありません。',back:'ホームへ戻る',sectionTitles:['旅行情報','文化ツール','パーソナライズ','有料商品','外部コンテンツ'],sectionBodies:[['ルート、営業時間、休業、飲食店情報、韓服レンタルの利用可否は変わる可能性があります。Korea Concierge は旅行計画を支援するもので、入場、在庫、価格、営業状況を保証しません。時期に左右される情報を利用する前に、リンク先の公式情報を再確認してください。'],['四柱、干支、韓国名のコンテンツは文化・娯楽目的です。医療、法律、金融その他の専門的助言ではなく、確実な未来予測として扱うべきではありません。'],['パーソナルカラーと韓服の結果は、入力内容と決定論的なルールに基づくスタイル提案です。専門的なカラー診断や、保護対象・機微な個人属性の評価ではありません。'],['プレローンチ決済モード中は実際の支払いを受け付けません。開始前に、価格、提供内容、販売者/サポート情報、返金・キャンセル処理、提供条件を購入前に明確に表示します。'],['一部のビジュアル参考資料や旅行情報は、ライセンス済みまたは公式の第三者情報源へリンクしています。名称、商標、外部サービスには各権利者の条件が適用されます。']]},
  refunds:{title:'返金・キャンセル',updated:'2026年9月12日更新',intro:'現在は実決済が無効のため、Korea Concierge には現時点でキャンセルまたは返金できる実際の有料注文はありません。',back:'ホームへ戻る',sectionTitles:['現在のプレローンチ状態','My Korea Look の予定対応','法定権利と最終販売条件'],sectionBodies:[['Korea Concierge 専用の所有権・納品・返金管理が利用可能になるまでは、どのページも実際の支払いを受け付けません。テストや仮の決済状態から有料権利が生じることはありません。','実決済を開始する前に、法的な販売者名、カスタマーサポートのメール、返金窓口、拘束力のある販売条件を公開します。'],['開始時の契約では、最初の結果完成から30日以内の成功した修正1回と、90日間の結果閲覧を含める予定です。確定した支払いから15分以内に最初の結果が生成されない場合、全額返金を自動申請する設計です。これらの有料商品条件は実決済開始後にのみ有効になります。','失敗した修正は含まれる修正回数を消費しません。結果の再表示、表示言語の変更、同じ結果の再ダウンロードは修正ではありません。'],['適用される法定の消費者権利は、ここに記載する運用上の約束に優先します。デジタルコンテンツへの同意、キャンセル例外、税、決済事業者の返金処理は、実際の販売者と販売地域に合わせて開始前に確定する必要があります。','販売者が確定すべき詳細が公開されるまで、Korea Concierge の実決済はフェイルクローズのまま維持します。']]}
 },
 'zh-TW':{
  about:{title:'關於 Korea Concierge',intro:'Korea Concierge 為國際旅客提供韓國旅行與文化的實用個人化工具。',back:'返回首頁',sectionTitles:['我們提供什麼','產品原則']},
  contact:{title:'聯絡與支援',updated:'更新於 2026 年 9 月 12 日',intro:'Korea Concierge 目前仍處於真實付款上線前階段。',back:'返回首頁',sectionTitles:['開放結帳之前','旅遊資訊'],sectionBodies:[['在開放真實付款前，我們不會虛構商戶身分或客服地址。法定商戶名稱、客戶支援電子郵件、回覆管道與退款聯絡方式會在實際付款啟用前於此頁公布。','在這些資訊與控制完成前，任何頁面都不應把真實付費結帳表示為已可使用。'],['營業時間、臨時休館、庫存和餐廳資訊都可能變更。請使用相關頁面提供的官方來源，並在出行當天再次確認。']]},
  privacy:{title:'隱私',updated:'更新於 2026 年 9 月 12 日',intro:'目前上線前版本盡量減少資料收集，並把多項個人化處理保留在裝置本機。',back:'返回首頁',sectionTitles:['個人色彩','四柱與韓國命名','付款與帳戶','第三方連結'],sectionBodies:[['免費的個人色彩預覽會在你的瀏覽器中處理所選 JPEG、PNG 或 WebP 圖片。目前分析流程不會把自拍上傳到 AI 模型或 Korea Concierge 伺服器。','結果只是照片中可見顏色傾向的提示，不用來推測種族、族裔、國籍、健康狀態或身分。'],['目前的四柱與韓國命名體驗使用確定性的本機或伺服器應用邏輯，不需要呼叫大型語言模型。出生時間未知時不會自行猜測。','目前上線前版本不會把結果儲存到帳戶，除非未來明確啟用保存結果功能。'],['真實結帳目前關閉。開放前必須部署並測試 Korea Concierge 專用帳戶/資料庫環境、列級所有權控制、持久化付款事件處理與私有付費結果交付。','開放真實付款前，本頁會補充付款服務商和帳戶相關的最終隱私資訊。'],['官方旅遊、宮殿、圖片來源與其他外部連結由第三方營運，並適用各自的隱私政策。']]},
  terms:{title:'使用條款',updated:'更新於 2026 年 9 月 12 日',intro:'這些上線前條款適用於目前的免費網站體驗。真實付款尚未開放。',back:'返回首頁',sectionTitles:['旅遊資訊','文化工具','個人化','付費產品','外部內容'],sectionBodies:[['路線、營業時間、休館安排、餐廳資訊和韓服租借可用情況都可能變動。Korea Concierge 提供旅行規劃協助，不保證入場、庫存、價格或營業狀態。依賴具時效性的資訊前，請重新確認連結的官方來源。'],['四柱、生肖和韓國命名內容僅供文化與娛樂體驗，不構成醫療、法律、金融或其他專業建議，也不應視為確定的未來預測。'],['個人色彩和韓服結果是根據你提供的輸入與確定性規則產生的風格建議，並非專業色彩診斷，也不是對受保護或敏感個人特徵的評估。'],['網站處於付款上線前模式時不會接受真實付款。開放前會在購買前清楚顯示價格、提供內容、商戶/客服資訊、退款與取消處理方式和交付條款。'],['部分視覺參考與旅行事實連結至經授權或官方第三方來源，其名稱、商標和外部服務仍受各權利人和條款約束。']]},
  refunds:{title:'退款與取消',updated:'更新於 2026 年 9 月 12 日',intro:'目前尚未開放真實付款，因此現在沒有可在 Korea Concierge 取消或退款的真實付費訂單。',back:'返回首頁',sectionTitles:['目前上線前狀態','My Korea Look 預計處理方式','法定權利與最終銷售條款'],sectionBodies:[['在 Korea Concierge 專用的所有權、交付與退款控制尚未就緒前，任何頁面都不應收取真實款項。測試或暫代的結帳狀態不會產生付費權益。','在開放真實付款前，我們會公布法定商戶名稱、客戶支援電子郵件、退款聯絡方式與具約束力的銷售條款。'],['預計的上線合約包含：首次結果完成後30天內一次成功修改，以及90天的結果存取期。若已確認付款但15分鐘內仍未產生首次結果，系統設計為自動提出全額退款申請。這些付費承諾僅在真實結帳開放後生效。','失敗的修改不會消耗所包含的一次修改。重新查看結果、切換顯示語言或再次下載相同結果不算修改。'],['適用的法定消費者權利優先於此處描述的營運承諾。數位內容同意、取消例外、稅費與支付服務商退款流程，必須依實際商戶與銷售地區在上線前最終確定。','在這些由賣家確認的細節正式公布前，Korea Concierge 的真實付款必須維持關閉。']]}
 },
 vi:{
  about:{title:'Về Korea Concierge',intro:'Korea Concierge là website du lịch và văn hóa dành cho khách quốc tế muốn có trợ giúp thực tế, cá nhân hóa khi đến Hàn Quốc.',back:'Về trang chủ',sectionTitles:['Chúng tôi xây dựng gì','Nguyên tắc sản phẩm']},
  contact:{title:'Liên hệ & hỗ trợ',updated:'Cập nhật ngày 12/09/2026',intro:'Korea Concierge hiện vẫn ở giai đoạn trước khi mở thanh toán thật.',back:'Về trang chủ',sectionTitles:['Trước khi mở checkout','Thông tin du lịch'],sectionBodies:[['Chúng tôi không tạo ra danh tính người bán hay địa chỉ hỗ trợ giả. Tên pháp nhân bán hàng, email hỗ trợ khách hàng, kênh phản hồi và đầu mối hoàn tiền sẽ được công bố tại đây trước khi bật thanh toán thật.','Cho đến lúc đó, không trang nào được trình bày checkout trả phí thật như một chức năng đã sẵn sàng.'],['Giờ mở cửa, ngày đóng cửa, tồn kho và thông tin nhà hàng có thể thay đổi. Hãy dùng nguồn chính thức được liên kết trên trang liên quan để xác nhận lại trong ngày đi.']]},
  privacy:{title:'Quyền riêng tư',updated:'Cập nhật ngày 12/09/2026',intro:'Bản pre-launch hiện tại giảm tối đa việc thu thập dữ liệu và giữ nhiều bước cá nhân hóa trên thiết bị.',back:'Về trang chủ',sectionTitles:['Personal Color','Saju & đặt tên Hàn','Thanh toán & tài khoản','Liên kết bên thứ ba'],sectionBodies:[['Bản xem trước Personal Color miễn phí xử lý ảnh JPEG, PNG hoặc WebP đã chọn ngay trong trình duyệt. Luồng phân tích hiện tại không tải ảnh selfie lên mô hình AI hay máy chủ Korea Concierge.','Kết quả chỉ mô tả xu hướng màu có thể nhìn thấy trong ảnh, không suy đoán chủng tộc, dân tộc, quốc tịch, sức khỏe hay danh tính.'],['Trải nghiệm Saju và đặt tên Hàn hiện tại dùng logic ứng dụng xác định ở máy khách hoặc máy chủ và không cần gọi LLM. Khi không biết giờ sinh, hệ thống không tự đoán.','Trong bản pre-launch hiện tại, kết quả không được lưu vào tài khoản trừ khi một tính năng lưu kết quả trong tương lai được bật rõ ràng.'],['Checkout thật hiện đang tắt. Trước khi mở, cần triển khai và kiểm thử môi trường tài khoản/cơ sở dữ liệu riêng cho Korea Concierge, quyền sở hữu theo từng hàng dữ liệu, xử lý sự kiện thanh toán bền vững và giao kết quả trả phí riêng tư.','Thông tin quyền riêng tư cuối cùng về nhà cung cấp thanh toán và tài khoản sẽ được bổ sung tại đây trước khi bật thanh toán thật.'],['Các liên kết tới nguồn du lịch chính thức, cung điện, nguồn hình ảnh và dịch vụ bên ngoài do bên thứ ba vận hành và tuân theo chính sách quyền riêng tư của họ.']]},
  terms:{title:'Điều khoản sử dụng',updated:'Cập nhật ngày 12/09/2026',intro:'Các điều khoản pre-launch này áp dụng cho trải nghiệm miễn phí hiện tại. Thanh toán thật chưa được bật.',back:'Về trang chủ',sectionTitles:['Thông tin du lịch','Công cụ văn hóa','Cá nhân hóa','Sản phẩm trả phí','Nội dung bên ngoài'],sectionBodies:[['Lộ trình, giờ mở cửa, ngày đóng cửa, thông tin nhà hàng và khả năng thuê Hanbok có thể thay đổi. Korea Concierge hỗ trợ lập kế hoạch chuyến đi, không bảo đảm việc vào cửa, tồn kho, giá hay trạng thái hoạt động. Hãy kiểm tra lại nguồn chính thức được liên kết trước khi dựa vào thông tin nhạy theo thời gian.'],['Nội dung Saju, con giáp và đặt tên được cung cấp cho mục đích văn hóa và giải trí. Đây không phải tư vấn y tế, pháp lý, tài chính hay tư vấn chuyên môn khác và không nên được xem là dự đoán chắc chắn.'],['Kết quả Personal Color và Hanbok là gợi ý phong cách dựa trên dữ liệu bạn cung cấp và các quy tắc xác định. Chúng không phải chẩn đoán màu chuyên nghiệp hay đánh giá các đặc điểm cá nhân được bảo vệ hoặc nhạy cảm.'],['Không được mở thanh toán thật khi trang vẫn ở chế độ pre-launch. Trước khi mở, giá, nội dung bàn giao, thông tin người bán/hỗ trợ, cách xử lý hoàn tiền/hủy và điều khoản giao kết quả sẽ được hiển thị rõ trước khi mua.'],['Một số tài liệu hình ảnh và dữ kiện du lịch liên kết tới nguồn bên thứ ba chính thức hoặc đã được cấp phép. Tên, nhãn hiệu và dịch vụ bên ngoài vẫn chịu điều khoản của chủ sở hữu tương ứng.']]},
  refunds:{title:'Hoàn tiền & hủy',updated:'Cập nhật ngày 12/09/2026',intro:'Thanh toán thật hiện đang tắt, vì vậy hiện không có đơn hàng trả phí thật nào trên Korea Concierge để hủy hoặc hoàn tiền.',back:'Về trang chủ',sectionTitles:['Trạng thái pre-launch hiện tại','Cách xử lý dự kiến cho My Korea Look','Quyền theo luật và điều khoản bán cuối cùng'],sectionBodies:[['Không trang nào được nhận tiền thật khi hệ thống sở hữu, giao kết quả và hoàn tiền dành riêng cho Korea Concierge chưa sẵn sàng. Trạng thái checkout thử nghiệm hoặc giữ chỗ không tạo quyền lợi trả phí.','Tên pháp nhân bán hàng, email hỗ trợ khách hàng, kênh liên hệ hoàn tiền và điều khoản bán có hiệu lực sẽ được công bố trước khi mở thanh toán thật.'],['Hợp đồng dự kiến khi ra mắt gồm một lần chỉnh sửa thành công trong vòng 30 ngày kể từ khi hoàn tất kết quả đầu tiên và quyền truy cập kết quả trong 90 ngày. Nếu khoản thanh toán đã được xác nhận nhưng kết quả đầu tiên không được tạo trong 15 phút, hệ thống được thiết kế để tự động yêu cầu hoàn tiền toàn bộ. Các cam kết trả phí này chỉ có hiệu lực sau khi checkout thật được mở.','Lần chỉnh sửa thất bại không làm mất lượt chỉnh sửa đi kèm. Mở lại kết quả, đổi ngôn ngữ hiển thị hoặc tải lại cùng kết quả không được tính là chỉnh sửa.'],['Quyền người tiêu dùng theo luật áp dụng được ưu tiên hơn các cam kết vận hành mô tả tại đây. Đồng ý cung cấp nội dung số, ngoại lệ hủy, thuế và quy trình hoàn tiền của nhà cung cấp thanh toán phải được chốt theo pháp nhân bán hàng và khu vực bán thực tế trước khi ra mắt.','Cho đến khi các chi tiết do người bán kiểm soát được công bố, thanh toán thật của Korea Concierge phải tiếp tục ở trạng thái fail-closed.']]}
 },
 th:{
  about:{title:'เกี่ยวกับ Korea Concierge',intro:'Korea Concierge เป็นเว็บไซต์ท่องเที่ยวและวัฒนธรรมสำหรับนักท่องเที่ยวต่างชาติที่ต้องการความช่วยเหลือแบบใช้งานจริงและปรับตามความต้องการในเกาหลี',back:'กลับหน้าแรก',sectionTitles:['สิ่งที่เราสร้าง','หลักการผลิตภัณฑ์']},
  contact:{title:'ติดต่อและช่วยเหลือ',updated:'อัปเดต 12 กันยายน 2026',intro:'Korea Concierge ยังอยู่ในช่วงก่อนเปิดระบบชำระเงินจริง',back:'กลับหน้าแรก',sectionTitles:['ก่อนเปิด checkout','ข้อมูลท่องเที่ยว'],sectionBodies:[['เราจะไม่สร้างชื่อผู้ขายหรือที่อยู่ฝ่ายช่วยเหลือขึ้นมาเอง ชื่อนิติบุคคลผู้ขาย อีเมลบริการลูกค้า ช่องทางตอบกลับ และช่องทางติดต่อเรื่องคืนเงินจะเผยแพร่ในหน้านี้ก่อนเปิดชำระเงินจริง','ก่อนข้อมูลและระบบควบคุมเหล่านี้พร้อม จะไม่มีหน้าใดแสดงว่าการชำระเงินจริงพร้อมใช้งานแล้ว'],['เวลาเปิดปิด วันหยุด สต็อก และข้อมูลร้านอาหารอาจเปลี่ยนแปลงได้ โปรดใช้แหล่งข้อมูลทางการที่ลิงก์ไว้ในหน้าที่เกี่ยวข้องเพื่อตรวจสอบอีกครั้งในวันที่เดินทาง']]},
  privacy:{title:'ความเป็นส่วนตัว',updated:'อัปเดต 12 กันยายน 2026',intro:'รุ่น pre-launch ปัจจุบันลดการเก็บข้อมูลและเก็บขั้นตอนการปรับแต่งหลายส่วนไว้บนอุปกรณ์',back:'กลับหน้าแรก',sectionTitles:['Personal Color','ซาจูและการตั้งชื่อเกาหลี','การชำระเงินและบัญชี','ลิงก์ภายนอก'],sectionBodies:[['ตัวอย่าง Personal Color ฟรีจะประมวลผลไฟล์ JPEG, PNG หรือ WebP ที่เลือกภายในเบราว์เซอร์ เส้นทางการวิเคราะห์ปัจจุบันจะไม่อัปโหลดรูปเซลฟีไปยังโมเดล AI หรือเซิร์ฟเวอร์ของ Korea Concierge','ผลลัพธ์เป็นเพียงแนวโน้มของสีที่มองเห็นในภาพ ไม่ใช้อนุมานเชื้อชาติ ชาติพันธุ์ สัญชาติ สุขภาพ หรืออัตลักษณ์'],['ประสบการณ์ซาจูและการตั้งชื่อเกาหลีในปัจจุบันใช้ตรรกะแบบกำหนดแน่นอนบนอุปกรณ์หรือเซิร์ฟเวอร์ และไม่ต้องเรียก LLM หากไม่ทราบเวลาเกิด ระบบจะไม่เดาเวลาให้เอง','ในรุ่น pre-launch ปัจจุบัน ผลลัพธ์จะไม่ถูกบันทึกไว้ในบัญชี เว้นแต่จะมีการเปิดใช้ฟีเจอร์บันทึกผลอย่างชัดเจนในอนาคต'],['ขณะนี้ checkout จริงถูกปิด ก่อนเปิดใช้งานต้องติดตั้งและทดสอบสภาพแวดล้อมบัญชี/ฐานข้อมูลเฉพาะของ Korea Concierge การควบคุมสิทธิระดับแถว การจัดการเหตุการณ์ชำระเงินแบบถาวร และการส่งมอบผลลัพธ์แบบชำระเงินที่เป็นส่วนตัว','ข้อมูลความเป็นส่วนตัวฉบับสุดท้ายเกี่ยวกับผู้ให้บริการชำระเงินและบัญชีจะอัปเดตในหน้านี้ก่อนเปิดรับเงินจริง'],['ลิงก์ไปยังข้อมูลท่องเที่ยวทางการ พระราชวัง แหล่งที่มาของรูปภาพ และบริการภายนอกดำเนินการโดยบุคคลที่สามและอยู่ภายใต้นโยบายความเป็นส่วนตัวของแต่ละราย']]},
  terms:{title:'ข้อกำหนดการใช้งาน',updated:'อัปเดต 12 กันยายน 2026',intro:'ข้อกำหนด pre-launch นี้ใช้กับประสบการณ์ฟรีในปัจจุบัน ระบบชำระเงินจริงยังไม่เปิด',back:'กลับหน้าแรก',sectionTitles:['ข้อมูลท่องเที่ยว','เครื่องมือวัฒนธรรม','การปรับแต่ง','ผลิตภัณฑ์แบบชำระเงิน','เนื้อหาภายนอก'],sectionBodies:[['เส้นทาง เวลาเปิดปิด วันหยุด ข้อมูลร้านอาหาร และความพร้อมของการเช่าฮันบกอาจเปลี่ยนแปลงได้ Korea Concierge ช่วยวางแผนการเดินทาง แต่ไม่รับประกันการเข้าชม สต็อก ราคา หรือสถานะการเปิดบริการ โปรดตรวจสอบแหล่งข้อมูลทางการที่ลิงก์ไว้อีกครั้งก่อนใช้ข้อมูลที่เปลี่ยนตามเวลา'],['เนื้อหาซาจู นักษัตร และการตั้งชื่อมีไว้เพื่อวัฒนธรรมและความบันเทิง ไม่ใช่คำแนะนำทางการแพทย์ กฎหมาย การเงิน หรือวิชาชีพอื่น และไม่ควรถือเป็นการทำนายอนาคตที่แน่นอน'],['ผลลัพธ์ Personal Color และฮันบกเป็นคำแนะนำด้านสไตล์ตามข้อมูลที่ผู้ใช้ระบุและกฎแบบกำหนดแน่นอน ไม่ใช่การวินิจฉัยสีแบบมืออาชีพหรือการประเมินคุณลักษณะส่วนบุคคลที่ได้รับการคุ้มครองหรือมีความอ่อนไหว'],['จะไม่มีการรับเงินจริงขณะที่เว็บไซต์ยังอยู่ในโหมดก่อนเปิดชำระเงิน ก่อนเปิดใช้งานจะแสดงราคา สิ่งที่ได้รับ ข้อมูลผู้ขาย/ฝ่ายช่วยเหลือ วิธีจัดการคืนเงิน/ยกเลิก และเงื่อนไขการส่งมอบอย่างชัดเจนก่อนซื้อ'],['ข้อมูลภาพและข้อเท็จจริงด้านการเดินทางบางส่วนเชื่อมไปยังแหล่งข้อมูลบุคคลที่สามที่ได้รับอนุญาตหรือเป็นทางการ ชื่อ เครื่องหมายการค้า และบริการภายนอกยังอยู่ภายใต้เงื่อนไขของเจ้าของแต่ละราย']]},
  refunds:{title:'การคืนเงินและการยกเลิก',updated:'อัปเดต 12 กันยายน 2026',intro:'ขณะนี้ระบบชำระเงินจริงยังปิดอยู่ จึงยังไม่มีคำสั่งซื้อแบบชำระเงินจริงใน Korea Concierge ที่ต้องยกเลิกหรือคืนเงิน',back:'กลับหน้าแรก',sectionTitles:['สถานะก่อนเปิดใช้งานในปัจจุบัน','แนวทางที่วางแผนไว้สำหรับ My Korea Look','สิทธิตามกฎหมายและเงื่อนไขการขายฉบับสุดท้าย'],sectionBodies:[['จะไม่มีหน้าใดรับเงินจริงจนกว่าระบบเฉพาะของ Korea Concierge สำหรับการเป็นเจ้าของผลลัพธ์ การส่งมอบ และการคืนเงินจะพร้อมใช้งาน สถานะ checkout แบบทดสอบหรือชั่วคราวไม่ก่อให้เกิดสิทธิแบบชำระเงิน','ชื่อผู้ขายตามกฎหมาย อีเมลฝ่ายบริการลูกค้า ช่องทางติดต่อเรื่องคืนเงิน และเงื่อนไขการขายที่มีผลผูกพันจะเผยแพร่ก่อนเปิดรับชำระเงินจริง'],['สัญญาที่วางแผนไว้เมื่อเปิดตัวจะรวมการแก้ไขที่สำเร็จหนึ่งครั้งภายใน 30 วันหลังผลลัพธ์แรกเสร็จ และการเข้าถึงผลลัพธ์ 90 วัน หากยืนยันการชำระเงินแล้วแต่ยังไม่ได้ผลลัพธ์แรกภายใน 15 นาที ระบบถูกออกแบบให้ยื่นคำขอคืนเงินเต็มจำนวนโดยอัตโนมัติ คำมั่นสำหรับผลิตภัณฑ์แบบชำระเงินเหล่านี้จะมีผลเมื่อเปิด checkout จริงเท่านั้น','การแก้ไขที่ล้มเหลวจะไม่ใช้สิทธิแก้ไขที่รวมมา การเปิดดูผลลัพธ์อีกครั้ง การเปลี่ยนภาษาที่แสดง หรือดาวน์โหลดผลเดิมซ้ำไม่ถือเป็นการแก้ไข'],['สิทธิผู้บริโภคตามกฎหมายที่ใช้บังคับมีลำดับเหนือกว่าคำมั่นด้านการดำเนินงานที่อธิบายไว้ที่นี่ การยินยอมสำหรับเนื้อหาดิจิทัล ข้อยกเว้นการยกเลิก ภาษี และขั้นตอนคืนเงินของผู้ให้บริการชำระเงินต้องสรุปให้ตรงกับผู้ขายและพื้นที่ขายจริงก่อนเปิดตัว','จนกว่ารายละเอียดที่ผู้ขายต้องยืนยันเหล่านี้จะถูกเผยแพร่ ระบบชำระเงินจริงของ Korea Concierge ต้องคงสถานะปิดแบบ fail-closed']]}
 }
};

export function LegalPage({locale,kind}:{locale:string;kind:LegalKind}){
 const l=(locale in LOCALIZED?locale:'en') as Locale;const base=EN[kind];const local=LOCALIZED[l]?.[kind];
 return <main style={{maxWidth:900,margin:'0 auto',padding:'44px 20px 80px'}}><header><h1>{local?.title??base.title}</h1><p>{local?.intro??base.intro}</p><small>{local?.updated??base.updated}</small></header><div style={{display:'grid',gap:24,marginTop:32}}>{base.sections.map((section,index)=><section key={section.title}><h2>{local?.sectionTitles[index]??section.title}</h2>{(local?.sectionBodies?.[index]??section.body).map(p=><p key={p}>{p}</p>)}</section>)}</div><Link className="secondaryButton" href="/">{local?.back??base.back}</Link></main>;
}
