import {Link} from '@/i18n/navigation';

type Locale='en'|'zh-CN'|'ja'|'zh-TW'|'vi'|'th';
export type LegalKind='about'|'contact'|'privacy'|'terms'|'refunds';
type Section={title:string;body:string[]};
type Doc={title:string;updated:string;intro:string;sections:Section[];back:string};
type LocalizedDoc={title:string;intro:string;back:string;sectionTitles:string[];sectionBodies?:string[][]};

const EN:Record<LegalKind,Doc>={
 about:{title:'About Korea Concierge',updated:'Updated September 9, 2026',intro:'Korea Concierge is a travel-and-culture website for international visitors who want practical, personalized help before and during a Korea trip.',sections:[{title:'What we build',body:['Free tools include browser-local Personal Color guidance, rule-based Hanbok matching, Gyeongbokgung route planning, sourced food/cafe discovery, Saju cultural exploration, Korean naming, and Quick Help.','Premium features are not treated as live until ownership, delivery, recovery and payment controls pass launch QA.']},{title:'Product principles',body:['Prefer deterministic/local processing when it is good enough. Keep AI calls optional and cost-controlled. Do not infer nationality, ethnicity, religion, health, emotion or other sensitive traits from a selfie or voice.','For changing travel and business information, show the source and verification date and ask visitors to re-check before traveling.']}],back:'Back to home'},
 contact:{title:'Contact & support',updated:'Updated September 9, 2026',intro:'Korea Concierge is still in pre-launch payment mode.',sections:[{title:'Before checkout opens',body:['We will not invent a merchant identity or support address. The legal merchant name, customer-support email, response channel and refund contact will be published here before real payment is enabled.','Until then, no page should represent live paid checkout as available.']},{title:'For travel information',body:['Opening hours, closures, inventory and restaurant details can change. Use the linked official source on the relevant page for same-day confirmation.']}],back:'Back to home'},
 privacy:{title:'Privacy',updated:'Updated September 9, 2026',intro:'The current pre-launch build minimizes data collection and keeps several personalization steps on the device.',sections:[{title:'Personal Color',body:['The free Personal Color preview processes the selected JPEG, PNG or WebP in your browser. Its current analysis path does not upload the selfie to an AI model or Korea Concierge server.','The result is a visible-color tendency, not an inference of race, ethnicity, nationality, health or identity.']},{title:'Saju & Naming',body:['The current Saju and Naming experiences use deterministic local/server application logic and do not require an LLM call. Birth time is not guessed when unknown.','Results are not persisted to an account in the current pre-launch build unless a future saved-result feature is explicitly enabled.']},{title:'Payments and accounts',body:['Real checkout is currently disabled. Before it opens, a dedicated Korea Concierge account/database environment, row-level ownership controls, durable payment-event handling and private paid-result delivery must be deployed and tested.','Payment-provider and account privacy details will be updated here before live checkout is enabled.']},{title:'Third-party links',body:['Official tourism, palace, image-source and other external links are operated by third parties and follow their own privacy policies.']}],back:'Back to home'},
 terms:{title:'Terms of use',updated:'Updated September 9, 2026',intro:'These pre-launch terms describe the current free website experience. Live paid checkout is not yet enabled.',sections:[{title:'Travel information',body:['Routes, hours, closures, restaurant information and rental availability can change. Korea Concierge provides planning assistance, not a guarantee of admission, inventory, price or operating hours. Re-check the linked official source before relying on time-sensitive information.']},{title:'Cultural tools',body:['Saju, zodiac and naming content is provided for cultural and entertainment purposes. It is not medical, legal, financial or other professional advice and should not be treated as a certain prediction.']},{title:'Personalization',body:['Personal Color and Hanbok outputs are style suggestions based on the inputs you provide and deterministic rules. They are not professional color diagnosis or an assessment of protected/sensitive personal traits.']},{title:'Paid products',body:['No real-money checkout should be available while the site is in pre-launch payment mode. Before payment opens, price, deliverables, merchant/support details, refund/cancellation handling and delivery terms will be shown clearly before purchase.']},{title:'External content',body:['Some visual references and travel facts link to licensed or official third-party sources. Their names, trademarks and external services remain subject to their respective owners and terms.']}],back:'Back to home'},
 refunds:{title:'Refunds & cancellations',updated:'Updated September 12, 2026',intro:'Real-money checkout is currently disabled, so there is no live paid order to cancel or refund on Korea Concierge today.',sections:[{title:'Current pre-launch status',body:['No page should accept a real payment while the dedicated Korea Concierge ownership, fulfillment and refund controls remain unavailable. A test or placeholder checkout state does not create a paid entitlement.','The legal merchant name, customer-support email, refund contact and binding sale terms will be published before real checkout is enabled.']},{title:'Planned My Korea Look handling',body:['The launch contract is intended to include one successful revision within 30 days and result access for 90 days. If a confirmed payment does not produce the first result within 15 minutes, the service is designed to request a full refund automatically. These paid-product promises do not become active until checkout is actually enabled.','A failed revision must not consume the included revision. Re-opening a result, changing display language or downloading the same result again is not a revision.']},{title:'Legal rights and final sale terms',body:['Applicable statutory consumer rights take priority over the operating promises described here. Digital-content consent, cancellation exceptions, taxes and provider-specific refund handling must be finalized for the actual merchant and sale regions before launch.','Until those seller-controlled details are published, Korea Concierge must remain fail-closed for real-money checkout.']}],back:'Back to home'}
};

const LOCALIZED:Partial<Record<Locale,Partial<Record<LegalKind,LocalizedDoc>>>>={
 'zh-CN':{
  about:{title:'关于 Korea Concierge',intro:'Korea Concierge 面向国际游客，提供韩国旅行与文化的实用个性化工具。',back:'返回首页',sectionTitles:['我们提供什么','产品原则']},
  contact:{title:'联系与支持',intro:'Korea Concierge 目前仍处于付款上线前阶段。',back:'返回首页',sectionTitles:['开放结账之前','旅行信息']},
  privacy:{title:'隐私',intro:'当前上线前版本尽量减少数据收集，并把多项个性化处理保留在设备本地。',back:'返回首页',sectionTitles:['个人色彩','四柱与韩国命名','付款与账户','第三方链接']},
  terms:{title:'使用条款',intro:'这些上线前条款适用于当前免费网站体验。真实付款尚未开放。',back:'返回首页',sectionTitles:['旅行信息','文化工具','个性化','付费产品','外部内容']},
  refunds:{title:'退款与取消',intro:'目前尚未开放真实付款，因此现在没有可在 Korea Concierge 取消或退款的真实付费订单。',back:'返回首页',sectionTitles:['当前上线前状态','My Korea Look 计划处理方式','法定权利与最终销售条款'],sectionBodies:[['在 Korea Concierge 专用的所有权、交付和退款控制尚未就绪时，任何页面都不应收取真实款项。测试或占位结账状态不会产生付费权益。','在开放真实付款前，我们会公布法定商户名称、客户支持邮箱、退款联系方式和具有约束力的销售条款。'],['计划的上线合同包括：首次结果完成后 30 天内一次成功修改，以及 90 天的结果访问期。若已确认付款但 15 分钟内仍未产生首次结果，系统设计为自动请求全额退款。这些付费承诺只有在真实结账开放后才生效。','失败的修改不会消耗所包含的一次修改。重新查看结果、切换显示语言或再次下载同一结果不算修改。'],['适用的法定消费者权利优先于此处描述的运营承诺。数字内容同意、取消例外、税费和支付服务商退款流程必须在上线前按照实际商户和销售地区最终确定。','在这些由卖家确认的细节正式公布前，Korea Concierge 的真实付款必须保持关闭状态。']]}
 },
 ja:{
  about:{title:'Korea Concierge について',intro:'Korea Concierge は、海外からの旅行者向けに韓国旅行と文化の実用的なパーソナライズ支援を提供するウェブサイトです。',back:'ホームへ戻る',sectionTitles:['提供するもの','プロダクト原則']},
  contact:{title:'お問い合わせ・サポート',intro:'Korea Concierge は現在、決済プレローンチ段階です。',back:'ホームへ戻る',sectionTitles:['決済開始前','旅行情報について']},
  privacy:{title:'プライバシー',intro:'現在のプレローンチ版ではデータ収集を最小限にし、複数のパーソナライズ処理を端末内に保ちます。',back:'ホームへ戻る',sectionTitles:['パーソナルカラー','四柱・韓国名','決済・アカウント','外部リンク']},
  terms:{title:'利用規約',intro:'このプレローンチ規約は現在の無料サイト体験に適用されます。実決済はまだ有効ではありません。',back:'ホームへ戻る',sectionTitles:['旅行情報','文化ツール','パーソナライズ','有料商品','外部コンテンツ']},
  refunds:{title:'返金・キャンセル',intro:'現在は実決済が無効のため、Korea Concierge には現時点でキャンセルまたは返金できる実際の有料注文はありません。',back:'ホームへ戻る',sectionTitles:['現在のプレローンチ状態','My Korea Look の予定対応','法定権利と最終販売条件'],sectionBodies:[['Korea Concierge 専用の所有権・納品・返金管理が利用可能になるまでは、どのページも実際の支払いを受け付けません。テストや仮の決済状態から有料権利が生じることはありません。','実決済を開始する前に、法的な販売者名、カスタマーサポートのメール、返金窓口、拘束力のある販売条件を公開します。'],['開始時の契約では、最初の結果完成から30日以内の成功した修正1回と、90日間の結果閲覧を含める予定です。確定した支払いから15分以内に最初の結果が生成されない場合、全額返金を自動申請する設計です。これらの有料商品条件は実決済開始後にのみ有効になります。','失敗した修正は含まれる修正回数を消費しません。結果の再表示、表示言語の変更、同じ結果の再ダウンロードは修正ではありません。'],['適用される法定の消費者権利は、ここに記載する運用上の約束に優先します。デジタルコンテンツへの同意、キャンセル例外、税、決済事業者の返金処理は、実際の販売者と販売地域に合わせて開始前に確定する必要があります。','販売者が確定すべき詳細が公開されるまで、Korea Concierge の実決済はフェイルクローズのまま維持します。']]}
 },
 'zh-TW':{
  about:{title:'關於 Korea Concierge',intro:'Korea Concierge 為國際旅客提供韓國旅行與文化的實用個人化工具。',back:'返回首頁',sectionTitles:['我們提供什麼','產品原則']},
  contact:{title:'聯絡與支援',intro:'Korea Concierge 目前仍處於付款上線前階段。',back:'返回首頁',sectionTitles:['開放結帳之前','旅遊資訊']},
  privacy:{title:'隱私',intro:'目前上線前版本盡量減少資料收集，並把多項個人化處理保留在裝置本機。',back:'返回首頁',sectionTitles:['個人色彩','四柱與韓國命名','付款與帳戶','第三方連結']},
  terms:{title:'使用條款',intro:'這些上線前條款適用於目前的免費網站體驗。真實付款尚未開放。',back:'返回首頁',sectionTitles:['旅遊資訊','文化工具','個人化','付費產品','外部內容']},
  refunds:{title:'退款與取消',intro:'目前尚未開放真實付款，因此現在沒有可在 Korea Concierge 取消或退款的真實付費訂單。',back:'返回首頁',sectionTitles:['目前上線前狀態','My Korea Look 預計處理方式','法定權利與最終銷售條款'],sectionBodies:[['在 Korea Concierge 專用的所有權、交付與退款控制尚未就緒前，任何頁面都不應收取真實款項。測試或暫代的結帳狀態不會產生付費權益。','在開放真實付款前，我們會公布法定商戶名稱、客戶支援電子郵件、退款聯絡方式與具約束力的銷售條款。'],['預計的上線合約包含：首次結果完成後30天內一次成功修改，以及90天的結果存取期。若已確認付款但15分鐘內仍未產生首次結果，系統設計為自動提出全額退款申請。這些付費承諾僅在真實結帳開放後生效。','失敗的修改不會消耗所包含的一次修改。重新查看結果、切換顯示語言或再次下載相同結果不算修改。'],['適用的法定消費者權利優先於此處描述的營運承諾。數位內容同意、取消例外、稅費與支付服務商退款流程，必須依實際商戶與銷售地區在上線前最終確定。','在這些由賣家確認的細節正式公布前，Korea Concierge 的真實付款必須維持關閉。']]}
 },
 vi:{
  about:{title:'Về Korea Concierge',intro:'Korea Concierge là website du lịch và văn hóa dành cho khách quốc tế muốn có trợ giúp thực tế, cá nhân hóa khi đến Hàn Quốc.',back:'Về trang chủ',sectionTitles:['Chúng tôi xây dựng gì','Nguyên tắc sản phẩm']},
  contact:{title:'Liên hệ & hỗ trợ',intro:'Korea Concierge hiện vẫn ở giai đoạn trước khi mở thanh toán.',back:'Về trang chủ',sectionTitles:['Trước khi mở checkout','Thông tin du lịch']},
  privacy:{title:'Quyền riêng tư',intro:'Bản pre-launch hiện tại giảm tối đa việc thu thập dữ liệu và giữ nhiều bước cá nhân hóa trên thiết bị.',back:'Về trang chủ',sectionTitles:['Personal Color','Saju & đặt tên Hàn','Thanh toán & tài khoản','Liên kết bên thứ ba']},
  terms:{title:'Điều khoản sử dụng',intro:'Các điều khoản pre-launch này áp dụng cho trải nghiệm miễn phí hiện tại. Thanh toán thật chưa được bật.',back:'Về trang chủ',sectionTitles:['Thông tin du lịch','Công cụ văn hóa','Cá nhân hóa','Sản phẩm trả phí','Nội dung bên ngoài']},
  refunds:{title:'Hoàn tiền & hủy',intro:'Thanh toán thật hiện đang tắt, vì vậy hiện không có đơn hàng trả phí thật nào trên Korea Concierge để hủy hoặc hoàn tiền.',back:'Về trang chủ',sectionTitles:['Trạng thái pre-launch hiện tại','Cách xử lý dự kiến cho My Korea Look','Quyền theo luật và điều khoản bán cuối cùng'],sectionBodies:[['Không trang nào được nhận tiền thật khi hệ thống sở hữu, giao kết quả và hoàn tiền dành riêng cho Korea Concierge chưa sẵn sàng. Trạng thái checkout thử nghiệm hoặc giữ chỗ không tạo quyền lợi trả phí.','Tên pháp nhân bán hàng, email hỗ trợ khách hàng, kênh liên hệ hoàn tiền và điều khoản bán có hiệu lực sẽ được công bố trước khi mở thanh toán thật.'],['Hợp đồng dự kiến khi ra mắt gồm một lần chỉnh sửa thành công trong vòng 30 ngày kể từ khi hoàn tất kết quả đầu tiên và quyền truy cập kết quả trong 90 ngày. Nếu khoản thanh toán đã được xác nhận nhưng kết quả đầu tiên không được tạo trong 15 phút, hệ thống được thiết kế để tự động yêu cầu hoàn tiền toàn bộ. Các cam kết trả phí này chỉ có hiệu lực sau khi checkout thật được mở.','Lần chỉnh sửa thất bại không làm mất lượt chỉnh sửa đi kèm. Mở lại kết quả, đổi ngôn ngữ hiển thị hoặc tải lại cùng kết quả không được tính là chỉnh sửa.'],['Quyền người tiêu dùng theo luật áp dụng được ưu tiên hơn các cam kết vận hành mô tả tại đây. Đồng ý cung cấp nội dung số, ngoại lệ hủy, thuế và quy trình hoàn tiền của nhà cung cấp thanh toán phải được chốt theo pháp nhân bán hàng và khu vực bán thực tế trước khi ra mắt.','Cho đến khi các chi tiết do người bán kiểm soát được công bố, thanh toán thật của Korea Concierge phải tiếp tục ở trạng thái fail-closed.']]}
 },
 th:{
  about:{title:'เกี่ยวกับ Korea Concierge',intro:'Korea Concierge เป็นเว็บไซต์ท่องเที่ยวและวัฒนธรรมสำหรับนักท่องเที่ยวต่างชาติที่ต้องการความช่วยเหลือแบบใช้งานจริงและปรับตามความต้องการในเกาหลี',back:'กลับหน้าแรก',sectionTitles:['สิ่งที่เราสร้าง','หลักการผลิตภัณฑ์']},
  contact:{title:'ติดต่อและช่วยเหลือ',intro:'Korea Concierge ยังอยู่ในช่วงก่อนเปิดระบบชำระเงินจริง',back:'กลับหน้าแรก',sectionTitles:['ก่อนเปิด checkout','ข้อมูลท่องเที่ยว']},
  privacy:{title:'ความเป็นส่วนตัว',intro:'รุ่น pre-launch ปัจจุบันลดการเก็บข้อมูลและเก็บขั้นตอนการปรับแต่งหลายส่วนไว้บนอุปกรณ์',back:'กลับหน้าแรก',sectionTitles:['Personal Color','ซาจูและการตั้งชื่อเกาหลี','การชำระเงินและบัญชี','ลิงก์ภายนอก']},
  terms:{title:'ข้อกำหนดการใช้งาน',intro:'ข้อกำหนด pre-launch นี้ใช้กับประสบการณ์ฟรีในปัจจุบัน ระบบชำระเงินจริงยังไม่เปิด',back:'กลับหน้าแรก',sectionTitles:['ข้อมูลท่องเที่ยว','เครื่องมือวัฒนธรรม','การปรับแต่ง','ผลิตภัณฑ์แบบชำระเงิน','เนื้อหาภายนอก']},
  refunds:{title:'การคืนเงินและการยกเลิก',intro:'ขณะนี้ระบบชำระเงินจริงยังปิดอยู่ จึงยังไม่มีคำสั่งซื้อแบบชำระเงินจริงใน Korea Concierge ที่ต้องยกเลิกหรือคืนเงิน',back:'กลับหน้าแรก',sectionTitles:['สถานะก่อนเปิดใช้งานในปัจจุบัน','แนวทางที่วางแผนไว้สำหรับ My Korea Look','สิทธิตามกฎหมายและเงื่อนไขการขายฉบับสุดท้าย'],sectionBodies:[['จะไม่มีหน้าใดรับเงินจริงจนกว่าระบบเฉพาะของ Korea Concierge สำหรับการเป็นเจ้าของผลลัพธ์ การส่งมอบ และการคืนเงินจะพร้อมใช้งาน สถานะ checkout แบบทดสอบหรือชั่วคราวไม่ก่อให้เกิดสิทธิแบบชำระเงิน','ชื่อผู้ขายตามกฎหมาย อีเมลฝ่ายบริการลูกค้า ช่องทางติดต่อเรื่องคืนเงิน และเงื่อนไขการขายที่มีผลผูกพันจะเผยแพร่ก่อนเปิดรับชำระเงินจริง'],['สัญญาที่วางแผนไว้เมื่อเปิดตัวจะรวมการแก้ไขที่สำเร็จหนึ่งครั้งภายใน 30 วันหลังผลลัพธ์แรกเสร็จ และการเข้าถึงผลลัพธ์ 90 วัน หากยืนยันการชำระเงินแล้วแต่ยังไม่ได้ผลลัพธ์แรกภายใน 15 นาที ระบบถูกออกแบบให้ยื่นคำขอคืนเงินเต็มจำนวนโดยอัตโนมัติ คำมั่นสำหรับผลิตภัณฑ์แบบชำระเงินเหล่านี้จะมีผลเมื่อเปิด checkout จริงเท่านั้น','การแก้ไขที่ล้มเหลวจะไม่ใช้สิทธิแก้ไขที่รวมมา การเปิดดูผลลัพธ์อีกครั้ง การเปลี่ยนภาษาที่แสดง หรือดาวน์โหลดผลเดิมซ้ำไม่ถือเป็นการแก้ไข'],['สิทธิผู้บริโภคตามกฎหมายที่ใช้บังคับมีลำดับเหนือกว่าคำมั่นด้านการดำเนินงานที่อธิบายไว้ที่นี่ การยินยอมสำหรับเนื้อหาดิจิทัล ข้อยกเว้นการยกเลิก ภาษี และขั้นตอนคืนเงินของผู้ให้บริการชำระเงินต้องสรุปให้ตรงกับผู้ขายและพื้นที่ขายจริงก่อนเปิดตัว','จนกว่ารายละเอียดที่ผู้ขายต้องยืนยันเหล่านี้จะถูกเผยแพร่ ระบบชำระเงินจริงของ Korea Concierge ต้องคงสถานะปิดแบบ fail-closed']]}
 }
};

export function LegalPage({locale,kind}:{locale:string;kind:LegalKind}){
 const l=(locale in LOCALIZED?locale:'en') as Locale;const base=EN[kind];const local=LOCALIZED[l]?.[kind];
 return <main style={{maxWidth:900,margin:'0 auto',padding:'44px 20px 80px'}}><header><h1>{local?.title??base.title}</h1><p>{local?.intro??base.intro}</p><small>{base.updated}</small></header><div style={{display:'grid',gap:24,marginTop:32}}>{base.sections.map((section,index)=><section key={section.title}><h2>{local?.sectionTitles[index]??section.title}</h2>{(local?.sectionBodies?.[index]??section.body).map(p=><p key={p}>{p}</p>)}</section>)}</div><Link className="secondaryButton" href="/">{local?.back??base.back}</Link></main>;
}
