import {CURATED_LOOKS_CATALOG,type CuratedLook} from './catalog';

/**
 * Source-checked expansion required by BUILD_SPEC §4.
 *
 * These six reference photographs are from Korea.net / Korean Culture and
 * Information Service cultural fashion showcases on Wikimedia Commons. Each
 * file page records CC BY-SA 2.0, attribution requirements and VRT/Flickr
 * license verification. Visual metadata below is deliberately limited to
 * visible garment form/color and product-useful trade-offs; it does not claim
 * historical rank, rental inventory, body type or identity attributes.
 */
export const ADDITIONAL_CURATED_LOOKS: readonly CuratedLook[] = [
  {
    id: 'look-modern-gold-chima-07',
    src: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Korea_Hanbok_Fashion_Show_03_%288422279573%29.jpg?width=1200',
    width: 2185,
    height: 3174,
    kind: 'reference-photo',
    alt: 'Modern black upper garment with pale gold full chima and colorful norigae',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Korea_Hanbok_Fashion_Show_03_(8422279573).jpg',
    creator: 'Korea.net / Korean Culture and Information Service (Jeon Han)',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    commercialUseEvidence: 'Wikimedia Commons records the Korea.net/KOCIS Flickr file as verified CC BY-SA 2.0; commercial reuse is permitted with attribution and ShareAlike compliance.',
    checkedAt: '2026-09-11',
    cropPosition: 'center 40%',
    styleId: 'princess-prince',
    garmentType: 'chima',
    coverage: 'standard',
    seasons: ['spring', 'autumn'],
    walkingSuitability: 'easy',
    accessoryIds: ['norigae-tassel'],
    title: 'Pale Gold & Black Modern Chima',
    tagline: 'A clean modern contrast with a light full skirt and one strong accessory line',
    description: 'A contemporary chima look pairing a sculptural black upper layer with a pale gold full skirt and a colorful norigae accent.',
    palette: {top: 'Soft Black (#171717)',bottom: 'Pale Gold (#F1D98D)',accent: 'Berry Red (#8B2942)',undertone: 'neutral',description: 'Neutral black and pale gold with a small saturated accent.'},
    reasons: ['The full pale skirt keeps the silhouette light despite the dark upper layer.','A single vertical norigae accent adds color without crowding the look.','The shorter upper silhouette keeps the skirt shape visually clear in full-length photos.'],
    tradeOff: 'The pale hem will show dust more readily on gravel paths; use normal care around palace courtyards.',
    recommendedLocation: {name: 'Hyangwonjeong Pavilion Pond',koreanName: '향원정',description: 'A palace pond setting with open sight lines for a full-length silhouette.',photoAngle: 'Use a simple full-length frame and keep railings or planting from cutting across the skirt.'},
    rentalShopCard: {hangulTitle: '연한 금빛 치마 한복 요청',hangulStaffNote: '연한 금빛/아이보리 계열의 풍성한 치마와 짙은색 상의 조합을 찾고 있습니다. 노리개는 한 가지 포인트로 부탁드립니다. 실제 디자인과 추가 요금은 먼저 확인해 주세요.',englishExplanation: 'Ask for a pale-gold or ivory full skirt with a dark upper layer and one norigae accent. Confirm the actual design and any extra fee before renting.'},
    photoRoute: [{order:1,spotName:'Hyangwonjeong area',koreanName:'향원정 일대',bestTime:'Daylight; verify palace hours',photoTip:'Favor an uncluttered full-length frame.'}],
  },
  {
    id: 'look-layered-ivory-baji-08',
    src: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Korea_Hanbok_Fashion_Show_20_%288423372268%29.jpg?width=1200',
    width: 2360,
    height: 3800,
    kind: 'reference-photo',
    alt: 'Contemporary layered ivory Hanbok-inspired outfit with visible baji trousers',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Korea_Hanbok_Fashion_Show_20_(8423372268).jpg',
    creator: 'Korea.net / Korean Culture and Information Service (Jeon Han)',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    commercialUseEvidence: 'Wikimedia Commons records the Korea.net/KOCIS Flickr file as verified CC BY-SA 2.0; commercial reuse is permitted with attribution and ShareAlike compliance.',
    checkedAt: '2026-09-11',
    cropPosition: 'center 42%',
    styleId: 'princess-prince',
    garmentType: 'baji',
    coverage: 'more-coverage',
    seasons: ['spring', 'autumn'],
    walkingSuitability: 'easy',
    accessoryIds: [],
    title: 'Layered Ivory Modern Baji',
    tagline: 'Soft monochrome layers with trousers for a lighter walking-focused direction',
    description: 'A modern ivory layered outfit with visible loose trousers, using texture and drape rather than ornate accessories.',
    palette: {top: 'Warm Ivory (#F5F1E8)',bottom: 'Clay Brown (#8A563C)',accent: 'Soft Stone (#CFC8BD)',undertone: 'warm',description: 'Low-saturation warm neutrals with a small earthy trouser accent.'},
    reasons: ['Loose trousers provide a practical alternative to a full skirt silhouette.','The near-monochrome upper layers keep visual noise low.','Minimal accessories make the direction easier to simplify further at a rental shop.'],
    tradeOff: 'The runway reference is contemporary and layered; rental shops may only have a simpler ivory baji interpretation.',
    recommendedLocation: {name: 'Bukchon Hanok lanes',koreanName: '북촌 한옥길',description: 'A traditional streetscape where a restrained neutral palette can stand apart from dark timber walls.',photoAngle: 'Use a wider lane and avoid blocking resident entrances.'},
    rentalShopCard: {hangulTitle: '아이보리 바지 한복 요청',hangulStaffNote: '아이보리/크림 계열의 밝은 상의와 편하게 걸을 수 있는 바지 한복을 찾고 있습니다. 장식은 최소화하고 싶습니다. 실제 디자인과 추가 요금은 먼저 확인해 주세요.',englishExplanation: 'Ask for an ivory or cream upper layer with comfortable baji trousers and minimal accessories. Confirm the actual design and any extra fee before renting.'},
    photoRoute: [{order:1,spotName:'Bukchon public walking lanes',koreanName:'북촌 공공 보행로',bestTime:'Daylight; respect resident restrictions',photoTip:'Keep doorways clear and use a wider public lane.'}],
  },
  {
    id: 'look-teal-gold-chima-09',
    src: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/KOCIS_Korea_Hanbok-AoDai_FashionShow_71_%289766412975%29.jpg?width=1200',
    width: 3000,
    height: 4596,
    kind: 'reference-photo',
    alt: 'Deep teal patterned jeogori with golden chima and jade-toned norigae',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:KOCIS_Korea_Hanbok-AoDai_FashionShow_71_(9766412975).jpg',
    creator: 'Korea.net / Korean Culture and Information Service (Jeon Han)',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    commercialUseEvidence: 'Wikimedia Commons records the Korea.net/KOCIS Flickr file as verified CC BY-SA 2.0; commercial reuse is permitted with attribution and ShareAlike compliance.',
    checkedAt: '2026-09-11',
    cropPosition: 'center 38%',
    styleId: 'queen-king',
    garmentType: 'chima',
    coverage: 'standard',
    seasons: ['all-season'],
    walkingSuitability: 'moderate',
    accessoryIds: ['norigae-tassel','hairpin'],
    title: 'Deep Teal & Gold Formal Chima',
    tagline: 'Patterned jewel tones with a composed court-inspired color balance',
    description: 'A formal chima direction combining a deep teal patterned jeogori, muted gold skirt, plum ribbon and jade-toned pendant accents.',
    palette: {top: 'Deep Teal (#274653)',bottom: 'Muted Gold (#E9C46A)',accent: 'Plum (#7A3550)',undertone: 'neutral',description: 'Balanced jewel tones with a warm gold lower field and cooler teal upper contrast.'},
    reasons: ['Deep teal creates a strong frame around the face without requiring a bright overall outfit.','Muted gold keeps the skirt formal while avoiding an all-red royal palette.','The plum ribbon and jade-toned accessory provide two controlled accent points.'],
    tradeOff: 'Patterned upper layers and multiple accents read busier at close range; simplify accessories if a quieter portrait is preferred.',
    recommendedLocation: {name: 'Geunjeongjeon Throne Hall courtyard',koreanName: '근정전 조정',description: 'A formal palace courtyard suited to a structured, dignified color direction.',photoAngle: 'Keep the outfit centered against repeated columns or courtyard lines rather than adding extra props.'},
    rentalShopCard: {hangulTitle: '청록·금빛 치마 한복 요청',hangulStaffNote: '짙은 청록 계열 저고리와 차분한 금빛/노랑 계열 치마 조합을 찾고 있습니다. 노리개는 과하지 않게 부탁드립니다. 실제 디자인과 추가 요금은 먼저 확인해 주세요.',englishExplanation: 'Ask for a deep teal jeogori with a muted gold or yellow chima and restrained norigae. Confirm the actual design and any extra fee before renting.'},
    photoRoute: [{order:1,spotName:'Geunjeongjeon courtyard',koreanName:'근정전 조정',bestTime:'Daylight; verify palace hours',photoTip:'Use the courtyard lines for a formal centered composition.'}],
  },
  {
    id: 'look-indigo-modern-baji-10',
    src: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Korea_Hanbok_Fashion_Show_04_%288422279531%29.jpg?width=1200',
    width: 2002,
    height: 3101,
    kind: 'reference-photo',
    alt: 'Modern indigo and blue Hanbok-inspired trouser look from KOCIS cultural showcase',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Korea_Hanbok_Fashion_Show_04_(8422279531).jpg',
    creator: 'Korea.net / Korean Culture and Information Service (Jeon Han)',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    commercialUseEvidence: 'Wikimedia Commons records the Korea.net/KOCIS Flickr file as verified CC BY-SA 2.0; commercial reuse is permitted with attribution and ShareAlike compliance.',
    checkedAt: '2026-09-11',
    cropPosition: 'center 40%',
    styleId: 'queen-king',
    garmentType: 'baji',
    coverage: 'standard',
    seasons: ['spring', 'autumn'],
    walkingSuitability: 'moderate',
    accessoryIds: [],
    title: 'Indigo Blue Structured Baji',
    tagline: 'A restrained cool-toned trouser direction with a cleaner modern profile',
    description: 'A cool indigo-blue modern Hanbok direction built around a trouser silhouette and structured upper layers.',
    palette: {top: 'Indigo Navy (#263A63)',bottom: 'Muted Blue (#5E6A9A)',accent: 'Soft Ivory (#EFE9DA)',undertone: 'cool',description: 'Cool indigo and blue with a restrained light neutral accent.'},
    reasons: ['The cool tonal range is distinct from the red-and-gold ceremonial options.','A trouser silhouette supports a more practical walking direction.','Limited ornament keeps the overall presentation formal without becoming ceremonial.'],
    tradeOff: 'This is a modern fashion-show interpretation; ask for the color relationship and baji silhouette rather than an exact replica.',
    recommendedLocation: {name: 'Seochon stone-wall streets',koreanName: '서촌 골목',description: 'A quieter streetscape that suits a restrained blue walking look.',photoAngle: 'Use a simple wall or lane backdrop and preserve pedestrian access.'},
    rentalShopCard: {hangulTitle: '인디고 바지 한복 요청',hangulStaffNote: '남색/인디고 계열의 차분한 상의와 편하게 걸을 수 있는 바지 한복을 찾고 있습니다. 장식은 적게 부탁드립니다. 실제 디자인과 추가 요금은 먼저 확인해 주세요.',englishExplanation: 'Ask for a restrained indigo or navy upper layer with comfortable baji trousers and minimal ornament. Confirm the actual design and any extra fee before renting.'},
    photoRoute: [{order:1,spotName:'Seochon public lanes',koreanName:'서촌 공공 골목길',bestTime:'Daylight',photoTip:'Use a quiet public wall or lane without obstructing residents.'}],
  },
  {
    id: 'look-jeonmo-gold-chima-11',
    src: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/KOCIS_Korea_Hanbok-AoDai_FashionShow_57_%289766196921%29.jpg?width=1200',
    width: 2928,
    height: 4488,
    kind: 'reference-photo',
    alt: 'Black outer layer, golden chima, red ribbon and large traditional head covering in KOCIS showcase',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:KOCIS_Korea_Hanbok-AoDai_FashionShow_57_(9766196921).jpg',
    creator: 'Korea.net / Korean Culture and Information Service (Jeon Han)',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    commercialUseEvidence: 'Wikimedia Commons records the Korea.net/KOCIS Flickr file as verified CC BY-SA 2.0; commercial reuse is permitted with attribution and ShareAlike compliance.',
    checkedAt: '2026-09-11',
    cropPosition: 'center 38%',
    styleId: 'royal',
    garmentType: 'chima',
    coverage: 'more-coverage',
    seasons: ['all-season'],
    walkingSuitability: 'photo-focused',
    accessoryIds: ['traditional-head-covering'],
    title: 'Black, Red & Gold Dramatic Chima',
    tagline: 'A high-impact reference built around a gold skirt, dark outer layer and oversized head silhouette',
    description: 'A dramatic chima reference with a golden embroidered skirt, dark outer layer, red ribbon and a large traditional head covering; best treated as photo-first inspiration rather than an inventory promise.',
    palette: {top: 'Soft Black (#151515)',bottom: 'Warm Gold (#E6B85C)',accent: 'Ceremonial Red (#B3262E)',undertone: 'warm',description: 'High-contrast black, gold and red for a deliberately theatrical photo direction.'},
    reasons: ['The gold skirt remains visually dominant under the dark outer layer.','Red ribbon creates a clear focal accent between black and gold.','The large head silhouette makes this materially different from the simpler palace-walk looks.'],
    tradeOff: 'The oversized head covering and display styling are photo-focused; availability and comfort must be confirmed at the rental shop.',
    recommendedLocation: {name: 'Gyeonghoeru pavilion area',koreanName: '경회루 일대',description: 'An open palace backdrop that leaves space around a larger accessory silhouette.',photoAngle: 'Keep extra space above and beside the head covering and avoid crowded passages.'},
    rentalShopCard: {hangulTitle: '검정·금빛 포토 한복 요청',hangulStaffNote: '검정 겉옷과 금빛 치마, 붉은 포인트처럼 대비가 강한 포토 중심 한복을 찾고 있습니다. 큰 머리 장식은 착용 가능 여부와 추가 요금을 먼저 확인해 주세요.',englishExplanation: 'Ask for a high-contrast black/gold look with a red accent. If considering a large head accessory, confirm availability, comfort and any extra fee first.'},
    photoRoute: [{order:1,spotName:'Gyeonghoeru area',koreanName:'경회루 일대',bestTime:'Daylight; verify palace hours',photoTip:'Leave visual space around large accessories and keep walkways clear.'}],
  },
  {
    id: 'look-scarlet-brocade-baji-12',
    src: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Korea_Hanbok_Fashion_Show_18_%288422278535%29.jpg?width=1200',
    width: 2286,
    height: 3744,
    kind: 'reference-photo',
    alt: 'Black asymmetrical upper garment with scarlet and gold brocade trouser silhouette',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Korea_Hanbok_Fashion_Show_18_(8422278535).jpg',
    creator: 'Korea.net / Korean Culture and Information Service (Jeon Han)',
    license: 'CC BY-SA 2.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    commercialUseEvidence: 'Wikimedia Commons records the Korea.net/KOCIS Flickr file as verified CC BY-SA 2.0; commercial reuse is permitted with attribution and ShareAlike compliance.',
    checkedAt: '2026-09-11',
    cropPosition: 'center 38%',
    styleId: 'royal',
    garmentType: 'baji',
    coverage: 'standard',
    seasons: ['all-season'],
    walkingSuitability: 'photo-focused',
    accessoryIds: [],
    title: 'Scarlet Brocade & Black Photo Baji',
    tagline: 'A dramatic modern royal direction using black structure and scarlet-gold brocade',
    description: 'A fashion-forward baji reference with a sculptural black upper layer and vivid scarlet brocade lower silhouette, intended as a photo-first color and shape direction.',
    palette: {top: 'Soft Black (#131313)',bottom: 'Scarlet Brocade (#A4161A)',accent: 'Antique Gold (#C9A227)',undertone: 'warm',description: 'Black and scarlet with metallic-gold patterning for maximum visual contrast.'},
    reasons: ['Scarlet brocade makes the lower silhouette the strongest color field.','Black upper structure provides a clear high-contrast frame.','The color relationship offers a baji-based alternative to the catalog’s royal chima references.'],
    tradeOff: 'This avant-garde runway reference is intentionally dramatic; request a wearable black/red baji interpretation rather than an exact copy.',
    recommendedLocation: {name: 'Gwanghwamun Gate approach',koreanName: '광화문 일대',description: 'A broad architectural backdrop that can support a high-contrast outfit without adding visual clutter.',photoAngle: 'Use a full-length frame from a safe pedestrian area and avoid blocking entrances.'},
    rentalShopCard: {hangulTitle: '검정·진홍 바지 한복 요청',hangulStaffNote: '검정 상의와 진홍/금빛 포인트가 있는 바지 한복을 찾고 있습니다. 사진용으로 대비가 강하되 걷기 가능한 구성인지 확인 부탁드립니다. 실제 디자인과 추가 요금은 먼저 확인해 주세요.',englishExplanation: 'Ask for a black upper layer with scarlet/gold accents and a baji silhouette. Confirm that the available interpretation is comfortable enough to walk in and check any extra fee.'},
    photoRoute: [{order:1,spotName:'Gwanghwamun public approach',koreanName:'광화문 일대',bestTime:'Daylight',photoTip:'Use a clear full-length frame from a safe public pedestrian area.'}],
  },
];

export const EXPANDED_CURATED_LOOKS_CATALOG: readonly CuratedLook[] = Object.freeze([
  ...CURATED_LOOKS_CATALOG,
  ...ADDITIONAL_CURATED_LOOKS,
]);
