'use client';

import {useMemo,useState} from 'react';
import {filterFoodPlaces,type FoodCategory} from '@/lib/travel/gyeongbokgung-food';
type Locale='en'|'zh-CN'|'ja'|'zh-TW'|'vi'|'th';
const C:Record<Locale,Record<string,string>>={
 en:{title:'Food & café finder',intro:'Filter a small source-checked list near Gyeongbokgung. Hours can change, so open the official source before you go.',all:'All',meal:'Korean meal',halal:'Halal-listed',tea:'Traditional tea',coffee:'Coffee',hours:'Hours',closed:'Closed / note',address:'Address',source:'Verify source',diet:'Dietary note',empty:'No verified place in this filter yet.'},
 'zh-CN':{title:'餐厅与咖啡馆查找',intro:'筛选景福宫周边已核对来源的小型列表。营业时间可能变化，出发前请打开官方来源确认。',all:'全部',meal:'韩国料理',halal:'清真列表',tea:'传统茶',coffee:'咖啡',hours:'营业时间',closed:'休息/备注',address:'地址',source:'查看官方来源',diet:'饮食备注',empty:'此筛选暂无已核对地点。'},
 ja:{title:'食事・カフェ検索',intro:'景福宮周辺の出典確認済みの小さなリストを絞り込めます。営業時間は変わるため訪問前に公式情報を確認してください。',all:'すべて',meal:'韓国料理',halal:'ハラール掲載',tea:'伝統茶',coffee:'コーヒー',hours:'営業時間',closed:'休業/メモ',address:'住所',source:'公式情報を確認',diet:'食事条件メモ',empty:'この条件で確認済みの場所はまだありません。'},
 'zh-TW':{title:'餐廳與咖啡館查找',intro:'篩選景福宮周邊已核對來源的小型清單。營業時間可能變動，出發前請開啟官方來源確認。',all:'全部',meal:'韓國料理',halal:'清真列表',tea:'傳統茶',coffee:'咖啡',hours:'營業時間',closed:'休息/備註',address:'地址',source:'查看官方來源',diet:'飲食備註',empty:'此篩選暫無已核對地點。'},
 vi:{title:'Tìm món ăn & quán cà phê',intro:'Lọc danh sách nhỏ đã kiểm tra nguồn quanh Gyeongbokgung. Giờ mở cửa có thể đổi, hãy mở nguồn chính thức trước khi đi.',all:'Tất cả',meal:'Món Hàn',halal:'Có thông tin halal',tea:'Trà truyền thống',coffee:'Cà phê',hours:'Giờ',closed:'Nghỉ / ghi chú',address:'Địa chỉ',source:'Kiểm tra nguồn',diet:'Ghi chú ăn uống',empty:'Chưa có địa điểm đã xác minh cho bộ lọc này.'},
 th:{title:'ค้นหาอาหารและคาเฟ่',intro:'กรองรายชื่อเล็ก ๆ รอบคยองบกกุงที่ตรวจแหล่งข้อมูลแล้ว เวลาเปิดอาจเปลี่ยน โปรดเปิดแหล่งทางการก่อนเดินทาง',all:'ทั้งหมด',meal:'อาหารเกาหลี',halal:'มีข้อมูลฮาลาล',tea:'ชาดั้งเดิม',coffee:'กาแฟ',hours:'เวลา',closed:'วันหยุด/หมายเหตุ',address:'ที่อยู่',source:'ตรวจแหล่งข้อมูล',diet:'หมายเหตุอาหาร',empty:'ยังไม่มีสถานที่ที่ตรวจสอบแล้วในตัวกรองนี้'}
};
export function FoodFinder({locale}:{locale:string}){const l=(locale in C?locale:'en') as Locale,c=C[l];const [category,setCategory]=useState<FoodCategory|'all'>('all');const places=useMemo(()=>filterFoodPlaces(category),[category]);return <section style={{maxWidth:1000,margin:'0 auto',padding:'28px 20px 70px'}}><h1>{c.title}</h1><p>{c.intro}</p><label style={{display:'grid',gap:6,maxWidth:320}}>{c.all}<select value={category} onChange={e=>setCategory(e.target.value as FoodCategory|'all')}><option value="all">{c.all}</option><option value="korean-meal">{c.meal}</option><option value="halal">{c.halal}</option><option value="traditional-tea">{c.tea}</option><option value="coffee">{c.coffee}</option></select></label><div aria-live="polite" style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:14,marginTop:22}}>{places.map(place=><article key={place.id} style={{border:'1px solid currentColor',padding:16}}><h2>{place.name}</h2><p>{place.summary}</p><p><strong>{c.hours}:</strong> {place.hours}</p><p><strong>{c.closed}:</strong> {place.closed}</p><p><strong>{c.address}:</strong> {place.address}</p>{place.dietaryNote?<p><strong>{c.diet}:</strong> {place.dietaryNote}</p>:null}<a href={place.sourceUrl} target="_blank" rel="noreferrer">{c.source} ↗</a><p><small>Checked {place.checkedAt}</small></p></article>)}</div>{!places.length?<p>{c.empty}</p>:null}</section>}
