'use client';

import {useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {filterFoodPlaces,foodAvailabilityAt,foodSourceFreshness,type FoodCategory,type FoodPlace} from '@/lib/travel/gyeongbokgung-food-core';
type Locale='en'|'zh-CN'|'ja'|'zh-TW'|'vi'|'th';
type Copy={title:string;intro:string;all:string;meal:string;halal:string;tea:string;coffee:string;hours:string;closed:string;address:string;source:string;diet:string;empty:string;plan:string;date:string;time:string;openOnly:string;available:string;unavailable:string;verify:string;checked:string;staleSource:string;invalidSource:string;save:string;saved:string;showSaved:string;copyAddress:string;copied:string;map:string;walking:string;storageNote:string};
const C:Record<Locale,Copy>={
 en:{title:'Food & café finder',intro:'Filter a source-checked list near Gyeongbokgung. Add your planned arrival time to hide places that are clearly outside their listed hours.',all:'All',meal:'Korean meal',halal:'Halal-listed',tea:'Traditional tea',coffee:'Coffee',hours:'Hours',closed:'Closed / note',address:'Address',source:'Verify source',diet:'Dietary note',empty:'No source-checked place matches this filter.',plan:'After-palace plan',date:'Date',time:'Expected arrival',openOnly:'Hide clearly closed places',available:'Listed hours fit this time',unavailable:'Outside listed hours / closed day',verify:'Schedule needs re-check',checked:'Source checked',staleSource:'Source check is over 30 days old. Verify the current schedule before visiting.',invalidSource:'Source check date is invalid. Verify the current source before visiting.',save:'Save place',saved:'Saved',showSaved:'Show saved only',copyAddress:'Copy address',copied:'Address copied',map:'Open map',walking:'Walk from Gyeongbokgung',storageNote:'Saved places are stored only as place IDs in this browser.'},
 'zh-CN':{title:'餐厅与咖啡馆查找',intro:'筛选景福宫周边已核对来源的列表。加入预计到达时间后，可隐藏明显不在营业时间内的地点。',all:'全部',meal:'韩国料理',halal:'清真列表',tea:'传统茶',coffee:'咖啡',hours:'营业时间',closed:'休息/备注',address:'地址',source:'查看官方来源',diet:'饮食备注',empty:'没有符合筛选条件的已核对地点。',plan:'宫殿后的安排',date:'日期',time:'预计到达',openOnly:'隐藏明显已关门地点',available:'该时间符合已列营业时间',unavailable:'不在营业时间/休息日',verify:'需要再次确认营业安排',checked:'来源核对',staleSource:'来源核对已超过30天。到访前请重新确认当前营业安排。',invalidSource:'来源核对日期无效。到访前请重新确认当前来源。',save:'收藏地点',saved:'已收藏',showSaved:'只看收藏',copyAddress:'复制地址',copied:'已复制地址',map:'打开地图',walking:'从景福宫步行前往',storageNote:'收藏仅以地点 ID 保存在此浏览器中。'},
 ja:{title:'食事・カフェ検索',intro:'景福宮周辺の出典確認済みリストを絞り込めます。到着予定時刻を入れると、営業時間外と明確に判断できる場所を除外できます。',all:'すべて',meal:'韓国料理',halal:'ハラール掲載',tea:'伝統茶',coffee:'コーヒー',hours:'営業時間',closed:'休業/メモ',address:'住所',source:'公式情報を確認',diet:'食事条件メモ',empty:'条件に合う確認済みの場所はありません。',plan:'宮殿後の予定',date:'日付',time:'到着予定',openOnly:'明確に営業時間外の場所を隠す',available:'掲載営業時間内です',unavailable:'営業時間外 / 休業日',verify:'営業時間を再確認してください',checked:'出典確認',staleSource:'出典確認から30日を超えています。訪問前に最新の営業情報を確認してください。',invalidSource:'出典確認日が無効です。訪問前に最新の情報源を確認してください。',save:'場所を保存',saved:'保存済み',showSaved:'保存済みのみ',copyAddress:'住所をコピー',copied:'住所をコピーしました',map:'地図を開く',walking:'景福宮から徒歩ルート',storageNote:'保存されるのはこのブラウザ内の場所IDだけです。'},
 'zh-TW':{title:'餐廳與咖啡館查找',intro:'篩選景福宮周邊已核對來源的清單。加入預計抵達時間後，可隱藏明顯不在營業時間內的地點。',all:'全部',meal:'韓國料理',halal:'清真列表',tea:'傳統茶',coffee:'咖啡',hours:'營業時間',closed:'休息/備註',address:'地址',source:'查看官方來源',diet:'飲食備註',empty:'沒有符合篩選條件的已核對地點。',plan:'宮殿後的安排',date:'日期',time:'預計抵達',openOnly:'隱藏明顯已關門地點',available:'此時間符合已列營業時間',unavailable:'不在營業時間/休息日',verify:'需要再次確認營業安排',checked:'來源核對',staleSource:'來源核對已超過30天。到訪前請重新確認目前營業安排。',invalidSource:'來源核對日期無效。到訪前請重新確認目前來源。',save:'收藏地點',saved:'已收藏',showSaved:'只看收藏',copyAddress:'複製地址',copied:'已複製地址',map:'開啟地圖',walking:'從景福宮步行前往',storageNote:'收藏只會以地點 ID 儲存在此瀏覽器中。'},
 vi:{title:'Tìm món ăn & quán cà phê',intro:'Lọc danh sách đã kiểm tra nguồn quanh Gyeongbokgung. Thêm giờ dự kiến đến để ẩn những nơi rõ ràng nằm ngoài giờ niêm yết.',all:'Tất cả',meal:'Món Hàn',halal:'Có thông tin halal',tea:'Trà truyền thống',coffee:'Cà phê',hours:'Giờ',closed:'Nghỉ / ghi chú',address:'Địa chỉ',source:'Kiểm tra nguồn',diet:'Ghi chú ăn uống',empty:'Không có địa điểm đã kiểm tra nguồn phù hợp bộ lọc.',plan:'Kế hoạch sau cung điện',date:'Ngày',time:'Giờ dự kiến đến',openOnly:'Ẩn nơi rõ ràng đã đóng',available:'Giờ niêm yết phù hợp',unavailable:'Ngoài giờ / ngày nghỉ',verify:'Cần kiểm tra lại lịch',checked:'Đã kiểm tra nguồn',staleSource:'Nguồn đã được kiểm tra hơn 30 ngày trước. Hãy xác minh lịch hiện tại trước khi đến.',invalidSource:'Ngày kiểm tra nguồn không hợp lệ. Hãy xác minh nguồn hiện tại trước khi đến.',save:'Lưu địa điểm',saved:'Đã lưu',showSaved:'Chỉ hiện đã lưu',copyAddress:'Sao chép địa chỉ',copied:'Đã sao chép địa chỉ',map:'Mở bản đồ',walking:'Đi bộ từ Gyeongbokgung',storageNote:'Chỉ ID địa điểm được lưu trong trình duyệt này.'},
 th:{title:'ค้นหาอาหารและคาเฟ่',intro:'กรองรายชื่อรอบคยองบกกุงที่ตรวจแหล่งข้อมูลแล้ว เพิ่มเวลาที่คาดว่าจะไปถึงเพื่อซ่อนสถานที่ที่อยู่นอกเวลาเปิดอย่างชัดเจน',all:'ทั้งหมด',meal:'อาหารเกาหลี',halal:'มีข้อมูลฮาลาล',tea:'ชาดั้งเดิม',coffee:'กาแฟ',hours:'เวลา',closed:'วันหยุด/หมายเหตุ',address:'ที่อยู่',source:'ตรวจแหล่งข้อมูล',diet:'หมายเหตุอาหาร',empty:'ไม่มีสถานที่ที่ตรวจสอบแหล่งข้อมูลแล้วตรงกับตัวกรอง',plan:'แผนหลังเที่ยวพระราชวัง',date:'วันที่',time:'เวลาที่คาดว่าจะถึง',openOnly:'ซ่อนสถานที่ที่ปิดชัดเจน',available:'เวลาที่ระบุรองรับช่วงนี้',unavailable:'นอกเวลา / วันหยุด',verify:'ควรตรวจตารางเวลาอีกครั้ง',checked:'ตรวจแหล่งข้อมูล',staleSource:'ตรวจแหล่งข้อมูลมานานกว่า 30 วันแล้ว โปรดยืนยันตารางเวลาปัจจุบันก่อนเดินทาง',invalidSource:'วันที่ตรวจแหล่งข้อมูลไม่ถูกต้อง โปรดยืนยันแหล่งข้อมูลปัจจุบันก่อนเดินทาง',save:'บันทึกสถานที่',saved:'บันทึกแล้ว',showSaved:'แสดงเฉพาะที่บันทึก',copyAddress:'คัดลอกที่อยู่',copied:'คัดลอกที่อยู่แล้ว',map:'เปิดแผนที่',walking:'เดินจากพระราชวังคยองบกกุง',storageNote:'ระบบบันทึกเฉพาะ ID ของสถานที่ไว้ในเบราว์เซอร์นี้'}
};
const FAVORITES_KEY='kc-food-favorites-v1';
const GYEONGBOKGUNG_ORIGIN='Gwanghwamun Gate, Gyeongbokgung Palace, Seoul';
function mapHref(name:string,address:string){return`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${name}, ${address}`)}`;}
function walkingHref(name:string,address:string){return`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(GYEONGBOKGUNG_ORIGIN)}&destination=${encodeURIComponent(`${name}, ${address}`)}&travelmode=walking`;}
export function FoodFinder({locale,places:contentPlaces}:{locale:string;places:readonly FoodPlace[]}){
 const l=(locale in C?locale:'en') as Locale,c=C[l];const searchParams=useSearchParams();
 const [category,setCategory]=useState<FoodCategory|'all'>('all');
 const [date,setDate]=useState(searchParams.get('date')??'');const [time,setTime]=useState(searchParams.get('time')??'');const [openOnly,setOpenOnly]=useState(Boolean(searchParams.get('date')&&searchParams.get('time')));
 const [favorites,setFavorites]=useState<Set<string>>(new Set());const [showSaved,setShowSaved]=useState(false);const [copied,setCopied]=useState('');
 const validPlaceIds=useMemo(()=>new Set(contentPlaces.map(place=>place.id)),[contentPlaces]);
 useEffect(()=>{try{const raw=localStorage.getItem(FAVORITES_KEY);if(raw){const ids=JSON.parse(raw);if(Array.isArray(ids)){const valid=ids.filter((id):id is string=>typeof id==='string'&&validPlaceIds.has(id));setFavorites(new Set(valid));if(valid.length!==ids.length)localStorage.setItem(FAVORITES_KEY,JSON.stringify(valid));}}}catch{}},[validPlaceIds]);
 function toggleFavorite(id:string){setFavorites(previous=>{const next=new Set(previous);if(next.has(id))next.delete(id);else next.add(id);try{localStorage.setItem(FAVORITES_KEY,JSON.stringify([...next]));}catch{}return next;});}
 async function copyAddress(id:string,address:string){try{await navigator.clipboard?.writeText(address);setCopied(id);}catch{setCopied('');}}
 const places=useMemo(()=>filterFoodPlaces(contentPlaces,category).map(place=>{const freshness=foodSourceFreshness(place.checkedAt);const scheduleStatus=foodAvailabilityAt(place,date,time);const status=freshness==='fresh'?scheduleStatus:'verify';return{place,status,freshness};}).filter(item=>(!openOnly||item.status!=='closed')&&(!showSaved||favorites.has(item.place.id))),[contentPlaces,category,date,time,openOnly,showSaved,favorites]);
 const statusText=(status:'open'|'closed'|'verify'|'unknown')=>status==='open'?c.available:status==='closed'?c.unavailable:status==='verify'?c.verify:'';
 return <section style={{maxWidth:1000,margin:'0 auto',padding:'28px 20px 70px'}}><h1>{c.title}</h1><p>{c.intro}</p>
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12,alignItems:'end',margin:'20px 0'}}>
   <label style={{display:'grid',gap:6}}>{c.all}<select value={category} onChange={e=>setCategory(e.target.value as FoodCategory|'all')}><option value="all">{c.all}</option><option value="korean-meal">{c.meal}</option><option value="halal">{c.halal}</option><option value="traditional-tea">{c.tea}</option><option value="coffee">{c.coffee}</option></select></label>
   <label style={{display:'grid',gap:6}}>{c.date}<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>
   <label style={{display:'grid',gap:6}}>{c.time}<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label>
   <label style={{display:'flex',gap:8,alignItems:'center',minHeight:44}}><input type="checkbox" checked={openOnly} disabled={!date||!time} onChange={e=>setOpenOnly(e.target.checked)}/>{c.openOnly}</label>
   <label style={{display:'flex',gap:8,alignItems:'center',minHeight:44}}><input type="checkbox" checked={showSaved} onChange={e=>setShowSaved(e.target.checked)}/>{c.showSaved}</label>
  </div>
  {date&&time?<p><strong>{c.plan}:</strong> {date} · {time}</p>:null}
  <div aria-live="polite" style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:14,marginTop:22}}>{places.map(({place,status,freshness})=>{const saved=favorites.has(place.id);return <article key={place.id} style={{border:'1px solid currentColor',padding:16,borderRadius:12}}><h2>{place.name}</h2><p>{place.summary}</p>{status!=='unknown'?<p><strong>{statusText(status)}</strong></p>:null}{freshness!=='fresh'?<p role="status"><strong>{freshness==='stale'?c.staleSource:c.invalidSource}</strong></p>:null}<p><strong>{c.hours}:</strong> {place.hours}</p><p><strong>{c.closed}:</strong> {place.closed}</p><p><strong>{c.address}:</strong> {place.address}</p>{place.dietaryNote?<p><strong>{c.diet}:</strong> {place.dietaryNote}</p>:null}<div style={{display:'flex',gap:8,flexWrap:'wrap',margin:'12px 0'}}><button type="button" className="secondaryButton" aria-pressed={saved} onClick={()=>toggleFavorite(place.id)}>{saved?c.saved:c.save}</button><button type="button" className="secondaryButton" onClick={()=>copyAddress(place.id,place.address)}>{copied===place.id?c.copied:c.copyAddress}</button><a className="secondaryButton" href={mapHref(place.name,place.address)} target="_blank" rel="noreferrer">{c.map}</a><a className="secondaryButton" href={walkingHref(place.name,place.address)} target="_blank" rel="noreferrer">{c.walking}</a></div><a href={place.sourceUrl} target="_blank" rel="noreferrer">{c.source} ↗</a><p><small>{c.checked}: {place.checkedAt}</small></p></article>})}</div>{!places.length?<p>{c.empty}</p>:null}<p><small>{c.storageNote}</small></p></section>;
}