'use client';

import {FormEvent,useMemo,useState} from 'react';
import {Link} from '@/i18n/navigation';

type Locale='en'|'zh-CN'|'ja'|'zh-TW'|'vi'|'th';
type Focus='photo'|'history'|'relaxed';
type Duration=60|120|240;
type Stop={id:string;name:string;ko:string;weight:number;photo:string;history:string};

type Copy={title:string;intro:string;date:string;start:string;duration:string;focus:string;photo:string;history:string;relaxed:string;build:string;route:string;closed:string;hours:string;night:string;nightText:string;minutes:string;arrival:string;stay:string;tip:string;buffer:string;source:string;food:string;hanbok:string;beforeOpen:string;afterClose:string;budget:string};
const C:Record<Locale,Copy>={
 en:{title:'Build my palace route',intro:'Choose a visit date, start time, time budget and priority. The route is recalculated locally without an AI API.',date:'Visit date',start:'Start time',duration:'Time inside the palace',focus:'Priority',photo:'Photos',history:'History',relaxed:'Relaxed pace',build:'Build route',route:'Your timed route',closed:'Gyeongbokgung is normally closed on Tuesdays. Public holidays can change the closure, so verify the official notice before visiting.',hours:'Regular opening hours',night:'2026 autumn night viewing',nightText:'Sep 2–Oct 2, 19:00–21:30, last entry 20:30; no night viewing Mondays or Tuesdays. Ticket rules apply.',minutes:'min',arrival:'Arrive',stay:'Stay',tip:'Tip',buffer:'The route budget includes about 8 minutes between stops. Keep extra time outside this budget for ticketing, entry queues and Hanbok return.',source:'Official palace information',food:'Find food & cafés after the route',hanbok:'Match a Hanbok before you go',beforeOpen:'Your selected start is before regular opening time.',afterClose:'This route would extend beyond regular closing time. Choose an earlier start or a shorter route.',budget:'Planned inside-palace time'},
 'zh-CN':{title:'生成我的宫殿路线',intro:'选择日期、开始时间、可用时间和重点。路线在本地重新计算，不使用 AI API。',date:'游览日期',start:'开始时间',duration:'宫内可用时间',focus:'重点',photo:'拍照',history:'历史',relaxed:'轻松节奏',build:'生成路线',route:'你的时间表',closed:'景福宫通常每周二休宫。遇节假日可能调整，请出发前查看官方公告。',hours:'常规开放时间',night:'2026秋季夜间开放',nightText:'9月2日–10月2日 19:00–21:30，20:30停止入场；周一、周二无夜间开放。需遵守购票规则。',minutes:'分钟',arrival:'到达',stay:'停留',tip:'提示',buffer:'路线预算已包含景点之间约8分钟步行。购票、入场排队和归还韩服请另外预留时间。',source:'宫殿官方信息',food:'路线结束后找餐厅与咖啡馆',hanbok:'出发前匹配韩服',beforeOpen:'选择的开始时间早于常规开门时间。',afterClose:'此路线预计会超过常规闭馆时间，请提前开始或缩短路线。',budget:'宫内计划时间'},
 ja:{title:'宮殿ルートを作る',intro:'日付・開始時刻・滞在時間・優先項目を選ぶと、AI APIなしでルートを再計算します。',date:'訪問日',start:'開始時刻',duration:'宮殿内の時間',focus:'優先',photo:'写真',history:'歴史',relaxed:'ゆったり',build:'ルートを作る',route:'時間つきルート',closed:'景福宮は通常火曜日が休宮です。祝日は変更されることがあるため公式告知を確認してください。',hours:'通常観覧時間',night:'2026年秋 夜間観覧',nightText:'9/2–10/2 19:00–21:30、入場締切20:30。月・火は夜間観覧なし。チケット条件あり。',minutes:'分',arrival:'到着',stay:'滞在',tip:'ポイント',buffer:'各スポット間の移動約8分を予算に含めています。チケット、入場列、韓服返却は別に余裕を取ってください。',source:'宮殿公式情報',food:'ルート後の食事・カフェを探す',hanbok:'訪問前に韓服をマッチ',beforeOpen:'選択した開始時刻は通常の開門前です。',afterClose:'このルートは通常の閉門時刻を超える見込みです。開始を早めるか短いルートを選んでください。',budget:'宮殿内予定時間'},
 'zh-TW':{title:'建立我的宮殿路線',intro:'選擇日期、開始時間、可用時間與重點。路線在本機重新計算，不使用 AI API。',date:'參觀日期',start:'開始時間',duration:'宮內可用時間',focus:'重點',photo:'拍照',history:'歷史',relaxed:'悠閒節奏',build:'建立路線',route:'你的時間表',closed:'景福宮通常每週二休宮。遇國定假日可能調整，出發前請查看官方公告。',hours:'一般開放時間',night:'2026秋季夜間開放',nightText:'9月2日–10月2日 19:00–21:30，20:30停止入場；週一、週二無夜間開放。須遵守購票規則。',minutes:'分鐘',arrival:'抵達',stay:'停留',tip:'提示',buffer:'路線預算已包含景點間約8分鐘步行。購票、入場排隊與歸還韓服請另外預留時間。',source:'宮殿官方資訊',food:'路線結束後找餐廳與咖啡館',hanbok:'出發前配對韓服',beforeOpen:'選擇的開始時間早於一般開門時間。',afterClose:'此路線預計會超過一般閉館時間，請提早開始或縮短路線。',budget:'宮內計畫時間'},
 vi:{title:'Tạo lộ trình cung điện',intro:'Chọn ngày, giờ bắt đầu, quỹ thời gian và ưu tiên. Tuyến đường được tính lại cục bộ, không dùng AI API.',date:'Ngày tham quan',start:'Giờ bắt đầu',duration:'Thời gian trong cung',focus:'Ưu tiên',photo:'Chụp ảnh',history:'Lịch sử',relaxed:'Thư thả',build:'Tạo lộ trình',route:'Lộ trình theo giờ',closed:'Gyeongbokgung thường đóng cửa vào thứ Ba. Ngày lễ có thể thay đổi lịch, hãy kiểm tra thông báo chính thức.',hours:'Giờ mở cửa thường lệ',night:'Ngắm đêm mùa thu 2026',nightText:'2/9–2/10, 19:00–21:30, vào cửa cuối 20:30; không mở đêm thứ Hai và thứ Ba. Có quy định vé.',minutes:'phút',arrival:'Đến',stay:'Ở lại',tip:'Gợi ý',buffer:'Ngân sách lộ trình đã gồm khoảng 8 phút di chuyển giữa các điểm. Hãy chừa thêm thời gian cho vé, xếp hàng và trả Hanbok.',source:'Thông tin chính thức',food:'Tìm món ăn & cà phê sau lộ trình',hanbok:'Ghép Hanbok trước khi đi',beforeOpen:'Giờ bắt đầu đã chọn sớm hơn giờ mở cửa thường lệ.',afterClose:'Lộ trình này dự kiến vượt giờ đóng cửa. Hãy bắt đầu sớm hơn hoặc chọn lộ trình ngắn hơn.',budget:'Thời gian dự kiến trong cung'},
 th:{title:'สร้างเส้นทางพระราชวัง',intro:'เลือกวันที่ เวลาเริ่ม เวลาที่มี และสิ่งสำคัญ ระบบจะคำนวณเส้นทางใหม่ในเครื่องโดยไม่ใช้ AI API',date:'วันที่เที่ยว',start:'เวลาเริ่ม',duration:'เวลาในพระราชวัง',focus:'เน้น',photo:'ถ่ายรูป',history:'ประวัติศาสตร์',relaxed:'เดินสบาย ๆ',build:'สร้างเส้นทาง',route:'เส้นทางพร้อมเวลา',closed:'โดยปกติพระราชวังคยองบกปิดวันอังคาร วันหยุดอาจมีการเปลี่ยนแปลง โปรดตรวจประกาศทางการ',hours:'เวลาชมปกติ',night:'ชมกลางคืนฤดูใบไม้ร่วง 2026',nightText:'2 ก.ย.–2 ต.ค. 19:00–21:30 เข้าครั้งสุดท้าย 20:30; ไม่มีรอบกลางคืนวันจันทร์และอังคาร และมีเงื่อนไขตั๋ว',minutes:'นาที',arrival:'ถึง',stay:'อยู่',tip:'เคล็ดลับ',buffer:'เวลาในแผนรวมการเดินประมาณ 8 นาทีระหว่างจุดแล้ว ควรเผื่อเวลาซื้อตั๋ว ต่อคิว และคืนฮันบกแยกต่างหาก',source:'ข้อมูลทางการ',food:'หาอาหารและคาเฟ่หลังจบเส้นทาง',hanbok:'จับคู่ฮันบกก่อนเดินทาง',beforeOpen:'เวลาเริ่มที่เลือกอยู่ก่อนเวลาเปิดปกติ',afterClose:'เส้นทางนี้คาดว่าจะเกินเวลาปิดปกติ กรุณาเริ่มเร็วขึ้นหรือเลือกเส้นทางที่สั้นลง',budget:'เวลาที่วางแผนในพระราชวัง'}
};

const STOPS:Record<string,Stop>={
 gwanghwamun:{id:'gwanghwamun',name:'Gwanghwamun Gate',ko:'광화문',weight:10,photo:'Wide gate-and-mountain establishing shot.',history:'Main southern gate of Gyeongbokgung.'},
 heungnyemun:{id:'heungnyemun',name:'Heungnyemun Gate',ko:'흥례문',weight:8,photo:'Layer the red gate frames for depth.',history:'Second ceremonial gate on the main axis.'},
 geunjeongjeon:{id:'geunjeongjeon',name:'Geunjeongjeon Hall',ko:'근정전',weight:22,photo:'Use the stone terrace and symmetrical courtyard.',history:'Main throne hall for major state ceremonies.'},
 sajeongjeon:{id:'sajeongjeon',name:'Sajeongjeon Hall',ko:'사정전',weight:13,photo:'Quieter court architecture and dancheong details.',history:'King’s council and daily governance space.'},
 gangnyeongjeon:{id:'gangnyeongjeon',name:'Gangnyeongjeon Hall',ko:'강녕전',weight:12,photo:'Human-scale residential courtyard.',history:'King’s living quarters.'},
 gyotaejeon:{id:'gyotaejeon',name:'Gyotaejeon Hall',ko:'교태전',weight:12,photo:'Elegant residential court lines.',history:'Queen’s main living quarters.'},
 amisan:{id:'amisan',name:'Amisan Garden',ko:'아미산',weight:12,photo:'Chimneys and garden details work well for close portraits.',history:'Terraced rear garden associated with Gyotaejeon.'},
 gyeonghoeru:{id:'gyeonghoeru',name:'Gyeonghoeru Pavilion',ko:'경회루',weight:20,photo:'Pond reflections and a wide pavilion backdrop.',history:'Royal banquet pavilion set over a pond.'},
 hyangwonjeong:{id:'hyangwonjeong',name:'Hyangwonjeong Pavilion',ko:'향원정',weight:20,photo:'Pond, bridge and softer garden scenery.',history:'Hexagonal garden pavilion in the northern palace grounds.'},
 jibokjae:{id:'jibokjae',name:'Jibokjae',ko:'집옥재',weight:12,photo:'Distinctive architectural details away from the busiest axis.',history:'Royal library complex associated with King Gojong.'}
};
const ROUTES:Record<Duration,Record<Focus,string[]>>={
 60:{photo:['gwanghwamun','geunjeongjeon','gyeonghoeru'],history:['gwanghwamun','heungnyemun','geunjeongjeon','sajeongjeon'],relaxed:['gwanghwamun','geunjeongjeon','gyeonghoeru']},
 120:{photo:['gwanghwamun','geunjeongjeon','gyeonghoeru','hyangwonjeong'],history:['gwanghwamun','heungnyemun','geunjeongjeon','sajeongjeon','gangnyeongjeon','gyotaejeon'],relaxed:['gwanghwamun','geunjeongjeon','gyeonghoeru','hyangwonjeong']},
 240:{photo:['gwanghwamun','geunjeongjeon','gyeonghoeru','gangnyeongjeon','gyotaejeon','amisan','hyangwonjeong','jibokjae'],history:['gwanghwamun','heungnyemun','geunjeongjeon','sajeongjeon','gangnyeongjeon','gyotaejeon','amisan','gyeonghoeru','hyangwonjeong','jibokjae'],relaxed:['gwanghwamun','geunjeongjeon','gyeonghoeru','gangnyeongjeon','gyotaejeon','hyangwonjeong']}
};

function isTuesday(date:string){if(!date)return false;const d=new Date(`${date}T12:00:00+09:00`);return !Number.isNaN(d.getTime())&&d.getUTCDay()===2;}
function isNightWindow(date:string){return date>='2026-09-02'&&date<='2026-10-02';}
function openingWindow(date:string){const m=Number(date.slice(5,7));if(m===1||m===2||m===11||m===12)return {open:540,close:1020,label:'09:00–17:00'};if(m>=6&&m<=8)return {open:540,close:1110,label:'09:00–18:30'};return {open:540,close:1080,label:'09:00–18:00'};}
function toMinutes(value:string){const [h,m]=value.split(':').map(Number);return h*60+m;}
function clock(value:number){const wrapped=((value%1440)+1440)%1440;return `${String(Math.floor(wrapped/60)).padStart(2,'0')}:${String(wrapped%60).padStart(2,'0')}`;}
function planStops(duration:Duration,focus:Focus){
 const stops=ROUTES[duration][focus].map(id=>STOPS[id]);
 const walk=8;const walkingTotal=Math.max(0,stops.length-1)*walk;const available=Math.max(stops.length*5,duration-walkingTotal);const weightTotal=stops.reduce((sum,s)=>sum+s.weight,0);
 let allocated=0;
 return stops.map((stop,index)=>{const stay=index===stops.length-1?Math.max(5,available-allocated):Math.max(5,Math.round(stop.weight/weightTotal*available));allocated+=stay;return {...stop,stay,walkAfter:index===stops.length-1?0:walk};});
}

export function GyeongbokgungPlannerV2({locale}:{locale:string}){
 const l=(locale in C?locale:'en') as Locale,c=C[l];
 const initialDate=useMemo(()=>new Date().toISOString().slice(0,10),[]);
 const [date,setDate]=useState(initialDate),[start,setStart]=useState('09:30'),[duration,setDuration]=useState<Duration>(120),[focus,setFocus]=useState<Focus>('photo'),[built,setBuilt]=useState(false);
 const planned=useMemo(()=>planStops(duration,focus),[duration,focus]);
 const timeline=useMemo(()=>{let cursor=toMinutes(start);return planned.map(stop=>{const arrival=cursor;cursor+=stop.stay+stop.walkAfter;return {...stop,arrival};});},[planned,start]);
 const end=timeline.length?timeline[timeline.length-1].arrival+timeline[timeline.length-1].stay:toMinutes(start);
 const window=openingWindow(date);
 function submit(e:FormEvent){e.preventDefault();setBuilt(true);}
 function invalidate(){setBuilt(false);}
 return <section style={{maxWidth:1050,margin:'0 auto',padding:'28px 20px 72px'}}><h2>{c.title}</h2><p>{c.intro}</p><form onSubmit={submit} style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:12,alignItems:'end'}}><label style={{display:'grid',gap:5}}>{c.date}<input required type="date" value={date} onChange={e=>{setDate(e.target.value);invalidate();}}/></label><label style={{display:'grid',gap:5}}>{c.start}<input required type="time" value={start} onChange={e=>{setStart(e.target.value);invalidate();}}/></label><label style={{display:'grid',gap:5}}>{c.duration}<select value={duration} onChange={e=>{setDuration(Number(e.target.value) as Duration);invalidate();}}><option value={60}>1H</option><option value={120}>2H</option><option value={240}>4H</option></select></label><label style={{display:'grid',gap:5}}>{c.focus}<select value={focus} onChange={e=>{setFocus(e.target.value as Focus);invalidate();}}><option value="photo">{c.photo}</option><option value="history">{c.history}</option><option value="relaxed">{c.relaxed}</option></select></label><button className="primaryButton" type="submit">{c.build}</button></form><div style={{marginTop:18,padding:14,border:'1px solid rgba(0,0,0,.12)',borderRadius:12}}><p><strong>{c.hours}:</strong> {window.label}</p>{isTuesday(date)?<p role="alert">{c.closed}</p>:null}{isNightWindow(date)?<p><strong>{c.night}:</strong> {c.nightText}</p>:null}<a href="https://royal.khs.go.kr/ROYAL/contents/R701000000.do" target="_blank" rel="noreferrer">{c.source} ↗</a></div>{built?<div style={{marginTop:24}} aria-live="polite"><h3>{c.route}</h3><p><strong>{c.budget}:</strong> {duration} {c.minutes} · {clock(toMinutes(start))}–{clock(end)}</p>{toMinutes(start)<window.open?<p role="alert">{c.beforeOpen}</p>:null}{end>window.close?<p role="alert">{c.afterClose}</p>:null}{!isTuesday(date)?<ol style={{display:'grid',gap:12,paddingLeft:22}}>{timeline.map(stop=><li key={stop.id}><article style={{border:'1px solid rgba(0,0,0,.1)',borderRadius:12,padding:14}}><strong>{stop.name} · {stop.ko}</strong><p><b>{c.arrival}:</b> {clock(stop.arrival)} · <b>{c.stay}:</b> {stop.stay} {c.minutes}</p><p><b>{c.tip}:</b> {focus==='history'?stop.history:stop.photo}</p></article></li>)}</ol>:null}<p>{c.buffer}</p><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><Link className="secondaryButton" href="/explore/food">{c.food}</Link><Link className="secondaryButton" href="/hanbok">{c.hanbok}</Link></div></div>:null}</section>;
}
