'use client';

import {useMemo,useState} from 'react';
import {GYEONGBOKGUNG_OFFICIAL_GUIDE_SOURCE,GYEONGBOKGUNG_OFFICIAL_VISIT_SOURCE,GYEONGBOKGUNG_VISIT_FACTS_CHECKED_AT,gyeongbokgungGuidedTourTimes,gyeongbokgungVisitFacts,type GyeongbokgungGuideLanguage} from '@/lib/travel/gyeongbokgung-visit-facts';

type Locale='en'|'zh-CN'|'ja'|'zh-TW'|'vi'|'th';
type Copy={title:string;intro:string;date:string;hours:string;last:string;closed:string;verify:string;guide:string;guideHelp:string;english:string;japanese:string;chinese:string;slots:string;select:string;selected:string;meeting:string;duration:string;individual:string;group:string;punctual:string;copy:string;copied:string;source:string;checked:string;privacy:string};
const C:Record<Locale,Copy>={
 en:{title:'Check entry cutoff & guided tours',intro:'Use the official seasonal entry cutoff and foreign-language tour schedule before building your palace route.',date:'Visit date',hours:'Regular hours',last:'Last admission',closed:'Tuesday is the regular closure day.',verify:'Public holidays can move the closure. Verify the official notice before relying on a Tuesday visit.',guide:'Foreign-language guided tour',guideHelp:'Choose the language you plan to join. Times can change for operational reasons.',english:'English',japanese:'Japanese',chinese:'Chinese',slots:'Available regular times',select:'Choose a tour time',selected:'Selected tour',meeting:'Meeting point: in front of the Gyeongbokgung Information Center, inside Heungnyemun Gate.',duration:'Official duration: about 60–90 minutes.',individual:'Fewer than 10 individual visitors can normally join without a separate reservation.',group:'Groups of 10 or more require advance phone reservation; verify current rules on the official page.',punctual:'Tours depart on time, so arrive before the listed start time.',copy:'Copy visit note',copied:'Visit note copied',source:'Official source',checked:'Source checked',privacy:'This helper is deterministic, uses no AI API and sends no itinerary data anywhere.'},
 'zh-CN':{title:'确认入场截止时间与外语讲解',intro:'规划宫殿路线前，先根据官方季节时间确认入场截止时间和外语讲解时段。',date:'参观日期',hours:'常规开放时间',last:'停止入场',closed:'周二为常规休宫日。',verify:'遇节假日休宫日可能调整，周二出行前请核对官方公告。',guide:'外语定时讲解',guideHelp:'选择准备参加的语言。因现场运营安排，时间可能调整。',english:'英语',japanese:'日语',chinese:'中文',slots:'常规定时',select:'选择讲解时间',selected:'已选讲解',meeting:'集合地点：兴礼门内侧的景福宫咨询处前。',duration:'官方说明时长约60–90分钟。',individual:'少于10人的个人游客通常无需单独预约即可参加。',group:'10人及以上团体需要提前电话预约，请在官方页面再次确认现行规则。',punctual:'讲解准时出发，请在所选时间前抵达。',copy:'复制参观备注',copied:'已复制参观备注',source:'官方来源',checked:'来源核对',privacy:'此工具为本地确定性计算，不使用 AI API，也不会发送你的行程数据。'},
 ja:{title:'入場締切と外国語ガイドを確認',intro:'宮殿ルートを作る前に、公式の季節別入場締切と外国語ガイド時間を確認できます。',date:'訪問日',hours:'通常観覧時間',last:'入場締切',closed:'火曜日は通常の休宮日です。',verify:'祝日は休宮日が移動する場合があります。火曜日に訪問する場合は公式告知を確認してください。',guide:'外国語定時ガイド',guideHelp:'参加したい言語を選んでください。運営事情で時間が変更される場合があります。',english:'英語',japanese:'日本語',chinese:'中国語',slots:'通常の開始時刻',select:'ガイド時刻を選ぶ',selected:'選択したガイド',meeting:'集合場所：興礼門内側、景福宮案内所前。',duration:'公式の所要時間は約60〜90分です。',individual:'10人未満の個人観覧客は通常、別途予約なしで参加できます。',group:'10人以上の団体は事前の電話予約が必要です。現行ルールは公式ページで再確認してください。',punctual:'ガイドは定刻に出発するため、開始時刻より前に到着してください。',copy:'訪問メモをコピー',copied:'訪問メモをコピーしました',source:'公式情報',checked:'出典確認',privacy:'このヘルパーは決定論的に動作し、AI APIを使わず、旅程データを外部送信しません。'},
 'zh-TW':{title:'確認入場截止與外語導覽',intro:'建立宮殿路線前，先依官方季節時間確認入場截止與外語導覽時段。',date:'參觀日期',hours:'一般開放時間',last:'停止入場',closed:'週二為一般休宮日。',verify:'遇國定假日休宮日可能調整，週二出發前請核對官方公告。',guide:'外語定時導覽',guideHelp:'選擇準備參加的語言。因現場營運安排，時間可能調整。',english:'英文',japanese:'日文',chinese:'中文',slots:'一般時段',select:'選擇導覽時間',selected:'已選導覽',meeting:'集合地點：興禮門內側的景福宮服務處前。',duration:'官方說明時間約60–90分鐘。',individual:'少於10人的個人旅客通常可免另外預約參加。',group:'10人以上團體需要提前電話預約，請在官方頁面再次確認現行規則。',punctual:'導覽準時出發，請在所選時間前抵達。',copy:'複製參觀備註',copied:'已複製參觀備註',source:'官方來源',checked:'來源核對',privacy:'此工具採本機確定性計算，不使用 AI API，也不會傳送你的行程資料。'},
 vi:{title:'Kiểm tra giờ ngừng vào cửa & tour ngoại ngữ',intro:'Xem giờ ngừng vào cửa theo mùa và lịch tour ngoại ngữ chính thức trước khi tạo lộ trình trong cung.',date:'Ngày tham quan',hours:'Giờ mở cửa thường lệ',last:'Giờ vào cửa cuối',closed:'Thứ Ba là ngày đóng cửa thường lệ.',verify:'Ngày lễ có thể làm thay đổi ngày đóng cửa. Hãy kiểm tra thông báo chính thức trước khi dựa vào kế hoạch thứ Ba.',guide:'Tour hướng dẫn ngoại ngữ',guideHelp:'Chọn ngôn ngữ bạn muốn tham gia. Giờ có thể thay đổi vì lý do vận hành.',english:'Tiếng Anh',japanese:'Tiếng Nhật',chinese:'Tiếng Trung',slots:'Giờ thường lệ',select:'Chọn giờ tour',selected:'Tour đã chọn',meeting:'Điểm gặp: trước Trung tâm Thông tin Gyeongbokgung, bên trong cổng Heungnyemun.',duration:'Thời lượng chính thức: khoảng 60–90 phút.',individual:'Khách lẻ dưới 10 người thường có thể tham gia mà không cần đặt riêng.',group:'Nhóm từ 10 người cần đặt trước qua điện thoại; hãy kiểm tra quy định hiện hành trên trang chính thức.',punctual:'Tour khởi hành đúng giờ, vì vậy hãy đến trước giờ bắt đầu.',copy:'Sao chép ghi chú',copied:'Đã sao chép ghi chú',source:'Nguồn chính thức',checked:'Đã kiểm tra nguồn',privacy:'Công cụ này chạy xác định, không dùng AI API và không gửi dữ liệu hành trình ra ngoài.'},
 th:{title:'เช็กเวลาปิดรับเข้าและทัวร์ภาษาต่างประเทศ',intro:'ตรวจเวลาปิดรับเข้าตามฤดูกาลและรอบทัวร์ภาษาต่างประเทศจากข้อมูลทางการก่อนวางเส้นทางในพระราชวัง',date:'วันที่เที่ยว',hours:'เวลาชมปกติ',last:'เวลาปิดรับเข้า',closed:'วันอังคารเป็นวันปิดประจำ',verify:'วันหยุดราชการอาจทำให้วันปิดเปลี่ยนไป โปรดตรวจประกาศทางการก่อนวางแผนไปวันอังคาร',guide:'ทัวร์ภาษาต่างประเทศ',guideHelp:'เลือกภาษาที่ต้องการเข้าร่วม เวลาอาจเปลี่ยนได้ตามการดำเนินงาน',english:'อังกฤษ',japanese:'ญี่ปุ่น',chinese:'จีน',slots:'รอบปกติ',select:'เลือกรอบทัวร์',selected:'รอบที่เลือก',meeting:'จุดนัดพบ: หน้าศูนย์ข้อมูลคยองบกกุง ด้านในประตูฮึงรเยมุน',duration:'ระยะเวลาตามข้อมูลทางการประมาณ 60–90 นาที',individual:'ผู้เข้าชมรายบุคคลน้อยกว่า 10 คนโดยทั่วไปเข้าร่วมได้โดยไม่ต้องจองแยก',group:'กลุ่ม 10 คนขึ้นไปต้องจองล่วงหน้าทางโทรศัพท์ โปรดตรวจเงื่อนไขปัจจุบันในหน้าทางการ',punctual:'ทัวร์ออกตรงเวลา โปรดมาถึงก่อนเวลาเริ่ม',copy:'คัดลอกบันทึกการเที่ยว',copied:'คัดลอกบันทึกแล้ว',source:'แหล่งข้อมูลทางการ',checked:'ตรวจสอบแหล่งข้อมูล',privacy:'ตัวช่วยนี้คำนวณแบบกำหนดแน่นอน ไม่ใช้ AI API และไม่ส่งข้อมูลแผนการเดินทางออกไป'}
};

function localToday(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function defaultGuideLanguage(locale:Locale):GyeongbokgungGuideLanguage{return locale==='ja'?'ja':locale==='zh-CN'||locale==='zh-TW'?'zh-CN':'en';}

export function GyeongbokgungVisitHelper({locale}:{locale:string}){
 const l=(locale in C?locale:'en') as Locale,c=C[l];
 const [date,setDate]=useState(localToday);
 const [language,setLanguage]=useState<GyeongbokgungGuideLanguage>(()=>defaultGuideLanguage(l));
 const [selected,setSelected]=useState('');
 const [status,setStatus]=useState('');
 const facts=useMemo(()=>gyeongbokgungVisitFacts(date),[date]);
 const tours=useMemo(()=>gyeongbokgungGuidedTourTimes(date,language),[date,language]);
 function changeDate(value:string){setDate(value);setSelected('');setStatus('');}
 function changeLanguage(value:GyeongbokgungGuideLanguage){setLanguage(value);setSelected('');setStatus('');}
 async function copyVisitNote(){
  const languageLabel=language==='ja'?c.japanese:language==='zh-CN'?c.chinese:c.english;
  const lines=[`Gyeongbokgung · ${date}`,`${c.hours}: ${facts.open}–${facts.close}`,`${c.last}: ${facts.lastAdmission}`,`${c.guide}: ${languageLabel}${selected?` · ${selected}`:''}`,c.meeting,c.duration,c.punctual];
  try{await navigator.clipboard?.writeText(lines.join('\n'));setStatus(c.copied);}catch{setStatus('');}
 }
 return <section style={{maxWidth:1050,margin:'0 auto',padding:'8px 20px 28px'}} aria-labelledby="gyeongbokgung-visit-helper-title">
  <div style={{border:'1px solid rgba(0,0,0,.12)',borderRadius:14,padding:18}}>
   <h2 id="gyeongbokgung-visit-helper-title">{c.title}</h2><p>{c.intro}</p><p><small>{c.privacy}</small></p>
   <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12,alignItems:'end'}}>
    <label style={{display:'grid',gap:6}}>{c.date}<input type="date" value={date} onChange={e=>changeDate(e.target.value)}/></label>
    <label style={{display:'grid',gap:6}}>{c.guide}<select value={language} onChange={e=>changeLanguage(e.target.value as GyeongbokgungGuideLanguage)}><option value="en">{c.english}</option><option value="ja">{c.japanese}</option><option value="zh-CN">{c.chinese}</option></select></label>
   </div>
   <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12,marginTop:16}}><article style={{padding:14,borderRadius:10,background:'rgba(0,0,0,.035)'}}><strong>{c.hours}</strong><p>{facts.open}–{facts.close}</p></article><article style={{padding:14,borderRadius:10,background:'rgba(0,0,0,.035)'}}><strong>{c.last}</strong><p>{facts.lastAdmission}</p></article></div>
   {facts.verificationRequired?<div role="alert" style={{marginTop:14}}><strong>{c.closed}</strong><p>{c.verify}</p></div>:<div style={{marginTop:18}}><h3>{c.select}</h3><p><small>{c.guideHelp}</small></p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{tours.map(time=><button type="button" className="secondaryButton" aria-pressed={selected===time} key={time} onClick={()=>{setSelected(time);setStatus('');}}>{time}</button>)}</div>{selected?<div style={{marginTop:14}}><p><strong>{c.selected}:</strong> {selected}</p><p>{c.meeting}</p><p>{c.duration} {c.punctual}</p><p><small>{c.individual} {c.group}</small></p></div>:null}</div>}
   <div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:18}}><button type="button" className="secondaryButton" onClick={copyVisitNote}>{c.copy}</button><a href={GYEONGBOKGUNG_OFFICIAL_VISIT_SOURCE} target="_blank" rel="noreferrer">{c.source} · {c.hours} ↗</a><a href={GYEONGBOKGUNG_OFFICIAL_GUIDE_SOURCE} target="_blank" rel="noreferrer">{c.source} · {c.guide} ↗</a></div>
   <p><small>{c.checked}: {GYEONGBOKGUNG_VISIT_FACTS_CHECKED_AT}</small></p>{status?<p role="status"><strong>{status}</strong></p>:null}
  </div>
 </section>;
}
