'use client';

import {useMemo,useState} from 'react';
import {
  GYEONGBOKGUNG_OFFICIAL_GUIDE_SOURCE,
  GYEONGBOKGUNG_OFFICIAL_VISIT_SOURCE,
  gyeongbokgungGuidedTourTimes,
  gyeongbokgungVisitFacts,
  type GyeongbokgungGuideLanguage,
} from '@/lib/travel/gyeongbokgung-visit-facts';

type Locale='en'|'zh-CN'|'ja'|'zh-TW'|'vi'|'th';
type Copy={title:string;intro:string;date:string;arrival:string;language:string;english:string;japanese:string;chinese:string;closed:string;beforeOpen:string;tooLate:string;canEnter:string;nextTour:string;noTour:string;tourNote:string;lastAdmission:string;copy:string;copied:string;source:string};
const C:Record<Locale,Copy>={
 en:{title:'Can I still enter or catch a guide?',intro:'Use your planned arrival time to check the regular admission cutoff and the next foreign-language tour.',date:'Visit date',arrival:'Arrival at palace gate',language:'Guide language',english:'English',japanese:'Japanese',chinese:'Chinese',closed:'Regular Tuesday closure — verify the official notice because public holidays can move the closure.',beforeOpen:'You are arriving before opening. Plan to wait until the regular opening time.',tooLate:'This arrival is after the regular last-admission cutoff. Do not rely on regular entry.',canEnter:'This arrival is within the regular admission window.',nextTour:'Next regular guided tour',noTour:'No regular tour remains after this arrival time.',tourNote:'Tour times can change for operational reasons; the official page remains authoritative.',lastAdmission:'Regular last admission',copy:'Copy arrival note',copied:'Arrival note copied',source:'Official source'},
 'zh-CN':{title:'还能入场或赶上讲解吗？',intro:'输入预计到达时间，查看常规停止入场时间和下一场外语讲解。',date:'参观日期',arrival:'预计到达宫门时间',language:'讲解语言',english:'英语',japanese:'日语',chinese:'中文',closed:'周二为常规休宫日；节假日可能调整，请以官方公告为准。',beforeOpen:'到达时间早于开门时间，请预留等待时间。',tooLate:'到达时间晚于常规停止入场时间，请勿依赖常规入场。',canEnter:'该到达时间位于常规入场时段内。',nextTour:'下一场常规外语讲解',noTour:'此到达时间之后当天没有常规讲解场次。',tourNote:'讲解时间可能因运营调整，请以官方页面为准。',lastAdmission:'常规停止入场',copy:'复制到达提示',copied:'已复制到达提示',source:'官方来源'},
 ja:{title:'まだ入場・ガイド参加できる？',intro:'到着予定時刻から通常の入場締切と次の外国語ガイドを確認します。',date:'訪問日',arrival:'宮殿到着予定',language:'ガイド言語',english:'英語',japanese:'日本語',chinese:'中国語',closed:'火曜日は通常休宮です。祝日は休宮日が移動する場合があるため公式告知を確認してください。',beforeOpen:'開門前の到着です。通常開門まで待つ時間を見込んでください。',tooLate:'通常の入場締切後です。通常入場を前提にしないでください。',canEnter:'通常の入場可能時間内です。',nextTour:'次の通常外国語ガイド',noTour:'この到着時刻以降の通常ガイドはありません。',tourNote:'運営都合で時間が変わる場合があります。公式ページを優先してください。',lastAdmission:'通常入場締切',copy:'到着メモをコピー',copied:'到着メモをコピーしました',source:'公式情報'},
 'zh-TW':{title:'還能入場或趕上導覽嗎？',intro:'輸入預計抵達時間，查看一般停止入場時間與下一場外語導覽。',date:'參觀日期',arrival:'預計抵達宮門時間',language:'導覽語言',english:'英文',japanese:'日文',chinese:'中文',closed:'週二為一般休宮日；國定假日可能調整，請以官方公告為準。',beforeOpen:'抵達時間早於開門時間，請預留等待時間。',tooLate:'抵達時間晚於一般停止入場時間，請勿依賴一般入場。',canEnter:'此抵達時間位於一般入場時段內。',nextTour:'下一場一般外語導覽',noTour:'此抵達時間之後當天沒有一般導覽場次。',tourNote:'導覽時間可能因營運調整，請以官方頁面為準。',lastAdmission:'一般停止入場',copy:'複製抵達提示',copied:'已複製抵達提示',source:'官方來源'},
 vi:{title:'Còn kịp vào cung hoặc tham gia tour?',intro:'Dùng giờ dự kiến đến để kiểm tra hạn vào cửa thường lệ và tour ngoại ngữ tiếp theo.',date:'Ngày tham quan',arrival:'Giờ đến cổng cung',language:'Ngôn ngữ tour',english:'Tiếng Anh',japanese:'Tiếng Nhật',chinese:'Tiếng Trung',closed:'Thứ Ba là ngày đóng cửa thường lệ; ngày lễ có thể làm đổi lịch, hãy kiểm tra thông báo chính thức.',beforeOpen:'Bạn đến trước giờ mở cửa. Hãy tính thời gian chờ đến giờ mở cửa thường lệ.',tooLate:'Giờ đến đã qua hạn vào cửa thường lệ. Đừng dựa vào khả năng vào cửa thông thường.',canEnter:'Giờ đến nằm trong khung vào cửa thường lệ.',nextTour:'Tour ngoại ngữ thường lệ tiếp theo',noTour:'Không còn tour thường lệ nào sau giờ đến này.',tourNote:'Lịch tour có thể thay đổi do vận hành; trang chính thức là nguồn ưu tiên.',lastAdmission:'Hạn vào cửa thường lệ',copy:'Sao chép ghi chú đến nơi',copied:'Đã sao chép ghi chú',source:'Nguồn chính thức'},
 th:{title:'ยังเข้าพระราชวังหรือทันรอบไกด์ไหม?',intro:'ใช้เวลาที่คาดว่าจะถึงเพื่อตรวจเวลาปิดรับเข้าปกติและรอบไกด์ภาษาต่างประเทศถัดไป',date:'วันที่เที่ยว',arrival:'เวลาถึงประตูพระราชวัง',language:'ภาษาไกด์',english:'อังกฤษ',japanese:'ญี่ปุ่น',chinese:'จีน',closed:'วันอังคารเป็นวันปิดปกติ วันหยุดอาจทำให้วันปิดเปลี่ยน โปรดตรวจประกาศทางการ',beforeOpen:'คุณจะถึงก่อนเวลาเปิด ควรเผื่อเวลารอจนถึงเวลาเปิดปกติ',tooLate:'เวลาที่เลือกเลยเวลาปิดรับเข้าปกติแล้ว ไม่ควรคาดว่าจะเข้าชมแบบปกติได้',canEnter:'เวลาที่เลือกอยู่ในช่วงเข้าชมปกติ',nextTour:'รอบไกด์ภาษาต่างประเทศถัดไป',noTour:'ไม่มีรอบไกด์ปกติหลังเวลาที่เลือกในวันนี้',tourNote:'เวลาไกด์อาจเปลี่ยนตามการดำเนินงาน โปรดยึดหน้าทางการเป็นหลัก',lastAdmission:'เวลาปิดรับเข้าปกติ',copy:'คัดลอกบันทึกการมาถึง',copied:'คัดลอกบันทึกแล้ว',source:'แหล่งข้อมูลทางการ'}
};

function localToday(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function minutes(value:string){const [h,m]=value.split(':').map(Number);return h*60+m;}
function defaultLanguage(locale:Locale):GyeongbokgungGuideLanguage{if(locale==='ja')return'ja';if(locale==='zh-CN'||locale==='zh-TW')return'zh-CN';return'en';}

export function GyeongbokgungArrivalAdvisor({locale}:{locale:string}){
 const l=(locale in C?locale:'en') as Locale,c=C[l];
 const [date,setDate]=useState(localToday);const [arrival,setArrival]=useState('10:30');const [language,setLanguage]=useState<GyeongbokgungGuideLanguage>(()=>defaultLanguage(l));const [status,setStatus]=useState('');
 const facts=useMemo(()=>gyeongbokgungVisitFacts(date),[date]);
 const tours=useMemo(()=>gyeongbokgungGuidedTourTimes(date,language),[date,language]);
 const arrivalMinute=minutes(arrival),openMinute=minutes(facts.open),lastMinute=minutes(facts.lastAdmission);
 const nextTour=useMemo(()=>tours.find(value=>minutes(value)>=Math.max(arrivalMinute,openMinute))??'',[tours,arrivalMinute,openMinute]);
 const state=facts.regularTuesdayClosure?'closed':arrivalMinute<openMinute?'before':arrivalMinute>lastMinute?'late':'ok';
 const stateText=state==='closed'?c.closed:state==='before'?c.beforeOpen:state==='late'?c.tooLate:c.canEnter;
 async function copy(){const lines=[`Gyeongbokgung · ${date}`,`${c.arrival}: ${arrival}`,`${c.lastAdmission}: ${facts.lastAdmission}`,stateText,`${c.nextTour}: ${nextTour||c.noTour}`];try{await navigator.clipboard?.writeText(lines.join('\n'));setStatus(c.copied);}catch{setStatus('');}}
 return <section style={{maxWidth:1050,margin:'0 auto',padding:'0 20px 28px'}}><div style={{border:'1px solid rgba(0,0,0,.12)',borderRadius:14,padding:18}}><h2>{c.title}</h2><p>{c.intro}</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12}}><label style={{display:'grid',gap:6}}>{c.date}<input type="date" value={date} onChange={e=>{setDate(e.target.value);setStatus('');}}/></label><label style={{display:'grid',gap:6}}>{c.arrival}<input type="time" value={arrival} onChange={e=>{setArrival(e.target.value);setStatus('');}}/></label><label style={{display:'grid',gap:6}}>{c.language}<select value={language} onChange={e=>{setLanguage(e.target.value as GyeongbokgungGuideLanguage);setStatus('');}}><option value="en">{c.english}</option><option value="ja">{c.japanese}</option><option value="zh-CN">{c.chinese}</option></select></label></div><p role={state==='late'||state==='closed'?'alert':undefined}><strong>{stateText}</strong></p><p><strong>{c.lastAdmission}:</strong> {facts.lastAdmission}<br/><strong>{c.nextTour}:</strong> {nextTour||c.noTour}</p><p><small>{c.tourNote}</small></p><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><button type="button" className="secondaryButton" onClick={copy}>{c.copy}</button><a className="secondaryButton" href={GYEONGBOKGUNG_OFFICIAL_VISIT_SOURCE} target="_blank" rel="noreferrer">{c.source}: hours ↗</a><a className="secondaryButton" href={GYEONGBOKGUNG_OFFICIAL_GUIDE_SOURCE} target="_blank" rel="noreferrer">{c.source}: tours ↗</a></div>{status?<p role="status"><strong>{status}</strong></p>:null}</div></section>;
}
