'use client';

import {FormEvent,useMemo,useState} from 'react';

type Locale='en'|'zh-CN'|'ja'|'zh-TW'|'vi'|'th';
type Focus='photo'|'history'|'relaxed';
type Stop={id:string;name:string;ko:string;minutes:number;photo:string;history:string};
const STOPS:Record<string,Stop>={
 gwanghwamun:{id:'gwanghwamun',name:'Gwanghwamun Gate',ko:'광화문',minutes:10,photo:'Wide gate-and-mountain establishing shot.',history:'Main southern gate of Gyeongbokgung.'},
 heungnyemun:{id:'heungnyemun',name:'Heungnyemun Gate',ko:'흥례문',minutes:10,photo:'Layer the red gate frames for depth.',history:'Second ceremonial gate on the main axis.'},
 geunjeongjeon:{id:'geunjeongjeon',name:'Geunjeongjeon Hall',ko:'근정전',minutes:25,photo:'Use the stone terrace and symmetrical courtyard.',history:'The main throne hall for major state ceremonies.'},
 sajeongjeon:{id:'sajeongjeon',name:'Sajeongjeon Hall',ko:'사정전',minutes:15,photo:'Quieter court architecture and dancheong details.',history:'King’s council and daily governance space.'},
 gangnyeongjeon:{id:'gangnyeongjeon',name:'Gangnyeongjeon Hall',ko:'강녕전',minutes:15,photo:'Human-scale residential courtyard.',history:'King’s living quarters.'},
 gyotaejeon:{id:'gyotaejeon',name:'Gyotaejeon Hall',ko:'교태전',minutes:15,photo:'Elegant residential court lines.',history:'Queen’s main living quarters.'},
 amisan:{id:'amisan',name:'Amisan Garden',ko:'아미산',minutes:15,photo:'Chimneys and garden details work well for close portraits.',history:'Terraced rear garden associated with Gyotaejeon.'},
 gyeonghoeru:{id:'gyeonghoeru',name:'Gyeonghoeru Pavilion',ko:'경회루',minutes:25,photo:'Pond reflections and a wide pavilion backdrop.',history:'Royal banquet pavilion set over a pond.'},
 hyangwonjeong:{id:'hyangwonjeong',name:'Hyangwonjeong Pavilion',ko:'향원정',minutes:25,photo:'Pond, bridge and softer garden scenery.',history:'Hexagonal garden pavilion in the northern palace grounds.'},
 jibokjae:{id:'jibokjae',name:'Jibokjae',ko:'집옥재',minutes:15,photo:'Distinctive architectural details away from the busiest axis.',history:'Royal library complex associated with King Gojong.'},
};
const ROUTES:Record<60|120|240,Record<Focus,string[]>>={
 60:{photo:['gwanghwamun','geunjeongjeon','gyeonghoeru'],history:['gwanghwamun','heungnyemun','geunjeongjeon','sajeongjeon'],relaxed:['gwanghwamun','geunjeongjeon','gyeonghoeru']},
 120:{photo:['gwanghwamun','geunjeongjeon','gyeonghoeru','hyangwonjeong'],history:['gwanghwamun','heungnyemun','geunjeongjeon','sajeongjeon','gangnyeongjeon','gyotaejeon'],relaxed:['gwanghwamun','geunjeongjeon','gyeonghoeru','hyangwonjeong']},
 240:{photo:['gwanghwamun','geunjeongjeon','gyeonghoeru','gangnyeongjeon','gyotaejeon','amisan','hyangwonjeong','jibokjae'],history:['gwanghwamun','heungnyemun','geunjeongjeon','sajeongjeon','gangnyeongjeon','gyotaejeon','amisan','gyeonghoeru','hyangwonjeong','jibokjae'],relaxed:['gwanghwamun','geunjeongjeon','gyeonghoeru','gangnyeongjeon','gyotaejeon','hyangwonjeong']}
};
const C:Record<Locale,Record<string,string>>={
 en:{title:'Build my palace route',intro:'Choose a date, time budget and priority. This planner runs locally and creates a practical route without an AI API.',date:'Visit date',duration:'Time available',focus:'Priority',photo:'Photos',history:'History',relaxed:'Relaxed pace',build:'Build route',route:'Your route',closed:'Gyeongbokgung is normally closed on Tuesdays. Public holidays can shift the closure, so verify the official notice before visiting.',hours:'Regular opening hours',season1:'09:00–17:00 (last entry 16:00)',season2:'09:00–18:00 (last entry 17:00)',season3:'09:00–18:30 (last entry 17:30)',night:'2026 autumn night viewing',nightText:'Sep 2–Oct 2, 19:00–21:30, last entry 20:30; no night viewing Mondays or Tuesdays. Ticket rules apply.',minutes:'min',tip:'Tip',buffer:'Keep at least 15–20 minutes for ticketing, walking between gates and returning rental Hanbok.',source:'Official palace information'},
 'zh-CN':{title:'生成我的宫殿路线',intro:'选择日期、可用时间和重点。规划器在本地运行，不使用 AI API。',date:'游览日期',duration:'可用时间',focus:'重点',photo:'拍照',history:'历史',relaxed:'轻松节奏',build:'生成路线',route:'你的路线',closed:'景福宫通常每周二休宫。遇节假日可能调整，请出发前查看官方公告。',hours:'常规开放时间',season1:'09:00–17:00（16:00停止入场）',season2:'09:00–18:00（17:00停止入场）',season3:'09:00–18:30（17:30停止入场）',night:'2026秋季夜间开放',nightText:'9月2日–10月2日 19:00–21:30，20:30停止入场；周一、周二无夜间开放。需遵守购票规则。',minutes:'分钟',tip:'提示',buffer:'请至少预留15–20分钟用于购票、门区步行和归还韩服。',source:'宫殿官方信息'},
 ja:{title:'宮殿ルートを作る',intro:'日付・滞在時間・優先したいことを選ぶと、AI APIを使わずローカルでルートを作ります。',date:'訪問日',duration:'使える時間',focus:'優先',photo:'写真',history:'歴史',relaxed:'ゆったり',build:'ルートを作る',route:'あなたのルート',closed:'景福宮は通常火曜日が休宮です。祝日は変更されることがあるため公式告知を確認してください。',hours:'通常観覧時間',season1:'09:00–17:00（入場締切16:00）',season2:'09:00–18:00（入場締切17:00）',season3:'09:00–18:30（入場締切17:30）',night:'2026年秋 夜間観覧',nightText:'9/2–10/2 19:00–21:30、入場締切20:30。月・火は夜間観覧なし。チケット条件あり。',minutes:'分',tip:'ポイント',buffer:'チケット購入・門間の移動・韓服返却用に15～20分以上の余裕を確保してください。',source:'宮殿公式情報'},
 'zh-TW':{title:'建立我的宮殿路線',intro:'選擇日期、可用時間與重點。規劃器在本機運作，不使用 AI API。',date:'參觀日期',duration:'可用時間',focus:'重點',photo:'拍照',history:'歷史',relaxed:'悠閒節奏',build:'建立路線',route:'你的路線',closed:'景福宮通常每週二休宮。遇國定假日可能調整，出發前請查看官方公告。',hours:'一般開放時間',season1:'09:00–17:00（16:00停止入場）',season2:'09:00–18:00（17:00停止入場）',season3:'09:00–18:30（17:30停止入場）',night:'2026秋季夜間開放',nightText:'9月2日–10月2日 19:00–21:30，20:30停止入場；週一、週二無夜間開放。須遵守購票規則。',minutes:'分鐘',tip:'提示',buffer:'請至少預留15–20分鐘給購票、門區步行與歸還韓服。',source:'宮殿官方資訊'},
 vi:{title:'Tạo lộ trình cung điện',intro:'Chọn ngày, thời gian và ưu tiên. Trình lập kế hoạch chạy cục bộ, không dùng AI API.',date:'Ngày tham quan',duration:'Thời gian',focus:'Ưu tiên',photo:'Chụp ảnh',history:'Lịch sử',relaxed:'Thư thả',build:'Tạo lộ trình',route:'Lộ trình của bạn',closed:'Gyeongbokgung thường đóng cửa vào thứ Ba. Ngày lễ có thể thay đổi lịch, hãy kiểm tra thông báo chính thức.',hours:'Giờ mở cửa thường lệ',season1:'09:00–17:00 (vào cửa cuối 16:00)',season2:'09:00–18:00 (vào cửa cuối 17:00)',season3:'09:00–18:30 (vào cửa cuối 17:30)',night:'Ngắm đêm mùa thu 2026',nightText:'2/9–2/10, 19:00–21:30, vào cửa cuối 20:30; không mở đêm thứ Hai và thứ Ba. Có quy định vé.',minutes:'phút',tip:'Gợi ý',buffer:'Nên chừa ít nhất 15–20 phút cho mua vé, đi giữa các cổng và trả Hanbok.',source:'Thông tin chính thức'},
 th:{title:'สร้างเส้นทางพระราชวัง',intro:'เลือกวันที่ เวลาที่มี และสิ่งสำคัญ ระบบวางแผนทำงานในเครื่องโดยไม่ใช้ AI API',date:'วันที่เที่ยว',duration:'เวลาที่มี',focus:'เน้น',photo:'ถ่ายรูป',history:'ประวัติศาสตร์',relaxed:'เดินสบาย ๆ',build:'สร้างเส้นทาง',route:'เส้นทางของคุณ',closed:'โดยปกติพระราชวังคยองบกปิดวันอังคาร วันหยุดอาจมีการเปลี่ยนแปลง โปรดตรวจประกาศทางการ',hours:'เวลาชมปกติ',season1:'09:00–17:00 (เข้าครั้งสุดท้าย 16:00)',season2:'09:00–18:00 (เข้าครั้งสุดท้าย 17:00)',season3:'09:00–18:30 (เข้าครั้งสุดท้าย 17:30)',night:'ชมกลางคืนฤดูใบไม้ร่วง 2026',nightText:'2 ก.ย.–2 ต.ค. 19:00–21:30 เข้าครั้งสุดท้าย 20:30; ไม่มีรอบกลางคืนวันจันทร์และอังคาร และมีเงื่อนไขตั๋ว',minutes:'นาที',tip:'เคล็ดลับ',buffer:'เผื่ออย่างน้อย 15–20 นาทีสำหรับซื้อตั๋ว เดินระหว่างประตู และคืนฮันบก',source:'ข้อมูลทางการ'}
};
function regularHours(date:string,c:Record<string,string>){const m=Number(date.slice(5,7));return m===1||m===2||m===11||m===12?c.season1:m>=6&&m<=8?c.season3:c.season2;}
function isTuesday(date:string){const d=new Date(`${date}T12:00:00+09:00`);return !Number.isNaN(d.getTime())&&d.getUTCDay()===2;}
function isNightWindow(date:string){return date>='2026-09-02'&&date<='2026-10-02';}
export function GyeongbokgungPlanner({locale}:{locale:string}){
 const l=(locale in C?locale:'en') as Locale,c=C[l];const today='2026-09-09';
 const [date,setDate]=useState(today),[duration,setDuration]=useState<60|120|240>(120),[focus,setFocus]=useState<Focus>('photo'),[built,setBuilt]=useState(false);
 const route=useMemo(()=>ROUTES[duration][focus].map(id=>STOPS[id]),[duration,focus]);
 function submit(e:FormEvent){e.preventDefault();setBuilt(true);}
 return <section style={{maxWidth:1050,margin:'0 auto',padding:'24px 20px 64px'}}><h2>{c.title}</h2><p>{c.intro}</p><form onSubmit={submit} style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12}}><label>{c.date}<input type="date" value={date} onChange={e=>{setDate(e.target.value);setBuilt(false)}}/></label><label>{c.duration}<select value={duration} onChange={e=>{setDuration(Number(e.target.value) as 60|120|240);setBuilt(false)}}><option value={60}>1H</option><option value={120}>2H</option><option value={240}>4H</option></select></label><label>{c.focus}<select value={focus} onChange={e=>{setFocus(e.target.value as Focus);setBuilt(false)}}><option value="photo">{c.photo}</option><option value="history">{c.history}</option><option value="relaxed">{c.relaxed}</option></select></label><button className="primaryButton" type="submit">{c.build}</button></form><div style={{marginTop:18,border:'1px solid currentColor',padding:14}}><strong>{c.hours}: {regularHours(date,c)}</strong>{isTuesday(date)?<p role="alert">{c.closed}</p>:null}{isNightWindow(date)?<p><strong>{c.night}:</strong> {c.nightText}</p>:null}<a href="https://royal.khs.go.kr/ROYAL/contents/R702000000.do" target="_blank" rel="noreferrer">{c.source} ↗</a></div>{built?<div aria-live="polite" style={{marginTop:24}}><h3>{c.route}</h3><ol>{route.map((stop,index)=><li key={stop.id} style={{marginBottom:14}}><strong>{index+1}. {stop.name} · {stop.ko}</strong> <span>({stop.minutes} {c.minutes})</span><div><small>{c.tip}: {focus==='history'?stop.history:stop.photo}</small></div></li>)}</ol><p><strong>{c.buffer}</strong></p></div>:null}</section>;
}
