'use client';

import {useMemo,useState} from 'react';
import {GYEONGBOKGUNG_HANBOK_RENTALS,hanbokRentalMapHref,hanbokRentalToPalaceDirectionsHref} from '@/lib/travel/gyeongbokgung-hanbok-rentals';
import {buildKoreaDayPlan,dayPlanFoodMapHref,type DayPlanWarningCode,type PalaceDuration} from '@/lib/travel/korea-day-plan';
import type {FoodCategory} from '@/lib/travel/gyeongbokgung-food-core';
import {Link} from '@/i18n/navigation';

type Locale='en'|'zh-CN'|'ja'|'zh-TW'|'vi'|'th';
type Copy={title:string;intro:string;date:string;entry:string;duration:string;hanbok:string;shop:string;meal:string;build:string;result:string;valid:string;invalid:string;fitting:string;walk:string;palace:string;returnHanbok:string;mealStop:string;map:string;shopToPalace:string;details:string;privacy:string;korean:string;halal:string;tea:string;coffee:string;noHanbok:string;warnings:Record<DayPlanWarningCode,string>};
const C:Record<Locale,Copy>={
 en:{title:'Build my Korea day',intro:'Turn Hanbok fitting, palace time and a meal stop into one practical schedule. Everything is calculated locally from source-checked data.',date:'Visit date',entry:'Palace entry',duration:'Palace time',hanbok:'Wear Hanbok',shop:'Rental shop',meal:'After-palace stop',build:'Build day plan',result:'Your day plan',valid:'This schedule fits the checked regular-hour rules.',invalid:'Adjust the highlighted timing before relying on this plan.',fitting:'Hanbok fitting',walk:'Walk / entry buffer',palace:'Gyeongbokgung visit',returnHanbok:'Return Hanbok',mealStop:'Food / café',map:'Open map',shopToPalace:'Shop → palace walking route',details:'Open detailed palace planner',privacy:'No AI API, booking API or location tracking is used. Hours and inventory can change, so recheck sources before travel.',korean:'Korean meal',halal:'Halal-aware option',tea:'Traditional tea',coffee:'Coffee',noHanbok:'No Hanbok',warnings:{'palace-closed':'The palace is normally closed on Tuesday; verify holiday exceptions on the official site.','before-open':'Your palace entry is before regular opening.','after-last-admission':'Your palace entry is after the regular last-admission cutoff.','past-closing':'The selected palace duration would run past regular closing.','rental-closed':'The selected rental shop is closed at the planned fitting time.','rental-recheck':'The rental shop schedule needs a same-day recheck.','food-unavailable':'No source-checked place in this category is clearly usable at the calculated time.','food-source-stale':'The food-place source is old enough that you should verify it before travel.'}},
 'zh-CN':{title:'安排我的韩国一日行程',intro:'把韩服试穿、景福宫游览和餐饮安排合成一个实际时间表。所有计算都在本地完成。',date:'参观日期',entry:'入宫时间',duration:'宫内时间',hanbok:'穿韩服',shop:'租赁店',meal:'游览后去处',build:'生成一日行程',result:'你的一日行程',valid:'该时间表符合当前核对的常规开放规则。',invalid:'使用前请先调整有警告的时间。',fitting:'韩服试穿',walk:'步行 / 入场缓冲',palace:'景福宫游览',returnHanbok:'归还韩服',mealStop:'餐饮 / 咖啡',map:'打开地图',shopToPalace:'租赁店 → 景福宫步行路线',details:'打开详细宫殿规划器',privacy:'不使用 AI API、预约 API 或位置追踪。营业时间和库存可能变化，出发前请再次核对。',korean:'韩式餐',halal:'清真友好选项',tea:'传统茶',coffee:'咖啡',noHanbok:'不穿韩服',warnings:{'palace-closed':'景福宫通常周二休宫；节假日例外请查看官方公告。','before-open':'选择的入宫时间早于常规开放时间。','after-last-admission':'选择的入宫时间晚于常规停止入场时间。','past-closing':'所选游览时长会超过常规闭馆时间。','rental-closed':'所选租赁店在计划试穿时间已关闭。','rental-recheck':'租赁店营业安排需要当天再次确认。','food-unavailable':'按计算时间，没有可明确确认可用的同类已核对餐饮地点。','food-source-stale':'餐饮来源信息已较旧，出发前请再次确认。'}},
 ja:{title:'韓国での1日プランを作る',intro:'韓服の試着、景福宮、食事・カフェを1つの実用的な時間表にまとめます。計算は端末内で行います。',date:'訪問日',entry:'宮殿入場',duration:'宮殿滞在',hanbok:'韓服を着る',shop:'レンタル店',meal:'宮殿後の立ち寄り',build:'1日プランを作る',result:'1日プラン',valid:'確認済みの通常営業時間ルール内に収まっています。',invalid:'警告された時刻を調整してから利用してください。',fitting:'韓服試着',walk:'徒歩 / 入場バッファ',palace:'景福宮',returnHanbok:'韓服返却',mealStop:'食事 / カフェ',map:'地図を開く',shopToPalace:'店舗 → 景福宮 徒歩ルート',details:'詳細な宮殿プランナーを開く',privacy:'AI API・予約API・位置追跡は使いません。営業時間や在庫は変わるため訪問前に再確認してください。',korean:'韓国料理',halal:'ハラール配慮',tea:'伝統茶',coffee:'コーヒー',noHanbok:'韓服なし',warnings:{'palace-closed':'景福宮は通常火曜日が休宮です。祝日の例外は公式案内を確認してください。','before-open':'入場予定が通常開門前です。','after-last-admission':'入場予定が通常の入場締切後です。','past-closing':'選択した滞在時間では通常閉門を過ぎます。','rental-closed':'試着予定時刻に選択したレンタル店が閉店しています。','rental-recheck':'レンタル店の営業時間は当日に再確認が必要です。','food-unavailable':'計算された時刻に明確に利用できる確認済み店舗がありません。','food-source-stale':'飲食店情報が古くなっているため訪問前に確認してください。'}},
 'zh-TW':{title:'安排我的韓國一日行程',intro:'把韓服試穿、景福宮參觀與餐飲安排整合成一個實際時間表，全部在本機計算。',date:'參觀日期',entry:'入宮時間',duration:'宮內時間',hanbok:'穿韓服',shop:'租借店',meal:'參觀後去處',build:'建立一日行程',result:'你的一日行程',valid:'此時間表符合目前核對的一般開放規則。',invalid:'使用前請先調整有警告的時間。',fitting:'韓服試穿',walk:'步行 / 入場緩衝',palace:'景福宮參觀',returnHanbok:'歸還韓服',mealStop:'餐飲 / 咖啡',map:'開啟地圖',shopToPalace:'租借店 → 景福宮步行路線',details:'開啟詳細宮殿規劃器',privacy:'不使用 AI API、預約 API 或位置追蹤。營業時間與庫存可能變動，出發前請再次確認。',korean:'韓式餐',halal:'清真友善選項',tea:'傳統茶',coffee:'咖啡',noHanbok:'不穿韓服',warnings:{'palace-closed':'景福宮通常週二休宮；國定假日例外請查看官方公告。','before-open':'選擇的入宮時間早於一般開放時間。','after-last-admission':'選擇的入宮時間晚於一般停止入場時間。','past-closing':'所選參觀時間會超過一般閉館時間。','rental-closed':'所選租借店在預定試穿時間已關閉。','rental-recheck':'租借店營業安排需要當天再次確認。','food-unavailable':'依計算時間，沒有可明確確認可用的同類已核對餐飲地點。','food-source-stale':'餐飲來源資訊已較舊，出發前請再次確認。'}},
 vi:{title:'Lập kế hoạch một ngày ở Hàn Quốc',intro:'Ghép thử Hanbok, tham quan Gyeongbokgung và điểm ăn/uống thành một lịch trình thực tế. Mọi phép tính chạy cục bộ.',date:'Ngày tham quan',entry:'Giờ vào cung',duration:'Thời gian trong cung',hanbok:'Mặc Hanbok',shop:'Cửa hàng thuê',meal:'Điểm sau cung điện',build:'Tạo kế hoạch ngày',result:'Kế hoạch của bạn',valid:'Lịch này phù hợp với quy tắc giờ mở cửa thường lệ đã kiểm tra.',invalid:'Hãy chỉnh các mốc thời gian có cảnh báo trước khi dùng.',fitting:'Thử Hanbok',walk:'Đi bộ / thời gian đệm',palace:'Tham quan Gyeongbokgung',returnHanbok:'Trả Hanbok',mealStop:'Ăn uống / cà phê',map:'Mở bản đồ',shopToPalace:'Cửa hàng → cung điện',details:'Mở trình lập kế hoạch cung điện chi tiết',privacy:'Không dùng AI API, API đặt chỗ hay theo dõi vị trí. Giờ mở cửa và tồn kho có thể thay đổi, hãy kiểm tra lại trước khi đi.',korean:'Món Hàn',halal:'Lựa chọn chú ý halal',tea:'Trà truyền thống',coffee:'Cà phê',noHanbok:'Không mặc Hanbok',warnings:{'palace-closed':'Gyeongbokgung thường đóng cửa thứ Ba; hãy kiểm tra ngoại lệ ngày lễ trên trang chính thức.','before-open':'Giờ vào cung sớm hơn giờ mở cửa thường lệ.','after-last-admission':'Giờ vào cung muộn hơn hạn vào cửa thường lệ.','past-closing':'Thời lượng đã chọn sẽ vượt giờ đóng cửa thường lệ.','rental-closed':'Cửa hàng thuê đã đóng vào giờ thử đồ dự kiến.','rental-recheck':'Cần kiểm tra lại giờ của cửa hàng thuê trong ngày đi.','food-unavailable':'Không có địa điểm cùng loại đã kiểm tra nguồn nào rõ ràng phù hợp giờ tính toán.','food-source-stale':'Nguồn thông tin ăn uống đã cũ, hãy xác minh trước khi đi.'}},
 th:{title:'วางแผนวันเที่ยวเกาหลี',intro:'รวมการลองฮันบก เที่ยวคยองบกกุง และร้านอาหาร/คาเฟ่เป็นตารางเดียว คำนวณในเครื่องทั้งหมด',date:'วันที่เที่ยว',entry:'เวลาเข้าพระราชวัง',duration:'เวลาในพระราชวัง',hanbok:'ใส่ฮันบก',shop:'ร้านเช่า',meal:'จุดแวะหลังพระราชวัง',build:'สร้างแผนวันเที่ยว',result:'แผนวันเที่ยวของคุณ',valid:'ตารางนี้อยู่ในกฎเวลาเปิดปกติที่ตรวจสอบแล้ว',invalid:'โปรดปรับเวลาที่มีคำเตือนก่อนใช้งาน',fitting:'ลองฮันบก',walk:'เดิน / เวลาสำรอง',palace:'เที่ยวคยองบกกุง',returnHanbok:'คืนฮันบก',mealStop:'อาหาร / คาเฟ่',map:'เปิดแผนที่',shopToPalace:'ร้าน → พระราชวัง',details:'เปิดตัววางแผนพระราชวังแบบละเอียด',privacy:'ไม่ใช้ AI API, API จอง หรือการติดตามตำแหน่ง เวลาเปิดและสต็อกอาจเปลี่ยน โปรดตรวจอีกครั้งก่อนเดินทาง',korean:'อาหารเกาหลี',halal:'ตัวเลือกคำนึงถึงฮาลาล',tea:'ชาเกาหลี',coffee:'กาแฟ',noHanbok:'ไม่ใส่ฮันบก',warnings:{'palace-closed':'คยองบกกุงปกติปิดวันอังคาร โปรดตรวจข้อยกเว้นวันหยุดจากเว็บไซต์ทางการ','before-open':'เวลาเข้าพระราชวังเร็วกว่าเวลาเปิดปกติ','after-last-admission':'เวลาเข้าพระราชวังเลยเวลาปิดรับเข้าปกติ','past-closing':'ระยะเวลาที่เลือกจะเลยเวลาปิดปกติ','rental-closed':'ร้านเช่าที่เลือกปิดในเวลาลองชุดที่วางไว้','rental-recheck':'ควรตรวจเวลาเปิดร้านเช่าอีกครั้งในวันเดินทาง','food-unavailable':'ไม่มีสถานที่หมวดนี้ที่ตรวจสอบแหล่งข้อมูลแล้วและยืนยันได้ชัดว่าใช้ได้ตามเวลาที่คำนวณ','food-source-stale':'ข้อมูลร้านอาหารเก่าเกินไป ควรตรวจอีกครั้งก่อนเดินทาง'}}
};

function localToday(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
const MEALS:Array<[FoodCategory,keyof Copy]>=[['korean-meal','korean'],['halal','halal'],['traditional-tea','tea'],['coffee','coffee']];
const EVENT_LABEL:Record<KoreaDayPlanEventId,keyof Copy>={fitting:'fitting','walk-to-palace':'walk',palace:'palace','return-hanbok':'returnHanbok',meal:'mealStop'};
type KoreaDayPlanEventId='fitting'|'walk-to-palace'|'palace'|'return-hanbok'|'meal';

export function KoreaDayPlanner({locale}:{locale:string}){
 const l=(locale in C?locale:'en') as Locale,c=C[l];
 const [date,setDate]=useState(localToday);const [entry,setEntry]=useState('10:30');const [duration,setDuration]=useState<PalaceDuration>(120);const [useHanbok,setUseHanbok]=useState(true);const [shopId,setShopId]=useState(GYEONGBOKGUNG_HANBOK_RENTALS[0].id);const [meal,setMeal]=useState<FoodCategory>('korean-meal');const [built,setBuilt]=useState(false);
 const plan=useMemo(()=>buildKoreaDayPlan({date,palaceEntry:entry,palaceMinutes:duration,useHanbok,rentalShopId:shopId,mealCategory:meal}),[date,entry,duration,useHanbok,shopId,meal]);
 function invalidate(){setBuilt(false);}
 return <section style={{maxWidth:1050,margin:'0 auto',padding:'28px 20px 72px'}}><h1>{c.title}</h1><p>{c.intro}</p><p><small>{c.privacy}</small></p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12,alignItems:'end'}}><label style={{display:'grid',gap:6}}>{c.date}<input type="date" value={date} onChange={e=>{setDate(e.target.value);invalidate();}}/></label><label style={{display:'grid',gap:6}}>{c.entry}<input type="time" value={entry} onChange={e=>{setEntry(e.target.value);invalidate();}}/></label><label style={{display:'grid',gap:6}}>{c.duration}<select value={duration} onChange={e=>{setDuration(Number(e.target.value) as PalaceDuration);invalidate();}}><option value={60}>1H</option><option value={120}>2H</option><option value={240}>4H</option></select></label><label style={{display:'flex',gap:8,alignItems:'center',minHeight:44}}><input type="checkbox" checked={useHanbok} onChange={e=>{setUseHanbok(e.target.checked);invalidate();}}/>{c.hanbok}</label>{useHanbok?<label style={{display:'grid',gap:6}}>{c.shop}<select value={shopId} onChange={e=>{setShopId(e.target.value);invalidate();}}>{GYEONGBOKGUNG_HANBOK_RENTALS.map(shop=><option key={shop.id} value={shop.id}>{shop.name}</option>)}</select></label>:null}<label style={{display:'grid',gap:6}}>{c.meal}<select value={meal} onChange={e=>{setMeal(e.target.value as FoodCategory);invalidate();}}>{MEALS.map(([value,key])=><option key={value} value={value}>{String(c[key])}</option>)}</select></label><button type="button" className="primaryButton" onClick={()=>setBuilt(true)}>{c.build}</button></div>{built?<div aria-live="polite" style={{marginTop:24}}><h2>{c.result}</h2><p role={plan.valid?undefined:'alert'}><strong>{plan.valid?c.valid:c.invalid}</strong></p>{plan.warnings.length?<ul>{plan.warnings.map(code=><li key={code}>{c.warnings[code]}</li>)}</ul>:null}<ol style={{display:'grid',gap:10,paddingLeft:22}}>{plan.events.map(event=><li key={`${event.id}-${event.start}`}><strong>{c[EVENT_LABEL[event.id]]}</strong> · {event.start}{event.end?`–${event.end}`:''}<br/><span>{event.label}</span></li>)}</ol><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:16}}>{plan.rentalShop?<><a className="secondaryButton" href={hanbokRentalMapHref(plan.rentalShop)} target="_blank" rel="noreferrer">{c.map}: {plan.rentalShop.name}</a><a className="secondaryButton" href={hanbokRentalToPalaceDirectionsHref(plan.rentalShop)} target="_blank" rel="noreferrer">{c.shopToPalace}</a></>:null}{plan.mealPlace?<a className="secondaryButton" href={dayPlanFoodMapHref(plan.mealPlace)} target="_blank" rel="noreferrer">{c.map}: {plan.mealPlace.name}</a>:null}<Link className="secondaryButton" href={`/explore/gyeongbokgung?date=${encodeURIComponent(date)}&time=${encodeURIComponent(entry)}`}>{c.details}</Link></div></div>:null}</section>;
}
