'use client';

import {FormEvent,useState} from 'react';
import {generateKoreanNames,type KoreanNameCandidate,type KoreanSurnameKey,type NamingSound,type NamingVibe} from '@/lib/naming/korean-name-generator';

type Locale='en'|'zh-CN'|'ja'|'zh-TW'|'vi'|'th';
type Copy={title:string;intro:string;note:string;vibe:string;sound:string;surname:string;seed:string;seedHelp:string;generate:string;results:string;gentle:string;elegant:string;bright:string;strong:string;modern:string;soft:string;crisp:string;balanced:string;none:string;pronunciation:string;meaning:string;hanja:string;copy:string;copied:string;legal:string};
const C:Record<Locale,Copy>={
 en:{title:'Korean Naming Studio',intro:'Create Korean-style name ideas from a curated catalog. No AI API, account or payment is required.',note:'These are cultural nickname/name-inspiration ideas. They do not replace your legal name or guarantee one Hanja meaning.',vibe:'Name vibe',sound:'Sound preference',surname:'Optional Korean surname',seed:'Optional personal keyword',seedHelp:'A short word only changes the deterministic ordering and is not sent anywhere.',generate:'Create name ideas',results:'Your name ideas',gentle:'Gentle',elegant:'Elegant',bright:'Bright',strong:'Strong',modern:'Modern',soft:'Soft',crisp:'Crisp',balanced:'Balanced',none:'Given name only',pronunciation:'Pronunciation',meaning:'Possible meaning theme',hanja:'One possible Hanja writing',copy:'Copy',copied:'Copied',legal:'The same Hangul name can use different Hanja. Verify permitted characters and spelling separately before legal use.'},
 'zh-CN':{title:'韩文命名工作室',intro:'从人工整理的名字库生成韩文风格名字灵感。无需 AI API、账号或付费。',note:'这些是文化昵称/取名灵感，不替代法定姓名，也不保证唯一汉字含义。',vibe:'名字氛围',sound:'发音偏好',surname:'可选韩国姓氏',seed:'可选个人关键词',seedHelp:'短词只会改变固定排序，不会上传。',generate:'生成名字灵感',results:'你的名字灵感',gentle:'温柔',elegant:'优雅',bright:'明亮',strong:'有力量',modern:'现代',soft:'柔和',crisp:'清晰',balanced:'均衡',none:'只要名字',pronunciation:'发音',meaning:'可能的含义主题',hanja:'一种可能的汉字写法',copy:'复制',copied:'已复制',legal:'同一韩文名可能对应不同汉字。若用于法律用途，请另行确认可登记汉字与拼写。'},
 ja:{title:'韓国名スタジオ',intro:'人が選定したカタログから韓国風の名前アイデアを作ります。AI API・アカウント・支払いは不要です。',note:'文化的なニックネーム／名前の着想用で、法的氏名や唯一の漢字意味を保証しません。',vibe:'雰囲気',sound:'響き',surname:'任意の韓国姓',seed:'任意のキーワード',seedHelp:'短い語は決定論的な並び順だけを変え、外部送信されません。',generate:'名前候補を作る',results:'名前候補',gentle:'やさしい',elegant:'上品',bright:'明るい',strong:'力強い',modern:'モダン',soft:'柔らかい',crisp:'はっきり',balanced:'バランス',none:'名だけ',pronunciation:'発音',meaning:'意味テーマの例',hanja:'漢字表記の一例',copy:'コピー',copied:'コピー済み',legal:'同じハングル名でも漢字は複数あり得ます。法的に使う場合は使用可能な文字と表記を別途確認してください。'},
 'zh-TW':{title:'韓文命名工作室',intro:'從人工整理的名字庫產生韓文風格名字靈感。無需 AI API、帳號或付款。',note:'這些是文化暱稱／取名靈感，不取代法定姓名，也不保證唯一漢字含義。',vibe:'名字氛圍',sound:'發音偏好',surname:'可選韓國姓氏',seed:'可選個人關鍵字',seedHelp:'短詞只會改變固定排序，不會上傳。',generate:'產生名字靈感',results:'你的名字靈感',gentle:'溫柔',elegant:'優雅',bright:'明亮',strong:'有力量',modern:'現代',soft:'柔和',crisp:'清晰',balanced:'均衡',none:'只要名字',pronunciation:'發音',meaning:'可能的含義主題',hanja:'一種可能的漢字寫法',copy:'複製',copied:'已複製',legal:'同一韓文名可能對應不同漢字。若用於法律用途，請另行確認可登記漢字與拼寫。'},
 vi:{title:'Korean Naming Studio',intro:'Tạo ý tưởng tên kiểu Hàn từ danh mục tuyển chọn thủ công. Không cần AI API, tài khoản hay thanh toán.',note:'Đây là gợi ý biệt danh/tên mang tính văn hóa, không thay thế tên pháp lý hoặc bảo đảm một nghĩa Hanja duy nhất.',vibe:'Phong cách',sound:'Âm thanh',surname:'Họ Hàn Quốc tùy chọn',seed:'Từ khóa tùy chọn',seedHelp:'Từ ngắn chỉ thay đổi thứ tự xác định và không được gửi ra ngoài.',generate:'Tạo gợi ý tên',results:'Gợi ý tên của bạn',gentle:'Nhẹ nhàng',elegant:'Thanh lịch',bright:'Tươi sáng',strong:'Mạnh mẽ',modern:'Hiện đại',soft:'Mềm',crisp:'Rõ',balanced:'Cân bằng',none:'Chỉ tên riêng',pronunciation:'Phát âm',meaning:'Chủ đề ý nghĩa có thể dùng',hanja:'Một cách viết Hanja khả dĩ',copy:'Sao chép',copied:'Đã sao chép',legal:'Một tên Hangul có thể dùng nhiều Hanja. Hãy kiểm tra ký tự và cách viết nếu dùng hợp pháp.'},
 th:{title:'Korean Naming Studio',intro:'สร้างไอเดียชื่อสไตล์เกาหลีจากคลังที่คัดสรรไว้ ไม่ใช้ AI API ไม่ต้องมีบัญชีหรือชำระเงิน',note:'เป็นไอเดียชื่อเล่น/ชื่อเชิงวัฒนธรรม ไม่ใช่ชื่อทางกฎหมายและไม่รับประกันความหมายฮันจาเพียงแบบเดียว',vibe:'บรรยากาศชื่อ',sound:'สไตล์เสียง',surname:'นามสกุลเกาหลี (ไม่บังคับ)',seed:'คีย์เวิร์ด (ไม่บังคับ)',seedHelp:'คำสั้น ๆ เปลี่ยนเฉพาะลำดับแบบกำหนดแน่นอนและไม่ถูกส่งออกไป',generate:'สร้างไอเดียชื่อ',results:'ไอเดียชื่อของคุณ',gentle:'อ่อนโยน',elegant:'สง่างาม',bright:'สดใส',strong:'เข้มแข็ง',modern:'ทันสมัย',soft:'นุ่ม',crisp:'ชัด',balanced:'สมดุล',none:'เฉพาะชื่อ',pronunciation:'การออกเสียง',meaning:'ธีมความหมายที่เป็นไปได้',hanja:'ตัวอย่างการเขียนฮันจา',copy:'คัดลอก',copied:'คัดลอกแล้ว',legal:'ชื่อฮันกึลเดียวกันอาจมีฮันจาหลายแบบ หากใช้ทางกฎหมายควรตรวจสอบตัวอักษรและการสะกดแยกต่างหาก'}
};
const SURNAMES:Array<[KoreanSurnameKey,string]>=[['none','—'],['kim','김 Kim'],['lee','이 Lee'],['park','박 Park'],['choi','최 Choi'],['jeong','정 Jeong']];

export function NamingStudio({locale}:{locale:string}){
 const l=(locale in C?locale:'en') as Locale,c=C[l];
 const [vibe,setVibe]=useState<NamingVibe>('modern'),[sound,setSound]=useState<NamingSound>('balanced'),[surname,setSurname]=useState<KoreanSurnameKey>('none'),[seed,setSeed]=useState(''),[results,setResults]=useState<KoreanNameCandidate[]>([]),[copied,setCopied]=useState('');
 function submit(e:FormEvent){e.preventDefault();setResults(generateKoreanNames({vibe,sound,surname,seed},6));setCopied('');}
 async function copyName(x:KoreanNameCandidate){try{await navigator.clipboard?.writeText(`${x.fullHangul} · ${x.fullRomanized} · ${x.hanja}`);setCopied(x.id);}catch{setCopied('');}}
 return <section style={{maxWidth:960,margin:'0 auto',padding:'24px 20px 64px'}}><h1>{c.title}</h1><p>{c.intro}</p><p><strong>{c.note}</strong></p><form onSubmit={submit} style={{display:'grid',gap:14,marginTop:22}}><label>{c.vibe}<select value={vibe} onChange={e=>setVibe(e.target.value as NamingVibe)}><option value="gentle">{c.gentle}</option><option value="elegant">{c.elegant}</option><option value="bright">{c.bright}</option><option value="strong">{c.strong}</option><option value="modern">{c.modern}</option></select></label><label>{c.sound}<select value={sound} onChange={e=>setSound(e.target.value as NamingSound)}><option value="soft">{c.soft}</option><option value="crisp">{c.crisp}</option><option value="balanced">{c.balanced}</option></select></label><label>{c.surname}<select value={surname} onChange={e=>setSurname(e.target.value as KoreanSurnameKey)}>{SURNAMES.map(([key,label])=><option key={key} value={key}>{key==='none'?c.none:label}</option>)}</select></label><label>{c.seed}<input maxLength={80} value={seed} onChange={e=>setSeed(e.target.value)}/><small>{c.seedHelp}</small></label><button className="primaryButton" type="submit">{c.generate}</button></form>{results.length?<div aria-live="polite" style={{marginTop:32}}><h2>{c.results}</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:12}}>{results.map(x=><article key={x.id} style={{border:'1px solid currentColor',padding:14}}><h3 style={{fontSize:28,margin:'0 0 4px'}}>{x.fullHangul}</h3><p><strong>{x.fullRomanized}</strong></p><p>{c.pronunciation}: {x.pronunciation}</p><p>{c.hanja}: {x.hanja}</p><p>{c.meaning}: {x.hanjaMeaning}</p><button className="secondaryButton" type="button" onClick={()=>copyName(x)}>{copied===x.id?c.copied:c.copy}</button></article>)}</div><p style={{marginTop:18}}>{c.legal}</p></div>:null}</section>;
}
