'use client';

import {FormEvent,useMemo,useState} from 'react';
import {calculateSajuExperience,type SajuExperienceResult} from '@/lib/saju/experience';
import {buildSajuFunctionalReading} from '@/lib/saju/reading';
import {buildFiveYearOutlooks,visibleStemRoles,type TenGod} from '@/lib/saju/ten-gods';
import type {FiveElementsElement} from '@/lib/saju/input-contracts';

type Locale='en'|'zh-CN'|'ja'|'zh-TW'|'vi'|'th';
type TimeMode='exact'|'rough'|'unknown';
type Period='night'|'morning'|'afternoon'|'evening';

type Labels={title:string;intro:string;notice:string;name:string;nameHelp:string;date:string;timeMode:string;exact:string;rough:string;unknown:string;time:string;period:string;night:string;morning:string;afternoon:string;evening:string;zone:string;zoneHelp:string;go:string;reset:string;error:string;result:string;chart:string;year:string;month:string;day:string;hour:string;unknownHour:string;elements:string;dayMaster:string;strongest:string;weakest:string;partial:string;tenGods:string;tenGodHelp:string;self:string;fiveYear:string;theme:string;focus:string;caution:string;copy:string;copied:string;copyFail:string;download:string;downloaded:string;privacy:string;method:string};

const L:Record<Locale,Labels>={
 en:{title:'Saju fortune reading',intro:'Enter your birth details for a deterministic Four Pillars chart, visible-stem Ten Gods and a five-year symbolic outlook.',notice:'For cultural and entertainment use only. It is not a guaranteed prediction or medical, legal, financial, investment, or other professional advice.',name:'Name (optional)',nameHelp:'Display label only. Your name never changes the Four Pillars calculation.',date:'Birth date',timeMode:'Birth time',exact:'Exact time',rough:'Approximate period',unknown:"I don’t know",time:'Time',period:'Period',night:'Night · 00–06',morning:'Morning · 06–12',afternoon:'Afternoon · 12–18',evening:'Evening · 18–24',zone:'Birthplace timezone',zoneHelp:'Use the IANA timezone of the birthplace, for example Asia/Seoul or America/New_York.',go:'Read my Saju',reset:'Start over',error:'Please check the birth details.',result:'Your Saju reading',chart:'Four Pillars chart',year:'Year',month:'Month',day:'Day',hour:'Hour',unknownHour:'Not guessed',elements:'Five Elements',dayMaster:'Day Master',strongest:'Most represented',weakest:'Least represented',partial:'Birth time is unknown or approximate, so the element balance is intentionally partial.',tenGods:'Ten Gods · visible stems',tenGodHelp:'These are traditional relationship labels between your Day Master and the visible heavenly stems. They are symbolic categories, not scores.',self:'Self / Day Master',fiveYear:'Five-year outlook',theme:'Theme',focus:'Useful focus',caution:'Watch for',copy:'Copy reading',copied:'Reading copied',copyFail:'Copy was blocked. Download the text reading instead.',download:'Download text reading',downloaded:'Reading downloaded',privacy:'Calculation runs in this browser. Birth details are not sent to an AI model and are not saved by this feature.',method:'Method: deterministic calendar calculation plus fixed Five Elements and Ten Gods rules. The five-year section is a symbolic cultural interpretation, not certainty.'},
 'zh-CN':{title:'四柱文化运势解读',intro:'输入出生信息，查看确定性四柱、明透天干十神与未来五年的象征性走势。',notice:'仅供文化与娱乐体验，不是确定性预言，也不构成医疗、法律、金融、投资等专业建议。',name:'姓名（可选）',nameHelp:'只作为结果标签，姓名不会改变四柱计算。',date:'出生日期',timeMode:'出生时间',exact:'准确时间',rough:'大概时段',unknown:'不知道',time:'时间',period:'时段',night:'夜间 · 00–06',morning:'上午 · 06–12',afternoon:'下午 · 12–18',evening:'晚上 · 18–24',zone:'出生地时区',zoneHelp:'请输入出生地 IANA 时区，例如 Asia/Shanghai 或 Asia/Seoul。',go:'查看我的四柱',reset:'重新开始',error:'请检查出生信息。',result:'你的四柱解读',chart:'四柱命盘',year:'年柱',month:'月柱',day:'日柱',hour:'时柱',unknownHour:'不猜测',elements:'五行',dayMaster:'日主',strongest:'相对最多',weakest:'相对最少',partial:'出生时间未知或不精确，因此五行分布只显示可确定部分。',tenGods:'十神 · 明透天干',tenGodHelp:'十神表示日主与命盘中明透天干之间的传统关系，是象征分类而不是评分。',self:'自身 / 日主',fiveYear:'未来五年走势',theme:'主题',focus:'适合关注',caution:'需要留意',copy:'复制解读',copied:'已复制',copyFail:'浏览器阻止复制，请下载文字版。',download:'下载文字版',downloaded:'已下载',privacy:'计算在浏览器内完成。出生信息不会发送给 AI 模型，本功能也不会保存。',method:'方法：确定性历法计算，加上固定的五行与十神规则。五年走势属于文化象征性解读，不表示必然发生。'},
 ja:{title:'四柱・運勢リーディング',intro:'出生情報から決定論的な四柱、表に出る天干の通変星（十神）、今後5年の象徴的な流れを表示します。',notice:'文化・娯楽向けです。確定的な予言ではなく、医療・法律・金融・投資などの専門助言ではありません。',name:'名前（任意）',nameHelp:'結果の表示名だけに使い、四柱計算には使いません。',date:'生年月日',timeMode:'出生時刻',exact:'正確な時刻',rough:'おおよその時間帯',unknown:'不明',time:'時刻',period:'時間帯',night:'夜 · 00–06',morning:'朝 · 06–12',afternoon:'午後 · 12–18',evening:'夜 · 18–24',zone:'出生地タイムゾーン',zoneHelp:'Asia/Tokyo、Asia/Seoul など出生地の IANA タイムゾーンを使ってください。',go:'四柱を読む',reset:'やり直す',error:'出生情報を確認してください。',result:'四柱リーディング',chart:'四柱命式',year:'年柱',month:'月柱',day:'日柱',hour:'時柱',unknownHour:'推測しない',elements:'五行',dayMaster:'日主',strongest:'比較的多い',weakest:'比較的少ない',partial:'出生時刻が不明または概算のため、五行バランスは確定できる範囲のみです。',tenGods:'十神 · 表の天干',tenGodHelp:'日主と命式に見える天干の伝統的な関係分類です。点数や確率ではありません。',self:'自分 / 日主',fiveYear:'今後5年の流れ',theme:'テーマ',focus:'意識したいこと',caution:'注意したいこと',copy:'結果をコピー',copied:'コピーしました',copyFail:'コピーできませんでした。テキスト版をダウンロードしてください。',download:'テキスト版をダウンロード',downloaded:'ダウンロードしました',privacy:'計算はブラウザ内で行います。出生情報を AI モデルへ送らず、この機能では保存しません。',method:'方法：決定論的な暦計算と固定の五行・十神ルール。5年の流れは文化的な象徴解釈であり、確実性を主張しません。'},
 'zh-TW':{title:'四柱文化運勢解讀',intro:'輸入出生資料，查看確定性四柱、明透天干十神與未來五年的象徵性走勢。',notice:'僅供文化與娛樂體驗，不是確定性預言，也不構成醫療、法律、金融、投資等專業建議。',name:'姓名（選填）',nameHelp:'只作為結果標籤，姓名不會改變四柱計算。',date:'出生日期',timeMode:'出生時間',exact:'準確時間',rough:'大概時段',unknown:'不知道',time:'時間',period:'時段',night:'夜間 · 00–06',morning:'上午 · 06–12',afternoon:'下午 · 12–18',evening:'晚上 · 18–24',zone:'出生地時區',zoneHelp:'請輸入出生地 IANA 時區，例如 Asia/Taipei 或 Asia/Seoul。',go:'查看我的四柱',reset:'重新開始',error:'請檢查出生資料。',result:'你的四柱解讀',chart:'四柱命盤',year:'年柱',month:'月柱',day:'日柱',hour:'時柱',unknownHour:'不猜測',elements:'五行',dayMaster:'日主',strongest:'相對最多',weakest:'相對最少',partial:'出生時間未知或不精確，因此五行分布只顯示可確定部分。',tenGods:'十神 · 明透天干',tenGodHelp:'十神表示日主與命盤中明透天干的傳統關係，是象徵分類而不是評分。',self:'自身 / 日主',fiveYear:'未來五年走勢',theme:'主題',focus:'適合關注',caution:'需要留意',copy:'複製解讀',copied:'已複製',copyFail:'瀏覽器阻擋複製，請下載文字版。',download:'下載文字版',downloaded:'已下載',privacy:'計算在瀏覽器內完成。出生資料不會傳送給 AI 模型，本功能也不會保存。',method:'方法：確定性曆法計算，加上固定五行與十神規則。五年走勢屬文化象徵性解讀，不代表必然發生。'},
 vi:{title:'Đọc vận Saju',intro:'Nhập thông tin sinh để xem Tứ trụ xác định, Thập thần của thiên can lộ và xu hướng biểu tượng trong 5 năm tới.',notice:'Chỉ dành cho văn hóa và giải trí. Không phải tiên đoán chắc chắn hay tư vấn y tế, pháp lý, tài chính, đầu tư hoặc chuyên môn.',name:'Tên (không bắt buộc)',nameHelp:'Chỉ dùng làm nhãn kết quả, không thay đổi phép tính Tứ trụ.',date:'Ngày sinh',timeMode:'Giờ sinh',exact:'Giờ chính xác',rough:'Khoảng thời gian',unknown:'Không biết',time:'Giờ',period:'Khoảng',night:'Đêm · 00–06',morning:'Sáng · 06–12',afternoon:'Chiều · 12–18',evening:'Tối · 18–24',zone:'Múi giờ nơi sinh',zoneHelp:'Dùng múi giờ IANA của nơi sinh như Asia/Ho_Chi_Minh hoặc Asia/Seoul.',go:'Đọc Saju của tôi',reset:'Làm lại',error:'Hãy kiểm tra thông tin sinh.',result:'Kết quả Saju',chart:'Biểu đồ Tứ trụ',year:'Năm',month:'Tháng',day:'Ngày',hour:'Giờ',unknownHour:'Không đoán',elements:'Ngũ hành',dayMaster:'Nhật chủ',strongest:'Nhiều hơn tương đối',weakest:'Ít hơn tương đối',partial:'Giờ sinh chưa rõ hoặc chỉ ước lượng nên cân bằng Ngũ hành chỉ hiển thị phần có thể xác định.',tenGods:'Thập thần · thiên can lộ',tenGodHelp:'Đây là các nhãn quan hệ truyền thống giữa Nhật chủ và thiên can nhìn thấy, không phải điểm số hay xác suất.',self:'Bản thân / Nhật chủ',fiveYear:'Xu hướng 5 năm',theme:'Chủ đề',focus:'Nên tập trung',caution:'Cần lưu ý',copy:'Sao chép kết quả',copied:'Đã sao chép',copyFail:'Trình duyệt chặn sao chép. Hãy tải bản văn bản.',download:'Tải bản văn bản',downloaded:'Đã tải',privacy:'Phép tính chạy trong trình duyệt. Dữ liệu sinh không được gửi tới mô hình AI và không được lưu bởi tính năng này.',method:'Phương pháp: lịch xác định cộng với quy tắc Ngũ hành và Thập thần cố định. Phần 5 năm là diễn giải văn hóa mang tính biểu tượng, không khẳng định chắc chắn.'},
 th:{title:'อ่านดวงซาจู',intro:'กรอกข้อมูลเกิดเพื่อดูสี่เสาแบบกำหนดแน่นอน สิบเทพของก้านฟ้าที่ปรากฏ และแนวโน้มเชิงสัญลักษณ์ 5 ปีข้างหน้า',notice:'เพื่อวัฒนธรรมและความบันเทิงเท่านั้น ไม่ใช่คำทำนายที่แน่นอนหรือคำแนะนำทางการแพทย์ กฎหมาย การเงิน การลงทุน หรือวิชาชีพ',name:'ชื่อ (ไม่บังคับ)',nameHelp:'ใช้เป็นป้ายชื่อผลลัพธ์เท่านั้น ไม่เปลี่ยนการคำนวณสี่เสา',date:'วันเกิด',timeMode:'เวลาเกิด',exact:'เวลาที่แน่นอน',rough:'ช่วงเวลาโดยประมาณ',unknown:'ไม่ทราบ',time:'เวลา',period:'ช่วง',night:'กลางคืน · 00–06',morning:'เช้า · 06–12',afternoon:'บ่าย · 12–18',evening:'เย็น · 18–24',zone:'เขตเวลาสถานที่เกิด',zoneHelp:'ใช้เขตเวลา IANA ของสถานที่เกิด เช่น Asia/Bangkok หรือ Asia/Seoul',go:'อ่านซาจูของฉัน',reset:'เริ่มใหม่',error:'โปรดตรวจสอบข้อมูลเกิด',result:'ผลการอ่านซาจู',chart:'แผนผังสี่เสา',year:'ปี',month:'เดือน',day:'วัน',hour:'ยาม',unknownHour:'ไม่เดา',elements:'ธาตุทั้งห้า',dayMaster:'Day Master',strongest:'มีมากกว่าโดยเปรียบเทียบ',weakest:'มีน้อยกว่าโดยเปรียบเทียบ',partial:'ไม่ทราบเวลาเกิดหรือเป็นเวลาโดยประมาณ จึงแสดงสมดุลธาตุเท่าที่คำนวณได้เท่านั้น',tenGods:'สิบเทพ · ก้านฟ้าที่ปรากฏ',tenGodHelp:'เป็นป้ายความสัมพันธ์แบบดั้งเดิมระหว่าง Day Master กับก้านฟ้าที่มองเห็น ไม่ใช่คะแนนหรือความน่าจะเป็น',self:'ตัวตน / Day Master',fiveYear:'แนวโน้ม 5 ปี',theme:'ธีม',focus:'จุดที่ควรโฟกัส',caution:'สิ่งที่ควรระวัง',copy:'คัดลอกผล',copied:'คัดลอกแล้ว',copyFail:'เบราว์เซอร์บล็อกการคัดลอก โปรดดาวน์โหลดข้อความแทน',download:'ดาวน์โหลดข้อความ',downloaded:'ดาวน์โหลดแล้ว',privacy:'การคำนวณทำในเบราว์เซอร์ ข้อมูลเกิดไม่ถูกส่งไปยังโมเดล AI และฟีเจอร์นี้ไม่บันทึกข้อมูล',method:'วิธี: การคำนวณปฏิทินแบบกำหนดแน่นอนร่วมกับกฎธาตุทั้งห้าและสิบเทพคงที่ ส่วน 5 ปีเป็นการตีความเชิงวัฒนธรรม ไม่อ้างความแน่นอน'}
};

const ELEMENT:Record<Locale,Record<FiveElementsElement,string>>={
 en:{wood:'Wood',fire:'Fire',earth:'Earth',metal:'Metal',water:'Water'},'zh-CN':{wood:'木',fire:'火',earth:'土',metal:'金',water:'水'},ja:{wood:'木',fire:'火',earth:'土',metal:'金',water:'水'},'zh-TW':{wood:'木',fire:'火',earth:'土',metal:'金',water:'水'},vi:{wood:'Mộc',fire:'Hỏa',earth:'Thổ',metal:'Kim',water:'Thủy'},th:{wood:'ไม้',fire:'ไฟ',earth:'ดิน',metal:'โลหะ',water:'น้ำ'}
};

const GOD:Record<Locale,Record<TenGod|string,string>>={
 en:{peer:'Peer',robWealth:'Rob Wealth',eatingGod:'Eating God',hurtingOfficer:'Hurting Officer',indirectWealth:'Indirect Wealth',directWealth:'Direct Wealth',sevenKillings:'Seven Killings',directOfficer:'Direct Officer',indirectResource:'Indirect Resource',directResource:'Direct Resource',self:'Self'},
 'zh-CN':{peer:'比肩',robWealth:'劫财',eatingGod:'食神',hurtingOfficer:'伤官',indirectWealth:'偏财',directWealth:'正财',sevenKillings:'七杀',directOfficer:'正官',indirectResource:'偏印',directResource:'正印',self:'日主'},
 ja:{peer:'比肩',robWealth:'劫財',eatingGod:'食神',hurtingOfficer:'傷官',indirectWealth:'偏財',directWealth:'正財',sevenKillings:'七殺',directOfficer:'正官',indirectResource:'偏印',directResource:'印綬',self:'日主'},
 'zh-TW':{peer:'比肩',robWealth:'劫財',eatingGod:'食神',hurtingOfficer:'傷官',indirectWealth:'偏財',directWealth:'正財',sevenKillings:'七殺',directOfficer:'正官',indirectResource:'偏印',directResource:'正印',self:'日主'},
 vi:{peer:'Tỷ Kiên',robWealth:'Kiếp Tài',eatingGod:'Thực Thần',hurtingOfficer:'Thương Quan',indirectWealth:'Thiên Tài',directWealth:'Chính Tài',sevenKillings:'Thất Sát',directOfficer:'Chính Quan',indirectResource:'Thiên Ấn',directResource:'Chính Ấn',self:'Nhật chủ'},
 th:{peer:'เพื่อนร่วมธาตุ',robWealth:'คู่แข่งทรัพย์',eatingGod:'การแสดงออกที่มั่นคง',hurtingOfficer:'การแสดงออกอิสระ',indirectWealth:'โอกาสทรัพย์ยืดหยุ่น',directWealth:'ทรัพย์แบบมีระบบ',sevenKillings:'แรงกดดันท้าทาย',directOfficer:'โครงสร้างและหน้าที่',indirectResource:'การเรียนรู้เชิงทดลอง',directResource:'การสนับสนุนและการเรียนรู้',self:'Day Master'}
};

const GOD_NOTE:Record<Locale,Record<TenGod,string>>={
 en:{peer:'identity, peers and self-direction',robWealth:'competition, sharing and boundaries',eatingGod:'craft, expression and steady output',hurtingOfficer:'independent expression and challenging conventions',indirectWealth:'flexible opportunities and resource movement',directWealth:'structured resources, budgeting and practical responsibility',sevenKillings:'pressure, challenge and decisive action',directOfficer:'structure, duty and measured responsibility',indirectResource:'unusual learning, intuition and experimentation',directResource:'support, study, preparation and recovery'},
 'zh-CN':{peer:'自我、同伴与自主性',robWealth:'竞争、分享与边界',eatingGod:'技能、表达与稳定产出',hurtingOfficer:'独立表达与挑战惯例',indirectWealth:'灵活机会与资源流动',directWealth:'有序资源、预算与实际责任',sevenKillings:'压力、挑战与果断行动',directOfficer:'秩序、责任与稳健执行',indirectResource:'非典型学习、直觉与探索',directResource:'支持、学习、准备与恢复'},
 ja:{peer:'自己軸・仲間・自立性',robWealth:'競争・分かち合い・境界線',eatingGod:'技能・表現・安定したアウトプット',hurtingOfficer:'独自表現・慣例への問い直し',indirectWealth:'柔軟な機会・資源の流動',directWealth:'計画的な資源・予算・実務責任',sevenKillings:'圧力・挑戦・決断',directOfficer:'秩序・役割・着実な責任',indirectResource:'独自の学び・直感・実験',directResource:'支援・学習・準備・回復'},
 'zh-TW':{peer:'自我、同伴與自主性',robWealth:'競爭、分享與界線',eatingGod:'技能、表達與穩定產出',hurtingOfficer:'獨立表達與挑戰慣例',indirectWealth:'彈性機會與資源流動',directWealth:'有序資源、預算與實際責任',sevenKillings:'壓力、挑戰與果斷行動',directOfficer:'秩序、責任與穩健執行',indirectResource:'非典型學習、直覺與探索',directResource:'支持、學習、準備與恢復'},
 vi:{peer:'bản sắc, đồng hành và tự chủ',robWealth:'cạnh tranh, chia sẻ và ranh giới',eatingGod:'kỹ năng, biểu đạt và đầu ra đều đặn',hurtingOfficer:'biểu đạt độc lập và chất vấn khuôn mẫu',indirectWealth:'cơ hội linh hoạt và dòng nguồn lực',directWealth:'nguồn lực có cấu trúc, ngân sách và trách nhiệm thực tế',sevenKillings:'áp lực, thử thách và hành động quyết đoán',directOfficer:'trật tự, nghĩa vụ và trách nhiệm có chừng mực',indirectResource:'học khác lối, trực giác và thử nghiệm',directResource:'hỗ trợ, học tập, chuẩn bị và hồi phục'},
 th:{peer:'ตัวตน เพื่อนร่วมทาง และความเป็นอิสระ',robWealth:'การแข่งขัน การแบ่งปัน และขอบเขต',eatingGod:'ทักษะ การแสดงออก และผลงานสม่ำเสมอ',hurtingOfficer:'การแสดงออกอิสระและการตั้งคำถามต่อแบบแผน',indirectWealth:'โอกาสยืดหยุ่นและการเคลื่อนของทรัพยากร',directWealth:'ทรัพยากรแบบมีระบบ งบประมาณ และความรับผิดชอบ',sevenKillings:'แรงกดดัน ความท้าทาย และการตัดสินใจ',directOfficer:'โครงสร้าง หน้าที่ และความรับผิดชอบ',indirectResource:'การเรียนรู้นอกกรอบ สัญชาตญาณ และการทดลอง',directResource:'การสนับสนุน การเรียนรู้ การเตรียมตัว และการฟื้นตัว'}
};

function parseDate(v:string){const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(v);if(!m)throw new RangeError('Invalid date');return{year:Number(m[1]),month:Number(m[2]),day:Number(m[3])};}
function pillarText(p?:{stem:string;branch:string}){return p?`${p.stem}${p.branch}`:'—';}

export function SajuDeepExperience({locale}:{locale:string}){
 const active=(locale in L?locale:'en') as Locale,c=L[active];
 const [name,setName]=useState('');const [date,setDate]=useState('');const [mode,setMode]=useState<TimeMode>('unknown');const [time,setTime]=useState('12:00');const [period,setPeriod]=useState<Period>('morning');const [zone,setZone]=useState('');const [result,setResult]=useState<SajuExperienceResult|null>(null);const [error,setError]=useState('');const [message,setMessage]=useState('');
 const base=useMemo(()=>result?buildSajuFunctionalReading(result,new Date().getFullYear()):null,[result]);
 const roles=useMemo(()=>result?visibleStemRoles(result):[],[result]);
 const future=useMemo(()=>result?buildFiveYearOutlooks(result,new Date().getFullYear()):[],[result]);
 const counts=result?(result.fiveElements.exact??result.fiveElements.base):null;
 function submit(e:FormEvent){e.preventDefault();setError('');setMessage('');try{const d=parseDate(date);if(!zone.trim())throw new RangeError(c.zoneHelp);let birthTime;if(mode==='exact'){const m=/^(\d{2}):(\d{2})$/.exec(time);if(!m)throw new RangeError(c.error);birthTime={mode:'exact' as const,hour:Number(m[1]),minute:Number(m[2])};}else if(mode==='rough')birthTime={mode:'rough' as const,period};else birthTime={mode:'unknown' as const};setResult(calculateSajuExperience({...d,timeZone:zone.trim(),time:birthTime}));}catch(err){setResult(null);setError(err instanceof Error?err.message:c.error);}}
 const exportText=useMemo(()=>{if(!result||!base)return'';const rows=[`${name.trim()?`${name.trim()} — `:''}${c.result}`,`${c.chart}: ${c.year} ${pillarText(result.pillars.year)} · ${c.month} ${pillarText(result.pillars.month)} · ${c.day} ${pillarText(result.pillars.day)} · ${c.hour} ${pillarText(result.pillars.hour)}`,`${c.dayMaster}: ${base.dayMaster.stem} · ${ELEMENT[active][base.dayMaster.element]}`,`${c.strongest}: ${ELEMENT[active][base.strongest]} · ${c.weakest}: ${ELEMENT[active][base.weakest]}`,c.tenGods,...roles.map(r=>`${r.pillar}: ${r.stem} · ${r.tenGod==='self'?c.self:GOD[active][r.tenGod]}${r.tenGod==='self'?'':` — ${GOD_NOTE[active][r.tenGod]}`}`),c.fiveYear,...future.map(y=>`${y.year} ${pillarText(y.pillar)} · ${GOD[active][y.tenGod]} — ${GOD_NOTE[active][y.tenGod]}`),'',c.notice,c.method,c.privacy];return rows.join('\n');},[active,base,c,future,name,result,roles]);
 async function copy(){if(!exportText)return;try{if(!navigator.clipboard?.writeText)throw new Error();await navigator.clipboard.writeText(exportText);setMessage(c.copied);}catch{setMessage(c.copyFail);}}
 function download(){if(!exportText)return;const blob=new Blob([exportText],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='korea-concierge-saju.txt';a.click();URL.revokeObjectURL(url);setMessage(c.downloaded);}
 function reset(){setName('');setDate('');setMode('unknown');setTime('12:00');setPeriod('morning');setZone('');setResult(null);setError('');setMessage('');}
 return <section style={{maxWidth:960,margin:'0 auto',padding:'2rem 1rem'}}><h1>{c.title}</h1><p>{c.intro}</p><p><strong>{c.notice}</strong></p>
 {!result?<form onSubmit={submit} noValidate><p><label>{c.name}<br/><input value={name} onChange={e=>setName(e.target.value)} maxLength={80} autoComplete="name"/></label><br/><small>{c.nameHelp}</small></p><p><label>{c.date}<br/><input type="date" required value={date} min="1900-01-01" max="2100-12-31" onChange={e=>setDate(e.target.value)}/></label></p><fieldset><legend>{c.timeMode}</legend><label><input type="radio" checked={mode==='exact'} onChange={()=>setMode('exact')}/>{c.exact}</label>{' '}<label><input type="radio" checked={mode==='rough'} onChange={()=>setMode('rough')}/>{c.rough}</label>{' '}<label><input type="radio" checked={mode==='unknown'} onChange={()=>setMode('unknown')}/>{c.unknown}</label></fieldset>{mode==='exact'&&<p><label>{c.time}<br/><input type="time" value={time} onChange={e=>setTime(e.target.value)} required/></label></p>}{mode==='rough'&&<p><label>{c.period}<br/><select value={period} onChange={e=>setPeriod(e.target.value as Period)}><option value="night">{c.night}</option><option value="morning">{c.morning}</option><option value="afternoon">{c.afternoon}</option><option value="evening">{c.evening}</option></select></label></p>}<p><label>{c.zone}<br/><input value={zone} onChange={e=>setZone(e.target.value)} placeholder="Asia/Seoul" list="saju-timezones" required/></label><br/><small>{c.zoneHelp}</small></p><datalist id="saju-timezones"><option value="Asia/Seoul"/><option value="Asia/Tokyo"/><option value="Asia/Shanghai"/><option value="Asia/Taipei"/><option value="Asia/Bangkok"/><option value="Asia/Ho_Chi_Minh"/><option value="America/New_York"/><option value="America/Los_Angeles"/><option value="Europe/London"/><option value="Europe/Paris"/></datalist><button type="submit">{c.go}</button>{error&&<p role="alert">{error}</p>}</form>:
 <div><h2>{name.trim()?`${name.trim()} — ${c.result}`:c.result}</h2><section><h3>{c.chart}</h3><dl><dt>{c.year}</dt><dd>{pillarText(result.pillars.year)}</dd><dt>{c.month}</dt><dd>{pillarText(result.pillars.month)}</dd><dt>{c.day}</dt><dd>{pillarText(result.pillars.day)}</dd><dt>{c.hour}</dt><dd>{result.pillars.hour?pillarText(result.pillars.hour):c.unknownHour}</dd></dl></section>{base&&<section><h3>{c.elements}</h3><p><strong>{c.dayMaster}:</strong> {base.dayMaster.stem} · {ELEMENT[active][base.dayMaster.element]} · {base.dayMaster.polarity}</p><p><strong>{c.strongest}:</strong> {ELEMENT[active][base.strongest]} · <strong>{c.weakest}:</strong> {ELEMENT[active][base.weakest]}</p>{counts&&<ul>{(['wood','fire','earth','metal','water'] as FiveElementsElement[]).map(el=><li key={el}>{ELEMENT[active][el]}: {counts[el]??0}</li>)}</ul>}{base.balanceIsPartial&&<p>{c.partial}</p>}</section>}<section><h3>{c.tenGods}</h3><p>{c.tenGodHelp}</p><ul>{roles.map(r=><li key={r.pillar}><strong>{r.pillar} · {r.stem}:</strong> {r.tenGod==='self'?c.self:GOD[active][r.tenGod]}{r.tenGod!=='self'&&<> — {GOD_NOTE[active][r.tenGod]}</>}</li>)}</ul></section><section><h3>{c.fiveYear}</h3>{future.map(y=><article key={y.year}><h4>{y.year} · {pillarText(y.pillar)} · {ELEMENT[active][y.element]}</h4><p><strong>{c.theme}:</strong> {GOD[active][y.tenGod]}</p><p>{GOD_NOTE[active][y.tenGod]}</p><p><strong>{c.focus}:</strong> {y.relation==='support'||y.relation==='reinforce'?GOD_NOTE[active][y.tenGod]:GOD_NOTE[active][y.tenGod]}</p><p><strong>{c.caution}:</strong> {c.notice}</p></article>)}</section>{result.warnings.length>0&&<p>{c.partial}</p>}<p>{c.method}</p><p>{c.privacy}</p><p><button type="button" onClick={copy}>{c.copy}</button>{' '}<button type="button" onClick={download}>{c.download}</button>{' '}<button type="button" onClick={reset}>{c.reset}</button></p><p role="status" aria-live="polite">{message}</p></div>}
 </section>;
}
