'use client';

import {FormEvent,useMemo,useState} from 'react';
import {calculateSajuExperience,type SajuExperienceResult} from '@/lib/saju/experience';
import {buildSajuFunctionalReading,type SajuRelation} from '@/lib/saju/reading';
import type {FiveElementsElement} from '@/lib/saju/input-contracts';

type Locale='en'|'zh-CN'|'ja'|'zh-TW'|'vi'|'th';
type TimeMode='exact'|'rough'|'unknown';
type Period='night'|'morning'|'afternoon'|'evening';

type Copy={
 title:string;intro:string;notice:string;name:string;nameHelp:string;date:string;timeMode:string;exact:string;rough:string;unknown:string;time:string;period:string;night:string;morning:string;afternoon:string;evening:string;zone:string;zoneHelp:string;go:string;reset:string;error:string;result:string;chart:string;year:string;month:string;day:string;hour:string;unknownHour:string;elements:string;dayMaster:string;strongest:string;weakest:string;partial:string;reading:string;core:string;balance:string;future:string;work:string;money:string;relationships:string;pace:string;action:string;caution:string;copy:string;copied:string;copyFail:string;download:string;downloaded:string;privacy:string;method:string;nameNotMath:string;
};

const COPY:Record<Locale,Copy>={
 en:{title:'Saju fortune reading',intro:'Enter your birth details to calculate a traditional Four Pillars chart and a rule-based cultural reading of your present strengths and the next two years.',notice:'For cultural and entertainment use only. This is not a guaranteed prediction or medical, legal, investment, or other professional advice.',name:'Name (optional)',nameHelp:'Used only to label this reading. Your name does not change the Four Pillars calculation.',date:'Birth date',timeMode:'Birth time',exact:'Exact time',rough:'Approximate period',unknown:"I don’t know",time:'Time',period:'Period',night:'Night · 00–06',morning:'Morning · 06–12',afternoon:'Afternoon · 12–18',evening:'Evening · 18–24',zone:'Birthplace timezone',zoneHelp:'Use an IANA timezone such as Asia/Seoul, Asia/Tokyo or America/New_York. It must match the birthplace, not your current location.',go:'Read my Saju',reset:'Start over',error:'Please check your birth details.',result:'Your Saju reading',chart:'Four Pillars chart',year:'Year',month:'Month',day:'Day',hour:'Hour',unknownHour:'Not guessed',elements:'Five Elements',dayMaster:'Day Master',strongest:'Most represented',weakest:'Least represented',partial:'Birth time is unknown or approximate, so element balance is intentionally partial.',reading:'Traditional symbolic reading',core:'Core tendency',balance:'Balance focus',future:'Yearly outlook',work:'Work / direction',money:'Resources / money',relationships:'Relationships',pace:'Energy / pace',action:'Useful focus',caution:'Watch for',copy:'Copy reading',copied:'Reading copied',copyFail:'Copy was blocked. Download the text reading instead.',download:'Download text reading',downloaded:'Reading downloaded',privacy:'Calculation and interpretation run in this browser. Birth details are not sent to an AI model and are not saved by this feature.',method:'The chart uses deterministic calendar rules. The interpretation is a fixed rule layer based on Day Master, Five Elements and annual stem relationships; it does not claim certainty.',nameNotMath:'Name is a display label only and is not used as a hidden fortune variable.'},
 'zh-CN':{title:'四柱文化运势解读',intro:'输入出生信息，计算传统四柱，并用固定规则解读当前倾向与未来两年的象征性走势。',notice:'仅供文化与娱乐体验，不是确定性预言，也不构成医疗、法律、投资等专业建议。',name:'姓名（可选）',nameHelp:'只用于标记本次结果，不参与四柱计算。',date:'出生日期',timeMode:'出生时间',exact:'准确时间',rough:'大概时段',unknown:'不知道',time:'时间',period:'时段',night:'夜间 · 00–06',morning:'上午 · 06–12',afternoon:'下午 · 12–18',evening:'晚上 · 18–24',zone:'出生地时区',zoneHelp:'请输入出生地的 IANA 时区，例如 Asia/Shanghai、Asia/Seoul。不要使用当前所在地时区替代。',go:'查看我的四柱',reset:'重新开始',error:'请检查出生信息。',result:'你的四柱解读',chart:'四柱命盘',year:'年柱',month:'月柱',day:'日柱',hour:'时柱',unknownHour:'不猜测',elements:'五行',dayMaster:'日主',strongest:'相对最多',weakest:'相对最少',partial:'出生时间未知或不精确，因此五行分布只显示可确定部分。',reading:'传统象征性解读',core:'核心倾向',balance:'平衡重点',future:'年度走势',work:'工作 / 方向',money:'资源 / 金钱',relationships:'关系',pace:'精力 / 节奏',action:'适合关注',caution:'需要留意',copy:'复制解读',copied:'已复制',copyFail:'浏览器阻止复制，请下载文字版。',download:'下载文字版',downloaded:'已下载',privacy:'计算和解读都在浏览器内完成。出生信息不会发送给 AI 模型，本功能也不会保存这些信息。',method:'命盘使用确定性历法规则；解读使用基于日主、五行和流年天干关系的固定规则，不声称必然发生。',nameNotMath:'姓名只作结果标签，不作为隐藏的运势变量。'},
 ja:{title:'四柱・運勢リーディング',intro:'出生情報から四柱を計算し、日主・五行・年の干の関係を使った固定ルールで今の傾向と今後2年を読み解きます。',notice:'文化・娯楽向けです。確定的な予言ではなく、医療・法律・投資などの専門助言ではありません。',name:'名前（任意）',nameHelp:'結果の表示名だけに使い、四柱計算には使いません。',date:'生年月日',timeMode:'出生時刻',exact:'正確な時刻',rough:'おおよその時間帯',unknown:'不明',time:'時刻',period:'時間帯',night:'夜 · 00–06',morning:'朝 · 06–12',afternoon:'午後 · 12–18',evening:'夜 · 18–24',zone:'出生地タイムゾーン',zoneHelp:'Asia/Tokyo、Asia/Seoul など出生地の IANA タイムゾーンを使ってください。現在地の時刻ではありません。',go:'四柱を読む',reset:'やり直す',error:'出生情報を確認してください。',result:'四柱リーディング',chart:'四柱命式',year:'年柱',month:'月柱',day:'日柱',hour:'時柱',unknownHour:'推測しない',elements:'五行',dayMaster:'日主',strongest:'比較的多い',weakest:'比較的少ない',partial:'出生時刻が不明または概算のため、五行バランスは確定できる範囲のみです。',reading:'伝統的な象徴解釈',core:'基本傾向',balance:'バランスの焦点',future:'年運の見通し',work:'仕事 / 方向性',money:'資源 / お金',relationships:'人間関係',pace:'エネルギー / ペース',action:'意識したいこと',caution:'注意したいこと',copy:'結果をコピー',copied:'コピーしました',copyFail:'コピーできませんでした。テキスト版をダウンロードしてください。',download:'テキスト版をダウンロード',downloaded:'ダウンロードしました',privacy:'計算と解釈はブラウザ内で行います。出生情報を AI モデルへ送らず、この機能では保存しません。',method:'命式は決定論的な暦計算、解釈は日主・五行・年干関係に基づく固定ルールです。結果の確実性は主張しません。',nameNotMath:'名前は表示ラベルのみで、隠れた運勢変数には使いません。'},
 'zh-TW':{title:'四柱文化運勢解讀',intro:'輸入出生資料，計算傳統四柱，並以固定規則解讀目前傾向與未來兩年的象徵性走勢。',notice:'僅供文化與娛樂體驗，不是確定性預言，也不構成醫療、法律、投資等專業建議。',name:'姓名（選填）',nameHelp:'只用於標記本次結果，不參與四柱計算。',date:'出生日期',timeMode:'出生時間',exact:'準確時間',rough:'大概時段',unknown:'不知道',time:'時間',period:'時段',night:'夜間 · 00–06',morning:'上午 · 06–12',afternoon:'下午 · 12–18',evening:'晚上 · 18–24',zone:'出生地時區',zoneHelp:'請輸入出生地 IANA 時區，例如 Asia/Taipei、Asia/Seoul，不要以目前所在地時區代替。',go:'查看我的四柱',reset:'重新開始',error:'請檢查出生資料。',result:'你的四柱解讀',chart:'四柱命盤',year:'年柱',month:'月柱',day:'日柱',hour:'時柱',unknownHour:'不猜測',elements:'五行',dayMaster:'日主',strongest:'相對最多',weakest:'相對最少',partial:'出生時間未知或不精確，因此五行分布只顯示可確定部分。',reading:'傳統象徵性解讀',core:'核心傾向',balance:'平衡重點',future:'年度走勢',work:'工作 / 方向',money:'資源 / 金錢',relationships:'關係',pace:'精力 / 節奏',action:'適合關注',caution:'需要留意',copy:'複製解讀',copied:'已複製',copyFail:'瀏覽器阻擋複製，請下載文字版。',download:'下載文字版',downloaded:'已下載',privacy:'計算與解讀都在瀏覽器內完成。出生資料不會傳送給 AI 模型，本功能也不會保存。',method:'命盤使用確定性曆法規則；解讀使用基於日主、五行與流年天干關係的固定規則，不聲稱必然發生。',nameNotMath:'姓名只作結果標籤，不作為隱藏的運勢變數。'},
 vi:{title:'Đọc vận Saju',intro:'Nhập thông tin sinh để tính Tứ trụ và nhận phần diễn giải văn hóa theo quy tắc cố định cho xu hướng hiện tại và hai năm tới.',notice:'Chỉ dành cho văn hóa và giải trí. Đây không phải lời tiên đoán chắc chắn hay tư vấn y tế, pháp lý, đầu tư hoặc chuyên môn.',name:'Tên (không bắt buộc)',nameHelp:'Chỉ dùng làm nhãn cho kết quả, không ảnh hưởng phép tính Tứ trụ.',date:'Ngày sinh',timeMode:'Giờ sinh',exact:'Giờ chính xác',rough:'Khoảng thời gian',unknown:'Không biết',time:'Giờ',period:'Khoảng',night:'Đêm · 00–06',morning:'Sáng · 06–12',afternoon:'Chiều · 12–18',evening:'Tối · 18–24',zone:'Múi giờ nơi sinh',zoneHelp:'Dùng múi giờ IANA của nơi sinh như Asia/Ho_Chi_Minh hoặc Asia/Seoul, không phải múi giờ hiện tại.',go:'Đọc Saju của tôi',reset:'Làm lại',error:'Hãy kiểm tra thông tin sinh.',result:'Kết quả Saju',chart:'Biểu đồ Tứ trụ',year:'Năm',month:'Tháng',day:'Ngày',hour:'Giờ',unknownHour:'Không đoán',elements:'Ngũ hành',dayMaster:'Nhật chủ',strongest:'Nhiều hơn tương đối',weakest:'Ít hơn tương đối',partial:'Giờ sinh chưa rõ hoặc chỉ ước lượng nên cân bằng Ngũ hành chỉ hiển thị phần có thể xác định.',reading:'Diễn giải biểu tượng truyền thống',core:'Xu hướng cốt lõi',balance:'Trọng tâm cân bằng',future:'Triển vọng theo năm',work:'Công việc / hướng đi',money:'Nguồn lực / tiền bạc',relationships:'Quan hệ',pace:'Năng lượng / nhịp độ',action:'Nên tập trung',caution:'Cần lưu ý',copy:'Sao chép kết quả',copied:'Đã sao chép',copyFail:'Trình duyệt chặn sao chép. Hãy tải bản văn bản.',download:'Tải bản văn bản',downloaded:'Đã tải',privacy:'Phép tính và diễn giải chạy trong trình duyệt. Dữ liệu sinh không được gửi tới mô hình AI và không được lưu bởi tính năng này.',method:'Biểu đồ dùng quy tắc lịch xác định; diễn giải dùng quy tắc cố định dựa trên Nhật chủ, Ngũ hành và quan hệ thiên can của năm, không khẳng định chắc chắn.',nameNotMath:'Tên chỉ là nhãn hiển thị, không phải biến số bí mật của vận mệnh.'},
 th:{title:'อ่านดวงซาจู',intro:'กรอกข้อมูลเกิดเพื่อคำนวณสี่เสา และอ่านแนวโน้มเชิงวัฒนธรรมด้วยกฎคงที่สำหรับปัจจุบันและสองปีข้างหน้า',notice:'เพื่อวัฒนธรรมและความบันเทิงเท่านั้น ไม่ใช่คำทำนายที่แน่นอนหรือคำแนะนำด้านการแพทย์ กฎหมาย การลงทุน หรือวิชาชีพ',name:'ชื่อ (ไม่บังคับ)',nameHelp:'ใช้เป็นป้ายชื่อผลลัพธ์เท่านั้น ไม่เปลี่ยนการคำนวณสี่เสา',date:'วันเกิด',timeMode:'เวลาเกิด',exact:'เวลาที่แน่นอน',rough:'ช่วงเวลาโดยประมาณ',unknown:'ไม่ทราบ',time:'เวลา',period:'ช่วง',night:'กลางคืน · 00–06',morning:'เช้า · 06–12',afternoon:'บ่าย · 12–18',evening:'เย็น · 18–24',zone:'เขตเวลาสถานที่เกิด',zoneHelp:'ใช้เขตเวลา IANA ของสถานที่เกิด เช่น Asia/Bangkok หรือ Asia/Seoul ไม่ใช่เขตเวลาที่อยู่ปัจจุบัน',go:'อ่านซาจูของฉัน',reset:'เริ่มใหม่',error:'กรุณาตรวจสอบข้อมูลเกิด',result:'ผลการอ่านซาจู',chart:'ผังสี่เสา',year:'ปี',month:'เดือน',day:'วัน',hour:'เวลา',unknownHour:'ไม่เดา',elements:'ธาตุทั้งห้า',dayMaster:'ธาตุประจำวัน',strongest:'มีมากกว่าโดยเปรียบเทียบ',weakest:'มีน้อยกว่าโดยเปรียบเทียบ',partial:'ไม่ทราบเวลาเกิดหรือเป็นเวลาโดยประมาณ จึงแสดงสมดุลธาตุเฉพาะส่วนที่ยืนยันได้',reading:'การตีความเชิงสัญลักษณ์แบบดั้งเดิม',core:'แนวโน้มหลัก',balance:'จุดเน้นเพื่อสมดุล',future:'แนวโน้มรายปี',work:'งาน / ทิศทาง',money:'ทรัพยากร / การเงิน',relationships:'ความสัมพันธ์',pace:'พลังงาน / จังหวะ',action:'จุดที่ควรโฟกัส',caution:'สิ่งที่ควรระวัง',copy:'คัดลอกผล',copied:'คัดลอกแล้ว',copyFail:'เบราว์เซอร์ไม่อนุญาตให้คัดลอก โปรดดาวน์โหลดข้อความแทน',download:'ดาวน์โหลดข้อความ',downloaded:'ดาวน์โหลดแล้ว',privacy:'การคำนวณและการตีความทำในเบราว์เซอร์ ข้อมูลเกิดไม่ถูกส่งไปยังโมเดล AI และฟีเจอร์นี้ไม่บันทึกข้อมูลดังกล่าว',method:'ผังใช้กฎปฏิทินแบบกำหนดแน่นอน การตีความใช้กฎคงที่จาก Day Master ธาตุทั้งห้า และความสัมพันธ์ของก้านฟ้ารายปี โดยไม่อ้างความแน่นอน',nameNotMath:'ชื่อใช้เป็นป้ายแสดงผลเท่านั้น ไม่ใช่ตัวแปรลับในการทำนาย'}
};

const ELEMENT_NAMES:Record<Locale,Record<FiveElementsElement,string>>={
 en:{wood:'Wood',fire:'Fire',earth:'Earth',metal:'Metal',water:'Water'},'zh-CN':{wood:'木',fire:'火',earth:'土',metal:'金',water:'水'},ja:{wood:'木',fire:'火',earth:'土',metal:'金',water:'水'},'zh-TW':{wood:'木',fire:'火',earth:'土',metal:'金',water:'水'},vi:{wood:'Mộc',fire:'Hỏa',earth:'Thổ',metal:'Kim',water:'Thủy'},th:{wood:'ไม้',fire:'ไฟ',earth:'ดิน',metal:'โลหะ',water:'น้ำ'}
};

const RELATION_TEXT:Record<Locale,Record<SajuRelation,{headline:string;action:string;caution:string}>>={
 en:{reinforce:{headline:'A year of self-direction and stronger personal momentum.',action:'Choose fewer priorities and commit to the ones you can own.',caution:'Competition or stubbornness can consume energy.'},support:{headline:'A supportive year for learning, recovery and useful allies.',action:'Build foundations, ask for help and improve a skill before scaling.',caution:'Comfort can become passivity if decisions are delayed.'},expression:{headline:'A year that favors expression, output and visible progress.',action:'Publish, present, travel or turn ideas into concrete work.',caution:'Overcommitting or speaking before checking details can create rework.'},opportunity:{headline:'A practical opportunity year focused on resources and execution.',action:'Track resources, negotiate clearly and convert effort into measurable outcomes.',caution:'Avoid treating symbolic fortune as financial advice or taking oversized risks.'},pressure:{headline:'A year of responsibility, structure and tests of discipline.',action:'Use schedules, boundaries and preparation to turn pressure into progress.',caution:'Do not read every obstacle as fate; reduce avoidable load and ask for support.'}},
 'zh-CN':{reinforce:{headline:'自我推动力较强的一年。',action:'减少优先事项，把精力放在自己能持续负责的目标上。',caution:'竞争心或固执可能消耗精力。'},support:{headline:'适合学习、恢复基础与获得支持的一年。',action:'先打基础、提升技能，需要时主动求助。',caution:'过度求稳可能变成拖延。'},expression:{headline:'更适合表达、产出与让成果被看见的一年。',action:'把想法做成作品、沟通、展示或旅行体验。',caution:'承诺太多或未经确认就行动容易返工。'},opportunity:{headline:'偏向资源管理与实际执行机会的一年。',action:'清楚记录资源、明确协商，把努力转成可衡量结果。',caution:'不要把文化运势当作投资建议，也不要因此承担过大风险。'},pressure:{headline:'责任、规则与自律感更突出的年份。',action:'通过计划、边界与准备把压力转成进度。',caution:'不要把所有阻力解释成命运，先减少可避免负担并寻求帮助。'}},
 ja:{reinforce:{headline:'自分の方向性と推進力が強まりやすい年。',action:'優先順位を絞り、自分で責任を持てることに集中する。',caution:'競争心や頑固さで消耗しすぎない。'},support:{headline:'学び、土台づくり、助けを受ける流れに向く年。',action:'基礎を整え、スキルを磨き、必要なら助けを求める。',caution:'安心感が先延ばしにならないようにする。'},expression:{headline:'表現、発信、成果を形にすることに向く年。',action:'企画を作品や発表、旅、具体的な仕事へ変える。',caution:'確認不足のまま約束を増やすと手戻りが増える。'},opportunity:{headline:'資源管理と実行力が機会につながりやすい年。',action:'資源を把握し、条件を明確にして成果へつなげる。',caution:'文化的な運勢を投資助言として扱わず、大きなリスクを取らない。'},pressure:{headline:'責任、規律、準備力が試されやすい年。',action:'予定、境界線、準備でプレッシャーを進捗に変える。',caution:'障害をすべて運命と考えず、減らせる負担を減らす。'}},
 'zh-TW':{reinforce:{headline:'自我推動力較強的一年。',action:'減少優先事項，專注在自己能長期負責的目標。',caution:'競爭心或固執可能消耗精力。'},support:{headline:'適合學習、恢復基礎與獲得支持的一年。',action:'先打好基礎、提升技能，需要時主動求助。',caution:'過度求穩可能變成拖延。'},expression:{headline:'較適合表達、產出與讓成果被看見的一年。',action:'把想法做成作品、溝通、展示或旅行體驗。',caution:'承諾過多或未確認細節就行動容易返工。'},opportunity:{headline:'偏向資源管理與實際執行機會的一年。',action:'清楚記錄資源、明確協商，把努力轉成可衡量成果。',caution:'不要把文化運勢當作投資建議，也不要因此承擔過大風險。'},pressure:{headline:'責任、規則與自律感較突出的年份。',action:'透過計畫、界線與準備把壓力轉成進度。',caution:'不要把所有阻力解讀成命運，先減少可避免負擔並尋求協助。'}},
 vi:{reinforce:{headline:'Năm nhấn mạnh tính chủ động và động lực cá nhân.',action:'Giảm số ưu tiên và cam kết với mục tiêu bạn có thể tự chịu trách nhiệm.',caution:'Cạnh tranh hoặc cố chấp có thể làm hao năng lượng.'},support:{headline:'Năm thuận cho học hỏi, củng cố nền tảng và nhận hỗ trợ.',action:'Xây nền, nâng kỹ năng và chủ động nhờ trợ giúp khi cần.',caution:'Sự thoải mái có thể biến thành trì hoãn.'},expression:{headline:'Năm thuận cho biểu đạt, tạo đầu ra và tiến bộ dễ nhìn thấy.',action:'Biến ý tưởng thành sản phẩm, bài trình bày, chuyến đi hoặc công việc cụ thể.',caution:'Cam kết quá nhiều hoặc thiếu kiểm tra sẽ tạo việc làm lại.'},opportunity:{headline:'Năm thiên về cơ hội thực tế, nguồn lực và thực thi.',action:'Theo dõi nguồn lực, thương lượng rõ và biến nỗ lực thành kết quả đo được.',caution:'Không dùng vận số tượng trưng như lời khuyên đầu tư hay lý do để chịu rủi ro lớn.'},pressure:{headline:'Năm nhấn mạnh trách nhiệm, cấu trúc và kỷ luật.',action:'Dùng lịch trình, ranh giới và chuẩn bị để biến áp lực thành tiến bộ.',caution:'Đừng coi mọi trở ngại là số phận; hãy giảm tải có thể tránh và tìm hỗ trợ.'}},
 th:{reinforce:{headline:'ปีที่เน้นแรงขับและการกำหนดทิศทางด้วยตนเอง',action:'ลดจำนวนสิ่งสำคัญและทุ่มให้เป้าหมายที่รับผิดชอบได้จริง',caution:'การแข่งขันหรือความดื้ออาจใช้พลังมากเกินไป'},support:{headline:'ปีที่เหมาะกับการเรียนรู้ ฟื้นฐาน และรับแรงสนับสนุน',action:'สร้างพื้นฐาน พัฒนาทักษะ และขอความช่วยเหลือเมื่อจำเป็น',caution:'ความสบายอาจกลายเป็นการผัดวันประกันพรุ่ง'},expression:{headline:'ปีที่เหมาะกับการแสดงออก ผลงาน และความก้าวหน้าที่มองเห็นได้',action:'เปลี่ยนไอเดียเป็นผลงาน การนำเสนอ การเดินทาง หรืองานที่จับต้องได้',caution:'รับปากมากเกินไปหรือไม่ตรวจรายละเอียดอาจทำให้ต้องแก้งาน'},opportunity:{headline:'ปีที่เน้นโอกาสเชิงปฏิบัติ ทรัพยากร และการลงมือทำ',action:'ติดตามทรัพยากร เจรจาให้ชัด และเปลี่ยนความพยายามเป็นผลลัพธ์ที่วัดได้',caution:'อย่าใช้ดวงเชิงสัญลักษณ์แทนคำแนะนำการลงทุนหรือเป็นเหตุให้เสี่ยงเกินตัว'},pressure:{headline:'ปีที่เน้นความรับผิดชอบ โครงสร้าง และวินัย',action:'ใช้ตาราง ขอบเขต และการเตรียมตัวเปลี่ยนแรงกดดันเป็นความก้าวหน้า',caution:'อย่ามองอุปสรรคทุกอย่างเป็นชะตา ลดภาระที่เลี่ยงได้และขอความช่วยเหลือ'}}
};

const CORE_TEXT:Record<Locale,Record<FiveElementsElement,string>>={
 en:{wood:'Growth-oriented: tradition associates Wood Day Masters with building, learning and gradual expansion.',fire:'Expression-oriented: Fire Day Masters are traditionally associated with visibility, warmth and rapid activation.',earth:'Stability-oriented: Earth Day Masters are traditionally associated with continuity, coordination and practical grounding.',metal:'Refinement-oriented: Metal Day Masters are traditionally associated with standards, selection and decisive structure.',water:'Flow-oriented: Water Day Masters are traditionally associated with observation, adaptation and movement.'},
 'zh-CN':{wood:'木日主在传统象征中偏向成长、学习与逐步扩展。',fire:'火日主在传统象征中偏向表达、可见度与快速启动。',earth:'土日主在传统象征中偏向稳定、协调与实际落地。',metal:'金日主在传统象征中偏向标准、筛选与明确结构。',water:'水日主在传统象征中偏向观察、适应与流动。'},
 ja:{wood:'木の日主は伝統的に、成長・学習・段階的な拡大の象徴とされます。',fire:'火の日主は伝統的に、表現・可視性・素早い始動の象徴とされます。',earth:'土の日主は伝統的に、安定・調整・現実的な基盤の象徴とされます。',metal:'金の日主は伝統的に、基準・選別・明確な構造の象徴とされます。',water:'水の日主は伝統的に、観察・適応・流動性の象徴とされます。'},
 'zh-TW':{wood:'木日主在傳統象徵中偏向成長、學習與逐步擴展。',fire:'火日主在傳統象徵中偏向表達、可見度與快速啟動。',earth:'土日主在傳統象徵中偏向穩定、協調與實際落地。',metal:'金日主在傳統象徵中偏向標準、篩選與明確結構。',water:'水日主在傳統象徵中偏向觀察、適應與流動。'},
 vi:{wood:'Nhật chủ Mộc theo truyền thống tượng trưng cho phát triển, học hỏi và mở rộng dần.',fire:'Nhật chủ Hỏa theo truyền thống tượng trưng cho biểu đạt, sự hiện diện và khởi động nhanh.',earth:'Nhật chủ Thổ theo truyền thống tượng trưng cho ổn định, điều phối và nền tảng thực tế.',metal:'Nhật chủ Kim theo truyền thống tượng trưng cho tiêu chuẩn, chọn lọc và cấu trúc rõ.',water:'Nhật chủ Thủy theo truyền thống tượng trưng cho quan sát, thích nghi và dịch chuyển.'},
 th:{wood:'Day Master ธาตุไม้ตามคติโบราณสื่อถึงการเติบโต การเรียนรู้ และการขยายอย่างค่อยเป็นค่อยไป',fire:'Day Master ธาตุไฟตามคติโบราณสื่อถึงการแสดงออก ความโดดเด่น และการเริ่มต้นอย่างรวดเร็ว',earth:'Day Master ธาตุดินตามคติโบราณสื่อถึงความมั่นคง การประสานงาน และพื้นฐานเชิงปฏิบัติ',metal:'Day Master ธาตุโลหะตามคติโบราณสื่อถึงมาตรฐาน การคัดเลือก และโครงสร้างที่ชัดเจน',water:'Day Master ธาตุน้ำตามคติโบราณสื่อถึงการสังเกต การปรับตัว และการเคลื่อนไหว'}
};

function parseDate(value:string){const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(value);if(!m)throw new RangeError('Invalid date');return {year:Number(m[1]),month:Number(m[2]),day:Number(m[3])};}
function pillarText(p?:{stem:string;branch:string}){return p?`${p.stem}${p.branch}`:'—';}

export function SajuFunctionalExperience({locale}: {locale:string}){
 const active=(locale in COPY?locale:'en') as Locale;const c=COPY[active];
 const [name,setName]=useState('');const [date,setDate]=useState('');const [mode,setMode]=useState<TimeMode>('unknown');const [time,setTime]=useState('12:00');const [period,setPeriod]=useState<Period>('morning');const [zone,setZone]=useState('');const [result,setResult]=useState<SajuExperienceResult|null>(null);const [error,setError]=useState('');const [message,setMessage]=useState('');
 const reading=useMemo(()=>result?buildSajuFunctionalReading(result,new Date().getFullYear()):null,[result]);
 const counts=result?(result.fiveElements.exact??result.fiveElements.base):null;
 function submit(event:FormEvent){event.preventDefault();setError('');setMessage('');try{const d=parseDate(date);if(!zone.trim())throw new RangeError(c.zoneHelp);let birthTime;if(mode==='exact'){const m=/^(\d{2}):(\d{2})$/.exec(time);if(!m)throw new RangeError(c.error);birthTime={mode:'exact' as const,hour:Number(m[1]),minute:Number(m[2])};}else if(mode==='rough'){birthTime={mode:'rough' as const,period};}else birthTime={mode:'unknown' as const};setResult(calculateSajuExperience({...d,timeZone:zone.trim(),time:birthTime}));}catch(e){setResult(null);setError(e instanceof Error?e.message:c.error);}}
 const exportText=useMemo(()=>{if(!result||!reading)return '';const who=name.trim()?`${name.trim()} — `:'';const lines=[`${who}${c.result}`,`${c.chart}: ${c.year} ${pillarText(result.pillars.year)} · ${c.month} ${pillarText(result.pillars.month)} · ${c.day} ${pillarText(result.pillars.day)} · ${c.hour} ${pillarText(result.pillars.hour)}`,`${c.dayMaster}: ${reading.dayMaster.stem} · ${ELEMENT_NAMES[active][reading.dayMaster.element]} · ${reading.dayMaster.polarity}`,`${c.strongest}: ${ELEMENT_NAMES[active][reading.strongest]}`,`${c.weakest}: ${ELEMENT_NAMES[active][reading.weakest]}`,CORE_TEXT[active][reading.dayMaster.element],...reading.outlooks.flatMap(o=>{const t=RELATION_TEXT[active][o.relation];return [`${o.year} · ${pillarText(o.pillar)} · ${ELEMENT_NAMES[active][o.element]}`,t.headline,`${c.action}: ${t.action}`,`${c.caution}: ${t.caution}`];}),'',c.notice,c.method,c.privacy];return lines.join('\n');},[active,c,name,reading,result]);
 async function copy(){if(!exportText)return;try{if(!navigator.clipboard?.writeText)throw new Error('clipboard unavailable');await navigator.clipboard.writeText(exportText);setMessage(c.copied);}catch{setMessage(c.copyFail);}}
 function download(){if(!exportText)return;const blob=new Blob([exportText],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='korea-concierge-saju.txt';a.click();URL.revokeObjectURL(url);setMessage(c.downloaded);}
 function reset(){setResult(null);setError('');setMessage('');setName('');setDate('');setMode('unknown');setTime('12:00');setPeriod('morning');setZone('');}
 return <section style={{maxWidth:900,margin:'0 auto',padding:'2rem 1rem'}}>
  <h1>{c.title}</h1><p>{c.intro}</p><p><strong>{c.notice}</strong></p>
  {!result&&<form onSubmit={submit} noValidate>
   <p><label>{c.name}<br/><input value={name} onChange={e=>setName(e.target.value)} maxLength={80} autoComplete="name"/></label><br/><small>{c.nameHelp}</small></p>
   <p><label>{c.date}<br/><input type="date" required value={date} min="1900-01-01" max="2100-12-31" onChange={e=>setDate(e.target.value)}/></label></p>
   <fieldset><legend>{c.timeMode}</legend><label><input type="radio" checked={mode==='exact'} onChange={()=>setMode('exact')}/>{c.exact}</label>{' '}<label><input type="radio" checked={mode==='rough'} onChange={()=>setMode('rough')}/>{c.rough}</label>{' '}<label><input type="radio" checked={mode==='unknown'} onChange={()=>setMode('unknown')}/>{c.unknown}</label></fieldset>
   {mode==='exact'&&<p><label>{c.time}<br/><input type="time" value={time} onChange={e=>setTime(e.target.value)} required/></label></p>}
   {mode==='rough'&&<p><label>{c.period}<br/><select value={period} onChange={e=>setPeriod(e.target.value as Period)}><option value="night">{c.night}</option><option value="morning">{c.morning}</option><option value="afternoon">{c.afternoon}</option><option value="evening">{c.evening}</option></select></label></p>}
   <p><label>{c.zone}<br/><input value={zone} onChange={e=>setZone(e.target.value)} placeholder="Asia/Seoul" list="saju-timezones" required/></label><br/><small>{c.zoneHelp}</small></p>
   <datalist id="saju-timezones"><option value="Asia/Seoul"/><option value="Asia/Tokyo"/><option value="Asia/Shanghai"/><option value="Asia/Taipei"/><option value="Asia/Bangkok"/><option value="Asia/Ho_Chi_Minh"/><option value="America/New_York"/><option value="America/Los_Angeles"/><option value="Europe/London"/><option value="Europe/Paris"/><option value="Australia/Sydney"/></datalist>
   <button type="submit">{c.go}</button>{error&&<p role="alert">{error}</p>}
  </form>}
  {result&&reading&&<div>
   <h2>{name.trim()?`${name.trim()} — ${c.result}`:c.result}</h2>
   <section><h3>{c.chart}</h3><dl><dt>{c.year}</dt><dd>{pillarText(result.pillars.year)}</dd><dt>{c.month}</dt><dd>{pillarText(result.pillars.month)}</dd><dt>{c.day}</dt><dd>{pillarText(result.pillars.day)}</dd><dt>{c.hour}</dt><dd>{result.pillars.hour?pillarText(result.pillars.hour):c.unknownHour}</dd></dl></section>
   <section><h3>{c.elements}</h3><p><strong>{c.dayMaster}:</strong> {reading.dayMaster.stem} · {ELEMENT_NAMES[active][reading.dayMaster.element]} · {reading.dayMaster.polarity}</p><p><strong>{c.strongest}:</strong> {ELEMENT_NAMES[active][reading.strongest]} · <strong>{c.weakest}:</strong> {ELEMENT_NAMES[active][reading.weakest]}</p>{counts&&<ul>{(Object.keys(ELEMENT_NAMES.en) as FiveElementsElement[]).map(el=><li key={el}>{ELEMENT_NAMES[active][el]}: {counts[el]??0}</li>)}</ul>}{reading.balanceIsPartial&&<p>{c.partial}</p>}</section>
   <section><h3>{c.reading}</h3><h4>{c.core}</h4><p>{CORE_TEXT[active][reading.dayMaster.element]}</p><h4>{c.balance}</h4><p>{ELEMENT_NAMES[active][reading.weakest]} ↔ {ELEMENT_NAMES[active][reading.strongest]}</p></section>
   <section><h3>{c.future}</h3>{reading.outlooks.map(o=>{const t=RELATION_TEXT[active][o.relation];return <article key={o.year}><h4>{o.year} · {pillarText(o.pillar)} · {ELEMENT_NAMES[active][o.element]}</h4><p>{t.headline}</p><p><strong>{c.action}:</strong> {t.action}</p><p><strong>{c.caution}:</strong> {t.caution}</p></article>})}</section>
   {result.warnings.length>0&&<section><h3>{c.caution}</h3><ul>{result.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul></section>}
   <section><h3>{c.method}</h3><p>{c.nameNotMath}</p><p>{c.privacy}</p></section>
   <p><button type="button" onClick={copy}>{c.copy}</button>{' '}<button type="button" onClick={download}>{c.download}</button>{' '}<button type="button" onClick={reset}>{c.reset}</button></p><p role="status" aria-live="polite">{message}</p>
  </div>}
 </section>;
}
