'use client';

import {useMemo,useState} from 'react';
import {hanbokRentalAvailabilityAt,hanbokRentalMapHref,hanbokRentalMinutesUntilPublishedClose,type HanbokRentalShop} from '@/lib/travel/gyeongbokgung-hanbok-rentals';

type Locale='en'|'zh-CN'|'ja'|'zh-TW'|'vi'|'th';
type Duration=120|240|360;
type Copy={title:string;intro:string;date:string;time:string;duration:string;two:string;four:string;six:string;fits:string;tight:string;recheck:string;none:string;remaining:string;map:string;source:string;notice:string};
const C:Record<Locale,Copy>={
 en:{title:'Will this shop timing fit my Hanbok outing?',intro:'Compare your planned arrival and outing length against each shop’s published closing time before choosing where to rent.',date:'Visit date',time:'Shop arrival',duration:'Planned rental outing',two:'About 2 hours',four:'About 4 hours',six:'About 6 hours',fits:'Published hours leave enough room',tight:'Too little time before published closing',recheck:'Schedule needs re-check',none:'No source-checked shop currently fits this timing.',remaining:'Time until published closing',map:'Map',source:'Verify shop source',notice:'This is planning support only. Shop closing time is not the same as a guaranteed rental return deadline; confirm stock, rental duration and return cutoff directly with the shop.'},
 'zh-CN':{title:'这家店的时间适合我的韩服行程吗？',intro:'根据预计到店时间和计划外出时长，对比各店公布的关门时间。',date:'到访日期',time:'到店时间',duration:'计划租赁外出时长',two:'约2小时',four:'约4小时',six:'约6小时',fits:'按公布营业时间有足够余量',tight:'距离公布关门时间太近',recheck:'营业时间需要再次确认',none:'目前没有已核对来源且适合该时间的店铺。',remaining:'距离公布关门时间',map:'地图',source:'核对店铺来源',notice:'仅用于规划。店铺关门时间不等于保证的归还截止时间，请直接向店铺确认库存、租赁时长和归还时间。'},
 ja:{title:'この店舗で予定時間に足りる？',intro:'到着予定と外出時間を、各店舗の公表閉店時刻と比較してからレンタル先を選べます。',date:'訪問日',time:'店舗到着',duration:'予定レンタル時間',two:'約2時間',four:'約4時間',six:'約6時間',fits:'公表営業時間上は余裕あり',tight:'公表閉店までの時間が不足',recheck:'営業時間の再確認が必要',none:'この時間条件に合う出典確認済み店舗がありません。',remaining:'公表閉店まで',map:'地図',source:'店舗情報源を確認',notice:'計画用の目安です。閉店時刻は返却締切を保証しません。在庫・レンタル時間・返却締切は店舗へ直接確認してください。'},
 'zh-TW':{title:'這家店的時間適合我的韓服行程嗎？',intro:'依預計到店時間與外出時長，比較各店公布的關門時間。',date:'到訪日期',time:'到店時間',duration:'預計租借外出時間',two:'約2小時',four:'約4小時',six:'約6小時',fits:'依公布營業時間有足夠餘量',tight:'距離公布關門時間太近',recheck:'營業時間需要再次確認',none:'目前沒有已核對來源且符合此時間的店家。',remaining:'距離公布關門時間',map:'地圖',source:'核對店家來源',notice:'僅供規劃。店家關門時間不等於保證的歸還截止時間，請直接向店家確認庫存、租借時數與歸還時間。'},
 vi:{title:'Khung giờ cửa hàng có đủ cho chuyến Hanbok?',intro:'So sánh giờ đến và thời lượng đi chơi với giờ đóng cửa công bố của từng cửa hàng.',date:'Ngày tham quan',time:'Giờ đến cửa hàng',duration:'Thời lượng dự kiến',two:'Khoảng 2 giờ',four:'Khoảng 4 giờ',six:'Khoảng 6 giờ',fits:'Giờ công bố còn đủ khoảng trống',tight:'Quá sát giờ đóng cửa công bố',recheck:'Cần kiểm tra lại lịch',none:'Chưa có cửa hàng đã kiểm tra nguồn phù hợp khung giờ này.',remaining:'Còn lại đến giờ đóng cửa công bố',map:'Bản đồ',source:'Kiểm tra nguồn cửa hàng',notice:'Chỉ dùng để lập kế hoạch. Giờ đóng cửa không phải hạn trả đồ được bảo đảm; hãy xác nhận trực tiếp tồn kho, thời lượng thuê và giờ trả.'},
 th:{title:'เวลาร้านพอสำหรับทริปฮันบกไหม?',intro:'เปรียบเทียบเวลาถึงร้านและระยะเวลาเที่ยวกับเวลาปิดที่แต่ละร้านประกาศ',date:'วันที่เที่ยว',time:'เวลาถึงร้าน',duration:'ระยะเวลาเช่าที่วางแผน',two:'ประมาณ 2 ชั่วโมง',four:'ประมาณ 4 ชั่วโมง',six:'ประมาณ 6 ชั่วโมง',fits:'เวลาที่ประกาศยังมีช่วงเหลือเพียงพอ',tight:'เหลือเวลาน้อยเกินไปก่อนเวลาปิดที่ประกาศ',recheck:'ต้องตรวจเวลาอีกครั้ง',none:'ยังไม่มีร้านที่ตรวจสอบแหล่งข้อมูลแล้วซึ่งเหมาะกับช่วงเวลานี้',remaining:'เวลาถึงเวลาปิดที่ประกาศ',map:'แผนที่',source:'ตรวจแหล่งข้อมูลร้าน',notice:'เป็นเพียงตัวช่วยวางแผน เวลาปิดร้านไม่ใช่กำหนดคืนชุดที่รับประกัน โปรดยืนยันสต็อก ระยะเวลาเช่า และเวลาคืนกับร้านโดยตรง'}
};

function localToday(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function durationLabel(minutes:number){const h=Math.floor(minutes/60),m=minutes%60;return m?`${h}h ${m}m`:`${h}h`;}

type Props={locale:string;shops:readonly HanbokRentalShop[];initialDate?:string;initialTime?:string};
export function HanbokRentalDurationAdvisor({locale,shops,initialDate,initialTime}:Props){
 const l=(locale in C?locale:'en') as Locale,c=C[l];
 const [date,setDate]=useState(initialDate??localToday());const [time,setTime]=useState(initialTime??'09:00');const [duration,setDuration]=useState<Duration>(240);
 const rows=useMemo(()=>shops.map(shop=>{const availability=hanbokRentalAvailabilityAt(shop,date,time);const remaining=hanbokRentalMinutesUntilPublishedClose(shop,time);const fit=remaining!==null&&remaining>=duration;return{shop,availability,remaining,fit};}).sort((a,b)=>Number(b.fit)-Number(a.fit)||(b.remaining??-1)-(a.remaining??-1)),[shops,date,time,duration]);
 const usable=rows.filter(row=>row.availability!=='closed'&&row.fit);
 return <section style={{maxWidth:1120,margin:'28px auto 36px',padding:'0 20px'}}><div style={{border:'1px solid rgba(0,0,0,.12)',borderRadius:14,padding:18}}><h2>{c.title}</h2><p>{c.intro}</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12}}><label style={{display:'grid',gap:6}}>{c.date}<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label style={{display:'grid',gap:6}}>{c.time}<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><label style={{display:'grid',gap:6}}>{c.duration}<select value={duration} onChange={e=>setDuration(Number(e.target.value) as Duration)}><option value={120}>{c.two}</option><option value={240}>{c.four}</option><option value={360}>{c.six}</option></select></label></div><div style={{display:'grid',gap:10,marginTop:16}}>{rows.map(({shop,availability,remaining,fit})=><article key={shop.id} style={{border:'1px solid rgba(0,0,0,.1)',borderRadius:10,padding:14,opacity:availability==='closed'?.65:1}}><strong>{shop.name} · {shop.koreanName}</strong><p>{availability==='closed'?c.tight:availability==='recheck'?c.recheck:fit?c.fits:c.tight}</p><p><small>{c.remaining}: {remaining===null?'—':durationLabel(remaining)}</small></p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><a className="secondaryButton" href={hanbokRentalMapHref(shop)} target="_blank" rel="noreferrer">{c.map}</a><a className="secondaryButton" href={shop.sourceUrl} target="_blank" rel="noreferrer">{c.source}</a></div></article>)}</div>{!usable.length?<p role="status"><strong>{c.none}</strong></p>:null}<p><small>{c.notice}</small></p></div></section>;
}
