export type FoodCategory='korean-meal'|'halal'|'traditional-tea'|'coffee';
export type FoodPlace={id:string;name:string;category:FoodCategory;summary:string;hours:string;closed:string;address:string;sourceUrl:string;checkedAt:string;dietaryNote?:string};
export const GYEONGBOKGUNG_FOOD_PLACES:readonly FoodPlace[]=[
 {id:'tosokchon',name:'Tosokchon Samgyetang',category:'korean-meal',summary:'Traditional samgyetang (ginseng chicken soup) in a hanok near Gyeongbokgung.',hours:'10:00–22:00 · last order 21:00',closed:'Open all year according to the current official tourism listing.',address:'5 Jahamun-ro 5-gil, Jongno-gu, Seoul',sourceUrl:'https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=97919',checkedAt:'2026-09-09'},
 {id:'iftar',name:'iftar',category:'halal',summary:'Traditional Korean dishes using ingredients described by Visit Seoul as certified under strict halal standards.',hours:'11:30–19:30',closed:'Check the current listing before visiting.',address:'1F, 50-1 Jahamun-ro 1-gil, Jongno-gu, Seoul',sourceUrl:'https://english.visitseoul.net/restaurants/iftar/ENPjp7b57',checkedAt:'2026-09-09',dietaryNote:'Visit Seoul lists no alcohol for sale and Muslim cooks available. Always confirm individual dietary requirements directly.'},
 {id:'seochon-dagwabang',name:'Seochon Dagwabang',category:'traditional-tea',summary:'Hanok cafe serving traditional tea and handmade Korean desserts near Gyeongbokgung Station.',hours:'11:00–20:00',closed:'Tuesday',address:'6 Pirundae-ro, Jongno-gu, Seoul',sourceUrl:'https://english.visitseoul.net/restaurants/dagwabang/ENPjmmeg3',checkedAt:'2026-09-09'},
 {id:'tailor-coffee-seochon',name:'Tailor Coffee Seochon Gyeongbokgung Branch',category:'coffee',summary:'Coffee and bakery stop along the western Gyeongbokgung stone-wall path.',hours:'08:00–21:00',closed:'Daily according to the current Visit Seoul listing.',address:'Seochon, west side of Gyeongbokgung Palace, Seoul',sourceUrl:'https://english.visitseoul.net/restaurants/tailorcoffee/ENPoy0arv',checkedAt:'2026-09-09'},
];
export function filterFoodPlaces(category:FoodCategory|'all'){return category==='all'?[...GYEONGBOKGUNG_FOOD_PLACES]:GYEONGBOKGUNG_FOOD_PLACES.filter(place=>place.category===category);}
