import type {FoodPlace} from './gyeongbokgung-food-core';
export type {FoodCategory,ScheduleConfidence,FoodPlace} from './gyeongbokgung-food-core';

export const GYEONGBOKGUNG_FOOD_PLACES:readonly FoodPlace[]=[
 {id:'tosokchon',name:'Tosokchon Samgyetang',category:'korean-meal',summary:'Traditional samgyetang (ginseng chicken soup) in a hanok near Gyeongbokgung.',hours:'10:00–22:00 · last order 21:00',closed:'Open all year according to the current official tourism listing.',address:'5 Jahamun-ro 5-gil, Jongno-gu, Seoul',sourceUrl:'https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=97919',checkedAt:'2026-09-09',openMinute:600,closeMinute:1320,closedWeekdays:[],scheduleConfidence:'verified'},
 {id:'iftar',name:'iftar',category:'halal',summary:'Traditional Korean dishes using ingredients described by Visit Seoul as certified under strict halal standards.',hours:'11:30–19:30',closed:'Check the current listing before visiting.',address:'1F, 50-1 Jahamun-ro 1-gil, Jongno-gu, Seoul',sourceUrl:'https://english.visitseoul.net/restaurants/iftar/ENPjp7b57',checkedAt:'2026-09-09',dietaryNote:'Visit Seoul lists no alcohol for sale and Muslim cooks available. Always confirm individual dietary requirements directly.',openMinute:690,closeMinute:1170,closedWeekdays:[],scheduleConfidence:'recheck'},
 {id:'seochon-dagwabang',name:'Seochon Dagwabang',category:'traditional-tea',summary:'Hanok cafe serving traditional tea and handmade Korean desserts near Gyeongbokgung Station.',hours:'11:00–20:00',closed:'Tuesday',address:'6 Pirundae-ro, Jongno-gu, Seoul',sourceUrl:'https://english.visitseoul.net/restaurants/dagwabang/ENPjmmeg3',checkedAt:'2026-09-09',openMinute:660,closeMinute:1200,closedWeekdays:[2],scheduleConfidence:'verified'},
 {id:'tailor-coffee-seochon',name:'Tailor Coffee Seochon Gyeongbokgung Branch',category:'coffee',summary:'Coffee and bakery stop along the western Gyeongbokgung stone-wall path.',hours:'08:00–21:00',closed:'Daily according to the current Visit Seoul listing.',address:'Seochon, west side of Gyeongbokgung Palace, Seoul',sourceUrl:'https://english.visitseoul.net/restaurants/tailorcoffee/ENPoy0arv',checkedAt:'2026-09-09',openMinute:480,closeMinute:1260,closedWeekdays:[],scheduleConfidence:'verified'},
 {id:'aino-garden-kitchen',name:'Aino Garden Kitchen',category:'korean-meal',summary:'Hanok-remodeled Seochon venue with a cafe on the first floor and Korean restaurant on the second floor.',hours:'11:00–21:00',closed:'Open all year according to the current Visit Seoul listing.',address:'2F, 10 Gyeonghuigung 2-gil, Jongno-gu, Seoul',sourceUrl:'https://english.visitseoul.net/restaurants/Aino-Garden-Kitchen/ENP9cr70y',checkedAt:'2026-09-09',openMinute:660,closeMinute:1260,closedWeekdays:[],scheduleConfidence:'verified'},
 {id:'cafe-haven',name:'Cafe Haven',category:'coffee',summary:'Seochon cafe where a traditional wooden Hanok structure is visible inside a modern exterior.',hours:'11:00–22:00',closed:'Monday',address:'52-1 Jahamun-ro, Jongno-gu, Seoul',sourceUrl:'https://english.visitseoul.net/PalaceArea/Cafe-HAVEN/ENPn8s2yl',checkedAt:'2026-09-09',openMinute:660,closeMinute:1320,closedWeekdays:[1],scheduleConfidence:'verified'},
 {id:'cafe-sinola',name:'Cafe Sinola',category:'coffee',summary:'LP-themed Seochon cafe known for drip coffee and brunch along the Gyeongbokgung stone-wall route.',hours:'09:00–19:00 · last order 18:00',closed:'Daily according to the current Visit Seoul listing.',address:'116 Jahamun-ro, Jongno-gu, Seoul',sourceUrl:'https://english.visitseoul.net/area/2024-sinola/ENP680zw5',checkedAt:'2026-09-09',dietaryNote:'Visit Seoul currently lists this venue as no-kids; confirm the current policy before visiting with children.',openMinute:540,closeMinute:1140,closedWeekdays:[],scheduleConfidence:'verified'},
];
