import type {SampleStylebook} from '@/lib/looks/samples';

export type SampleLocale='en'|'zh-CN'|'ja'|'zh-TW'|'vi'|'th';

type ShellCopy={
 sampleBadge:string;disclaimer:(product:string)=>string;eyebrow:string;plannedPrice:string;priceDesc:string;sampleNav:string;
 personaTitle:string;selectedVibe:string;colorHarmony:string;primaryTone:string;secondaryTone:string;accentTone:string;
 looksHeading:string;lookOf:(index:number)=>string;practicalNote:string;suggestedSpot:string;photoIdea:string;source:string;viewSource:string;checked:string;
 shopBadge:string;copyKorean:string;copied:string;copyFailed:string;shopHeading:string;koreanLabel:string;
 routeHeading:string;routeDisclaimer:string;stop:string;ctaTitle:string;ctaDesc:string;ctaButton:string;englishDetailNote:string;
};

type SampleCopy={
 title:string;tagline:string;badge:string;personaName:string;personaSummary:string;travelContext:string;selectedUndertone:string;selectedStyle:string;
 paletteTitle:string;paletteNotes:string;shopExplanation:string;tabLabel:string;
};

const SHELL:Record<SampleLocale,ShellCopy>={
 en:{sampleBadge:'Public sample',disclaimer:p=>`This is a fictitious one-adult public demonstration of the planned ${p} stylebook. It shows intended result depth, but paid checkout and private delivery stay unavailable until account, fulfillment, refund and merchant requirements are production-verified.`,eyebrow:'My Korea Look · Curated Sample',plannedPrice:'Planned launch price: $12.00 USD',priceDesc:'One adult · 3 curated looks · Korean shop card · photo-route plan',sampleNav:'Explore other curated samples',personaTitle:'Traveler profile & aesthetic goal',selectedVibe:'Selected vibe',colorHarmony:'Color harmony',primaryTone:'Primary tone',secondaryTone:'Secondary tone',accentTone:'Accent tone',looksHeading:'3 curated looks for this sample profile',lookOf:i=>`Look ${i} of 3`,practicalNote:'Practical note',suggestedSpot:'Suggested palace spot',photoIdea:'Photo idea',source:'Source',viewSource:'View source',checked:'Source checked',shopBadge:'Bilingual in-store request card',copyKorean:'Copy Korean text',copied:'Copied to clipboard',copyFailed:'Copy was blocked. Keep this screen open and show the Korean text to staff.',shopHeading:'Ask rental staff to check what is actually available',koreanLabel:'Korean staff request note',routeHeading:'Example 2-hour palace photo itinerary',routeDisclaimer:'This is a planning example, not live routing or crowd information. Check current palace hours, closures, weather and walking conditions before visiting.',stop:'STOP',ctaTitle:'Try the free My Korea Look preview',ctaDesc:'Use the free preference-based consultation now. Paid photo-aware styling, private delivery, revision and checkout remain unavailable until the required account, privacy, fulfillment, refund and merchant gates are verified.',ctaButton:'Start the free style preview',englishDetailNote:'Some deep garment notes remain in English while native editorial review continues; source and inventory cautions are unchanged.'},
 'zh-CN':{sampleBadge:'公开示例',disclaimer:p=>`这是${p}风格册的虚构单人公开示例，用于展示计划中的结果深度。账号、交付、退款和商户要求完成生产验证前，付费结账和私密交付仍不可用。`,eyebrow:'My Korea Look · 精选示例',plannedPrice:'计划首发价：12.00 美元',priceDesc:'1位成人 · 3套精选造型 · 韩文店内请求卡 · 拍照路线',sampleNav:'查看其他精选示例',personaTitle:'旅行者设定与审美目标',selectedVibe:'选择的风格',colorHarmony:'色彩方向',primaryTone:'主色',secondaryTone:'辅助色',accentTone:'点缀色',looksHeading:'适合此示例设定的3套精选造型',lookOf:i=>`造型 ${i}/3`,practicalNote:'实用提示',suggestedSpot:'推荐宫殿场景',photoIdea:'拍摄建议',source:'来源',viewSource:'查看来源',checked:'来源核对',shopBadge:'双语店内请求卡',copyKorean:'复制韩文',copied:'已复制',copyFailed:'浏览器阻止了复制。请保持此页面打开，直接向店员展示下方韩文。',shopHeading:'请租赁店员确认实际可提供的款式',koreanLabel:'给韩国店员看的请求文',routeHeading:'2小时宫殿拍照路线示例',routeDisclaimer:'这是规划示例，不是实时路线或拥挤信息。出发前请确认宫殿开放时间、休宫、天气和步行条件。',stop:'站点',ctaTitle:'免费试用 My Korea Look',ctaDesc:'现在可使用免费的偏好型咨询。照片感知造型、私密交付、修改和结账在账号、隐私、交付、退款及商户条件验证完成前保持关闭。',ctaButton:'开始免费造型预览',englishDetailNote:'部分深入服装说明在母语编辑审核完成前仍以英文显示；来源与库存提示不变。'},
 ja:{sampleBadge:'公開サンプル',disclaimer:p=>`これは${p}スタイルブックの架空の成人1名向け公開サンプルです。予定している結果の深さを示しますが、アカウント・生成/配信・返金・事業者要件が本番検証されるまで、有料決済と非公開配信は利用できません。`,eyebrow:'My Korea Look · キュレーションサンプル',plannedPrice:'予定ローンチ価格：12.00 USD',priceDesc:'成人1名 · 3ルック · 韓国語店舗カード · 撮影ルート',sampleNav:'他のサンプルを見る',personaTitle:'旅行者プロフィールとスタイル目標',selectedVibe:'選択スタイル',colorHarmony:'カラー方向',primaryTone:'メイン色',secondaryTone:'サブ色',accentTone:'アクセント色',looksHeading:'このサンプル向け3つのキュレーションルック',lookOf:i=>`ルック ${i}/3`,practicalNote:'実用メモ',suggestedSpot:'おすすめ宮殿スポット',photoIdea:'撮影アイデア',source:'出典',viewSource:'出典を見る',checked:'出典確認',shopBadge:'店頭用バイリンガル依頼カード',copyKorean:'韓国語をコピー',copied:'コピーしました',copyFailed:'ブラウザーでコピーできませんでした。この画面を開いたまま韓国語を店舗スタッフに見せてください。',shopHeading:'実際に用意できる衣装を店舗で確認',koreanLabel:'店舗スタッフ向け韓国語メモ',routeHeading:'2時間の宮殿撮影ルート例',routeDisclaimer:'これは計画例で、リアルタイム経路や混雑情報ではありません。訪問前に開館時間、休館、天気、歩行条件を確認してください。',stop:'STOP',ctaTitle:'無料 My Korea Look を試す',ctaDesc:'無料の好みベース診断は今すぐ使えます。写真を使う有料スタイリング、非公開配信、修正、決済は必要なアカウント・プライバシー・生成/配信・返金・事業者要件が検証されるまで停止します。',ctaButton:'無料スタイルプレビューを始める',englishDetailNote:'詳細な衣装メモの一部はネイティブ編集レビュー完了まで英語です。出典・在庫注意事項は変わりません。'},
 'zh-TW':{sampleBadge:'公開範例',disclaimer:p=>`這是${p}風格書的虛構單人公開範例，用來展示預計結果深度。帳號、交付、退款與商家要求完成正式驗證前，付費結帳與私密交付仍不可用。`,eyebrow:'My Korea Look · 精選範例',plannedPrice:'預計首發價：12.00 美元',priceDesc:'1位成人 · 3套精選造型 · 韓文店內需求卡 · 拍照路線',sampleNav:'查看其他精選範例',personaTitle:'旅客設定與美感目標',selectedVibe:'選擇風格',colorHarmony:'色彩方向',primaryTone:'主色',secondaryTone:'輔助色',accentTone:'點綴色',looksHeading:'適合此範例設定的3套精選造型',lookOf:i=>`造型 ${i}/3`,practicalNote:'實用提示',suggestedSpot:'建議宮殿場景',photoIdea:'拍攝建議',source:'來源',viewSource:'查看來源',checked:'來源核對',shopBadge:'雙語店內需求卡',copyKorean:'複製韓文',copied:'已複製',copyFailed:'瀏覽器阻擋了複製。請保持此頁開啟，直接向店員展示下方韓文。',shopHeading:'請租借店員確認實際可提供的款式',koreanLabel:'給韓國店員看的需求文字',routeHeading:'2小時宮殿拍照路線範例',routeDisclaimer:'這是規劃範例，不是即時路線或人潮資訊。出發前請確認宮殿開放時間、休宮、天氣與步行條件。',stop:'站點',ctaTitle:'免費試用 My Korea Look',ctaDesc:'現在可使用免費偏好型諮詢。照片感知造型、私密交付、修改與結帳在帳號、隱私、交付、退款及商家條件驗證完成前維持關閉。',ctaButton:'開始免費造型預覽',englishDetailNote:'部分深入服裝說明在母語編輯審核完成前仍以英文顯示；來源與庫存提醒不變。'},
 vi:{sampleBadge:'Mẫu công khai',disclaimer:p=>`Đây là mẫu công khai hư cấu cho một người lớn của stylebook ${p}. Mẫu cho thấy độ sâu kết quả dự kiến, nhưng thanh toán và giao kết quả riêng tư vẫn bị khóa cho đến khi tài khoản, hoàn thiện, hoàn tiền và yêu cầu người bán được kiểm chứng ở môi trường thật.`,eyebrow:'My Korea Look · Mẫu tuyển chọn',plannedPrice:'Giá ra mắt dự kiến: 12,00 USD',priceDesc:'1 người lớn · 3 look tuyển chọn · thẻ tiếng Hàn cho cửa hàng · lộ trình chụp ảnh',sampleNav:'Xem các mẫu tuyển chọn khác',personaTitle:'Hồ sơ du khách & mục tiêu thẩm mỹ',selectedVibe:'Phong cách đã chọn',colorHarmony:'Hướng màu',primaryTone:'Màu chính',secondaryTone:'Màu phụ',accentTone:'Màu nhấn',looksHeading:'3 look tuyển chọn cho hồ sơ mẫu này',lookOf:i=>`Look ${i}/3`,practicalNote:'Lưu ý thực tế',suggestedSpot:'Bối cảnh cung điện gợi ý',photoIdea:'Gợi ý chụp ảnh',source:'Nguồn',viewSource:'Xem nguồn',checked:'Đã kiểm tra nguồn',shopBadge:'Thẻ yêu cầu song ngữ tại cửa hàng',copyKorean:'Sao chép tiếng Hàn',copied:'Đã sao chép',copyFailed:'Trình duyệt chặn sao chép. Hãy giữ màn hình này mở và đưa phần tiếng Hàn bên dưới cho nhân viên.',shopHeading:'Yêu cầu cửa hàng kiểm tra mẫu thực tế đang có',koreanLabel:'Ghi chú tiếng Hàn cho nhân viên',routeHeading:'Ví dụ lộ trình chụp ảnh cung điện 2 giờ',routeDisclaimer:'Đây là ví dụ lập kế hoạch, không phải tuyến đường hay dữ liệu đông người theo thời gian thực. Hãy kiểm tra giờ mở cửa, ngày đóng, thời tiết và điều kiện đi bộ trước khi đi.',stop:'ĐIỂM',ctaTitle:'Thử My Korea Look miễn phí',ctaDesc:'Bạn có thể dùng tư vấn miễn phí theo sở thích ngay bây giờ. Tính năng trả phí dùng ảnh, giao riêng tư, chỉnh sửa và thanh toán vẫn khóa cho đến khi các điều kiện tài khoản, quyền riêng tư, hoàn thiện, hoàn tiền và người bán được xác minh.',ctaButton:'Bắt đầu xem trước phong cách miễn phí',englishDetailNote:'Một số ghi chú trang phục chuyên sâu vẫn dùng tiếng Anh trong khi chờ biên tập bản ngữ; nguồn và cảnh báo tồn kho không thay đổi.'},
 th:{sampleBadge:'ตัวอย่างสาธารณะ',disclaimer:p=>`นี่คือตัวอย่างสาธารณะสมมติสำหรับผู้ใหญ่ 1 คนของสไตล์บุ๊ก ${p} เพื่อแสดงความลึกของผลลัพธ์ที่วางแผนไว้ การชำระเงินและการส่งมอบแบบส่วนตัวยังคงปิดจนกว่าระบบบัญชี การสร้าง/ส่งมอบ การคืนเงิน และข้อกำหนดผู้ขายจะผ่านการตรวจสอบจริง`,eyebrow:'My Korea Look · ตัวอย่างคัดสรร',plannedPrice:'ราคาเปิดตัวที่วางแผนไว้: 12.00 USD',priceDesc:'ผู้ใหญ่ 1 คน · 3 ลุค · การ์ดภาษาเกาหลีสำหรับร้าน · เส้นทางถ่ายภาพ',sampleNav:'ดูตัวอย่างคัดสรรอื่น',personaTitle:'โปรไฟล์ผู้เดินทางและเป้าหมายด้านสไตล์',selectedVibe:'สไตล์ที่เลือก',colorHarmony:'ทิศทางสี',primaryTone:'สีหลัก',secondaryTone:'สีรอง',accentTone:'สีเน้น',looksHeading:'3 ลุคคัดสรรสำหรับโปรไฟล์ตัวอย่างนี้',lookOf:i=>`ลุค ${i}/3`,practicalNote:'ข้อควรคำนึง',suggestedSpot:'จุดพระราชวังที่แนะนำ',photoIdea:'ไอเดียถ่ายภาพ',source:'แหล่งที่มา',viewSource:'ดูแหล่งที่มา',checked:'ตรวจสอบแหล่งข้อมูล',shopBadge:'การ์ดคำขอในร้านสองภาษา',copyKorean:'คัดลอกภาษาเกาหลี',copied:'คัดลอกแล้ว',copyFailed:'เบราว์เซอร์บล็อกการคัดลอก โปรดเปิดหน้าจอนี้ไว้และแสดงข้อความภาษาเกาหลีด้านล่างให้พนักงานดู',shopHeading:'ให้ร้านเช่าตรวจสอบสิ่งที่มีจริง',koreanLabel:'ข้อความภาษาเกาหลีสำหรับพนักงาน',routeHeading:'ตัวอย่างเส้นทางถ่ายภาพพระราชวัง 2 ชั่วโมง',routeDisclaimer:'นี่คือตัวอย่างแผน ไม่ใช่เส้นทางหรือข้อมูลความหนาแน่นแบบเรียลไทม์ โปรดตรวจสอบเวลาเปิด วันปิด อากาศ และสภาพการเดินก่อนเดินทาง',stop:'จุด',ctaTitle:'ลอง My Korea Look ฟรี',ctaDesc:'ใช้คำแนะนำฟรีตามความชอบได้ตอนนี้ ส่วนการจัดสไตล์แบบใช้ภาพ การส่งผลลัพธ์ส่วนตัว การแก้ไข และการชำระเงินยังปิดจนกว่าข้อกำหนดด้านบัญชี ความเป็นส่วนตัว การสร้าง/ส่งมอบ การคืนเงิน และผู้ขายจะผ่านการตรวจสอบ',ctaButton:'เริ่มพรีวิวสไตล์ฟรี',englishDetailNote:'รายละเอียดเชิงลึกบางส่วนยังเป็นภาษาอังกฤษระหว่างรอการตรวจแก้โดยเจ้าของภาษา โดยแหล่งข้อมูลและคำเตือนเรื่องสต็อกไม่เปลี่ยนแปลง'}
};

const SAMPLES:Record<SampleLocale,Record<string,SampleCopy>>={
 en:{
  'palace-elegance':{title:'Joseon Court Dignity & Jewel-Tone Elegance',tagline:'Deep navy, crimson silk and pine greens for a dignified palace direction.',badge:'Queen & King court harmony',personaName:'Sample persona: Elena · solo traveler · spring Seoul visit',personaSummary:'Prefers dignified palace photos with historic presence rather than pastel glitter.',travelContext:'About two hours around Gyeongbokgung.',selectedUndertone:'Warm neutral · higher contrast',selectedStyle:'Queen / King · dignified heritage',paletteTitle:'Crimson dancheong & midnight navy',paletteNotes:'A strong jewel-tone contrast against stone courtyards and wooden halls.',shopExplanation:'Ask whether a similar crimson-and-navy court-inspired outfit and accessories are available and confirm any extra charge.',tabLabel:'Palace Elegance'},
  'modern-pastel':{title:'Luminous Lavender & Garden Light',tagline:'Airy pastel layers for soft natural-light palace portraits.',badge:'Princess & Prince pastel',personaName:'Sample persona: Chloe · solo traveler · first Korea trip',personaSummary:'Wants a whimsical, luminous outdoor-photo direction in palace gardens.',travelContext:'Morning palace portrait walk.',selectedUndertone:'Cool · light',selectedStyle:'Princess / Prince · soft and graceful',paletteTitle:'Soft lilac, ivory & blossom pink',paletteNotes:'Diffuse pastel tones for green water and foliage backgrounds.',shopExplanation:'Ask whether a similar ivory-and-lilac pastel outfit and simple ribbon styling are available and confirm any extra charge.',tabLabel:'Modern Pastel'},
  'royal-ceremony':{title:'Ceremonial Scarlet & Gold Royal Drama',tagline:'A dramatic ceremonial direction built around scarlet, gold and strong palace contrast.',badge:'High ceremonial drama',personaName:'Sample persona: Kenji · solo traveler · milestone trip',personaSummary:'Wants a theatrical color-and-silhouette direction for a memorable palace portrait session.',travelContext:'Palace portrait walk with extra fitting and return margin.',selectedUndertone:'Warm · golden',selectedStyle:'Royal · ceremonial drama',paletteTitle:'Scarlet, gold & onyx',paletteNotes:'High-contrast ceremonial colors for bold palace photography.',shopExplanation:'Ask whether a similar red-and-gold court-inspired outfit and accessories are available and confirm any extra charge.',tabLabel:'Royal Ceremony'}
 },
 'zh-CN':{
  'palace-elegance':{title:'朝鲜宫廷端庄感与宝石色优雅',tagline:'以深蓝、绯红与松绿色营造端庄的宫殿造型方向。',badge:'王后 / 国王宫廷和谐',personaName:'示例人物：Elena · 独自旅行 · 春季首尔',personaSummary:'偏好有历史感、端庄克制的宫殿照片，不追求闪亮粉彩。',travelContext:'约2小时景福宫行程。',selectedUndertone:'暖中性 · 较高对比',selectedStyle:'王后 / 国王 · 端庄传统',paletteTitle:'丹青绯红与午夜深蓝',paletteNotes:'宝石色强对比，适合石质庭院与木构殿阁背景。',shopExplanation:'询问是否有相近的绯红＋深蓝宫廷风组合与配件，并确认是否产生额外费用。',tabLabel:'宫廷优雅'},
  'modern-pastel':{title:'明亮薰衣草紫与庭园柔光',tagline:'轻盈粉彩层次，适合自然光下的宫苑人像。',badge:'公主 / 王子粉彩',personaName:'示例人物：Chloe · 独自旅行 · 首次韩国之旅',personaSummary:'希望在宫殿庭园拍出轻盈、明亮、带幻想感的户外照片。',travelContext:'上午宫殿拍照散步。',selectedUndertone:'冷色 · 明亮',selectedStyle:'公主 / 王子 · 柔和优雅',paletteTitle:'浅紫、象牙白与花瓣粉',paletteNotes:'柔和粉彩适合水面与绿植背景。',shopExplanation:'询问是否有相近的象牙白＋浅紫粉彩韩服与简洁缎带造型，并确认额外费用。',tabLabel:'现代粉彩'},
  'royal-ceremony':{title:'朱红与金色的皇家仪式张力',tagline:'以朱红、金色和强烈宫殿对比打造戏剧化仪式方向。',badge:'高仪式感皇家风',personaName:'示例人物：Kenji · 独自旅行 · 纪念旅行',personaSummary:'希望为重要旅行拍摄有戏剧感、轮廓鲜明的宫殿肖像。',travelContext:'预留试穿和归还时间的宫殿拍照行程。',selectedUndertone:'暖色 · 金调',selectedStyle:'皇家 · 仪式戏剧感',paletteTitle:'朱红、金色与玛瑙黑',paletteNotes:'高对比仪式色彩适合强烈的宫殿画面。',shopExplanation:'询问是否有相近的红金宫廷风服装与配件，并确认额外费用。',tabLabel:'皇家仪式'}
 },
 ja:{
  'palace-elegance':{title:'朝鮮王朝の品格とジュエルトーン',tagline:'濃紺・深紅・松緑で端正な宮殿スタイルを作る方向。',badge:'王妃 / 王の宮廷ハーモニー',personaName:'サンプル人物：Elena · 一人旅 · 春のソウル',personaSummary:'きらめくパステルより、歴史性と品格を感じる宮殿写真を好む設定。',travelContext:'景福宮周辺で約2時間。',selectedUndertone:'ウォームニュートラル · 高めのコントラスト',selectedStyle:'王妃 / 王 · 端正な伝統感',paletteTitle:'丹青の深紅とミッドナイトネイビー',paletteNotes:'石庭や木造建築に映える強めのジュエルトーン対比。',shopExplanation:'近い深紅×濃紺の宮廷風衣装と小物があるか、追加料金も含めて確認します。',tabLabel:'宮廷エレガンス'},
  'modern-pastel':{title:'ラベンダーと庭園のやわらかな光',tagline:'軽やかなパステルレイヤーで自然光の宮苑ポートレートへ。',badge:'プリンセス / プリンス・パステル',personaName:'サンプル人物：Chloe · 一人旅 · 初めての韓国',personaSummary:'宮苑で明るく幻想的な屋外写真を撮りたい設定。',travelContext:'午前の宮殿ポートレート散策。',selectedUndertone:'クール · ライト',selectedStyle:'プリンセス / プリンス · やわらかく優雅',paletteTitle:'淡いライラック、アイボリー、花びらピンク',paletteNotes:'水面と緑を背景にやわらかく見えるパステル配色。',shopExplanation:'近いアイボリー×ライラックのパステル衣装とシンプルなリボン演出が可能か、追加料金も確認します。',tabLabel:'モダンパステル'},
  'royal-ceremony':{title:'スカーレット＆ゴールドの王室ドラマ',tagline:'朱赤・金・強い宮殿コントラストで作る儀礼的な方向。',badge:'高い儀礼感のロイヤルスタイル',personaName:'サンプル人物：Kenji · 一人旅 · 記念旅行',personaSummary:'節目の旅行で、色とシルエットが強い劇的な宮殿ポートレートを望む設定。',travelContext:'試着と返却の余裕を含む宮殿撮影散策。',selectedUndertone:'ウォーム · ゴールド',selectedStyle:'ロイヤル · セレモニードラマ',paletteTitle:'スカーレット、ゴールド、オニキス',paletteNotes:'強いコントラストで宮殿写真に存在感を出す配色。',shopExplanation:'近い赤×金の宮廷風衣装と小物があるか、追加料金も含めて確認します。',tabLabel:'ロイヤルセレモニー'}
 },
 'zh-TW':{
  'palace-elegance':{title:'朝鮮宮廷端莊感與寶石色優雅',tagline:'以深藍、緋紅與松綠打造端莊的宮殿造型方向。',badge:'王后 / 國王宮廷和諧',personaName:'範例人物：Elena · 獨旅 · 春季首爾',personaSummary:'偏好具有歷史感、端莊克制的宮殿照片，而不是閃亮粉彩。',travelContext:'約2小時景福宮行程。',selectedUndertone:'暖中性 · 較高對比',selectedStyle:'王后 / 國王 · 端莊傳統',paletteTitle:'丹青緋紅與午夜深藍',paletteNotes:'寶石色強對比，適合石質庭院與木構宮殿背景。',shopExplanation:'詢問是否有相近的緋紅＋深藍宮廷風組合與配件，並確認是否有額外費用。',tabLabel:'宮廷優雅'},
  'modern-pastel':{title:'明亮薰衣草紫與庭園柔光',tagline:'輕盈粉彩層次，適合自然光下的宮苑人像。',badge:'公主 / 王子粉彩',personaName:'範例人物：Chloe · 獨旅 · 首次韓國之旅',personaSummary:'希望在宮殿庭園拍出輕盈、明亮、帶幻想感的戶外照片。',travelContext:'上午宮殿拍照散步。',selectedUndertone:'冷色 · 明亮',selectedStyle:'公主 / 王子 · 柔和優雅',paletteTitle:'淡紫、象牙白與花瓣粉',paletteNotes:'柔和粉彩適合水面與綠植背景。',shopExplanation:'詢問是否有相近的象牙白＋淡紫粉彩韓服與簡潔緞帶造型，並確認額外費用。',tabLabel:'現代粉彩'},
  'royal-ceremony':{title:'朱紅與金色的皇家儀式張力',tagline:'以朱紅、金色和強烈宮殿對比打造戲劇化儀式方向。',badge:'高儀式感皇家風',personaName:'範例人物：Kenji · 獨旅 · 紀念旅行',personaSummary:'希望為重要旅行拍攝有戲劇感、輪廓鮮明的宮殿肖像。',travelContext:'預留試穿與歸還時間的宮殿拍照行程。',selectedUndertone:'暖色 · 金調',selectedStyle:'皇家 · 儀式戲劇感',paletteTitle:'朱紅、金色與瑪瑙黑',paletteNotes:'高對比儀式色彩適合強烈的宮殿畫面。',shopExplanation:'詢問是否有相近的紅金宮廷風服裝與配件，並確認額外費用。',tabLabel:'皇家儀式'}
 },
 vi:{
  'palace-elegance':{title:'Vẻ trang trọng cung đình Joseon & tông đá quý',tagline:'Xanh navy, đỏ thẫm và xanh thông cho hướng cung điện trang nhã.',badge:'Hài hòa Vương hậu / Quốc vương',personaName:'Nhân vật mẫu: Elena · du lịch một mình · Seoul mùa xuân',personaSummary:'Ưu tiên ảnh cung điện trang trọng, có chiều sâu lịch sử thay vì pastel lấp lánh.',travelContext:'Khoảng 2 giờ quanh Gyeongbokgung.',selectedUndertone:'Ấm trung tính · tương phản cao hơn',selectedStyle:'Vương hậu / Quốc vương · trang trọng',paletteTitle:'Đỏ dancheong & navy đêm',paletteNotes:'Tương phản đá quý rõ trên sân đá và kiến trúc gỗ.',shopExplanation:'Hỏi cửa hàng có hướng đỏ thẫm + navy tương tự và phụ kiện phù hợp không, đồng thời xác nhận phụ phí.',tabLabel:'Thanh lịch cung đình'},
  'modern-pastel':{title:'Lavender sáng & ánh sáng vườn cung',tagline:'Các lớp pastel nhẹ cho ảnh chân dung cung điện dưới ánh sáng tự nhiên.',badge:'Pastel Công chúa / Hoàng tử',personaName:'Nhân vật mẫu: Chloe · du lịch một mình · lần đầu tới Hàn Quốc',personaSummary:'Muốn ảnh ngoài trời sáng, nhẹ và mơ mộng trong khu vườn cung điện.',travelContext:'Đi bộ chụp ảnh cung điện buổi sáng.',selectedUndertone:'Lạnh · sáng',selectedStyle:'Công chúa / Hoàng tử · mềm mại',paletteTitle:'Lilac nhạt, ngà & hồng cánh hoa',paletteNotes:'Pastel khuếch tán hợp nền mặt nước và cây xanh.',shopExplanation:'Hỏi có bộ ngà + lilac pastel tương tự và kiểu ruy băng đơn giản không, đồng thời xác nhận phụ phí.',tabLabel:'Pastel hiện đại'},
  'royal-ceremony':{title:'Kịch tính hoàng gia đỏ son & vàng',tagline:'Hướng nghi lễ nổi bật với đỏ son, vàng và tương phản mạnh cùng kiến trúc cung điện.',badge:'Phong cách nghi lễ hoàng gia',personaName:'Nhân vật mẫu: Kenji · du lịch một mình · chuyến đi kỷ niệm',personaSummary:'Muốn hướng màu và phom dáng có tính sân khấu cho buổi chụp chân dung cung điện đáng nhớ.',travelContext:'Đi chụp ảnh cung điện với thêm thời gian thử và trả trang phục.',selectedUndertone:'Ấm · vàng',selectedStyle:'Hoàng gia · nghi lễ kịch tính',paletteTitle:'Đỏ son, vàng & đen onyx',paletteNotes:'Màu nghi lễ tương phản cao tạo hình ảnh cung điện mạnh.',shopExplanation:'Hỏi có trang phục đỏ + vàng kiểu cung đình và phụ kiện tương tự không, đồng thời xác nhận phụ phí.',tabLabel:'Nghi lễ hoàng gia'}
 },
 th:{
  'palace-elegance':{title:'ความสง่างามราชสำนักโชซอนและโทนอัญมณี',tagline:'กรมท่า แดงเข้ม และเขียวสนสำหรับทิศทางพระราชวังที่สุขุมสง่างาม',badge:'ความกลมกลืนราชินี / กษัตริย์',personaName:'บุคคลตัวอย่าง: Elena · เที่ยวคนเดียว · โซลฤดูใบไม้ผลิ',personaSummary:'ชอบภาพพระราชวังที่สง่างามและมีบรรยากาศประวัติศาสตร์มากกว่าพาสเทลระยิบระยับ',travelContext:'ประมาณ 2 ชั่วโมงรอบคยองบกกุง',selectedUndertone:'อุ่นกลาง · คอนทราสต์สูงขึ้น',selectedStyle:'ราชินี / กษัตริย์ · สุขุมดั้งเดิม',paletteTitle:'แดงดันชองและกรมท่ากลางคืน',paletteNotes:'คอนทราสต์แบบอัญมณีเด่นบนลานหินและอาคารไม้',shopExplanation:'สอบถามว่ามีชุดแนวแดงเข้ม + กรมท่าที่ใกล้เคียงและเครื่องประดับหรือไม่ พร้อมยืนยันค่าใช้จ่ายเพิ่มเติม',tabLabel:'สง่างามราชสำนัก'},
  'modern-pastel':{title:'ลาเวนเดอร์สว่างและแสงนุ่มในสวน',tagline:'เลเยอร์พาสเทลเบาสำหรับภาพบุคคลในพระราชวังด้วยแสงธรรมชาติ',badge:'พาสเทลเจ้าหญิง / เจ้าชาย',personaName:'บุคคลตัวอย่าง: Chloe · เที่ยวคนเดียว · เกาหลีครั้งแรก',personaSummary:'ต้องการภาพกลางแจ้งที่สว่าง เบา และชวนฝันในสวนพระราชวัง',travelContext:'เดินถ่ายภาพพระราชวังช่วงเช้า',selectedUndertone:'เย็น · สว่าง',selectedStyle:'เจ้าหญิง / เจ้าชาย · นุ่มนวลสง่างาม',paletteTitle:'ไลแลคอ่อน ไอวอรี และชมพูกลีบดอก',paletteNotes:'พาสเทลนุ่มเข้ากับพื้นหลังน้ำและต้นไม้',shopExplanation:'สอบถามว่ามีชุดไอวอรี + ไลแลคพาสเทลใกล้เคียงและการจัดริบบิ้นแบบเรียบง่ายหรือไม่ พร้อมยืนยันค่าบริการเพิ่ม',tabLabel:'พาสเทลโมเดิร์น'},
  'royal-ceremony':{title:'ดราม่าราชสำนักสีแดงชาดและทอง',tagline:'ทิศทางพิธีการที่เด่นด้วยแดงชาด ทอง และคอนทราสต์พระราชวังที่ชัด',badge:'ราชสำนักพิธีการเข้มข้น',personaName:'บุคคลตัวอย่าง: Kenji · เที่ยวคนเดียว · ทริปสำคัญ',personaSummary:'ต้องการทิศทางสีและรูปทรงที่โดดเด่นสำหรับภาพพระราชวังในทริปที่น่าจดจำ',travelContext:'เดินถ่ายภาพพระราชวังพร้อมเผื่อเวลาลองและคืนชุด',selectedUndertone:'อุ่น · ทอง',selectedStyle:'ราชสำนัก · ดราม่าพิธีการ',paletteTitle:'แดงชาด ทอง และดำโอนิกซ์',paletteNotes:'สีพิธีการคอนทราสต์สูงสร้างภาพพระราชวังที่ทรงพลัง',shopExplanation:'สอบถามว่ามีชุดราชสำนักแดง + ทองและเครื่องประดับที่ใกล้เคียงหรือไม่ พร้อมยืนยันค่าใช้จ่ายเพิ่มเติม',tabLabel:'พิธีการราชสำนัก'}
 }
};

export function safeSampleLocale(locale:string):SampleLocale{return locale in SHELL?locale as SampleLocale:'en';}
export function getSampleShell(locale:string){return SHELL[safeSampleLocale(locale)];}
export function getSampleCopy(locale:string,slug:string,fallback:SampleStylebook):SampleCopy{
 const l=safeSampleLocale(locale);return SAMPLES[l][slug]??SAMPLES.en[slug]??{title:fallback.title,tagline:fallback.tagline,badge:fallback.badge,personaName:fallback.persona.name,personaSummary:fallback.persona.summary,travelContext:fallback.persona.travelContext,selectedUndertone:fallback.persona.selectedUndertone,selectedStyle:fallback.persona.selectedStyle,paletteTitle:fallback.colorAnalysisSummary.paletteTitle,paletteNotes:fallback.colorAnalysisSummary.paletteNotes,shopExplanation:fallback.koreanShopCardSummary.instructionEnglish,tabLabel:fallback.title};
}
export function getSampleMetadata(locale:string,slug:string,fallback:SampleStylebook){const copy=getSampleCopy(locale,slug,fallback);return{title:`${copy.title} — My Korea Look`,description:copy.tagline};}
export const SAMPLE_P0_LOCALES=Object.freeze(Object.keys(SHELL));
