'use client';

import {useMemo,useState} from 'react';
import {useLocale} from 'next-intl';
import {Link} from '@/i18n/navigation';
import type {Coverage,GarmentType,StyleId} from '@/lib/looks/catalog';
import {rankStyleInputV1,seasonFromVisitDate,type StyleComfort,type StyleDestination,type StyleInputV1,type StyleMood,type StylePalette,type StyleSeason} from '@/lib/looks/style-input-v1';

type Locale=StyleInputV1['locale'];
type Copy={title:string;intro:string;style:string;garment:string;palette:string;mood:string;comfort:string;coverage:string;season:string;date:string;dateHelp:string;destination:string;preview:string;notEnough:string;why:string;trade:string;location:string;source:string;route:string;request:string;save:string;restore:string;clear:string;copy:string;download:string;saved:string;restored:string;cleared:string;noSaved:string;storageFailed:string;copied:string;copyFailed:string;downloaded:string;freeNote:string;routeNote:string;rental:string;sample:string};
const C:Record<Locale,Copy>={
 en:{title:'My Korea Look',intro:'Set the full trip context. Your free three-look plan is ranked locally from the curated catalog.',style:'Style family',garment:'Garment',palette:'Palette',mood:'Mood',comfort:'Comfort',coverage:'Coverage',season:'Season',date:'Visit date (optional)',dateHelp:'A valid date automatically sets the seasonal fit.',destination:'Destination',preview:'Your 3-look plan',notEnough:'This combination has fewer than three verified looks. Change garment or coverage before continuing.',why:'Why it fits',trade:'Trade-off',location:'Curated palace setting',source:'Visual source',route:'Verified catalog photo route',request:'Korean rental request',save:'Save choices',restore:'Restore choices',clear:'Clear saved choices',copy:'Copy plan',download:'Download plan',saved:'Choices saved on this device.',restored:'Saved choices restored.',cleared:'Saved choices cleared.',noSaved:'No valid saved choices found.',storageFailed:'Device storage is unavailable. The current plan still works; copy or download it.',copied:'Plan copied.',copyFailed:'Copy was blocked. Download the text plan instead.',downloaded:'Text plan downloaded.',freeNote:'Free deterministic preview: no checkout, AI call or remote photo processing. Saved choices stay on this device.',routeNote:'Destination changes the editorial ranking. Catalog routes are verified Gyeongbokgung photo-route references; use Nearby Explorer for other-area walking plans.',rental:'Find rental shops',sample:'See sample'},
 'zh-CN':{title:'My Korea Look',intro:'填写完整行程偏好，系统会在本地从精选目录中确定性排序3套造型。',style:'风格系列',garment:'服装',palette:'配色',mood:'氛围',comfort:'舒适度',coverage:'遮盖度',season:'季节',date:'到访日期（可选）',dateHelp:'有效日期会自动用于季节适配。',destination:'目的地',preview:'你的3套造型',notEnough:'此组合不足3套已验证造型，请调整服装或遮盖度。',why:'适合原因',trade:'取舍',location:'精选宫殿场景',source:'图片来源',route:'已验证目录拍照路线',request:'韩文租赁请求',save:'保存选择',restore:'恢复选择',clear:'清除保存',copy:'复制计划',download:'下载计划',saved:'已保存在此设备。',restored:'已恢复保存的选择。',cleared:'已清除保存的选择。',noSaved:'没有找到有效的保存选择。',storageFailed:'无法访问设备存储。当前计划仍可使用，请复制或下载。',copied:'已复制计划。',copyFailed:'浏览器阻止复制，请下载文字计划。',downloaded:'已下载文字计划。',freeNote:'免费确定性预览：不结账、不调用AI、不远程处理照片；选择仅保存在本设备。',routeNote:'目的地会影响编辑排序。目录中的拍照路线为已核验的景福宫参考；其他区域步行计划请使用 Nearby Explorer。',rental:'查找租赁店',sample:'查看示例'},
 ja:{title:'My Korea Look',intro:'旅行条件をまとめて設定すると、選定済みカタログから端末内で3ルックを決定的に順位付けします。',style:'スタイル',garment:'衣装',palette:'配色',mood:'ムード',comfort:'快適さ',coverage:'カバー範囲',season:'季節',date:'訪問日（任意）',dateHelp:'有効な日付は季節適合に自動反映されます。',destination:'目的地',preview:'3ルックプラン',notEnough:'この組み合わせでは検証済みルックが3件未満です。衣装またはカバー範囲を変更してください。',why:'合う理由',trade:'注意点',location:'選定済み宮殿ロケーション',source:'画像出典',route:'検証済みカタログ撮影ルート',request:'韓国語レンタル依頼',save:'選択を保存',restore:'選択を復元',clear:'保存を削除',copy:'プランをコピー',download:'プランをダウンロード',saved:'この端末に保存しました。',restored:'保存した選択を復元しました。',cleared:'保存を削除しました。',noSaved:'有効な保存データがありません。',storageFailed:'端末ストレージを利用できません。現在のプランは使えるためコピーまたはダウンロードしてください。',copied:'プランをコピーしました。',copyFailed:'コピーがブロックされました。テキスト版をダウンロードしてください。',downloaded:'テキスト版をダウンロードしました。',freeNote:'無料の決定的プレビューです。決済・AI呼び出し・写真の外部処理はありません。保存は端末内のみです。',routeNote:'目的地は編集上の順位に反映されます。カタログ撮影ルートは検証済み景福宮参照です。他エリアは Nearby Explorer を利用してください。',rental:'レンタル店を探す',sample:'サンプルを見る'},
 'zh-TW':{title:'My Korea Look',intro:'設定完整旅程偏好後，系統會在裝置端從精選目錄確定性排序3套造型。',style:'風格系列',garment:'服裝',palette:'配色',mood:'氛圍',comfort:'舒適度',coverage:'遮蓋度',season:'季節',date:'到訪日期（選填）',dateHelp:'有效日期會自動套用季節適配。',destination:'目的地',preview:'你的3套造型',notEnough:'此組合少於3套已驗證造型，請調整服裝或遮蓋度。',why:'適合原因',trade:'取捨',location:'精選宮殿場景',source:'圖片來源',route:'已驗證目錄拍照路線',request:'韓文租借需求',save:'儲存選擇',restore:'還原選擇',clear:'清除儲存',copy:'複製計畫',download:'下載計畫',saved:'已儲存在此裝置。',restored:'已還原儲存的選擇。',cleared:'已清除儲存的選擇。',noSaved:'找不到有效的儲存選擇。',storageFailed:'無法存取裝置儲存空間。目前計畫仍可使用，請複製或下載。',copied:'已複製計畫。',copyFailed:'瀏覽器阻擋複製，請下載文字計畫。',downloaded:'已下載文字計畫。',freeNote:'免費確定性預覽：不結帳、不呼叫AI、不遠端處理照片；選擇只保留在此裝置。',routeNote:'目的地會影響編輯排序。目錄拍照路線是已核驗的景福宮參考；其他區域請使用 Nearby Explorer。',rental:'尋找租借店',sample:'查看範例'},
 vi:{title:'My Korea Look',intro:'Đặt đầy đủ bối cảnh chuyến đi để xếp hạng xác định 3 look ngay trên thiết bị từ danh mục tuyển chọn.',style:'Nhóm phong cách',garment:'Trang phục',palette:'Bảng màu',mood:'Không khí',comfort:'Độ thoải mái',coverage:'Độ che phủ',season:'Mùa',date:'Ngày ghé thăm (tùy chọn)',dateHelp:'Ngày hợp lệ tự động quyết định độ phù hợp theo mùa.',destination:'Điểm đến',preview:'Kế hoạch 3 look',notEnough:'Tổ hợp này có ít hơn 3 look đã xác minh. Hãy đổi trang phục hoặc độ che phủ.',why:'Vì sao phù hợp',trade:'Điểm đánh đổi',location:'Bối cảnh cung điện tuyển chọn',source:'Nguồn hình ảnh',route:'Tuyến chụp ảnh đã xác minh',request:'Yêu cầu thuê bằng tiếng Hàn',save:'Lưu lựa chọn',restore:'Khôi phục lựa chọn',clear:'Xóa lựa chọn đã lưu',copy:'Sao chép kế hoạch',download:'Tải kế hoạch',saved:'Đã lưu trên thiết bị này.',restored:'Đã khôi phục lựa chọn.',cleared:'Đã xóa lựa chọn.',noSaved:'Không tìm thấy lựa chọn hợp lệ đã lưu.',storageFailed:'Không thể truy cập bộ nhớ thiết bị. Kế hoạch hiện tại vẫn dùng được; hãy sao chép hoặc tải xuống.',copied:'Đã sao chép kế hoạch.',copyFailed:'Sao chép bị chặn. Hãy tải bản văn bản.',downloaded:'Đã tải bản văn bản.',freeNote:'Bản xem trước miễn phí và xác định: không thanh toán, không gọi AI, không xử lý ảnh từ xa. Lựa chọn chỉ lưu trên thiết bị.',routeNote:'Điểm đến ảnh hưởng xếp hạng biên tập. Tuyến trong danh mục là tham chiếu Gyeongbokgung đã xác minh; dùng Nearby Explorer cho khu vực khác.',rental:'Tìm cửa hàng thuê',sample:'Xem mẫu'},
 th:{title:'My Korea Look',intro:'ตั้งค่าบริบททริปให้ครบ แล้วจัดอันดับ 3 ลุคแบบกำหนดแน่นอนบนอุปกรณ์จากแคตตาล็อกที่คัดสรร',style:'กลุ่มสไตล์',garment:'ชุด',palette:'พาเลตสี',mood:'อารมณ์',comfort:'ความสบาย',coverage:'การปกปิด',season:'ฤดู',date:'วันที่ไป (ไม่บังคับ)',dateHelp:'วันที่ที่ถูกต้องจะใช้กำหนดความเหมาะสมตามฤดูอัตโนมัติ',destination:'จุดหมาย',preview:'แผน 3 ลุค',notEnough:'ชุดตัวเลือกนี้มีลุคที่ตรวจสอบแล้วน้อยกว่า 3 แบบ กรุณาเปลี่ยนชุดหรือระดับการปกปิด',why:'เหตุผลที่เหมาะ',trade:'ข้อแลกเปลี่ยน',location:'ฉากพระราชวังที่คัดสรร',source:'แหล่งภาพ',route:'เส้นทางถ่ายภาพจากแคตตาล็อกที่ตรวจสอบแล้ว',request:'คำขอเช่าภาษาเกาหลี',save:'บันทึกตัวเลือก',restore:'กู้คืนตัวเลือก',clear:'ล้างที่บันทึก',copy:'คัดลอกแผน',download:'ดาวน์โหลดแผน',saved:'บันทึกในอุปกรณ์นี้แล้ว',restored:'กู้คืนตัวเลือกแล้ว',cleared:'ล้างตัวเลือกแล้ว',noSaved:'ไม่พบตัวเลือกที่บันทึกไว้อย่างถูกต้อง',storageFailed:'เข้าถึงพื้นที่จัดเก็บไม่ได้ แผนปัจจุบันยังใช้ได้ โปรดคัดลอกหรือดาวน์โหลด',copied:'คัดลอกแผนแล้ว',copyFailed:'การคัดลอกถูกบล็อก โปรดดาวน์โหลดแผนข้อความ',downloaded:'ดาวน์โหลดแผนข้อความแล้ว',freeNote:'พรีวิวฟรีแบบกำหนดแน่นอน: ไม่มีการชำระเงิน ไม่มี AI และไม่มีการประมวลผลรูปจากระยะไกล การบันทึกอยู่ในอุปกรณ์เท่านั้น',routeNote:'จุดหมายมีผลต่อการจัดอันดับเชิงบรรณาธิการ เส้นทางในแคตตาล็อกเป็นข้อมูลอ้างอิงพระราชวังคยองบกที่ตรวจสอบแล้ว พื้นที่อื่นใช้ Nearby Explorer',rental:'ค้นหาร้านเช่า',sample:'ดูตัวอย่าง'}
};

const STORAGE_KEY='kc-my-korea-look-plan-v2';
const styles:StyleId[]=['princess-prince','queen-king','royal'];
const garments:GarmentType[]=['either','chima','baji'];
const palettes:StylePalette[]=['jadeIvory','roseNavy','moonBlue'];
const moods:StyleMood[]=['elegant','royal','romantic','minimal','kdrama'];
const comforts:StyleComfort[]=['walking','balanced','photoFirst'];
const coverages:Coverage[]=['standard','more-coverage'];
const seasons:StyleSeason[]=['springAutumn','summer','winter'];
const destinations:StyleDestination[]=['gyeongbokgung','bukchon','seochon'];
const label=(v:string)=>({princess-prince:'Princess / Prince','queen-king':'Queen / King',royal:'Royal',either:'Either',chima:'Chima',baji:'Baji',jadeIvory:'Jade & Ivory',roseNavy:'Rose & Navy',moonBlue:'Moon Blue',elegant:'Elegant',romantic:'Romantic',minimal:'Minimal',kdrama:'K-drama',walking:'Walking first',balanced:'Balanced',photoFirst:'Photo first',standard:'Standard','more-coverage':'More coverage',springAutumn:'Spring / Autumn',summer:'Summer',winter:'Winter',gyeongbokgung:'Gyeongbokgung',bukchon:'Bukchon',seochon:'Seochon'}[v]??v);

function isInput(value:unknown):value is StyleInputV1{
 if(!value||typeof value!=='object')return false;
 const x=value as Partial<StyleInputV1>;
 return x.version===1&&!!x.locale&&styles.includes(x.style as StyleId)&&garments.includes(x.garment as GarmentType)&&palettes.includes(x.palette as StylePalette)&&moods.includes(x.mood as StyleMood)&&comforts.includes(x.comfort as StyleComfort)&&coverages.includes(x.coverage as Coverage)&&seasons.includes(x.season as StyleSeason)&&destinations.includes(x.destination as StyleDestination)&&x.colorSource==='manual'&&(x.visitDate===undefined||seasonFromVisitDate(x.visitDate)!==null);
}

export function StyleConsultationV3(){
 const rawLocale=useLocale();const locale=(rawLocale in C?rawLocale:'en') as Locale;const c=C[locale];
 const [style,setStyle]=useState<StyleId>('princess-prince');
 const [garment,setGarment]=useState<GarmentType>('either');
 const [palette,setPalette]=useState<StylePalette>('jadeIvory');
 const [mood,setMood]=useState<StyleMood>('romantic');
 const [comfort,setComfort]=useState<StyleComfort>('balanced');
 const [coverage,setCoverage]=useState<Coverage>('standard');
 const [season,setSeason]=useState<StyleSeason>('springAutumn');
 const [destination,setDestination]=useState<StyleDestination>('gyeongbokgung');
 const [visitDate,setVisitDate]=useState('');const [message,setMessage]=useState('');
 const effectiveSeason=visitDate?seasonFromVisitDate(visitDate):null;
 const input=useMemo<StyleInputV1>(()=>({version:1,locale,style,garment,palette,mood,comfort,coverage,season:effectiveSeason??season,destination,...(visitDate&&effectiveSeason?{visitDate}:{}),colorSource:'manual'}),[locale,style,garment,palette,mood,comfort,coverage,season,destination,visitDate,effectiveSeason]);
 const ranked=useMemo(()=>rankStyleInputV1(input),[input]);const looks=ranked.slice(0,3).map(x=>x.look);const complete=looks.length===3;
 const planText=useMemo(()=>[
  'My Korea Look',`${c.style}: ${label(style)}`,`${c.garment}: ${label(garment)}`,`${c.palette}: ${label(palette)}`,`${c.mood}: ${label(mood)}`,`${c.comfort}: ${label(comfort)}`,`${c.coverage}: ${label(coverage)}`,`${c.season}: ${label(input.season)}`,`${c.destination}: ${label(destination)}`,...(input.visitDate?[`${c.date}: ${input.visitDate}`]:[]),'',
  ...looks.flatMap((look,i)=>[`#${i+1} ${look.title}`,look.description,`${c.location}: ${look.recommendedLocation.name} · ${look.recommendedLocation.koreanName}`,`${c.trade}: ${look.tradeOff}`,`${c.source}: ${look.creator} · ${look.license} · ${look.sourceUrl}`,`${c.request}: ${look.rentalShopCard.hangulTitle} / ${look.rentalShopCard.hangulStaffNote}`,`${c.route}: ${look.photoRoute.map(s=>`${s.order}. ${s.spotName}`).join(' → ')}`,'']),c.routeNote
 ].join('\n'),[c,style,garment,palette,mood,comfort,coverage,input,destination,looks]);
 const selectStyle={display:'grid',gap:5} as const;const resetMessage=()=>setMessage('');
 async function copy(){if(!navigator.clipboard?.writeText){setMessage(c.copyFailed);return;}try{await navigator.clipboard.writeText(planText);setMessage(c.copied);}catch{setMessage(c.copyFailed);}}
 function download(){try{const blob=new Blob([planText],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`my-korea-look-${locale}.txt`;document.body.appendChild(a);try{a.click();setMessage(c.downloaded);}finally{a.remove();URL.revokeObjectURL(url);}}catch{setMessage(c.copyFailed);}}
 function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(input));setMessage(c.saved);}catch{setMessage(c.storageFailed);}}
 function restore(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw){setMessage(c.noSaved);return;}let parsed:unknown;try{parsed=JSON.parse(raw);}catch{localStorage.removeItem(STORAGE_KEY);setMessage(c.noSaved);return;}if(!isInput(parsed)){localStorage.removeItem(STORAGE_KEY);setMessage(c.noSaved);return;}setStyle(parsed.style);setGarment(parsed.garment);setPalette(parsed.palette);setMood(parsed.mood);setComfort(parsed.comfort);setCoverage(parsed.coverage);setSeason(parsed.season);setDestination(parsed.destination);setVisitDate(parsed.visitDate??'');setMessage(c.restored);}catch{setMessage(c.storageFailed);}}
 function clear(){try{localStorage.removeItem(STORAGE_KEY);setMessage(c.cleared);}catch{setMessage(c.storageFailed);}}
 return <section style={{maxWidth:1080,margin:'0 auto',padding:'30px 20px 70px'}}><h1>{c.title}</h1><p>{c.intro}</p>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12,margin:'22px 0'}}>
  <label style={selectStyle}>{c.style}<select value={style} onChange={e=>{setStyle(e.target.value as StyleId);resetMessage();}}>{styles.map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label>
  <label style={selectStyle}>{c.garment}<select value={garment} onChange={e=>{setGarment(e.target.value as GarmentType);resetMessage();}}>{garments.map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label>
  <label style={selectStyle}>{c.palette}<select value={palette} onChange={e=>{setPalette(e.target.value as StylePalette);resetMessage();}}>{palettes.map(v=><option key={v} value={v}>{label(v)}</option>)}</select><Link href="/color"><small>Personal Color →</small></Link></label>
  <label style={selectStyle}>{c.mood}<select value={mood} onChange={e=>{setMood(e.target.value as StyleMood);resetMessage();}}>{moods.map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label>
  <label style={selectStyle}>{c.comfort}<select value={comfort} onChange={e=>{setComfort(e.target.value as StyleComfort);resetMessage();}}>{comforts.map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label>
  <label style={selectStyle}>{c.coverage}<select value={coverage} onChange={e=>{setCoverage(e.target.value as Coverage);resetMessage();}}>{coverages.map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label>
  <label style={selectStyle}>{c.season}<select value={effectiveSeason??season} disabled={!!effectiveSeason} onChange={e=>{setSeason(e.target.value as StyleSeason);resetMessage();}}>{seasons.map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label>
  <label style={selectStyle}>{c.destination}<select value={destination} onChange={e=>{setDestination(e.target.value as StyleDestination);resetMessage();}}>{destinations.map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label>
  <label style={selectStyle}>{c.date}<input type="date" min="1900-01-01" max="2100-12-31" value={visitDate} onChange={e=>{setVisitDate(e.target.value);resetMessage();}}/><small>{c.dateHelp}</small></label>
 </div>
 <h2>{c.preview}</h2>{!complete?<p role="alert"><strong>{c.notEnough}</strong></p>:null}
 {complete?<div aria-live="polite" style={{display:'grid',gap:18}}>{looks.map((look,i)=><article key={look.id} style={{border:'1px solid currentColor',padding:18,borderRadius:12}}><h3>#{i+1} {look.title}</h3><p>{look.description}</p><p><strong>{c.location}:</strong> {look.recommendedLocation.name} · {look.recommendedLocation.koreanName}</p><p><strong>{c.trade}:</strong> {look.tradeOff}</p><p><small><strong>{c.source}:</strong> {look.creator} · {look.license} · <a href={look.sourceUrl} target="_blank" rel="noopener noreferrer">source ↗</a></small></p><details><summary><strong>{c.request}</strong></summary><div lang="ko" style={{whiteSpace:'pre-line'}}>{look.rentalShopCard.hangulTitle}<br/>{look.rentalShopCard.hangulStaffNote}<br/>※ 동일한 색상/디자인 재고와 추가 요금이 있는지 먼저 확인 부탁드립니다.</div></details><details><summary><strong>{c.route}</strong></summary><ol>{look.photoRoute.map(s=><li key={`${look.id}-${s.order}`}><strong>{s.spotName} · {s.koreanName}</strong> — {s.bestTime}<br/><small>{s.photoTip}</small></li>)}</ol></details></article>)}</div>:null}
 <p><small>{c.routeNote}</small></p><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:18}}><button type="button" className="primaryButton" onClick={copy} disabled={!complete}>{c.copy}</button><button type="button" className="secondaryButton" onClick={download} disabled={!complete}>{c.download}</button><button type="button" className="secondaryButton" onClick={save}>{c.save}</button><button type="button" className="secondaryButton" onClick={restore}>{c.restore}</button><button type="button" className="secondaryButton" onClick={clear}>{c.clear}</button><Link className="secondaryButton" href="/hanbok#rental-finder">{c.rental}</Link><Link className="secondaryButton" href="/style/sample/palace-elegance">{c.sample}</Link></div><p><small>{c.freeNote}</small></p>{message?<p role="status"><strong>{message}</strong></p>:null}</section>;
}
