'use client';

import {useMemo,useState} from 'react';
import {useLocale} from 'next-intl';
import {Link} from '@/i18n/navigation';
import type {Coverage,GarmentType,StyleId} from '@/lib/looks/catalog';
import type {StyleHandoff} from '@/lib/looks/style-handoff';
import {rankStyleInputV1,seasonFromVisitDate,type StyleComfort,type StyleDestination,type StyleInputV1,type StyleMood,type StylePalette,type StyleSeason} from '@/lib/looks/style-input-v1';

type Locale=StyleInputV1['locale'];
type Copy={title:string;intro:string;style:string;garment:string;palette:string;mood:string;comfort:string;coverage:string;season:string;date:string;destination:string;preview:string;why:string;colors:string;accessories:string;alternate:string;trade:string;location:string;source:string;route:string;request:string;save:string;restore:string;clear:string;copy:string;download:string;notEnough:string;statusSaved:string;statusRestored:string;statusCleared:string;statusMissing:string;statusStorage:string;statusCopied:string;statusCopyFailed:string;statusDownloaded:string;freeNote:string;rental:string;localColorApplied:string;summary:(style:string,garment:string,palette:string)=>string;evidenceStyle:(input:string,result:string)=>string;evidencePalette:(input:string,undertone:string)=>string;evidencePractical:(comfort:string,season:string,destination:string,walking:string)=>string;tradeEasy:string;tradeModerate:string;tradePhoto:string;routeNote:string};

const C:Record<Locale,Copy>={
 en:{title:'My Korea Look',intro:'Set your trip context. One verified free look is ranked locally from the curated catalog.',style:'Style family',garment:'Garment',palette:'Palette',mood:'Mood',comfort:'Comfort',coverage:'Coverage',season:'Season',date:'Visit date (optional)',destination:'Destination',preview:'Your free look preview',why:'Why this matches your choice',colors:'Basic color direction',accessories:'Accessories',alternate:'Alternative colorway',trade:'Trade-off',location:'Curated setting',source:'Visual source',route:'Photo route',request:'Korean rental request',save:'Save choices',restore:'Restore choices',clear:'Clear saved',copy:'Copy preview',download:'Download preview',notEnough:'No verified free look matches this combination. Change garment or coverage.',statusSaved:'Choices saved on this device.',statusRestored:'Saved choices restored.',statusCleared:'Saved choices cleared.',statusMissing:'No valid saved choices found.',statusStorage:'Device storage is unavailable. The current preview still works; copy or download it.',statusCopied:'Preview copied.',statusCopyFailed:'Copy was blocked. Download the text preview instead.',statusDownloaded:'Text preview downloaded.',freeNote:'Free deterministic preview: one look, basic color direction and a short reason. No checkout, AI call or remote photo processing.',rental:'Find rental shops',localColorApplied:'Color direction carried over from your browser-local Personal Color result. No photo was transferred.',summary:(s,g,p)=>`${s} mood with ${g}, built around the ${p} palette.`,evidenceStyle:(a,b)=>`Your ${a} style preference maps to this ${b} catalog family.`,evidencePalette:(a,b)=>`Your ${a} palette preference is compatible with this ${b} undertone.`,evidencePractical:(c,s,d,w)=>`${c}, ${s}, and ${d} are balanced against ${w} walking suitability.`,tradeEasy:'Easy for walking; still confirm hem length, footwear and weather at the rental shop.',tradeModerate:'Balanced for photos and walking; allow extra time for heavier layers or accessories.',tradePhoto:'Photo-first styling can feel heavier or warmer; keep a lighter alternate ready.',routeNote:'Times are planning guidance, not live availability.'},
 'zh-CN':{title:'My Korea Look',intro:'设置行程条件，系统会在本地从已核验目录中确定性排序1套免费造型。',style:'风格',garment:'服装',palette:'配色',mood:'氛围',comfort:'舒适度',coverage:'遮盖度',season:'季节',date:'到访日期（可选）',destination:'目的地',preview:'你的免费造型预览',why:'为什么符合你的选择',colors:'基础配色方向',accessories:'配饰',alternate:'替代配色',trade:'取舍',location:'精选场景',source:'图片来源',route:'拍照路线',request:'韩文租赁请求',save:'保存选择',restore:'恢复选择',clear:'清除保存',copy:'复制预览',download:'下载预览',notEnough:'没有符合此组合的已核验免费造型，请调整服装或遮盖度。',statusSaved:'已保存在此设备。',statusRestored:'已恢复保存选择。',statusCleared:'已清除保存选择。',statusMissing:'没有有效的保存选择。',statusStorage:'无法访问设备存储。当前预览仍可使用，请复制或下载。',statusCopied:'已复制预览。',statusCopyFailed:'复制被阻止，请下载文字预览。',statusDownloaded:'已下载文字预览。',freeNote:'免费确定性预览：1套造型、基础配色方向和简短理由；无结账、无AI调用、无远程照片处理。',rental:'查找租赁店',localColorApplied:'已沿用浏览器本地 Personal Color 的色彩方向，没有传输照片。',summary:(s,g,p)=>`以${s}氛围搭配${g}，并围绕${p}配色完成。`,evidenceStyle:(a,b)=>`你选择的${a}风格与目录中的${b}系列相符。`,evidencePalette:(a,b)=>`你选择的${a}配色与这套造型的${b}色温方向兼容。`,evidencePractical:(c,s,d,w)=>`将${c}、${s}与${d}条件和${w}步行适配度一起权衡。`,tradeEasy:'适合步行；仍建议在租赁店确认裙摆长度、鞋子和当天天气。',tradeModerate:'兼顾拍照与步行；较厚层次或配饰需要预留更多时间。',tradePhoto:'拍照优先的造型可能更重或更热，建议准备一套轻便替代方案。',routeNote:'时间仅用于行程规划，不代表实时营业或预约情况。'},
 ja:{title:'My Korea Look',intro:'旅行条件を設定すると、検証済みカタログから無料の1ルックを端末内で決定的に順位付けします。',style:'スタイル',garment:'衣装',palette:'配色',mood:'ムード',comfort:'快適さ',coverage:'カバー範囲',season:'季節',date:'訪問日（任意）',destination:'目的地',preview:'無料ルックプレビュー',why:'選択に合う理由',colors:'基本の色方向',accessories:'小物',alternate:'代替カラー',trade:'注意点',location:'選定ロケーション',source:'画像出典',route:'撮影ルート',request:'韓国語レンタル依頼',save:'選択を保存',restore:'復元',clear:'保存を削除',copy:'プレビューをコピー',download:'プレビューをダウンロード',notEnough:'この条件に合う検証済み無料ルックがありません。衣装またはカバー範囲を変更してください。',statusSaved:'この端末に保存しました。',statusRestored:'保存した選択を復元しました。',statusCleared:'保存を削除しました。',statusMissing:'有効な保存データがありません。',statusStorage:'端末ストレージを利用できません。現在のプレビューはコピーまたはダウンロードできます。',statusCopied:'プレビューをコピーしました。',statusCopyFailed:'コピーがブロックされました。テキスト版プレビューをダウンロードしてください。',statusDownloaded:'テキスト版プレビューをダウンロードしました。',freeNote:'無料の決定的プレビュー：1ルック、基本の色方向、短い理由。決済・AI呼び出し・写真の外部処理はありません。',rental:'レンタル店を探す',localColorApplied:'ブラウザ内の Personal Color 結果から色方向だけを引き継ぎました。写真は転送されていません。',summary:(s,g,p)=>`${s}の雰囲気を${g}でまとめ、${p}の配色を軸にした提案です。`,evidenceStyle:(a,b)=>`選択した${a}の好みが、カタログの${b}系統に対応しています。`,evidencePalette:(a,b)=>`${a}の配色希望は、このルックの${b}アンダートーンと両立します。`,evidencePractical:(c,s,d,w)=>`${c}・${s}・${d}の条件を、${w}の歩きやすさと合わせて評価しています。`,tradeEasy:'歩きやすい構成です。裾丈・履物・当日の天候はレンタル店で確認してください。',tradeModerate:'撮影と歩行のバランス型です。厚手の重ね着や小物には余裕時間を見てください。',tradePhoto:'撮影優先のため重さや暑さを感じる場合があります。軽い代替案も準備してください。',routeNote:'時間は計画用の目安で、リアルタイムの営業・予約状況ではありません。'},
 'zh-TW':{title:'My Korea Look',intro:'設定旅程條件後，系統會在裝置端從已驗證目錄確定性排序1套免費造型。',style:'風格',garment:'服裝',palette:'配色',mood:'氛圍',comfort:'舒適度',coverage:'遮蓋度',season:'季節',date:'到訪日期（選填）',destination:'目的地',preview:'你的免費造型預覽',why:'符合你選擇的原因',colors:'基本配色方向',accessories:'配件',alternate:'替代配色',trade:'取捨',location:'精選場景',source:'圖片來源',route:'拍照路線',request:'韓文租借需求',save:'儲存選擇',restore:'還原',clear:'清除儲存',copy:'複製預覽',download:'下載預覽',notEnough:'此組合沒有符合的已驗證免費造型，請調整服裝或遮蓋度。',statusSaved:'已儲存在此裝置。',statusRestored:'已還原儲存選擇。',statusCleared:'已清除儲存選擇。',statusMissing:'找不到有效的儲存選擇。',statusStorage:'無法存取裝置儲存空間。目前預覽仍可複製或下載。',statusCopied:'已複製預覽。',statusCopyFailed:'複製被阻擋，請下載文字預覽。',statusDownloaded:'已下載文字預覽。',freeNote:'免費確定性預覽：1套造型、基本配色方向與簡短理由；無結帳、無AI呼叫、無遠端照片處理。',rental:'尋找租借店',localColorApplied:'已沿用瀏覽器本機 Personal Color 的色彩方向，沒有傳送照片。',summary:(s,g,p)=>`以${s}氛圍搭配${g}，並以${p}配色為核心。`,evidenceStyle:(a,b)=>`你選擇的${a}風格與目錄中的${b}系列相符。`,evidencePalette:(a,b)=>`你選擇的${a}配色與此造型的${b}色溫方向相容。`,evidencePractical:(c,s,d,w)=>`把${c}、${s}與${d}條件和${w}步行適配度一起評估。`,tradeEasy:'適合步行；仍建議在租借店確認下擺長度、鞋款與當天天氣。',tradeModerate:'兼顧拍照與步行；較厚層次或配件需要預留更多時間。',tradePhoto:'拍照優先的造型可能較重或較熱，建議準備輕便替代方案。',routeNote:'時間僅供行程規劃，不代表即時營業或預約狀態。'},
 vi:{title:'My Korea Look',intro:'Đặt bối cảnh chuyến đi để xếp hạng xác định 1 look miễn phí đã xác minh ngay trên thiết bị.',style:'Phong cách',garment:'Trang phục',palette:'Bảng màu',mood:'Không khí',comfort:'Độ thoải mái',coverage:'Độ che phủ',season:'Mùa',date:'Ngày ghé thăm (tùy chọn)',destination:'Điểm đến',preview:'Bản xem trước look miễn phí',why:'Vì sao phù hợp lựa chọn của bạn',colors:'Hướng màu cơ bản',accessories:'Phụ kiện',alternate:'Phối màu thay thế',trade:'Điểm đánh đổi',location:'Bối cảnh chọn lọc',source:'Nguồn hình ảnh',route:'Tuyến chụp ảnh',request:'Yêu cầu thuê bằng tiếng Hàn',save:'Lưu lựa chọn',restore:'Khôi phục',clear:'Xóa đã lưu',copy:'Sao chép bản xem trước',download:'Tải bản xem trước',notEnough:'Không có look miễn phí đã xác minh phù hợp tổ hợp này. Hãy đổi trang phục hoặc độ che phủ.',statusSaved:'Đã lưu trên thiết bị này.',statusRestored:'Đã khôi phục lựa chọn.',statusCleared:'Đã xóa lựa chọn.',statusMissing:'Không tìm thấy lựa chọn hợp lệ đã lưu.',statusStorage:'Không thể truy cập bộ nhớ thiết bị. Bản xem trước hiện tại vẫn có thể sao chép hoặc tải xuống.',statusCopied:'Đã sao chép bản xem trước.',statusCopyFailed:'Sao chép bị chặn. Hãy tải bản xem trước dạng văn bản.',statusDownloaded:'Đã tải bản xem trước dạng văn bản.',freeNote:'Bản xem trước miễn phí và xác định: 1 look, hướng màu cơ bản và lý do ngắn; không thanh toán, không AI, không xử lý ảnh từ xa.',rental:'Tìm cửa hàng thuê',localColorApplied:'Đã dùng hướng màu từ Personal Color xử lý trong trình duyệt. Không có ảnh nào được chuyển sang trang này.',summary:(s,g,p)=>`Phong cách ${s} với ${g}, xây dựng quanh bảng màu ${p}.`,evidenceStyle:(a,b)=>`Lựa chọn ${a} của bạn phù hợp với nhóm ${b} trong danh mục.`,evidencePalette:(a,b)=>`Bảng màu ${a} tương thích với sắc độ nền ${b} của look này.`,evidencePractical:(c,s,d,w)=>`${c}, ${s} và ${d} được cân bằng với mức phù hợp đi bộ ${w}.`,tradeEasy:'Dễ đi bộ; vẫn nên xác nhận độ dài gấu, giày và thời tiết tại cửa hàng thuê.',tradeModerate:'Cân bằng giữa chụp ảnh và đi bộ; nên chừa thêm thời gian cho lớp áo hoặc phụ kiện nặng.',tradePhoto:'Ưu tiên chụp ảnh có thể nặng hoặc nóng hơn; nên giữ một phương án nhẹ hơn.',routeNote:'Thời gian chỉ để lập kế hoạch, không phải tình trạng mở cửa hay đặt chỗ theo thời gian thực.'},
 th:{title:'My Korea Look',intro:'ตั้งค่าบริบททริปเพื่อจัดอันดับลุคฟรีที่ตรวจสอบแล้ว 1 ลุคแบบกำหนดแน่นอนบนอุปกรณ์',style:'สไตล์',garment:'ชุด',palette:'พาเลตสี',mood:'อารมณ์',comfort:'ความสบาย',coverage:'การปกปิด',season:'ฤดู',date:'วันที่ไป (ไม่บังคับ)',destination:'จุดหมาย',preview:'พรีวิวลุคฟรีของคุณ',why:'เหตุผลที่ตรงกับตัวเลือกของคุณ',colors:'ทิศทางสีพื้นฐาน',accessories:'เครื่องประดับ',alternate:'สีทางเลือก',trade:'ข้อแลกเปลี่ยน',location:'สถานที่คัดสรร',source:'แหล่งภาพ',route:'เส้นทางถ่ายภาพ',request:'คำขอเช่าภาษาเกาหลี',save:'บันทึกตัวเลือก',restore:'กู้คืน',clear:'ล้างที่บันทึก',copy:'คัดลอกพรีวิว',download:'ดาวน์โหลดพรีวิว',notEnough:'ไม่มีลุคฟรีที่ตรวจสอบแล้วตรงกับชุดตัวเลือกนี้ กรุณาเปลี่ยนชุดหรือระดับการปกปิด',statusSaved:'บันทึกในอุปกรณ์นี้แล้ว',statusRestored:'กู้คืนตัวเลือกแล้ว',statusCleared:'ล้างตัวเลือกแล้ว',statusMissing:'ไม่พบตัวเลือกที่บันทึกไว้อย่างถูกต้อง',statusStorage:'เข้าถึงพื้นที่จัดเก็บไม่ได้ พรีวิวปัจจุบันยังคัดลอกหรือดาวน์โหลดได้',statusCopied:'คัดลอกพรีวิวแล้ว',statusCopyFailed:'การคัดลอกถูกบล็อก โปรดดาวน์โหลดพรีวิวข้อความ',statusDownloaded:'ดาวน์โหลดพรีวิวข้อความแล้ว',freeNote:'พรีวิวฟรีแบบกำหนดแน่นอน: 1 ลุค ทิศทางสีพื้นฐาน และเหตุผลสั้น ๆ ไม่มีการชำระเงิน ไม่มี AI และไม่มีการประมวลผลรูปจากระยะไกล',rental:'ค้นหาร้านเช่า',localColorApplied:'นำเฉพาะทิศทางสีจาก Personal Color ที่ประมวลผลในเบราว์เซอร์มาใช้ โดยไม่มีการส่งรูปภาพ',summary:(s,g,p)=>`ลุคโทน ${s} กับ ${g} โดยยึดพาเลต ${p} เป็นหลัก`,evidenceStyle:(a,b)=>`สไตล์ ${a} ที่เลือกสอดคล้องกับกลุ่ม ${b} ในแคตตาล็อก`,evidencePalette:(a,b)=>`พาเลต ${a} เข้ากับอันเดอร์โทน ${b} ของลุคนี้`,evidencePractical:(c,s,d,w)=>`ประเมิน ${c}, ${s} และ ${d} ร่วมกับความเหมาะสมต่อการเดินระดับ ${w}`,tradeEasy:'เดินสะดวก แต่ควรยืนยันความยาวชายชุด รองเท้า และสภาพอากาศกับร้านเช่า',tradeModerate:'สมดุลระหว่างถ่ายภาพกับเดิน ควรเผื่อเวลาสำหรับชั้นผ้าหรือเครื่องประดับที่หนักขึ้น',tradePhoto:'ลุคเน้นภาพอาจหนักหรือร้อนกว่า ควรมีตัวเลือกที่เบากว่าไว้สำรอง',routeNote:'เวลาเป็นเพียงแนวทางวางแผน ไม่ใช่ข้อมูลเปิดบริการหรือการจองแบบเรียลไทม์'}
};

const STORAGE_KEY='kc-my-korea-look-plan-v2';
const locales:Locale[]=['en','zh-CN','ja','zh-TW','vi','th'];
const styles:StyleId[]=['princess-prince','queen-king','royal'];
const garments:GarmentType[]=['either','chima','baji'];
const palettes:StylePalette[]=['jadeIvory','roseNavy','moonBlue','suggest'];
const moods:StyleMood[]=['elegant','royal','romantic','minimal','kdrama'];
const comforts:StyleComfort[]=['walking','balanced','photoFirst'];
const coverages:Coverage[]=['standard','more-coverage'];
const seasons:StyleSeason[]=['springAutumn','summer','winter'];
const destinations:StyleDestination[]=['gyeongbokgung','bukchon','seochon'];

const LABELS:Record<Locale,Record<string,string>>={
 en:{'princess-prince':'Princess / Prince','queen-king':'Queen / King',royal:'Royal',either:'Either',chima:'Chima',baji:'Baji',jadeIvory:'Jade & Ivory',roseNavy:'Rose & Navy',moonBlue:'Moon Blue',suggest:'Suggest for me',elegant:'Elegant',romantic:'Romantic',minimal:'Minimal',kdrama:'K-drama',walking:'Walking first',balanced:'Balanced',photoFirst:'Photo first',standard:'Standard','more-coverage':'More coverage',springAutumn:'Spring / Autumn',summer:'Summer',winter:'Winter',gyeongbokgung:'Gyeongbokgung',bukchon:'Bukchon',seochon:'Seochon',warm:'warm',cool:'cool',neutral:'neutral',universal:'universal',easy:'easy',moderate:'moderate','photo-focused':'photo-first'},
 'zh-CN':{'princess-prince':'柔和王子/公主','queen-king':'端庄王后/国王',royal:'华丽宫廷',either:'不限款式',chima:'裙装韩服',baji:'裤装韩服',jadeIvory:'玉色与象牙白',roseNavy:'玫瑰与藏蓝',moonBlue:'月光蓝',suggest:'帮我推荐',elegant:'优雅',romantic:'浪漫',minimal:'简约',kdrama:'韩剧感',walking:'步行为主',balanced:'均衡',photoFirst:'拍照优先',standard:'标准','more-coverage':'更多遮盖',springAutumn:'春/秋',summer:'夏季',winter:'冬季',gyeongbokgung:'景福宫',bukchon:'北村',seochon:'西村',warm:'暖',cool:'冷',neutral:'中性',universal:'通用',easy:'轻松',moderate:'中等','photo-focused':'拍照优先'},
 ja:{'princess-prince':'やわらかい王子・姫','queen-king':'端正な王・王妃',royal:'華やかな宮廷',either:'どちらでも',chima:'チマ型',baji:'パジ型',jadeIvory:'翡翠×アイボリー',roseNavy:'ローズ×ネイビー',moonBlue:'ムーンブルー',suggest:'おすすめ',elegant:'上品',romantic:'ロマンチック',minimal:'ミニマル',kdrama:'Kドラマ風',walking:'歩きやすさ優先',balanced:'バランス',photoFirst:'撮影優先',standard:'標準','more-coverage':'露出控えめ',springAutumn:'春・秋',summer:'夏',winter:'冬',gyeongbokgung:'景福宮',bukchon:'北村',seochon:'西村',warm:'ウォーム',cool:'クール',neutral:'ニュートラル',universal:'ユニバーサル',easy:'歩きやすい',moderate:'中程度','photo-focused':'撮影優先'},
 'zh-TW':{'princess-prince':'柔和王子/公主','queen-king':'端莊王后/國王',royal:'華麗宮廷',either:'不限款式',chima:'裙裝韓服',baji:'褲裝韓服',jadeIvory:'玉色與象牙白',roseNavy:'玫瑰與藏藍',moonBlue:'月光藍',suggest:'幫我推薦',elegant:'優雅',romantic:'浪漫',minimal:'簡約',kdrama:'韓劇感',walking:'步行優先',balanced:'均衡',photoFirst:'拍照優先',standard:'標準','more-coverage':'更多遮蓋',springAutumn:'春/秋',summer:'夏季',winter:'冬季',gyeongbokgung:'景福宮',bukchon:'北村',seochon:'西村',warm:'暖',cool:'冷',neutral:'中性',universal:'通用',easy:'輕鬆',moderate:'中等','photo-focused':'拍照優先'},
 vi:{'princess-prince':'Hoàng tử / Công chúa nhẹ nhàng','queen-king':'Vua / Hoàng hậu trang trọng',royal:'Hoàng gia nổi bật',either:'Bất kỳ',chima:'Hanbok váy chima',baji:'Hanbok quần baji',jadeIvory:'Ngọc bích & ngà',roseNavy:'Hồng & xanh navy',moonBlue:'Xanh ánh trăng',suggest:'Gợi ý cho tôi',elegant:'Thanh lịch',romantic:'Lãng mạn',minimal:'Tối giản',kdrama:'Phong cách K-drama',walking:'Ưu tiên đi bộ',balanced:'Cân bằng',photoFirst:'Ưu tiên chụp ảnh',standard:'Tiêu chuẩn','more-coverage':'Che phủ nhiều hơn',springAutumn:'Xuân / Thu',summer:'Mùa hè',winter:'Mùa đông',gyeongbokgung:'Gyeongbokgung',bukchon:'Bukchon',seochon:'Seochon',warm:'ấm',cool:'lạnh',neutral:'trung tính',universal:'phổ quát',easy:'dễ',moderate:'trung bình','photo-focused':'ưu tiên ảnh'},
 th:{'princess-prince':'เจ้าชาย/เจ้าหญิงโทนอ่อน','queen-king':'ราชา/ราชินีแบบสุภาพ',royal:'ราชสำนักหรูหรา',either:'แบบใดก็ได้',chima:'ฮันบกกระโปรงชิมา',baji:'ฮันบกกางเกงบาจี',jadeIvory:'หยกและไอวอรี',roseNavy:'โรสและเนวี',moonBlue:'มูนบลู',suggest:'ช่วยแนะนำ',elegant:'สง่างาม',romantic:'โรแมนติก',minimal:'มินิมอล',kdrama:'สไตล์ K-drama',walking:'เน้นเดิน',balanced:'สมดุล',photoFirst:'เน้นถ่ายภาพ',standard:'มาตรฐาน','more-coverage':'ปกปิดมากขึ้น',springAutumn:'ใบไม้ผลิ / ใบไม้ร่วง',summer:'ฤดูร้อน',winter:'ฤดูหนาว',gyeongbokgung:'พระราชวังคยองบกกุง',bukchon:'บุกชอน',seochon:'ซอชน',warm:'โทนอุ่น',cool:'โทนเย็น',neutral:'กลาง',universal:'ใช้ได้กว้าง',easy:'ง่าย',moderate:'ปานกลาง','photo-focused':'เน้นภาพ'}
};
const label=(locale:Locale,value:string)=>LABELS[locale][value]??value;

function validInput(value:unknown):value is StyleInputV1{if(!value||typeof value!=='object')return false;const x=value as Partial<StyleInputV1>;return x.version===1&&locales.includes(x.locale as Locale)&&styles.includes(x.style as StyleId)&&garments.includes(x.garment as GarmentType)&&palettes.includes(x.palette as StylePalette)&&moods.includes(x.mood as StyleMood)&&comforts.includes(x.comfort as StyleComfort)&&coverages.includes(x.coverage as Coverage)&&seasons.includes(x.season as StyleSeason)&&destinations.includes(x.destination as StyleDestination)&&['manual','local-preview'].includes(String(x.colorSource))&&(x.visitDate===undefined||seasonFromVisitDate(x.visitDate)!==null);}

export function StyleConsultationV5({initialHandoff}:{initialHandoff?:StyleHandoff|null}){
 const rawLocale=useLocale();const locale=(locales.includes(rawLocale as Locale)?rawLocale:'en') as Locale;const c=C[locale];
 const [style,setStyle]=useState<StyleId>('princess-prince');const [garment,setGarment]=useState<GarmentType>('either');const [palette,setPalette]=useState<StylePalette>(initialHandoff?.palette??'jadeIvory');const [mood,setMood]=useState<StyleMood>(initialHandoff?.mood??'romantic');const [comfort,setComfort]=useState<StyleComfort>(initialHandoff?.comfort??'balanced');const [coverage,setCoverage]=useState<Coverage>('standard');const [season,setSeason]=useState<StyleSeason>(initialHandoff?.season??'springAutumn');const [destination,setDestination]=useState<StyleDestination>(initialHandoff?.destination??'gyeongbokgung');const [visitDate,setVisitDate]=useState('');const [colorSource,setColorSource]=useState<StyleInputV1['colorSource']>(initialHandoff?.colorSource??'manual');const [message,setMessage]=useState('');
 const dateSeason=visitDate?seasonFromVisitDate(visitDate):null;
 const input=useMemo<StyleInputV1>(()=>({version:1,locale,style,garment,palette,mood,comfort,coverage,season:dateSeason??season,destination,...(visitDate&&dateSeason?{visitDate}:{}),colorSource}),[locale,style,garment,palette,mood,comfort,coverage,season,destination,visitDate,dateSeason,colorSource]);
 const ranked=useMemo(()=>rankStyleInputV1(input),[input]);const looks=ranked.slice(0,1).map(x=>x.look);const complete=looks.length===1;
 const evidence=(look:(typeof looks)[number])=>[c.evidenceStyle(label(locale,input.style),label(locale,look.styleId)),c.evidencePalette(label(locale,input.palette),label(locale,look.palette.undertone)),c.evidencePractical(label(locale,input.comfort),label(locale,input.season),label(locale,input.destination),label(locale,look.walkingSuitability))] as const;
 const planText=useMemo(()=>[c.title,`${c.style}: ${label(locale,style)}`,`${c.garment}: ${label(locale,garment)}`,`${c.palette}: ${label(locale,palette)}`,`${c.mood}: ${label(locale,mood)}`,`${c.comfort}: ${label(locale,comfort)}`,`${c.coverage}: ${label(locale,coverage)}`,`${c.season}: ${label(locale,input.season)}`,`${c.destination}: ${label(locale,destination)}`,...(input.visitDate?[`${c.date}: ${input.visitDate}`]:[]),'',...looks.flatMap((look,index)=>[`#${index+1} ${look.title}`,c.summary(label(locale,input.mood),label(locale,look.garmentType),label(locale,input.palette)),`${c.why}: ${evidence(look)[0]}`,`${c.colors}: ${look.palette.top} / ${look.palette.bottom} / ${look.palette.accent}`,`${c.source}: ${look.creator} · ${look.license} · ${look.sourceUrl}`])].join('\n'),[c,locale,style,garment,palette,mood,comfort,coverage,input,destination,looks]);
 const selectStyle={display:'grid',gap:5} as const;const reset=()=>setMessage('');
 async function copy(){if(!navigator.clipboard?.writeText){setMessage(c.statusCopyFailed);return;}try{await navigator.clipboard.writeText(planText);setMessage(c.statusCopied);}catch{setMessage(c.statusCopyFailed);}}
 function download(){try{const blob=new Blob([planText],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`my-korea-look-${locale}.txt`;document.body.appendChild(a);try{a.click();setMessage(c.statusDownloaded);}finally{a.remove();URL.revokeObjectURL(url);}}catch{setMessage(c.statusCopyFailed);}}
 function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(input));setMessage(c.statusSaved);}catch{setMessage(c.statusStorage);}}
 function restore(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw){setMessage(c.statusMissing);return;}let parsed:unknown;try{parsed=JSON.parse(raw);}catch{localStorage.removeItem(STORAGE_KEY);setMessage(c.statusMissing);return;}if(!validInput(parsed)){localStorage.removeItem(STORAGE_KEY);setMessage(c.statusMissing);return;}setStyle(parsed.style);setGarment(parsed.garment);setPalette(parsed.palette);setMood(parsed.mood);setComfort(parsed.comfort);setCoverage(parsed.coverage);setSeason(parsed.season);setDestination(parsed.destination);setVisitDate(parsed.visitDate??'');setColorSource(parsed.colorSource);setMessage(c.statusRestored);}catch{setMessage(c.statusStorage);}}
 function clear(){try{localStorage.removeItem(STORAGE_KEY);setMessage(c.statusCleared);}catch{setMessage(c.statusStorage);}}
 return <section style={{maxWidth:1080,margin:'0 auto',padding:'30px 20px 70px'}}><h1>{c.title}</h1><p>{c.intro}</p>{colorSource==='local-preview'?<p role="status"><strong>{c.localColorApplied}</strong></p>:null}<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12,margin:'22px 0'}}>
  <label style={selectStyle}>{c.style}<select value={style} onChange={e=>{setStyle(e.target.value as StyleId);reset();}}>{styles.map(v=><option key={v} value={v}>{label(locale,v)}</option>)}</select></label>
  <label style={selectStyle}>{c.garment}<select value={garment} onChange={e=>{setGarment(e.target.value as GarmentType);reset();}}>{garments.map(v=><option key={v} value={v}>{label(locale,v)}</option>)}</select></label>
  <label style={selectStyle}>{c.palette}<select value={palette} onChange={e=>{setPalette(e.target.value as StylePalette);setColorSource('manual');reset();}}>{palettes.map(v=><option key={v} value={v}>{label(locale,v)}</option>)}</select><Link href="/color"><small>Personal Color →</small></Link></label>
  <label style={selectStyle}>{c.mood}<select value={mood} onChange={e=>{setMood(e.target.value as StyleMood);reset();}}>{moods.map(v=><option key={v} value={v}>{label(locale,v)}</option>)}</select></label>
  <label style={selectStyle}>{c.comfort}<select value={comfort} onChange={e=>{setComfort(e.target.value as StyleComfort);reset();}}>{comforts.map(v=><option key={v} value={v}>{label(locale,v)}</option>)}</select></label>
  <label style={selectStyle}>{c.coverage}<select value={coverage} onChange={e=>{setCoverage(e.target.value as Coverage);reset();}}>{coverages.map(v=><option key={v} value={v}>{label(locale,v)}</option>)}</select></label>
  <label style={selectStyle}>{c.season}<select value={dateSeason??season} disabled={!!dateSeason} onChange={e=>{setSeason(e.target.value as StyleSeason);reset();}}>{seasons.map(v=><option key={v} value={v}>{label(locale,v)}</option>)}</select></label>
  <label style={selectStyle}>{c.destination}<select value={destination} onChange={e=>{setDestination(e.target.value as StyleDestination);reset();}}>{destinations.map(v=><option key={v} value={v}>{label(locale,v)}</option>)}</select></label>
  <label style={selectStyle}>{c.date}<input type="date" min="1900-01-01" max="2100-12-31" value={visitDate} onChange={e=>{setVisitDate(e.target.value);reset();}}/></label>
 </div><h2>{c.preview}</h2>{!complete?<p role="alert"><strong>{c.notEnough}</strong></p>:null}
 {complete?<div aria-live="polite" style={{display:'grid',gap:18}}>{looks.map((look,index)=><article key={look.id} style={{border:'1px solid currentColor',padding:18,borderRadius:12}}><h3>#{index+1} {look.title}</h3><img src={look.visualSrc} alt={look.visualAlt} width={640} height={800} loading="lazy" style={{width:'100%',height:'auto',maxWidth:420}}/><p>{c.summary(label(locale,input.mood),label(locale,look.garmentType),label(locale,input.palette))}</p><p><strong>{c.why}:</strong> {evidence(look)[0]}</p><p><strong>{c.colors}:</strong> {look.palette.top} · {look.palette.bottom} · {look.palette.accent}</p><p><small><strong>{c.source}:</strong> {look.creator} · {look.license} · <a href={look.sourceUrl} target="_blank" rel="noopener noreferrer">source ↗</a></small></p></article>)}</div>:null}
 <div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:18}}><button type="button" className="primaryButton" onClick={copy} disabled={!complete}>{c.copy}</button><button type="button" className="secondaryButton" onClick={download} disabled={!complete}>{c.download}</button><button type="button" className="secondaryButton" onClick={save}>{c.save}</button><button type="button" className="secondaryButton" onClick={restore}>{c.restore}</button><button type="button" className="secondaryButton" onClick={clear}>{c.clear}</button><Link className="secondaryButton" href="/hanbok#rental-finder">{c.rental}</Link></div><p><small>{c.freeNote}</small></p>{message?<p role="status"><strong>{message}</strong></p>:null}</section>;
}
