'use client';

import {useMemo,useState} from 'react';
import {useLocale} from 'next-intl';
import {Link} from '@/i18n/navigation';
import {CURATED_LOOKS_CATALOG,type GarmentType,type Season,type StyleId} from '@/lib/looks/catalog';
import {rankCuratedLooks,type LookPriority,type LookUndertone} from '@/lib/looks/recommend';

type Locale='en'|'zh-CN'|'ja'|'zh-TW'|'vi'|'th';
type Copy={title:string;intro:string;style:string;garment:string;tone:string;priority:string;season:string;preview:string;why:string;trade:string;location:string;source:string;sample:string;colorHelp:string;princess:string;queen:string;royal:string;chima:string;baji:string;either:string;warm:string;cool:string;neutral:string;photo:string;walking:string;balanced:string;spring:string;summer:string;autumn:string;winter:string;palette:string;request:string;route:string;copyPlan:string;copied:string;copyFailed:string;downloadPlan:string;downloaded:string;savePlan:string;saved:string;restorePlan:string;restored:string;clearPlan:string;cleared:string;noSaved:string;storageFailed:string;rentalFinder:string;freeNote:string;shopCheck:string};
const C:Record<Locale,Copy>={
 en:{title:'My Korea Look',intro:'Change the choices below and your free 3-look plan updates from a 12-look curated catalog.',style:'Palace style',garment:'Garment',tone:'Color direction',priority:'Trip priority',season:'Season',preview:'Your free 3-look plan',why:'Why it ranked here',trade:'Practical trade-off',location:'Best palace setting',source:'Visual source',sample:'See a complete sample',colorHelp:'Not sure? Try Personal Color',princess:'Princess / Prince',queen:'Queen / King',royal:'Royal ceremony',chima:'Chima / skirt',baji:'Baji / robe & pants',either:'Either',warm:'Warm',cool:'Cool',neutral:'Neutral',photo:'Photo first',walking:'Walking comfort',balanced:'Balanced',spring:'Spring',summer:'Summer',autumn:'Autumn',winter:'Winter',palette:'Palette',request:'Korean rental request',route:'Photo route',copyPlan:'Copy full 3-look plan',copied:'3-look plan copied',copyFailed:'Copy was blocked by this browser. Download the text plan instead.',downloadPlan:'Download 3-look text plan',downloaded:'3-look text plan downloaded',savePlan:'Save choices on this device',saved:'Choices saved on this device',restorePlan:'Restore saved choices',restored:'Saved choices restored',clearPlan:'Clear saved choices',cleared:'Saved choices cleared',noSaved:'No saved choices were found on this device',storageFailed:'This browser could not access device storage. Your current plan still works; copy or download it instead.',rentalFinder:'Find rental shops',freeNote:'This planning result is free and does not call a checkout or AI API. Saved choices stay on this device, and exports are created locally.',shopCheck:'Confirm exact stock, design and any extra fee with the rental shop.'},
 'zh-CN':{title:'My Korea Look',intro:'更改下面的选项，免费3套造型计划会从12套人工整理造型中实时重新排序。',style:'宫廷风格',garment:'服装类型',tone:'色彩方向',priority:'旅行重点',season:'季节',preview:'你的免费3套造型计划',why:'为什么排在这里',trade:'实际注意事项',location:'推荐宫殿场景',source:'图片来源',sample:'查看完整示例',colorHelp:'不确定？先试个人色彩',princess:'公主 / 王子',queen:'王后 / 国王',royal:'王室仪式',chima:'裙装 Chima',baji:'裤装 / 长袍 Baji',either:'都可以',warm:'暖色',cool:'冷色',neutral:'中性',photo:'拍照优先',walking:'步行舒适',balanced:'均衡',spring:'春',summer:'夏',autumn:'秋',winter:'冬',palette:'配色',request:'韩文租赁请求',route:'拍照路线',copyPlan:'复制完整3套计划',copied:'已复制3套计划',copyFailed:'浏览器阻止了复制。请改为下载文字版计划。',downloadPlan:'下载3套造型文字计划',downloaded:'已下载3套造型文字计划',savePlan:'在此设备保存选择',saved:'选择已保存在此设备',restorePlan:'恢复已保存选择',restored:'已恢复保存的选择',clearPlan:'清除已保存选择',cleared:'已清除保存的选择',noSaved:'此设备上没有找到已保存的选择',storageFailed:'此浏览器无法访问设备存储。当前计划仍可使用；请改为复制或下载。',rentalFinder:'查找韩服租赁店',freeNote:'此规划结果免费，不调用结账或 AI API。保存的选择只保留在此设备，导出文件也在本地生成。',shopCheck:'实际库存、设计和额外费用请向租赁店确认。'},
 ja:{title:'My Korea Look',intro:'選択を変えると、12種類の選定済みルックから無料3ルックプランがその場で再計算されます。',style:'宮殿スタイル',garment:'衣装',tone:'カラー方向',priority:'旅の優先',season:'季節',preview:'無料3ルックプラン',why:'この順位の理由',trade:'実用上の注意',location:'おすすめの宮殿背景',source:'画像の出典',sample:'完成サンプルを見る',colorHelp:'迷ったらパーソナルカラーへ',princess:'Princess / Prince',queen:'Queen / King',royal:'Royal ceremony',chima:'チマ / スカート',baji:'パジ / ローブ＆パンツ',either:'どちらでも',warm:'ウォーム',cool:'クール',neutral:'ニュートラル',photo:'写真優先',walking:'歩きやすさ',balanced:'バランス',spring:'春',summer:'夏',autumn:'秋',winter:'冬',palette:'配色',request:'韓国語レンタル依頼',route:'撮影ルート',copyPlan:'3ルックプランをコピー',copied:'3ルックプランをコピーしました',copyFailed:'ブラウザーでコピーが許可されませんでした。代わりにテキスト版をダウンロードしてください。',downloadPlan:'3ルックのテキスト版をダウンロード',downloaded:'3ルックのテキスト版をダウンロードしました',savePlan:'この端末に選択内容を保存',saved:'この端末に選択内容を保存しました',restorePlan:'保存した選択を復元',restored:'保存した選択を復元しました',clearPlan:'保存した選択を削除',cleared:'保存した選択を削除しました',noSaved:'この端末に保存された選択はありません',storageFailed:'このブラウザーでは端末ストレージにアクセスできません。現在のプランはそのまま使えるので、コピーまたはダウンロードしてください。',rentalFinder:'レンタル店を探す',freeNote:'このプラン結果は無料で、決済やAI APIを呼び出しません。保存内容はこの端末だけに残り、書き出しも端末内で作成されます。',shopCheck:'実際の在庫・デザイン・追加料金はレンタル店で確認してください。'},
 'zh-TW':{title:'My Korea Look',intro:'更改下方選項，免費3套造型計畫會從12套人工整理造型中即時重新排序。',style:'宮廷風格',garment:'服裝類型',tone:'色彩方向',priority:'旅遊重點',season:'季節',preview:'你的免費3套造型計畫',why:'為什麼排在這裡',trade:'實際注意事項',location:'推薦宮殿場景',source:'圖片來源',sample:'查看完整範例',colorHelp:'不確定？先試個人色彩',princess:'公主 / 王子',queen:'王后 / 國王',royal:'王室儀式',chima:'裙裝 Chima',baji:'褲裝 / 長袍 Baji',either:'都可以',warm:'暖色',cool:'冷色',neutral:'中性',photo:'拍照優先',walking:'步行舒適',balanced:'均衡',spring:'春',summer:'夏',autumn:'秋',winter:'冬',palette:'配色',request:'韓文租借需求',route:'拍照路線',copyPlan:'複製完整3套計畫',copied:'已複製3套計畫',copyFailed:'瀏覽器阻擋了複製。請改為下載文字版計畫。',downloadPlan:'下載3套造型文字計畫',downloaded:'已下載3套造型文字計畫',savePlan:'在此裝置儲存選擇',saved:'選擇已儲存在此裝置',restorePlan:'還原已儲存選擇',restored:'已還原儲存的選擇',clearPlan:'清除已儲存選擇',cleared:'已清除儲存的選擇',noSaved:'此裝置沒有找到已儲存的選擇',storageFailed:'此瀏覽器無法存取裝置儲存空間。目前計畫仍可使用；請改為複製或下載。',rentalFinder:'查找韓服租借店',freeNote:'此規劃結果免費，不呼叫結帳或 AI API。儲存的選擇只保留在此裝置，匯出檔案也在本機建立。',shopCheck:'實際庫存、設計與額外費用請向租借店確認。'},
 vi:{title:'My Korea Look',intro:'Thay đổi lựa chọn và kế hoạch 3 look miễn phí sẽ được xếp lại ngay từ 12 bộ trang phục tuyển chọn.',style:'Phong cách cung điện',garment:'Trang phục',tone:'Hướng màu',priority:'Ưu tiên chuyến đi',season:'Mùa',preview:'Kế hoạch 3 look miễn phí',why:'Vì sao xếp hạng này',trade:'Điểm cần cân nhắc',location:'Bối cảnh cung điện hợp nhất',source:'Nguồn hình ảnh',sample:'Xem mẫu hoàn chỉnh',colorHelp:'Chưa chắc? Thử Personal Color',princess:'Princess / Prince',queen:'Queen / King',royal:'Royal ceremony',chima:'Chima / váy',baji:'Baji / áo choàng & quần',either:'Bất kỳ',warm:'Ấm',cool:'Lạnh',neutral:'Trung tính',photo:'Ưu tiên ảnh',walking:'Ưu tiên đi bộ',balanced:'Cân bằng',spring:'Xuân',summer:'Hè',autumn:'Thu',winter:'Đông',palette:'Bảng màu',request:'Yêu cầu thuê bằng tiếng Hàn',route:'Tuyến chụp ảnh',copyPlan:'Sao chép kế hoạch 3 look',copied:'Đã sao chép kế hoạch 3 look',copyFailed:'Trình duyệt đã chặn sao chép. Hãy tải bản kế hoạch dạng văn bản thay thế.',downloadPlan:'Tải kế hoạch 3 look dạng văn bản',downloaded:'Đã tải kế hoạch 3 look dạng văn bản',savePlan:'Lưu lựa chọn trên thiết bị này',saved:'Đã lưu lựa chọn trên thiết bị này',restorePlan:'Khôi phục lựa chọn đã lưu',restored:'Đã khôi phục lựa chọn đã lưu',clearPlan:'Xóa lựa chọn đã lưu',cleared:'Đã xóa lựa chọn đã lưu',noSaved:'Không tìm thấy lựa chọn đã lưu trên thiết bị này',storageFailed:'Trình duyệt này không thể truy cập bộ nhớ thiết bị. Kế hoạch hiện tại vẫn dùng được; hãy sao chép hoặc tải xuống thay thế.',rentalFinder:'Tìm cửa hàng thuê',freeNote:'Kết quả lập kế hoạch này miễn phí và không gọi thanh toán hoặc AI API. Lựa chọn đã lưu chỉ nằm trên thiết bị này và tệp xuất được tạo cục bộ.',shopCheck:'Hãy xác nhận mẫu thực tế, tồn kho và mọi phụ phí với cửa hàng cho thuê.'},
 th:{title:'My Korea Look',intro:'เปลี่ยนตัวเลือกแล้วแผนฟรี 3 ลุคจะจัดอันดับใหม่ทันทีจากลุคที่คัดสรรไว้ 12 แบบ',style:'สไตล์พระราชวัง',garment:'ชุด',tone:'โทนสี',priority:'ความสำคัญ',season:'ฤดู',preview:'แผนฟรี 3 ลุค',why:'เหตุผลของอันดับนี้',trade:'ข้อควรคำนึง',location:'ฉากพระราชวังที่เหมาะ',source:'แหล่งที่มาของภาพ',sample:'ดูตัวอย่างฉบับเต็ม',colorHelp:'ไม่แน่ใจ? ลอง Personal Color',princess:'Princess / Prince',queen:'Queen / King',royal:'Royal ceremony',chima:'Chima / กระโปรง',baji:'Baji / เสื้อคลุมและกางเกง',either:'แบบใดก็ได้',warm:'โทนอุ่น',cool:'โทนเย็น',neutral:'กลาง',photo:'เน้นถ่ายรูป',walking:'เน้นเดินสบาย',balanced:'สมดุล',spring:'ใบไม้ผลิ',summer:'ร้อน',autumn:'ใบไม้ร่วง',winter:'หนาว',palette:'พาเลตสี',request:'คำขอเช่าภาษาเกาหลี',route:'เส้นทางถ่ายรูป',copyPlan:'คัดลอกแผน 3 ลุค',copied:'คัดลอกแผน 3 ลุคแล้ว',copyFailed:'เบราว์เซอร์บล็อกการคัดลอก โปรดดาวน์โหลดแผนแบบข้อความแทน',downloadPlan:'ดาวน์โหลดแผน 3 ลุคแบบข้อความ',downloaded:'ดาวน์โหลดแผน 3 ลุคแบบข้อความแล้ว',savePlan:'บันทึกตัวเลือกในอุปกรณ์นี้',saved:'บันทึกตัวเลือกในอุปกรณ์นี้แล้ว',restorePlan:'กู้คืนตัวเลือกที่บันทึกไว้',restored:'กู้คืนตัวเลือกที่บันทึกไว้แล้ว',clearPlan:'ล้างตัวเลือกที่บันทึกไว้',cleared:'ล้างตัวเลือกที่บันทึกไว้แล้ว',noSaved:'ไม่พบตัวเลือกที่บันทึกไว้ในอุปกรณ์นี้',storageFailed:'เบราว์เซอร์นี้ไม่สามารถเข้าถึงพื้นที่จัดเก็บของอุปกรณ์ได้ แผนปัจจุบันยังใช้ได้ โปรดคัดลอกหรือดาวน์โหลดแทน',rentalFinder:'ค้นหาร้านเช่า',freeNote:'ผลการวางแผนนี้ฟรีและไม่เรียกการชำระเงินหรือ AI API ตัวเลือกที่บันทึกจะอยู่ในอุปกรณ์นี้เท่านั้น และไฟล์ส่งออกสร้างในอุปกรณ์',shopCheck:'โปรดยืนยันสต็อก แบบจริง และค่าใช้จ่ายเพิ่มเติมกับร้านเช่า'}
};
const RENTAL_CONFIRMATION_KO='※ 동일한 색상/디자인 재고와 추가 요금이 있는지 먼저 확인 부탁드립니다.';
const STORAGE_KEY='kc-my-korea-look-plan-v1';
type SavedPlan={version:1;style:StyleId;garment:GarmentType;tone:LookUndertone;priority:LookPriority;season:Season};
const STYLES:StyleId[]=['princess-prince','queen-king','royal'];
const GARMENTS:GarmentType[]=['chima','baji','either'];
const TONES:LookUndertone[]=['warm','cool','neutral'];
const PRIORITIES:LookPriority[]=['photo','walking','balanced'];
const SEASONS:Season[]=['spring','summer','autumn','winter'];
function isSavedPlan(value:unknown):value is SavedPlan{
 if(!value||typeof value!=='object')return false;
 const plan=value as Partial<SavedPlan>;
 return plan.version===1&&STYLES.includes(plan.style as StyleId)&&GARMENTS.includes(plan.garment as GarmentType)&&TONES.includes(plan.tone as LookUndertone)&&PRIORITIES.includes(plan.priority as LookPriority)&&SEASONS.includes(plan.season as Season);
}

export function StyleConsultationV2(){
 const locale=useLocale();const l=(locale in C?locale:'en') as Locale,c=C[l];
 const [style,setStyle]=useState<StyleId>('princess-prince'),[garment,setGarment]=useState<GarmentType>('either'),[tone,setTone]=useState<LookUndertone>('neutral'),[priority,setPriority]=useState<LookPriority>('balanced'),[season,setSeason]=useState<Season>('spring'),[message,setMessage]=useState('');
 const ranked=useMemo(()=>rankCuratedLooks({style,garment,tone,priority,season}),[style,garment,tone,priority,season]);
 const topLooks=(ranked.length?ranked.map(item=>item.look):CURATED_LOOKS_CATALOG).slice(0,3);
 const planText=useMemo(()=>topLooks.map((look,index)=>[
  `#${index+1} ${look.title}`,
  `${c.palette}: ${look.palette.top} / ${look.palette.bottom} / ${look.palette.accent}`,
  `${c.why}:`,...look.reasons.map(reason=>`- ${reason}`),
  `${c.location}: ${look.recommendedLocation.name} · ${look.recommendedLocation.koreanName}`,
  `${c.trade}: ${look.tradeOff}`,
  `${c.source}: ${look.creator} · ${look.license} · ${look.sourceUrl}`,
  '',look.rentalShopCard.hangulTitle,look.rentalShopCard.hangulStaffNote,RENTAL_CONFIRMATION_KO,'',
  `${c.route}:`,...look.photoRoute.map(stop=>`${stop.order}. ${stop.spotName} (${stop.koreanName}) · ${stop.bestTime} · ${stop.photoTip}`)
 ].join('\n')).join('\n\n---\n\n'),[topLooks,c]);
 async function copyPlan(){
  if(!navigator.clipboard?.writeText){setMessage(c.copyFailed);return;}
  try{await navigator.clipboard.writeText(planText);setMessage(c.copied);}catch{setMessage(c.copyFailed);}
 }
 function downloadPlan(){
  try{
   const blob=new Blob([planText],{type:'text/plain;charset=utf-8'});
   const objectUrl=URL.createObjectURL(blob);
   const anchor=document.createElement('a');
   anchor.href=objectUrl;anchor.download=`my-korea-look-${l}.txt`;anchor.hidden=true;
   document.body.appendChild(anchor);
   try{anchor.click();setMessage(c.downloaded);}finally{anchor.remove();URL.revokeObjectURL(objectUrl);}
  }catch{setMessage(c.copyFailed);}
 }
 function savePlan(){try{const payload:SavedPlan={version:1,style,garment,tone,priority,season};localStorage.setItem(STORAGE_KEY,JSON.stringify(payload));setMessage(c.saved);}catch{setMessage(c.storageFailed);}}
 function restorePlan(){
  try{
   const raw=localStorage.getItem(STORAGE_KEY);
   if(!raw){setMessage(c.noSaved);return;}
   let parsed:unknown;
   try{parsed=JSON.parse(raw);}catch{localStorage.removeItem(STORAGE_KEY);setMessage(c.noSaved);return;}
   if(!isSavedPlan(parsed)){localStorage.removeItem(STORAGE_KEY);setMessage(c.noSaved);return;}
   setStyle(parsed.style);setGarment(parsed.garment);setTone(parsed.tone);setPriority(parsed.priority);setSeason(parsed.season);setMessage(c.restored);
  }catch{setMessage(c.storageFailed);}
 }
 function clearPlan(){try{localStorage.removeItem(STORAGE_KEY);setMessage(c.cleared);}catch{setMessage(c.storageFailed);}}
 const selectStyle={display:'grid',gap:5} as const;
 return <section style={{maxWidth:1050,margin:'0 auto',padding:'30px 20px 70px'}}><h1>{c.title}</h1><p>{c.intro}</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12,margin:'22px 0'}}><label style={selectStyle}>{c.style}<select value={style} onChange={e=>{setStyle(e.target.value as StyleId);setMessage('');}}><option value="princess-prince">{c.princess}</option><option value="queen-king">{c.queen}</option><option value="royal">{c.royal}</option></select></label><label style={selectStyle}>{c.garment}<select value={garment} onChange={e=>{setGarment(e.target.value as GarmentType);setMessage('');}}><option value="either">{c.either}</option><option value="chima">{c.chima}</option><option value="baji">{c.baji}</option></select></label><label style={selectStyle}>{c.tone}<select value={tone} onChange={e=>{setTone(e.target.value as LookUndertone);setMessage('');}}><option value="warm">{c.warm}</option><option value="cool">{c.cool}</option><option value="neutral">{c.neutral}</option></select><Link href="/color"><small>{c.colorHelp} →</small></Link></label><label style={selectStyle}>{c.priority}<select value={priority} onChange={e=>{setPriority(e.target.value as LookPriority);setMessage('');}}><option value="photo">{c.photo}</option><option value="walking">{c.walking}</option><option value="balanced">{c.balanced}</option></select></label><label style={selectStyle}>{c.season}<select value={season} onChange={e=>{setSeason(e.target.value as Season);setMessage('');}}><option value="spring">{c.spring}</option><option value="summer">{c.summer}</option><option value="autumn">{c.autumn}</option><option value="winter">{c.winter}</option></select></label></div>
 <h2>{c.preview}</h2><div aria-live="polite" style={{display:'grid',gap:18}}>{topLooks.map((look,index)=><article key={look.id} style={{border:'1px solid currentColor',padding:18,borderRadius:12}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:20}}><div><img src={look.src} alt={look.alt} referrerPolicy="no-referrer" style={{width:'100%',aspectRatio:'4/5',objectFit:'cover',objectPosition:look.cropPosition}}/><p><small><strong>{c.source}:</strong> {look.creator} · {look.license} · <a href={look.sourceUrl} target="_blank" rel="noopener noreferrer">{look.kind==='style-illustration'?'Style illustration':'Reference photo'} ↗</a></small></p></div><div><p><strong>#{index+1}</strong></p><h3>{look.title}</h3><p>{look.description}</p><p><strong>{c.palette}:</strong><br/>{look.palette.top}<br/>{look.palette.bottom}<br/>{look.palette.accent}</p><h4>{c.why}</h4><ul>{look.reasons.map(x=><li key={x}>{x}</li>)}</ul><p><strong>{c.trade}:</strong> {look.tradeOff}</p><p><strong>{c.location}:</strong> {look.recommendedLocation.name} · {look.recommendedLocation.koreanName}</p></div></div><details style={{marginTop:14}}><summary><strong>{c.request}</strong></summary><div lang="ko" style={{whiteSpace:'pre-line',padding:12,marginTop:8,background:'rgba(0,0,0,.04)',borderRadius:8}}><strong>{look.rentalShopCard.hangulTitle}</strong><br/><br/>{look.rentalShopCard.hangulStaffNote}<br/><br/>{RENTAL_CONFIRMATION_KO}</div><p><small>{c.shopCheck}</small></p></details><details style={{marginTop:10}}><summary><strong>{c.route}</strong></summary><ol>{look.photoRoute.map(stop=><li key={`${look.id}-${stop.order}`}><strong>{stop.spotName} · {stop.koreanName}</strong><br/><small>{stop.bestTime}</small><p>{stop.photoTip}</p></li>)}</ol></details></article>)}</div>
 <div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:18}}><button className="primaryButton" type="button" onClick={copyPlan}>{c.copyPlan}</button><button className="secondaryButton" type="button" onClick={downloadPlan}>{c.downloadPlan}</button><button className="secondaryButton" type="button" onClick={savePlan}>{c.savePlan}</button><button className="secondaryButton" type="button" onClick={restorePlan}>{c.restorePlan}</button><button className="secondaryButton" type="button" onClick={clearPlan}>{c.clearPlan}</button><Link className="secondaryButton" href="/hanbok#rental-finder">{c.rentalFinder}</Link><Link className="secondaryButton" href="/style/sample/palace-elegance">{c.sample}</Link></div><p><small>{c.freeNote}</small></p>{message?<p role="status"><strong>{message}</strong></p>:null}</section>;
}
