'use client';

import {useMemo,useState} from 'react';
import {useLocale} from 'next-intl';
import {Link} from '@/i18n/navigation';
import type {Coverage,GarmentType,StyleId} from '@/lib/looks/catalog';
import {rankStyleInputV1,seasonFromVisitDate,type StyleComfort,type StyleDestination,type StyleInputV1,type StyleMood,type StylePalette,type StyleSeason} from '@/lib/looks/style-input-v1';

type Locale=StyleInputV1['locale'];
type Copy={title:string;intro:string;style:string;garment:string;palette:string;mood:string;comfort:string;coverage:string;season:string;date:string;destination:string;preview:string;why:string;colors:string;accessories:string;alternate:string;trade:string;location:string;source:string;route:string;request:string;save:string;restore:string;clear:string;copy:string;download:string;notEnough:string;statusSaved:string;statusRestored:string;statusCleared:string;statusMissing:string;statusStorage:string;statusCopied:string;statusCopyFailed:string;statusDownloaded:string;freeNote:string;rental:string};
const C:Record<Locale,Copy>={
 en:{title:'My Korea Look',intro:'Set your trip context. Three verified looks are ranked locally from the curated catalog.',style:'Style family',garment:'Garment',palette:'Palette',mood:'Mood',comfort:'Comfort',coverage:'Coverage',season:'Season',date:'Visit date (optional)',destination:'Destination',preview:'Your 3-look plan',why:'Why this matches your choices',colors:'Color relationship',accessories:'Accessories',alternate:'Alternative colorway',trade:'Trade-off',location:'Curated setting',source:'Visual source',route:'Photo route',request:'Korean rental request',save:'Save choices',restore:'Restore choices',clear:'Clear saved',copy:'Copy plan',download:'Download plan',notEnough:'This combination has fewer than three verified looks. Change garment or coverage.',statusSaved:'Choices saved on this device.',statusRestored:'Saved choices restored.',statusCleared:'Saved choices cleared.',statusMissing:'No valid saved choices found.',statusStorage:'Device storage is unavailable. The current plan still works; copy or download it.',statusCopied:'Plan copied.',statusCopyFailed:'Copy was blocked. Download the text plan instead.',statusDownloaded:'Text plan downloaded.',freeNote:'Free deterministic preview: no checkout, AI call or remote photo processing.',rental:'Find rental shops'},
 'zh-CN':{title:'My Korea Look',intro:'设置行程条件，系统会在本地从已核验目录中确定性排序3套造型。',style:'风格',garment:'服装',palette:'配色',mood:'氛围',comfort:'舒适度',coverage:'遮盖度',season:'季节',date:'到访日期（可选）',destination:'目的地',preview:'你的3套造型',why:'为什么符合你的选择',colors:'色彩关系',accessories:'配饰',alternate:'替代配色',trade:'取舍',location:'精选场景',source:'图片来源',route:'拍照路线',request:'韩文租赁请求',save:'保存选择',restore:'恢复选择',clear:'清除保存',copy:'复制计划',download:'下载计划',notEnough:'此组合不足3套已核验造型，请调整服装或遮盖度。',statusSaved:'已保存在此设备。',statusRestored:'已恢复保存选择。',statusCleared:'已清除保存选择。',statusMissing:'没有有效的保存选择。',statusStorage:'无法访问设备存储。当前计划仍可用，请复制或下载。',statusCopied:'已复制计划。',statusCopyFailed:'复制被阻止，请下载文字计划。',statusDownloaded:'已下载文字计划。',freeNote:'免费确定性预览：无结账、无AI调用、无远程照片处理。',rental:'查找租赁店'},
 ja:{title:'My Korea Look',intro:'旅行条件を設定すると、検証済みカタログから端末内で3ルックを決定的に順位付けします。',style:'スタイル',garment:'衣装',palette:'配色',mood:'ムード',comfort:'快適さ',coverage:'カバー範囲',season:'季節',date:'訪問日（任意）',destination:'目的地',preview:'3ルックプラン',why:'選択に合う理由',colors:'色の組み合わせ',accessories:'小物',alternate:'代替カラー',trade:'注意点',location:'選定ロケーション',source:'画像出典',route:'撮影ルート',request:'韓国語レンタル依頼',save:'選択を保存',restore:'復元',clear:'保存を削除',copy:'コピー',download:'ダウンロード',notEnough:'この条件では検証済みルックが3件未満です。衣装またはカバー範囲を変更してください。',statusSaved:'この端末に保存しました。',statusRestored:'保存した選択を復元しました。',statusCleared:'保存を削除しました。',statusMissing:'有効な保存データがありません。',statusStorage:'端末ストレージを利用できません。現在のプランはコピーまたはダウンロードできます。',statusCopied:'コピーしました。',statusCopyFailed:'コピーがブロックされました。テキスト版をダウンロードしてください。',statusDownloaded:'テキスト版をダウンロードしました。',freeNote:'無料の決定的プレビューです。決済・AI呼び出し・写真の外部処理はありません。',rental:'レンタル店を探す'},
 'zh-TW':{title:'My Korea Look',intro:'設定旅程條件後，系統會在裝置端從已驗證目錄確定性排序3套造型。',style:'風格',garment:'服裝',palette:'配色',mood:'氛圍',comfort:'舒適度',coverage:'遮蓋度',season:'季節',date:'到訪日期（選填）',destination:'目的地',preview:'你的3套造型',why:'符合你選擇的原因',colors:'色彩關係',accessories:'配件',alternate:'替代配色',trade:'取捨',location:'精選場景',source:'圖片來源',route:'拍照路線',request:'韓文租借需求',save:'儲存選擇',restore:'還原',clear:'清除儲存',copy:'複製',download:'下載',notEnough:'此組合少於3套已驗證造型，請調整服裝或遮蓋度。',statusSaved:'已儲存在此裝置。',statusRestored:'已還原儲存選擇。',statusCleared:'已清除儲存選擇。',statusMissing:'找不到有效的儲存選擇。',statusStorage:'無法存取裝置儲存空間。目前計畫仍可複製或下載。',statusCopied:'已複製計畫。',statusCopyFailed:'複製被阻擋，請下載文字計畫。',statusDownloaded:'已下載文字計畫。',freeNote:'免費確定性預覽：無結帳、無AI呼叫、無遠端照片處理。',rental:'尋找租借店'},
 vi:{title:'My Korea Look',intro:'Đặt bối cảnh chuyến đi để xếp hạng xác định 3 look đã xác minh ngay trên thiết bị.',style:'Phong cách',garment:'Trang phục',palette:'Bảng màu',mood:'Không khí',comfort:'Độ thoải mái',coverage:'Độ che phủ',season:'Mùa',date:'Ngày ghé thăm (tùy chọn)',destination:'Điểm đến',preview:'Kế hoạch 3 look',why:'Vì sao phù hợp lựa chọn của bạn',colors:'Quan hệ màu sắc',accessories:'Phụ kiện',alternate:'Phối màu thay thế',trade:'Điểm đánh đổi',location:'Bối cảnh chọn lọc',source:'Nguồn hình ảnh',route:'Tuyến chụp ảnh',request:'Yêu cầu thuê bằng tiếng Hàn',save:'Lưu lựa chọn',restore:'Khôi phục',clear:'Xóa đã lưu',copy:'Sao chép',download:'Tải xuống',notEnough:'Tổ hợp này có ít hơn 3 look đã xác minh. Hãy đổi trang phục hoặc độ che phủ.',statusSaved:'Đã lưu trên thiết bị này.',statusRestored:'Đã khôi phục lựa chọn.',statusCleared:'Đã xóa lựa chọn.',statusMissing:'Không tìm thấy lựa chọn hợp lệ đã lưu.',statusStorage:'Không thể truy cập bộ nhớ thiết bị. Kế hoạch vẫn có thể sao chép hoặc tải xuống.',statusCopied:'Đã sao chép kế hoạch.',statusCopyFailed:'Sao chép bị chặn. Hãy tải bản văn bản.',statusDownloaded:'Đã tải bản văn bản.',freeNote:'Bản xem trước miễn phí và xác định: không thanh toán, không AI, không xử lý ảnh từ xa.',rental:'Tìm cửa hàng thuê'},
 th:{title:'My Korea Look',intro:'ตั้งค่าบริบททริปเพื่อจัดอันดับ 3 ลุคที่ตรวจสอบแล้วแบบกำหนดแน่นอนบนอุปกรณ์',style:'สไตล์',garment:'ชุด',palette:'พาเลตสี',mood:'อารมณ์',comfort:'ความสบาย',coverage:'การปกปิด',season:'ฤดู',date:'วันที่ไป (ไม่บังคับ)',destination:'จุดหมาย',preview:'แผน 3 ลุค',why:'เหตุผลที่ตรงกับตัวเลือกของคุณ',colors:'ความสัมพันธ์ของสี',accessories:'เครื่องประดับ',alternate:'สีทางเลือก',trade:'ข้อแลกเปลี่ยน',location:'สถานที่คัดสรร',source:'แหล่งภาพ',route:'เส้นทางถ่ายภาพ',request:'คำขอเช่าภาษาเกาหลี',save:'บันทึกตัวเลือก',restore:'กู้คืน',clear:'ล้างที่บันทึก',copy:'คัดลอก',download:'ดาวน์โหลด',notEnough:'ตัวเลือกนี้มีลุคที่ตรวจสอบแล้วน้อยกว่า 3 แบบ กรุณาเปลี่ยนชุดหรือระดับการปกปิด',statusSaved:'บันทึกในอุปกรณ์นี้แล้ว',statusRestored:'กู้คืนตัวเลือกแล้ว',statusCleared:'ล้างตัวเลือกแล้ว',statusMissing:'ไม่พบตัวเลือกที่บันทึกไว้อย่างถูกต้อง',statusStorage:'เข้าถึงพื้นที่จัดเก็บไม่ได้ แผนยังคัดลอกหรือดาวน์โหลดได้',statusCopied:'คัดลอกแผนแล้ว',statusCopyFailed:'การคัดลอกถูกบล็อก โปรดดาวน์โหลดแผนข้อความ',statusDownloaded:'ดาวน์โหลดแผนข้อความแล้ว',freeNote:'พรีวิวฟรีแบบกำหนดแน่นอน: ไม่มีการชำระเงิน ไม่มี AI และไม่มีการประมวลผลรูปจากระยะไกล',rental:'ค้นหาร้านเช่า'}
};

const STORAGE_KEY='kc-my-korea-look-plan-v2';
const locales:Locale[]=['en','zh-CN','ja','zh-TW','vi','th'];
const styles:StyleId[]=['princess-prince','queen-king','royal'];
const garments:GarmentType[]=['either','chima','baji'];
const palettes:StylePalette[]=['jadeIvory','roseNavy','moonBlue','suggest'];
const moods:StyleMood[]=['elegant','royal','romantic','minimal','kdrama'];
const comforts:StyleComfort[]=['walking','balanced','photoFirst'];
const coverages:Coverage[]=['standard','more-coverage'];
const seasons:StyleSeason[]=['springAutumn','summer','winter'];
const destinations:StyleDestination[]=['gyeongbokgung','bukchon','seochon'];
const LABELS:Record<string,string>={'princess-prince':'Princess / Prince','queen-king':'Queen / King',royal:'Royal',either:'Either',chima:'Chima',baji:'Baji',jadeIvory:'Jade & Ivory',roseNavy:'Rose & Navy',moonBlue:'Moon Blue',suggest:'Suggest for me',elegant:'Elegant',romantic:'Romantic',minimal:'Minimal',kdrama:'K-drama',walking:'Walking first',balanced:'Balanced',photoFirst:'Photo first',standard:'Standard','more-coverage':'More coverage',springAutumn:'Spring / Autumn',summer:'Summer',winter:'Winter',gyeongbokgung:'Gyeongbokgung',bukchon:'Bukchon',seochon:'Seochon'};
const label=(value:string)=>LABELS[value]??value;

function validInput(value:unknown):value is StyleInputV1{
 if(!value||typeof value!=='object')return false;
 const x=value as Partial<StyleInputV1>;
 return x.version===1&&locales.includes(x.locale as Locale)&&styles.includes(x.style as StyleId)&&garments.includes(x.garment as GarmentType)&&palettes.includes(x.palette as StylePalette)&&moods.includes(x.mood as StyleMood)&&comforts.includes(x.comfort as StyleComfort)&&coverages.includes(x.coverage as Coverage)&&seasons.includes(x.season as StyleSeason)&&destinations.includes(x.destination as StyleDestination)&&x.colorSource==='manual'&&(x.visitDate===undefined||seasonFromVisitDate(x.visitDate)!==null);
}

export function StyleConsultationV4(){
 const rawLocale=useLocale(); const locale=(locales.includes(rawLocale as Locale)?rawLocale:'en') as Locale; const c=C[locale];
 const [style,setStyle]=useState<StyleId>('princess-prince'); const [garment,setGarment]=useState<GarmentType>('either'); const [palette,setPalette]=useState<StylePalette>('jadeIvory'); const [mood,setMood]=useState<StyleMood>('romantic'); const [comfort,setComfort]=useState<StyleComfort>('balanced'); const [coverage,setCoverage]=useState<Coverage>('standard'); const [season,setSeason]=useState<StyleSeason>('springAutumn'); const [destination,setDestination]=useState<StyleDestination>('gyeongbokgung'); const [visitDate,setVisitDate]=useState(''); const [message,setMessage]=useState('');
 const dateSeason=visitDate?seasonFromVisitDate(visitDate):null;
 const input=useMemo<StyleInputV1>(()=>({version:1,locale,style,garment,palette,mood,comfort,coverage,season:dateSeason??season,destination,...(visitDate&&dateSeason?{visitDate}:{}),colorSource:'manual'}),[locale,style,garment,palette,mood,comfort,coverage,season,destination,visitDate,dateSeason]);
 const ranked=useMemo(()=>rankStyleInputV1(input),[input]); const looks=ranked.slice(0,3).map(x=>x.look); const complete=looks.length===3;
 const altFor=(lookId:string,undertone:string)=>ranked.map(x=>x.look).find(x=>x.id!==lookId&&x.palette.undertone!==undertone)??ranked.map(x=>x.look).find(x=>x.id!==lookId);
 const evidence=(look:(typeof looks)[number])=>[
  `${c.style}: ${label(input.style)} → ${label(look.styleId)}`,
  `${c.palette}: ${label(input.palette)} → ${look.palette.undertone} · ${look.palette.description}`,
  `${c.comfort}: ${label(input.comfort)} · ${c.season}: ${label(input.season)} · ${c.destination}: ${label(input.destination)} → ${look.walkingSuitability} · ${look.recommendedLocation.name}`
 ] as const;
 const planText=useMemo(()=>['My Korea Look',`${c.style}: ${label(style)}`,`${c.garment}: ${label(garment)}`,`${c.palette}: ${label(palette)}`,`${c.mood}: ${label(mood)}`,`${c.comfort}: ${label(comfort)}`,`${c.coverage}: ${label(coverage)}`,`${c.season}: ${label(input.season)}`,`${c.destination}: ${label(destination)}`,...(input.visitDate?[`${c.date}: ${input.visitDate}`]:[]),'',...looks.flatMap((look,index)=>{const alt=altFor(look.id,look.palette.undertone);return [`#${index+1} ${look.title}`,look.description,`${c.why}:`,...evidence(look).map(x=>`- ${x}`),`${c.colors}: ${look.palette.top} / ${look.palette.bottom} / ${look.palette.accent}`,`${c.accessories}: ${look.accessoryIds.join(', ')}`,`${c.alternate}: ${alt?`${alt.title} — ${alt.palette.top} / ${alt.palette.bottom} / ${alt.palette.accent}`:'-'}`,`${c.location}: ${look.recommendedLocation.name} · ${look.recommendedLocation.koreanName}`,`${c.trade}: ${look.tradeOff}`,`${c.source}: ${look.creator} · ${look.license} · ${look.sourceUrl}`,`${c.request}: ${look.rentalShopCard.hangulTitle} / ${look.rentalShopCard.hangulStaffNote}`,`${c.route}: ${look.photoRoute.map(stop=>`${stop.order}. ${stop.spotName}`).join(' → ')}`,''];})].join('\n'),[c,style,garment,palette,mood,comfort,coverage,input,destination,looks,ranked]);
 const selectStyle={display:'grid',gap:5} as const; const reset=()=>setMessage('');
 async function copy(){if(!navigator.clipboard?.writeText){setMessage(c.statusCopyFailed);return;}try{await navigator.clipboard.writeText(planText);setMessage(c.statusCopied);}catch{setMessage(c.statusCopyFailed);}}
 function download(){try{const blob=new Blob([planText],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`my-korea-look-${locale}.txt`;document.body.appendChild(a);try{a.click();setMessage(c.statusDownloaded);}finally{a.remove();URL.revokeObjectURL(url);}}catch{setMessage(c.statusCopyFailed);}}
 function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(input));setMessage(c.statusSaved);}catch{setMessage(c.statusStorage);}}
 function restore(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw){setMessage(c.statusMissing);return;}let parsed:unknown;try{parsed=JSON.parse(raw);}catch{localStorage.removeItem(STORAGE_KEY);setMessage(c.statusMissing);return;}if(!validInput(parsed)){localStorage.removeItem(STORAGE_KEY);setMessage(c.statusMissing);return;}setStyle(parsed.style);setGarment(parsed.garment);setPalette(parsed.palette);setMood(parsed.mood);setComfort(parsed.comfort);setCoverage(parsed.coverage);setSeason(parsed.season);setDestination(parsed.destination);setVisitDate(parsed.visitDate??'');setMessage(c.statusRestored);}catch{setMessage(c.statusStorage);}}
 function clear(){try{localStorage.removeItem(STORAGE_KEY);setMessage(c.statusCleared);}catch{setMessage(c.statusStorage);}}
 return <section style={{maxWidth:1080,margin:'0 auto',padding:'30px 20px 70px'}}><h1>{c.title}</h1><p>{c.intro}</p>
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12,margin:'22px 0'}}>
   <label style={selectStyle}>{c.style}<select value={style} onChange={e=>{setStyle(e.target.value as StyleId);reset();}}>{styles.map(v=><option key={v}>{v}</option>)}</select></label>
   <label style={selectStyle}>{c.garment}<select value={garment} onChange={e=>{setGarment(e.target.value as GarmentType);reset();}}>{garments.map(v=><option key={v}>{v}</option>)}</select></label>
   <label style={selectStyle}>{c.palette}<select value={palette} onChange={e=>{setPalette(e.target.value as StylePalette);reset();}}>{palettes.map(v=><option key={v}>{label(v)}</option>)}</select><Link href="/color"><small>Personal Color →</small></Link></label>
   <label style={selectStyle}>{c.mood}<select value={mood} onChange={e=>{setMood(e.target.value as StyleMood);reset();}}>{moods.map(v=><option key={v}>{label(v)}</option>)}</select></label>
   <label style={selectStyle}>{c.comfort}<select value={comfort} onChange={e=>{setComfort(e.target.value as StyleComfort);reset();}}>{comforts.map(v=><option key={v}>{label(v)}</option>)}</select></label>
   <label style={selectStyle}>{c.coverage}<select value={coverage} onChange={e=>{setCoverage(e.target.value as Coverage);reset();}}>{coverages.map(v=><option key={v}>{label(v)}</option>)}</select></label>
   <label style={selectStyle}>{c.season}<select value={dateSeason??season} disabled={!!dateSeason} onChange={e=>{setSeason(e.target.value as StyleSeason);reset();}}>{seasons.map(v=><option key={v}>{label(v)}</option>)}</select></label>
   <label style={selectStyle}>{c.destination}<select value={destination} onChange={e=>{setDestination(e.target.value as StyleDestination);reset();}}>{destinations.map(v=><option key={v}>{label(v)}</option>)}</select></label>
   <label style={selectStyle}>{c.date}<input type="date" min="1900-01-01" max="2100-12-31" value={visitDate} onChange={e=>{setVisitDate(e.target.value);reset();}}/></label>
  </div><h2>{c.preview}</h2>{!complete?<p role="alert"><strong>{c.notEnough}</strong></p>:null}
  {complete?<div aria-live="polite" style={{display:'grid',gap:18}}>{looks.map((look,index)=>{const alt=altFor(look.id,look.palette.undertone);return <article key={look.id} style={{border:'1px solid currentColor',padding:18,borderRadius:12}}><h3>#{index+1} {look.title}</h3><img src={look.visualSrc} alt={look.visualAlt} width={640} height={800} loading="lazy" style={{width:'100%',height:'auto',maxWidth:420}}/><p>{look.description}</p><h4>{c.why}</h4><ol>{evidence(look).map((reason,i)=><li key={`${look.id}-reason-${i}`}>{reason}</li>)}</ol><p><strong>{c.colors}:</strong> {look.palette.top} · {look.palette.bottom} · {look.palette.accent}</p><p><strong>{c.accessories}:</strong> {look.accessoryIds.join(' · ')}</p>{alt?<p><strong>{c.alternate}:</strong> {alt.title} — {alt.palette.top} · {alt.palette.bottom} · {alt.palette.accent}</p>:null}<p><strong>{c.location}:</strong> {look.recommendedLocation.name} · {look.recommendedLocation.koreanName}</p><p><strong>{c.trade}:</strong> {look.tradeOff}</p><p><small><strong>{c.source}:</strong> {look.creator} · {look.license} · <a href={look.sourceUrl} target="_blank" rel="noopener noreferrer">source ↗</a></small></p><details><summary><strong>{c.request}</strong></summary><div lang="ko">{look.rentalShopCard.hangulTitle}<br/>{look.rentalShopCard.hangulStaffNote}<br/>※ 동일한 색상/디자인 재고와 추가 요금이 있는지 먼저 확인 부탁드립니다.</div></details><details><summary><strong>{c.route}</strong></summary><ol>{look.photoRoute.map(stop=><li key={`${look.id}-${stop.order}`}><strong>{stop.spotName} · {stop.koreanName}</strong> — {stop.bestTime}<br/><small>{stop.photoTip}</small></li>)}</ol></details></article>;})}</div>:null}
  <div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:18}}><button type="button" className="primaryButton" onClick={copy} disabled={!complete}>{c.copy}</button><button type="button" className="secondaryButton" onClick={download} disabled={!complete}>{c.download}</button><button type="button" className="secondaryButton" onClick={save}>{c.save}</button><button type="button" className="secondaryButton" onClick={restore}>{c.restore}</button><button type="button" className="secondaryButton" onClick={clear}>{c.clear}</button><Link className="secondaryButton" href="/hanbok#rental-finder">{c.rental}</Link></div><p><small>{c.freeNote}</small></p>{message?<p role="status"><strong>{message}</strong></p>:null}</section>;
}
