'use client';

import {useMemo,useState} from 'react';
import {useLocale} from 'next-intl';
import {Link} from '@/i18n/navigation';
import {CURATED_LOOKS_CATALOG,type GarmentType,type Season,type StyleId} from '@/lib/looks/catalog';
import {rankCuratedLooks,type LookPriority,type LookUndertone} from '@/lib/looks/recommend';

type Locale='en'|'zh-CN'|'ja'|'zh-TW'|'vi'|'th';
type Copy={title:string;intro:string;style:string;garment:string;tone:string;priority:string;season:string;preview:string;why:string;trade:string;location:string;sample:string;buy:string;disabled:string;colorHelp:string;princess:string;queen:string;royal:string;chima:string;baji:string;either:string;warm:string;cool:string;neutral:string;photo:string;walking:string;balanced:string;spring:string;summer:string;autumn:string;winter:string};
const C:Record<Locale,Copy>={
 en:{title:'My Korea Look',intro:'Change the choices below and your free recommendation updates from a 12-look curated catalog.',style:'Palace style',garment:'Garment',tone:'Color direction',priority:'Trip priority',season:'Season',preview:'Your free matched look',why:'Why it ranked first',trade:'Practical trade-off',location:'Best palace setting',sample:'See a complete sample',buy:'Get the 3-look stylebook — $12 one-time',disabled:'Checkout is still in pre-launch mode. Free matching and samples remain available.',colorHelp:'Not sure? Try Personal Color',princess:'Princess / Prince',queen:'Queen / King',royal:'Royal ceremony',chima:'Chima / skirt',baji:'Baji / robe & pants',either:'Either',warm:'Warm',cool:'Cool',neutral:'Neutral',photo:'Photo first',walking:'Walking comfort',balanced:'Balanced',spring:'Spring',summer:'Summer',autumn:'Autumn',winter:'Winter'},
 'zh-CN':{title:'My Korea Look',intro:'更改下面的选项，系统会从12套人工整理的造型中实时重新排序免费推荐。',style:'宫廷风格',garment:'服装类型',tone:'色彩方向',priority:'旅行重点',season:'季节',preview:'你的免费推荐',why:'为什么排第一',trade:'实际注意事项',location:'推荐宫殿场景',sample:'查看完整示例',buy:'获取3套造型册 — 一次性12美元',disabled:'结账仍处于上线前模式。免费匹配与示例可正常使用。',colorHelp:'不确定？先试个人色彩',princess:'公主 / 王子',queen:'王后 / 国王',royal:'王室仪式',chima:'裙装 Chima',baji:'裤装 / 长袍 Baji',either:'都可以',warm:'暖色',cool:'冷色',neutral:'中性',photo:'拍照优先',walking:'步行舒适',balanced:'均衡',spring:'春',summer:'夏',autumn:'秋',winter:'冬'},
 ja:{title:'My Korea Look',intro:'選択を変えると、12種類の選定済みルックから無料推薦がその場で再計算されます。',style:'宮殿スタイル',garment:'衣装',tone:'カラー方向',priority:'旅の優先',season:'季節',preview:'無料おすすめ',why:'1位になった理由',trade:'実用上の注意',location:'おすすめの宮殿背景',sample:'完成サンプルを見る',buy:'3ルックのスタイルブック — 12ドル買い切り',disabled:'決済はまだプレローンチです。無料マッチとサンプルは利用できます。',colorHelp:'迷ったらパーソナルカラーへ',princess:'Princess / Prince',queen:'Queen / King',royal:'Royal ceremony',chima:'チマ / スカート',baji:'パジ / ローブ＆パンツ',either:'どちらでも',warm:'ウォーム',cool:'クール',neutral:'ニュートラル',photo:'写真優先',walking:'歩きやすさ',balanced:'バランス',spring:'春',summer:'夏',autumn:'秋',winter:'冬'},
 'zh-TW':{title:'My Korea Look',intro:'更改下方選項，系統會從12套人工整理造型中即時重新排序免費推薦。',style:'宮廷風格',garment:'服裝類型',tone:'色彩方向',priority:'旅遊重點',season:'季節',preview:'你的免費推薦',why:'為什麼排第一',trade:'實際注意事項',location:'推薦宮殿場景',sample:'查看完整範例',buy:'取得3套造型冊 — 一次性12美元',disabled:'結帳仍在上線前模式。免費配對與範例可正常使用。',colorHelp:'不確定？先試個人色彩',princess:'公主 / 王子',queen:'王后 / 國王',royal:'王室儀式',chima:'裙裝 Chima',baji:'褲裝 / 長袍 Baji',either:'都可以',warm:'暖色',cool:'冷色',neutral:'中性',photo:'拍照優先',walking:'步行舒適',balanced:'均衡',spring:'春',summer:'夏',autumn:'秋',winter:'冬'},
 vi:{title:'My Korea Look',intro:'Thay đổi lựa chọn và gợi ý miễn phí sẽ được xếp lại ngay từ 12 bộ trang phục tuyển chọn.',style:'Phong cách cung điện',garment:'Trang phục',tone:'Hướng màu',priority:'Ưu tiên chuyến đi',season:'Mùa',preview:'Gợi ý miễn phí',why:'Vì sao xếp hạng đầu',trade:'Điểm cần cân nhắc',location:'Bối cảnh cung điện hợp nhất',sample:'Xem mẫu hoàn chỉnh',buy:'Nhận stylebook 3 look — $12 một lần',disabled:'Thanh toán vẫn đang ở chế độ trước khi ra mắt. Matching miễn phí và mẫu vẫn dùng được.',colorHelp:'Chưa chắc? Thử Personal Color',princess:'Princess / Prince',queen:'Queen / King',royal:'Royal ceremony',chima:'Chima / váy',baji:'Baji / áo choàng & quần',either:'Bất kỳ',warm:'Ấm',cool:'Lạnh',neutral:'Trung tính',photo:'Ưu tiên ảnh',walking:'Ưu tiên đi bộ',balanced:'Cân bằng',spring:'Xuân',summer:'Hè',autumn:'Thu',winter:'Đông'},
 th:{title:'My Korea Look',intro:'เปลี่ยนตัวเลือกแล้วคำแนะนำฟรีจะจัดอันดับใหม่ทันทีจากลุคที่คัดสรรไว้ 12 แบบ',style:'สไตล์พระราชวัง',garment:'ชุด',tone:'โทนสี',priority:'ความสำคัญ',season:'ฤดู',preview:'ลุคฟรีที่เหมาะกับคุณ',why:'เหตุผลที่ได้อันดับหนึ่ง',trade:'ข้อควรคำนึง',location:'ฉากพระราชวังที่เหมาะ',sample:'ดูตัวอย่างฉบับเต็ม',buy:'รับ stylebook 3 ลุค — $12 ครั้งเดียว',disabled:'ระบบชำระเงินยังเป็น pre-launch แต่ matching ฟรีและตัวอย่างใช้งานได้',colorHelp:'ไม่แน่ใจ? ลอง Personal Color',princess:'Princess / Prince',queen:'Queen / King',royal:'Royal ceremony',chima:'Chima / กระโปรง',baji:'Baji / เสื้อคลุมและกางเกง',either:'แบบใดก็ได้',warm:'โทนอุ่น',cool:'โทนเย็น',neutral:'กลาง',photo:'เน้นถ่ายรูป',walking:'เน้นเดินสบาย',balanced:'สมดุล',spring:'ใบไม้ผลิ',summer:'ร้อน',autumn:'ใบไม้ร่วง',winter:'หนาว'}
};

export function StyleConsultationV2(){
 const locale=useLocale();const l=(locale in C?locale:'en') as Locale,c=C[l];
 const [style,setStyle]=useState<StyleId>('princess-prince'),[garment,setGarment]=useState<GarmentType>('either'),[tone,setTone]=useState<LookUndertone>('neutral'),[priority,setPriority]=useState<LookPriority>('balanced'),[season,setSeason]=useState<Season>('spring'),[checkoutLoading,setCheckoutLoading]=useState(false),[message,setMessage]=useState('');
 const ranked=useMemo(()=>rankCuratedLooks({style,garment,tone,priority,season}),[style,garment,tone,priority,season]);
 const look=ranked[0]?.look??CURATED_LOOKS_CATALOG[0];
 async function checkout(){setCheckoutLoading(true);setMessage('');try{const r=await fetch('/api/checkout/stripe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productKey:'my_korea_look_v1',locale})});const data=await r.json();if(r.ok&&data.url){window.location.href=data.url;return;}setMessage(data.code==='CHECKOUT_DISABLED'?c.disabled:(data.error??c.disabled));}catch{setMessage(c.disabled);}finally{setCheckoutLoading(false);}}
 const selectStyle={display:'grid',gap:5} as const;
 return <section style={{maxWidth:1050,margin:'0 auto',padding:'30px 20px 70px'}}><h1>{c.title}</h1><p>{c.intro}</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12,margin:'22px 0'}}><label style={selectStyle}>{c.style}<select value={style} onChange={e=>setStyle(e.target.value as StyleId)}><option value="princess-prince">{c.princess}</option><option value="queen-king">{c.queen}</option><option value="royal">{c.royal}</option></select></label><label style={selectStyle}>{c.garment}<select value={garment} onChange={e=>setGarment(e.target.value as GarmentType)}><option value="either">{c.either}</option><option value="chima">{c.chima}</option><option value="baji">{c.baji}</option></select></label><label style={selectStyle}>{c.tone}<select value={tone} onChange={e=>setTone(e.target.value as LookUndertone)}><option value="warm">{c.warm}</option><option value="cool">{c.cool}</option><option value="neutral">{c.neutral}</option></select><Link href="/color"><small>{c.colorHelp} →</small></Link></label><label style={selectStyle}>{c.priority}<select value={priority} onChange={e=>setPriority(e.target.value as LookPriority)}><option value="photo">{c.photo}</option><option value="walking">{c.walking}</option><option value="balanced">{c.balanced}</option></select></label><label style={selectStyle}>{c.season}<select value={season} onChange={e=>setSeason(e.target.value as Season)}><option value="spring">{c.spring}</option><option value="summer">{c.summer}</option><option value="autumn">{c.autumn}</option><option value="winter">{c.winter}</option></select></label></div><article aria-live="polite" style={{border:'1px solid currentColor',padding:18}}><h2>{c.preview}</h2><div style={{display:'grid',gridTemplateColumns:'minmax(220px,380px) 1fr',gap:20}}><img src={look.src} alt={look.alt} referrerPolicy="no-referrer" style={{width:'100%',aspectRatio:'4/5',objectFit:'cover',objectPosition:look.cropPosition}}/><div><h3>{look.title}</h3><p>{look.description}</p><h4>{c.why}</h4><ul>{look.reasons.map(x=><li key={x}>{x}</li>)}</ul><p><strong>{c.trade}:</strong> {look.tradeOff}</p><p><strong>{c.location}:</strong> {look.recommendedLocation.name} · {look.recommendedLocation.koreanName}</p></div></div></article><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:18}}><Link className="secondaryButton" href="/style/sample/palace-elegance">{c.sample}</Link><button className="primaryButton" type="button" onClick={checkout} disabled={checkoutLoading}>{checkoutLoading?'…':c.buy}</button></div>{message?<p role="status">{message}</p>:null}</section>;
}
