import type {Metadata} from 'next';
import {setRequestLocale} from 'next-intl/server';
import {Link} from '@/i18n/navigation';
import {localizedAlternates} from '@/lib/seo/localized-metadata';
import {rankStyleInputV1,type StyleComfort,type StyleDestination,type StyleInputV1,type StyleMood,type StylePalette,type StyleSeason,type StyleColorSource} from '@/lib/looks/style-input-v1';
import type {Coverage,GarmentType,StyleId} from '@/lib/looks/catalog';

type Locale=StyleInputV1['locale'];
type Params={params:Promise<{locale:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>};
type Copy={title:string;intro:string;invalid:string;back:string;why:string;colors:string;location:string;request:string;route:string;source:string;privacy:string};
const C:Record<Locale,Copy>={
 en:{title:'Shared My Korea Look',intro:'This read-only preview reproduces the non-sensitive choices in the shared link.',invalid:'This share link is incomplete or invalid. Create a new link from My Korea Look.',back:'Build my own look',why:'Why it fits',colors:'Color direction',location:'Suggested setting',request:'Korean rental request',route:'Photo route',source:'Visual source',privacy:'No photo, account identifier or personal keyword is contained in this link.'},
 'zh-CN':{title:'共享 My Korea Look',intro:'此只读预览会根据分享链接中的非敏感选择重新生成推荐。',invalid:'分享链接不完整或无效，请从 My Korea Look 重新生成。',back:'创建我的造型',why:'推荐理由',colors:'配色方向',location:'建议场景',request:'韩文租赁请求',route:'拍照路线',source:'图片来源',privacy:'链接不包含照片、账号标识或个人关键词。'},
 ja:{title:'共有 My Korea Look',intro:'共有リンクに含まれる非機密の選択内容から、読み取り専用プレビューを再現します。',invalid:'共有リンクが不完全または無効です。My Korea Look から新しいリンクを作成してください。',back:'自分のルックを作る',why:'おすすめ理由',colors:'カラー方向',location:'おすすめ背景',request:'韓国語レンタル依頼',route:'撮影ルート',source:'画像出典',privacy:'このリンクには写真、アカウント識別子、個人キーワードは含まれません。'},
 'zh-TW':{title:'共享 My Korea Look',intro:'此唯讀預覽會依分享連結中的非敏感選擇重新產生推薦。',invalid:'分享連結不完整或無效，請從 My Korea Look 重新產生。',back:'建立我的造型',why:'推薦理由',colors:'配色方向',location:'建議場景',request:'韓文租借需求',route:'拍照路線',source:'圖片來源',privacy:'連結不包含照片、帳號識別碼或個人關鍵字。'},
 vi:{title:'My Korea Look được chia sẻ',intro:'Bản xem trước chỉ đọc tái tạo đề xuất từ các lựa chọn không nhạy cảm trong liên kết.',invalid:'Liên kết chia sẻ thiếu hoặc không hợp lệ. Hãy tạo liên kết mới từ My Korea Look.',back:'Tạo look của tôi',why:'Vì sao phù hợp',colors:'Hướng màu',location:'Bối cảnh gợi ý',request:'Yêu cầu thuê bằng tiếng Hàn',route:'Tuyến chụp ảnh',source:'Nguồn hình ảnh',privacy:'Liên kết không chứa ảnh, mã tài khoản hay từ khóa cá nhân.'},
 th:{title:'My Korea Look ที่แชร์',intro:'พรีวิวแบบอ่านอย่างเดียวจะสร้างคำแนะนำซ้ำจากตัวเลือกที่ไม่ละเอียดอ่อนในลิงก์',invalid:'ลิงก์แชร์ไม่ครบหรือไม่ถูกต้อง โปรดสร้างลิงก์ใหม่จาก My Korea Look',back:'สร้างลุคของฉัน',why:'เหตุผลที่เหมาะ',colors:'ทิศทางสี',location:'สถานที่แนะนำ',request:'คำขอเช่าภาษาเกาหลี',route:'เส้นทางถ่ายรูป',source:'แหล่งภาพ',privacy:'ลิงก์นี้ไม่มีรูปภาพ ตัวระบุบัญชี หรือคีย์เวิร์ดส่วนตัว'}
};
const STYLES=new Set<StyleId>(['princess-prince','queen-king','royal']);
const GARMENTS=new Set<GarmentType>(['chima','baji','either']);
const PALETTES=new Set<StylePalette>(['jadeIvory','roseNavy','moonBlue','suggest']);
const MOODS=new Set<StyleMood>(['elegant','royal','romantic','minimal','kdrama']);
const COMFORTS=new Set<StyleComfort>(['walking','balanced','photoFirst']);
const COVERAGES=new Set<Coverage>(['standard','more-coverage']);
const SEASONS=new Set<StyleSeason>(['springAutumn','summer','winter']);
const DESTINATIONS=new Set<StyleDestination>(['gyeongbokgung','bukchon','seochon']);
const SOURCES=new Set<StyleColorSource>(['manual','local-preview']);
function one(v:string|string[]|undefined){return typeof v==='string'?v:undefined;}
function validDate(v:string|undefined){if(!v)return true;if(!/^\d{4}-\d{2}-\d{2}$/.test(v))return false;const [y,m,d]=v.split('-').map(Number);const dt=new Date(Date.UTC(y,m-1,d));return dt.getUTCFullYear()===y&&dt.getUTCMonth()===m-1&&dt.getUTCDate()===d;}
function build(locale:Locale,q:Record<string,string|string[]|undefined>):StyleInputV1|null{
 const style=one(q.style) as StyleId|undefined,garment=one(q.garment) as GarmentType|undefined,palette=one(q.palette) as StylePalette|undefined,mood=one(q.mood) as StyleMood|undefined,comfort=one(q.comfort) as StyleComfort|undefined,coverage=one(q.coverage) as Coverage|undefined,season=one(q.season) as StyleSeason|undefined,destination=one(q.destination) as StyleDestination|undefined,colorSource=one(q.colorSource) as StyleColorSource|undefined,visitDate=one(q.date);
 if(!style||!STYLES.has(style)||!garment||!GARMENTS.has(garment)||!palette||!PALETTES.has(palette)||!mood||!MOODS.has(mood)||!comfort||!COMFORTS.has(comfort)||!coverage||!COVERAGES.has(coverage)||!season||!SEASONS.has(season)||!destination||!DESTINATIONS.has(destination)||!colorSource||!SOURCES.has(colorSource)||!validDate(visitDate))return null;
 return{version:1,locale,style,garment,palette,mood,comfort,coverage,season,destination,colorSource,...(visitDate?{visitDate}:{})};
}
export async function generateMetadata({params}:Pick<Params,'params'>):Promise<Metadata>{const {locale}=await params;const safe=(locale in C?locale:'en') as Locale;return{title:C[safe].title,robots:{index:false,follow:true},alternates:localizedAlternates(safe,'/style/shared')};}
export default async function SharedStylePage({params,searchParams}:Params){const [{locale},q]=await Promise.all([params,searchParams]);setRequestLocale(locale);const safe=(locale in C?locale:'en') as Locale,c=C[safe],input=build(safe,q);if(!input)return <main style={{maxWidth:960,margin:'0 auto',padding:'40px 20px 80px'}}><h1>{c.title}</h1><p role="alert">{c.invalid}</p><Link className="primaryButton" href="/style">{c.back}</Link></main>;const ranked=rankStyleInputV1(input);const look=ranked[0]?.look;if(!look)return <main style={{maxWidth:960,margin:'0 auto',padding:'40px 20px 80px'}}><h1>{c.title}</h1><p role="alert">{c.invalid}</p><Link className="primaryButton" href="/style">{c.back}</Link></main>;return <main style={{maxWidth:960,margin:'0 auto',padding:'40px 20px 80px'}}><h1>{c.title}</h1><p>{c.intro}</p><p><small>{c.privacy}</small></p><article style={{border:'1px solid rgba(0,0,0,.12)',borderRadius:14,padding:18}}><img src={look.visualSrc} alt={look.visualAlt} referrerPolicy="no-referrer" style={{width:'100%',maxHeight:620,objectFit:'cover',borderRadius:10}}/><h2>{look.title}</h2><p>{look.description}</p><h3>{c.why}</h3><ul>{look.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul><p><strong>{c.colors}:</strong> {look.palette.top} / {look.palette.bottom} / {look.palette.accent}</p><p><strong>{c.location}:</strong> {look.recommendedLocation.name} · {look.recommendedLocation.koreanName}</p><details><summary><strong>{c.request}</strong></summary><div lang="ko" style={{whiteSpace:'pre-line',padding:'10px 0'}}>{look.rentalShopCard.hangulStaffNote}</div></details><details><summary><strong>{c.route}</strong></summary><ol>{look.photoRoute.map(stop=><li key={stop.order}><strong>{stop.spotName} · {stop.koreanName}</strong> — {stop.bestTime}<br/>{stop.photoTip}</li>)}</ol></details><p><small><strong>{c.source}:</strong> {look.creator} · {look.license} · <a href={look.sourceUrl} target="_blank" rel="noreferrer">source ↗</a></small></p></article><p style={{marginTop:20}}><Link className="primaryButton" href="/style">{c.back}</Link></p></main>;}
